### ISSUE TITLE
🛎️ [호이스팅] 문서 최상단 or 스코프 최상단

### ISSUE THREAD

**Issue by pingandthepong** [yamoo9/likelion-FEQA#10]
## 문제 상황

안녕하세요 선생님!
호이스팅이 '문서 최상단'으로 올라가는 현상인지,
'스코프 최상단'으로 올라가는 현상인 것인지 정확한 표현을 여쭤보고 싶습니다.

**Comment by shoveller** [comment]
안녕하세요 @pingandthepong 님! 좋은 질문을 주셨네요!
호이스팅과 스코프는 기술면접에 자주 등장하는 문제이니 정리가 꼭 필요하겠습니다.

일단 호이스팅이 실제로 존재하는 현상이라는 전제에서 설명을 하자면,
**호이스팅은 스코프 최상단(=유효범위 최상단)으로 올라가는 현상입니다.**
`var` 로 선언한 변수를 예를 들어 증명해 보겠습니다.

## var 로 선언한 변수의 호이스팅

### 문서에 var로 선언한 변수는 스코프 최상단으로 호이스팅이 된다.
웹 브라우저의 개발자 도구를 여시고 아래의 코드를 복사해서 콘솔에 붙여넣고 엔터를 눌러보세요!
```jsx
console.log(a);
debugger;
var a = 1;
```
![1](https://user-images.githubusercontent.com/1357198/210789573-5725ea49-ff81-4ad8-a13f-0b6d9bd16ba0.png)


### 함수에 var로 선언한 변수는 스코프 최상단으로 호이스팅이 된다.
웹 브라우저의 개발자 도구를 여시고 아래의 코드를 복사해서 콘솔에 붙여넣고 엔터를 눌러보세요!
```jsx
debugger;
function 함수() {
  console.log(a);
  debugger;
  var a = 1;
}
함수()
```
![2](https://user-images.githubusercontent.com/1357198/210789662-dcb8b123-1d61-49b9-b19e-6735906e641d.png)

이제  ![step](https://user-images.githubusercontent.com/1357198/210789724-75febbfd-a73c-4391-9b69-b47f2abdcee8.png)를 눌러 `함수()` 안의 메모리 상태를 엿봅시다.
![3](https://user-images.githubusercontent.com/1357198/210789797-82346332-21ea-40f3-930d-6229090cd1b2.png)


### 함수속 함수에 var로 선언한 변수는 스코프 최상단으로 호이스팅이 된다.
웹 브라우저의 개발자 도구를 여시고 아래의 코드를 복사해서 콘솔에 붙여넣고 엔터를 눌러보세요!
```jsx
debugger;
function 함수() {
  
  debugger;
	function 함수속_함수() {
	  console.log(a);
    debugger;
    var a = 1;
	}
	함수속_함수()
}
함수()
```
![4](https://user-images.githubusercontent.com/1357198/210789962-6dbe4ad0-0d1f-43e3-b55a-36ecf1f1efdc.png)

이제  ![step](https://user-images.githubusercontent.com/1357198/210789984-4e77fe7a-27ee-4b71-9f7c-9d92ffeb7b2c.png)를 눌러 `함수()` 안의 메모리 상태를 엿봅시다.
![5](https://user-images.githubusercontent.com/1357198/210790024-04d334f5-287b-4cf2-812a-40e82564de39.png)

다시  ![step](https://user-images.githubusercontent.com/1357198/210789984-4e77fe7a-27ee-4b71-9f7c-9d92ffeb7b2c.png)를 눌러 `함수()` 안의 메모리 상태를 엿봅시다.
![6](https://user-images.githubusercontent.com/1357198/210790050-6603c10d-6fc6-434a-812c-46c677b91dfa.png)

### 결론
호이스팅으로 설명을 원하는 면접관이 있다면 `호이스팅은 스코프 최상단(=유효범위 최상단)으로 올라가는 현상` 이라고 설명하시면 되겠습니다.
일각에서는 호이스팅을 일종의 환각으로 평가하는 사람이 있는 것도 사실입니다.
이에 관한 의견은 아래의 문서를 참고해주시면 감사하겠습니다.
[호이스팅과 TDZ는 실제 존재하는 현상인가?](https://github.com/yamoo9/likelion-FEQA/wiki/3.-%ED%98%B8%EC%9D%B4%EC%8A%A4%ED%8C%85%EA%B3%BC-TDZ%EB%8A%94-%EC%8B%A4%EC%A0%9C-%EC%A1%B4%EC%9E%AC%ED%95%98%EB%8A%94-%ED%98%84%EC%83%81%EC%9D%B8%EA%B0%80%3F)

기술면접에서 도움이 되길 바랍니다!
화이팅!

### 덤
`function` 으로 선언한 함수는 어떻게 될까요?  
같은 방법으로 메모리를 추적해봐도 재미있겠습니다.

**Comment by pingandthepong** [comment]
자세한 설명 감사합니다!🙇🏻‍♀️
