### ISSUE TITLE
[LAB-4] ES6 class에서 값을 받아오는 방식이 궁금합니다.

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#100]
## 질문 작성자

김하연

## 문제 상황
![image](https://user-images.githubusercontent.com/111109573/220112177-4bdb4e78-a985-42d0-a2be-6d6d1022fcec.png)

이 코드에서 
```
constructor(name, age) {
    this.name = name;
    this.age = age;
  }
```
`construnctor(name, age)` 로 받으면 결과값이 이렇게 나옵니다.

<img width="393" alt="스크린샷 2023-02-20 오후 9 50 03" src="https://user-images.githubusercontent.com/111109573/220112954-4e2f93ac-4c5c-4695-8f5a-7cbb9839ee87.png">

하지만 `constructor({ name, age })` 로 받으면 제대로 나옵니다.

<img width="254" alt="스크린샷 2023-02-20 오후 9 50 57" src="https://user-images.githubusercontent.com/111109573/220113130-8f7c99b4-a1f1-47a4-829d-f5a0c7644565.png">

제가 하고싶은 것은 첫번째 처럼 
`construnctor(name, age)` 로 했을 때 값이 제대로 출력되는 것을 원합니다.
이 방식으로 출력값을 보고 싶을 때 어떤 식으로 코드를 다시 짜야할지 궁금합니다!

**Comment by shoveller** [comment]
안녕하세요. @hayeonn2 님.

```js
const person = new Person({
  name: '하연',
  age: 27
})
```

을

```js
const person = new Person('하연', 27)
```

로 바꿔 보시겠어요?

**Comment by shoveller** [comment]
참고로 
```js
const person = new Person('하연', 27)
```
은
```js
const person = new Person(27, '하연')
```
처럼 순서를 착각할 우려가 있다고 알려져 있습니다(=에러가 발생할 확률이 높아짐).
그래서 파라미터가 2개 이상이라면, 아래와 같이 객체로 넘기는 것이 권장됩니다.
```js
const person = new Person({
  name: '하연',
  age: 27
})
```

**Comment by yamoo9** [comment]
## 문제 원인

재원 멘토님께서 답변 주신 것처럼 Person 객체를 생성할 때 `이름`, `나이` 순이 아니라, `{ 이름, 나이 }` 객체로 전달했기 때문입니다.

```js
const person = new Person({
  name: '하연',
  age: 27
});
```

아래 그림을 보면 더 잘 이해되실 거에요.

<img width="600" alt="" src="https://user-images.githubusercontent.com/1850554/220178977-baca907f-70f5-4c2c-8812-35885256c450.png" />

## 문제 해결

@hayeonn2 님께서 원하는 바는 아래와 같죠.

> 제가 하고싶은 것은 첫번째 처럼 `construnctor(name, age)`로 했을 때 값이 제대로 출력되는 것을 원합니다.

그렇다면 Person 객체를 생성할 때 `이름`, `나이` 순으로 인자를 전달해주면 됩니다. 😊

```js
const person = new Person('하연', 27);
```
