### ISSUE TITLE
[LAB-7] SSR vs CSR

### ISSUE THREAD

**Issue by leejh4197** [yamoo9/likelion-FEQA#101]
## 질문 작성자

이주형

## 문제 상황

Next.js를 공부해보다 Next.js가 SSR방식이라 하여 코드를 따라해보다 궁금한 점이 생겨 이슈에 글을 남깁니다.
서버사이드 렌더링 방식은 초기 화면 구성에 필요한 모든 파일, 데이터들을 받아와 브라우저에 뿌려주는 것으로 이해하고 있는데 뭔가 MPA와 비슷하다는 생각이 들었습니다. 서버사이드 렌더링이 SEO에 장점을 가지고 있다고는하지만 사용자가 클릭을 하거나 필요한 데이터를 요청하면 다시 서버에 요청해야 하는데 성능면에서 봤을때 CSR이 훨씬 앞선다는 생각이 들어서 SSR를 왜 사용하는 것인지 궁금합니다!

**Comment by shoveller** [comment]
안녕하세요! @leejh4197 님.
말씀하신대로 SSR은 고전적인 MPA 구현과 매우 비슷합니다.
하지만 데이터를 가져오는 도중에 서버가 멈추거나 느리게 동작하는 등의 시나리오에 대응하기가 어려웠던게 사실입니다.
(저도 세션 처리를 제외하고는 SSR의 잇점을 찾기 어려웠네요.)
하지만, react18 부터 추가된 [서버 컴포넌트(Server Component)](https://beta.reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components) 와 [동시성 모드(Concurrent mode)](https://beta.reactjs.org/blog/2022/03/29/react-v18#what-is-concurrent-react) 등이 실제로 사용할 수 있는 단계가 되면 이야기가 달라질 수도 있겠습니다.

그런데.. 이 기능들은 아직 준비중인 단계이고, 실제로 api가 수시로 바뀌고 있어서 저도 딱히 무엇이라 설명을 드릴 수가 없어 안타깝습니다..
지금 단계에서는 이미 상용서비스로 존재하고 있는 서버리스 플랫폼들의 Edge Function(vercel, supabase, aws lambda)들과 밀접하게 연결되어 동작할 가능성이 있으니 늘 관심을 가지고 지켜보는게 최선이라는 생각입니다(모놀리식 서버에 node.js 를 동작시켜 ssr을 하는 시대는 끝났다는 뜻).
저도 기회가 되면 이 부분을 야무 선생님께 근황을 배우고 싶군요.

**Comment by yamoo9** [comment]
## 질문

서버사이드 렌더링이 SEO에 장점을 가지고 있다고는하지만 사용자가 클릭을 하거나 필요한 데이터를 요청하면 다시 서버에 요청해야 하는데 성능 면에서 봤을때 CSR이 훨씬 앞선다는 생각이 들어서 SSR를 왜 사용하는 것인지 궁금합니다!

## 답변

서버 사이드 렌더링(SSR)은 말 그대로 "서버에서 렌더링하는 것"입니다. 애플리케이션의 모든 콘텐츠가 포함된 HTML 파일을 서버에서 만들어 만들어 클라이언트(예: 웹 브라우저)에 보냅니다. (아래 그림의 SPA는 CSR을 의미 함)

<img width="544" alt="" src="https://user-images.githubusercontent.com/1850554/220432162-a6950d2c-5df8-4ce7-bd7a-f740fa641163.png">


서버에서 HTML을 만들어 보내므로 애플리케이션 사용자는 JavaScript 파일이 로드 되고 해석 되기를 기다리는 동안 빈 화면만 보고 있는 클라이언트 사이드 렌더링(CSR)보다 더 빠르게 모든 것을 볼 수 있습니다. 또한 클라이언트에서 HTML을 동적 생성하는 CSR과 달리, SSR은 검색엔진 최적화(SEO)에 더욱 효과 적입니다.

### SSR 장점

SSR은 전통적인 웹 애플리케이션 렌더링 방식으로 여러 장점을 가집니다.

- 인터넷 속도가 느리거나 CPU 성능이 떨어지는 환경에서 로딩 속도가 낫습니다. (사용자 경험 ↑)
- 검색 엔진에서 쉽게 크롤링(정보 수집 작업) 할 수 있습니다. (검색 노출 ↑)
- 소셜 미디어 인덱싱 문제가 상대적으로 적습니다. (마케팅 전략적 접근 ↑)
- 스크린 리더와 같은 보조 기기 구문 분석에 더 나은 결과를 보입니다. (접근성 향상 ↑)

### SSR 단점

반면 새로운 렌더링 방식인 CSR 보다 여러 단점도 있습니다.

- SSR은 서버 또는 서버리스(serverless) 백엔드 비용을 지불해야 합니다. (비용 증가 ↑)
- 빈번한 서버 요청, 전체 페이지 다시 로드 등 페이지 전환 속도가 느립니다. (사용자 경험 ↓)
- 여러 라이브러리 및 도구는 서버 사이드 렌더링을 지원하지 않습니다. (호환성 문제 ↑)
- 잘못 구현된 경우, 서버에서 만들어진 HTML 파일 크기가 더 큽니다. (잠재적 위험 ↑)

### SSR? CSR? 선택 기준은?

웹 애플리케이션을 구축할 때 SSR 또는 CSR 중 어떤 렌더링 전략을 사용할 지 결정해야 합니다. 앞서 이야기 한 SSR의 장점을 목적으로 해야 한다면 SSR을, 그렇지 않은 경우라면 CSR을 선택할 수 있을 것입니다.

SSR과 CSR 모두 장단점이 있습니다. 프로젝트에서 가장 적합한 방식에 대한 결정은 필요한 기능 및 지원 환경, 고려해야 할 준수 사항에 따라 달라질 수 있습니다.

전자 상거래(예: 온라인 쇼핑몰 등) 애플리케이션의 경우 SSR 전략이 더 나은 결과를 가져옵니다. 검색 노출(SEO)이 고객(제작 대행을 맡긴 서비스 회사) 입장에서는 매우 중요한데 Google, Bing, NAVER 등의 웹 크롤러는 애플리케이션 정보를 수집할 때 렌더링하는 데 걸리는 시간(TTFMP), 작동하는데 소요되는 시간(TTI)을 포함한 여려 지표로 검색 순위를 매기기 때문입니다.

1. [TTFMP](https://developer.chrome.com/ko/docs/lighthouse/performance/first-meaningful-paint/) : Time To First Meaningful Paint
1. [TTI](https://web.dev/i18n/ko/tti/) : Time to Interactive

**Comment by leejh4197** [comment]
감사합니다! 아직 확실하게 와닿지는 않지만 그래도 어떤 경우에 사용되는지 알 것 같습니다!
