### ISSUE TITLE
[LAB-5] React Docs 사이트를 읽는 도중 코드에 대한 결과가 제가 생각한 결과와 달라서 어째서 이런 결과가 나왔는지 궁금합니다.

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#102]
## 질문 작성자

신선영

## 문제 상황
![image](https://user-images.githubusercontent.com/48400229/220593744-5d842678-d4c3-4ba8-9022-60df03b9fcbc.png)
위에 사진 보시면 Cup 컴포넌트를 세 번 호출하게 되는데 그렇기 때문에 초기값 0을 가지고 세 번 호출 할 경우, 
![image](https://user-images.githubusercontent.com/48400229/220594145-2914bce7-61cd-4832-b8e1-ff31329a3b7f.png)
위 처럼 나와야하는 거 아닌가요? 어째서 저런 결과가 나오게 된 건지 궁금합니다.

위 코드는 https://beta.reactjs.org/learn/describing-the-ui 이 사이트에 있습니다.

## 코드 검토 리소스

- [codesandbox.io 활용] (https://codesandbox.io/s/naughty-sky-x238gu?file=/App.js)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요! @SSY1203 님. 아주 중요한 부분을 캐치하셨네요!
보내주신 [코드 검토 리소스](https://codesandbox.io/s/naughty-sky-x238gu?file=/App.js) 의 `index.js` 에서
8~12 번째 줄을 아래와 같이 수정해 보시겠어요?
```jsx
root.render(
  // <StrictMode>
  <App />
  // </StrictMode>
);
```

해당 현상은 react.js 의 [strict 모드](https://ko.reactjs.org/docs/strict-mode.html) 라는 것이 활성화되어 발생하는 것입니다.
문서에 따르면 잠재적인 문제를 찾아내 준다고는 하는데.. 괜히 이런 오해를 사게 만드는게 문제인것 같습니다..
프로덕션 빌드에서는 같은 문제가 발생하지 않으니 안심하셔요!

**Comment by SSY1203** [comment]
좋은 답변 감사합니다!! ㅎㅎ 그러면 애초에 fragment로 감싸면 안되나요? 안정성(?) 때문에 정식 배포할 땐 strictmode로 써야하나요?

**Comment by shoveller** [comment]
> 좋은 답변 감사합니다!! ㅎㅎ 그러면 애초에 fragment로 감싸면 안되나요? 안정성(?) 때문에 정식 배포할 땐 strictmode로 써야하나요?

네 용도가 다 있을 것이니 strictmode를 활성화 한 상태로 개발하시는 것이 좋을것 같습니다.
참고로 next.js 같은 프레임워크들은 strictmode 를 끄는 옵션을 제공하기도 합니다.
이 문서를 보니 미래를 대비해 켠 상태로 개발하라고 조언하고 있군요.

https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode

**Comment by SSY1203** [comment]
정말 감사합니다! 많은 도움이 됐어요 ㅎㅎ
