### ISSUE TITLE
[LAB-2] key이벤트 중 toLowerCase ()

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#103]
## 질문 작성자
오승택

## 문제 상황
키 이벤트 중에서 enter 키를 눌렀을 떄 toLowerCase() 를 사용하신 이유가 궁금합니다
![image](https://user-images.githubusercontent.com/109938280/220644692-e0eadad4-51d1-40ad-a7a0-be927b727c9b.png)

toLowerCase() 를 빼고 enter->Enter 로 바꾸고 사용해도 똑같이 작동이 되서 둘의 차이점이 궁금합니다
![image](https://user-images.githubusercontent.com/109938280/220645541-cc124fcd-6526-415a-9145-5f7d248a6876.png)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
@5wintaek 님 맞습니다. `enter` 대신 `Enter`로 비교해도 됩니다. 😃
어떤 방법을 선호하는 가의 문제입니다. 저는 **소문자로 변환해 비교하는 방법을 선호합니다.**
