### ISSUE TITLE
[LAB-4] stateless 와 stateful 의 차이점

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#104]
## 질문 작성자

김하연

## 문제 상황
오늘 배운 내용을 복습하다가 stateful이라는 개념을 알게 되었습니다.
stateful과 stateless  두가지를 상황에 맞게 사용한다고 하고
자료를 찾아보니 stateless를 웹서버에서 많이 쓴다는 사실을 알았습니다.
웹서버에서 stateful을 사용하는 경우도 있을까요?
마켓칼리 프로젝트 때 오늘하루 안보기 같은 팝업은 stateful에 해당하는건지.. 궁금합니다.

또, 요즘 stateless 컴포넌트로 개발을 하는 추세라고 하는데 정확한 이유가 궁금합니다!
확장성이나 서버가 달라져도 사용이 가능해서 일까요?

**Comment by shoveller** [comment]
안녕하세요. @hayeonn2 님. 굉장히 심오한 질문을 주셨네요.

> 웹서버에서 stateful을 사용하는 경우도 있을까요?

stateful 한 서버의 예로 로그인 세션 처리를 하는 서버를 들고 싶어요.
전통적인 웹 서버의 경우, `로그인을 했다는 증거`를 파일이나 데이터베이스, 메모리 등에 담아놓습니다.
그리고 `로그인을 했다는 증거`를 쿠키에 담아서 웹 프론트엔드에게 넘겨주고..
웹 프론드엔드는 `로그인을 했다는 증거`가 쿠키에 있는지를 따져서, 그것이 있으면 로그인으로 처리를 합니다.
이것을 세션이라고 하는데, 이 `로그인을 했다는 증거`(=세션)가 있다는 것 자체로 서버가 stateful 하다는 증거가 됩니다.
이 세션은 서버가 갑자기 꺼지기라도 하면 사라져 버리기 때문에 그것을 잃어버리지 않게 여러가지 백업을 해야 합니다.
그래서 최근엔 stateless 서버라고 해서, 세션을 만들지 않는 서버를 만들곤 합니다.

> 또, 요즘 stateless 컴포넌트로 개발을 하는 추세라고 하는데 정확한 이유가 궁금합니다!

네, 실무에서 stateful 한 컴포넌트를 만들게 되면 여러가지 문제점이 생길 수 있습니다.
특히 컴포넌트 안의 상태를 컴포넌트 바깥에서 제어하려고 할때 그 문제점이 도드라집니다.
[간단한 카운터 예제로 설명을 할 수 있을것 같아요.](https://codesandbox.io/p/sandbox/wizardly-bogdan-e6z6ld?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A11%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A16%7D%5D)
아주 극단적인 예를 들었지만, 컴포넌트가 자신만의 상태를 가지게 되면.. 
그 순간부터 제어가 어려워진다는 것으로 이해하시면 좋을 것 같습니다.
혹시 구두 설명이 필요하다면 DM을 부탁드립니다.

**Comment by hayeonn2** [comment]
그럼 로그인을 했을 때.. 요즘에 자동로그인이 되잖아요! (아이디 저장이나 자동로그인) 
stateless 서버인데 백업을 해놓아서 로그인이 자동으로 되게 해주는 것일까요?
아니면 이런 부분만 stateful 한 것일까요..?

**Comment by yamoo9** [comment]
@hayeonn2 님

수업 시간에 다룬 Stateless, Stateful은 React 학습 범위 내에서 안내해드렸습니다.
React 학습 범위 내에서 Stateless는 "상태를 가지지 않는 컴포넌트"이고, Stateful은 "상태를 가지는 컴포넌트"를 말합니다.

## Stateless Component

상위 컴포넌트로부터 전달받는 props에 의해 제어되는 컴포넌트입니다. 컴포넌트가 상태를 포함하지 않습니다.

```jsx
function ToggleButton(props) {
  return (
    <button 
      type="button" 
      className={`ToggleButton ${props.on ? 'on' : ''}.trim()`}
      aria-checked={props.on}
    >
      {props.on ? props.offText : props.onText}
    </button>
  );
}
```

```jsx
<ToggleButton on={true} onText="ON" offText="OFF" />
```

## Stateful Component

상위 컴포넌트와 상관없이 스스로 제어하는 컴포넌트입니다. 컴포넌트가 제어 가능한 상태를 포함합니다. 상태를 컴포넌트 스스로 제어하므로, 상위 컴포넌트에서 변경된 상태를 감지하기 위해서는 커스텀 이벤트(예: onToggled)를 설정할 수 있습니다.

```jsx
import { useState } from  'react';

function ToggleButton(props) {

  const [toggleState, setToggleState] = useState(false);

  const handleToggle = () => {
    setToggleState((toggleState) => !toggleState);
    props.onToggled?.(toggleState);
  };

  return (
    <button 
      type="button" 
      className={`ToggleButton ${toggleState ? 'on' : ''}.trim()`}
      aria-checked={toggleState}
      onClick={handleToggle}
    >
      {toggleState ? props.offText : props.onText}
    </button>
  );
}

ToggleButton.defaultProps = {
  onText: 'ON';
  offText: 'OFF';
};
```

사용자가 ToggleButton 컴포넌트를 클릭하면 컴포넌트 상태는 스스로 변경하며, 상위 컴포넌트는 onToggled 이벤트에 연결된 핸들러(함수)를 통해 변경된 상태를 전달 받을 수 있습니다.

```jsx
<ToggleButton onToggled={(toggleState) => {
  // 버튼이 토글 되면 상위 컴포넌트에서 토글 상태를 확인할 수 있습니다.
  console.log(toggleState);
}} />
```
