### ISSUE TITLE
[LAB-4] Vite로 절대경로 잡을 때 관련해서 궁금합니다.

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#105]
## 질문 작성자

김하연

## 문제 상황
<img width="669" alt="스크린샷 2023-02-22 오후 11 49 54" src="https://user-images.githubusercontent.com/111109573/220658437-e30dd702-8da3-4823-9d44-d1ddc7d1cfd1.png">

혹시 이부분.. 왜 이렇게 다시 잡아주셨는지 알 수 있을까요..!!
처음엔 `import { resolve } from 'node:path';` 가 아직 사용안해도 될 것 같다하셨는데
제가 수업 중 놓친건지.. 잘 모르겠습니다🥺

두번째로
`import '@/styles/global.css';` 이 부분에서 `@` 으로 절대경로를 잡아주는 것이 맞을까요?
자료를 몇가지 찾아보니 `find : '@'` 는 별칭이라는데 혹시 `@` 가 아닌 다른 것으로도 쓸 수 있는지 궁금합니다!

**Comment by shoveller** [comment]
안녕하세요. @hayeonn2 님. 점점 어려운 환경설정으로 접어들고 계시는군요.. ㅎㅎㅎ 환영합니다.

> 혹시 이부분.. 왜 이렇게 다시 잡아주셨는지 알 수 있을까요..!!

제가 맥락을 파악하지 못해서 패스하겠습니다. 양해를 부탁드립니다.


> 혹시 @ 가 아닌 다른 것으로도 쓸 수 있는지 궁금합니다!

네. 저는 개인적으로 다른 설정을 씁니다.
`alias: [{ find: 'src', replacement: resolve(__dirname, 'src') }]`
그러면.. 모든 절대경로가 `src` 로 시작하게 됩니다.
이게 inteliJ 같은 IDE에 별다른 설정을 안 해도, 라이브러리 임포트가 절대경로로 자동완성이 되어버리는 효과가 있어서 애용하고 있습니다.

**Comment by yamoo9** [comment]
## Vite 절대 경로 설정이 변경된 이유

[Vite](https://vitejs.dev/config/shared-options.html#resolve-alias) 공식 문서([번역](https://vitejs-kr.github.io/config/shared-options.html#resolve-alias))를 참고하면 "**파일 시스템 경로에 별칭을 만들 때에는, 반드시 절대 경로를 사용하세요.**" 라고 되어 있어 변경했습니다.

<img width="500" alt="" src="https://user-images.githubusercontent.com/1850554/220754135-46ed4ea7-b69c-4fee-a27d-8200fcfbec7e.png" />

## @ 대신 다른 기호를 사용할 수 있나?

네 가능합니다. 아래처럼 `~` 기호를 사용해 변경해 사용해도 정상 작동합니다.

```js
export default defineConfig({
  resolve: {
    alias: [{ find: '~', replacement: resolve(__dirname, './src') }],
  },
  // ...
});
```

설정 이후 `~` 기호를 사용해 절대 경로를 사용해 모듈을 불러올 수 있습니다.

```js
import '~/styles/global.css';
import { getColor } from '~/theme/utils';
```
