### ISSUE TITLE
[LAB-2] 인스턴스 매서드 vs 스태틱 매서드

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#106]
## 질문 작성자

오승택

## 문제 상황
https://github.com/yamoo9/likelion-react/commit/ead0096f58883d9c184003fad89d1bf6945b1be6
위의 링크는 어제 2/22 수업내용입니다. 커밋 기록을 보던 중 이 코드를 왜 작성하셨는지 이해가 잘 가지않아 질문드립니다.

또한 인스턴스 매서드와 스태틱 매서드의 개념과 차이점도 궁금하여 질문드립니다 ! 

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
## 질문

인스턴스 매서드와 스태틱 매서드의 개념과 차이점도 궁금하여 질문드립니다 !

## 답변

수업 중에 인스턴스(instance), 스태틱(static) 메서드의 차이점 그리고 `this`에 대한 접근 질문이 있었어요.
그것에 대한 설명 과정에서 작성한 코드입니다. 😃

https://github.com/yamoo9/likelion-react/commit/ead0096f58883d9c184003fad89d1bf6945b1be6

그리고 인스턴스, 스태틱 메서드의 개념과 차이점을 정리해봅시다.

인스턴스 메서드 | 스태틱 메서드
--- | ---
클래스로부터 생성된 인스턴스를 통해서만 사용 가능<br/>`new 클래스().인스턴스_메서드()` | 클래스의 멤버로 생성 과정 없이 바로 사용 가능<br/>`클래스.스태틱_메서드()`
인스턴스 메서드 안에서 인스턴스(`this`)에 접근 가능 | 인스턴스를 생성하지 않았으므로 인스턴스(`this`)에 접근 불가능
클래스 필드 영역에 작성된 함수<br />`함수() { ... }` | 클래스 필드 영역 안에 작성된 static 함수<br />`static 함수() { ... }`<br/>또는 클래스 영역 밖에 클래스의 메서드로 정의된 함수<br/>`클래스.메서드 = function() { .. }`

**ECMAScript 클래스 예시**

```jsx
class 고양이 {

  // 인스턴스 메서드
  그루밍() { ... /* 인스턴스(this) 접근 가능 */ }
  그르릉() { ... /* 인스턴스(this) 접근 가능 */ }

  // 스태틱(클래스) 메서드
  static 오해_바로알기() { ... /* 인스턴스(this) 접근 안됨 */ }

}

// 스태틱(클래스) 메서드
고양이.꼬리언어_해석하기 = function() { ... /* 인스턴스(this) 접근 안됨 */ }
```

**React 클래스 컴포넌트 예시**

```jsx
class Input extends React.Component {

  // 인스턴스 메서드
  render() { ... /* 인스턴스(this) 접근 가능 */ }
  componentDidMount() { ... /* 인스턴스(this) 접근 가능 */ }

  // 스태틱(클래스) 메서드
  static defaultProps = { ... /* 인스턴스(this) 접근 안됨 */ }

}

// 스태틱(클래스) 메서드
Input.propTypes = { ... /* 인스턴스(this) 접근 안됨 */ }
```
