### ISSUE TITLE
[LAB-4] 함수컴포넌트 밖에 변수를 지정하는 이유

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#107]
## 질문 작성자

김하연

## 문제 상황
- 함수 컴포넌트 밖에 변수를 지정한 것
<img width="417" alt="스크린샷 2023-02-24 오전 2 17 47" src="https://user-images.githubusercontent.com/111109573/220981503-689c40aa-db29-413a-82f0-721805faa902.png">

- 함수 컴포넌트 안에 변수를 지정한 것
<img width="434" alt="스크린샷 2023-02-24 오전 2 17 21" src="https://user-images.githubusercontent.com/111109573/220981417-b4638560-3d54-4098-9fce-9541f9131d7f.png">

혼자 차근차근 실습해보는 도중에.. 진짜 별거 아닌거 같긴한데 궁금해서 여쭤봅니다 🥺
함수 컴포넌트 밖이나 안에 써도 결과값은 동일한 것 같은데 혹시 밖에다가 써준 이유가 있을까요..

**Comment by yamoo9** [comment]
## 질문

함수 컴포넌트 밖이나 안에 써도 결과값은 동일한 것 같은데 혹시 밖에 다가 써준 이유가 있을까요?

## 답변

함수 컴포넌트 밖 또는 안에 작성해도 결과 값은 동일해요.
그런데 함수 안에 작성하면 함수 컴포넌트가 다시 실행(렌더링)될 때 마다 tokens을 통해 colors 값에 접근해야 하죠.
반면, 함수 밖에 작성하면 함수 컴포넌트가 다시 실행되더라도 colors 값에만 접근하면 됩니다.

하연님을 부를 때마다 "아름다운 한국 섬에 사는 하연님"이라고 말하는 것보다는 "하연님"이라고 부르는 것이 나은 것처럼 말이죠. 😃
