### ISSUE TITLE
[LAB-4] 버튼 컴포넌트에서 isSecondary를 사용한 이유

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#108]
## 질문 작성자

김하연

## 문제 상황

<img width="520"  src="https://user-images.githubusercontent.com/111109573/220992693-655b8758-f2f4-4133-a5ee-ddbfd86f5f58.png">

원래는 `let isPrimary = mode.includes('primary');` 를 변수로 받고,
 `isPrimary` 가 있을 때를 사용해 삼항연산자를 사용해 비교했습니다.
그리고 App.jsx에서 `<Button mode="secondary">로그인</Button>` 로 두번째 버튼에 지정을 해줬습니다!

근데 `isSecondary` 를 사용해 기본값으로 `false`를 받고 `<Button secondary>로그인</Button>` 로 해준 이유가 있을까요?
전체적인 흐름은 이해가 되는데 바꿔주신 이유가 잘..생각이 안납니다..
제가 생각했을때 좀 더 코드가 깔끔해보이긴하는데 그 이유일까요?

**Comment by yamoo9** [comment]
## 질문

근데 `isSecondary`를 사용해 기본 값으로 `false`를 받고 `<Button secondary>로그인</Button>`로 해준 이유가 있을까요?
전체적인 흐름은 이해가 되는데 바꿔주신 이유가 잘..생각이 안납니다..
제가 생각했을때 좀 더 코드가 깔끔해보이긴하는데 그 이유 일까요?

## 답변

개발자가 컴포넌트를 구현한 API 차이 에요. 😊

`mode` prop으로 문자 값을 받아서 처리하도록 구현 했다면 아래 처럼 작성해야 해요. 

```jsx
<Button mode="secondary">로그인</Button>
```

반면 `secondary` prop으로 불리언 값을 받아서 처리하도록 구현 했다면 아래 처럼 작성하죠.

```jsx
<Button secondary>로그인</Button>
```

하연님이 말했듯이 "코드가 깔끔해 보인다"고 말한 것은 **컴포넌트 사용자의 관점**이 되겠죠.
컴포넌트를 구현할 때 어떤 API로 만들면 사용자가 편하게 사용할지 고민하면 좋겠죠?

**"이렇게 입력해주세요. 그러면 요렇게 처리(출력할)해요."** 🤔
