### ISSUE TITLE
[LAB-4] 클래스네임 합성

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#109]
## 질문 작성자

김하연

## 문제 상황
복습을 하고 있는데 클래스네임을 합성했던 정확한 이유가 궁금합니다!

```
  // 클래스네임 합성
  // `${개발자의 클래스이름} ${사용자의 클래스이름}`
  // const combinedClassNames = `${classes.srOnly} ${className}`;
  return <ComponentName className={classes.srOnly} {...restProps} />;
```

제가 이해한 바로는 위와 같은 코드로 짰을때 `App.jsx` 에서 임의로 사용자가 `classes.color` 로 클래스네임을 지정했을 경우 element에 들어오지 않는 점을 확인했습니다.
```
<A11yHidden as="h2" className={classes.color}>접근성 준수한 제목</A11yHidden>
```

따라서
```
const combinedClassNames = `${classes.srOnly} ${className}`.trim();
return <ComponentName className={combinedClassNames} {...restProps} />;
```
이와 같이 클래스네임을 합성해야 element에 클래스네임이 두가지 모두 들어오던데
사용자가 지정하는 클래스네임도 함께 받아오기 위해서 클래스네임을 합성해준 것이 맞을까요?

**Comment by shoveller** [comment]
안녕하세요. @hayeonn2 님. 복습과 과제를 동시에 하시느라 고생이 많으셔요.

> 사용자가 지정하는 클래스네임도 함께 받아오기 위해서 클래스네임을 합성해준 것이 맞을까요?

위 예제가 혹시 [이 파일](https://github.com/yamoo9/likelion-react/blob/07-component-driven-development/stateful-component-form/src/components/A11yHidden/A11yHidden.jsx)을 가리키는 것인가요?
구현에는 차이가 있지만, 맥락을 보았을 때 정확하게 파악하고 계신 것 같아요. ^^

**Comment by hayeonn2** [comment]
넵 맞습니다!! 감사합니다ㅎㅎ🙇‍♀️
