### ISSUE TITLE
[LAB-11] webpack 설정 관련 질문 있습니다.

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#110]
## 질문 작성자

서석원

## 문제 상황
[css 파일 추출 설정 노션](https://euid.notion.site/CSS-1ffd5bdc74be49ca8ad6cdc6388c78e9)

css 파일 추출 설정 중에 **NODE.ENV** 에 따라 설정을 다르게 주는 로직이 있는데 **NODE.ENV**가 undefined로 나오는 문제가 발생합니다. 
저의 추측상 환경 변수문제로, **dotenv** 설정과 연관이 있어보이는데, **dotenv** 설정이 정확이 어떤 방식로 사용되는지 잘 이해가 안갑니다.

이부분 관련해서 피드백 부탁드립니다...!
![q1](https://user-images.githubusercontent.com/73629761/221362146-ebf3e05a-9403-4751-af1e-9a9165717e90.PNG)
![q2](https://user-images.githubusercontent.com/73629761/221362149-50a3407d-a0b3-45b2-a3ae-90d8f54f4b4e.PNG)
![q3](https://user-images.githubusercontent.com/73629761/221362151-e71e2731-429e-463c-b71b-d8156eddbfcd.PNG)

참고로 
plugins 에 추가하거나 
`new webpack.EnvironmentPlugin({
      NODE_ENV: 'development'
    })`
.env 에 추가하면
`NODE_ENV = 'development'`
다음과 같이 **NODE_ENV**에 충돌이 발생한다고 뜹니다...
![q4](https://user-images.githubusercontent.com/73629761/221362341-e7f6b5de-68ec-492e-8c72-234e4c844bc3.PNG)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

[해당 깃허브 레포지토리](https://github.com/ssw6750/webpackscaffolding-boilerplate)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
Webpack 구동 명령어에 `--node-env` 옵션을 다음과 같이 설정해보세요.

```json
{
  "scripts": {
    "start": "npm run dev -- --open",
    "dev": "webpack serve --config ./webpack/dev.js --node-env development",
    "build": "webpack build --progress --config ./webpack/build.js --node-env production"
  }
}
```

설정 후 개발, 빌드 명령을 실행하면 `process.env.NODE_ENV` 값이 출력됩니다.

```js
console.log(process.env.NODE_ENV); // 'development'
```

<img width="1436" alt="" src="https://user-images.githubusercontent.com/1850554/221373743-29f3067a-ea9c-474f-b665-6d593369a8f0.png">

**Comment by ssw6750** [comment]
오 성공했습니다..!! 감사합니다

근데 DotEnv를 어떻게 활용하는건지 아직 잘 모르겠습니다...

**Comment by yamoo9** [comment]
> 오 성공했습니다..!! 감사합니다
> 
> 근데 DotEnv를 어떻게 활용하는건지 아직 잘 모르겠습니다...

## 환경 변수 구성

[Webpack 환경 변수 구성 가이드 문서](https://euid.notion.site/c612f72f0ef6453da7a56a74e2696e8b) 질문이군요.
가이드 문서대로 구성한 다음 아래 안내 내용대로 사용할 수 있습니다.

`.env` 파일을 생성합니다.

```env
DB_HOST=127.0.0.1
DB_PASS=foobar
S3_API=mysecretkey
```

[DotEnv](https://github.com/mrsteele/dotenv-webpack#usage) 플러그인을 구성 했으므로 JavaScript 파일에서 환경 변수(`process.env.*`) 값을 사용할 수 있습니다.

```js
console.log(process.env.DB_HOST); // '127.0.0.1'
```

**Comment by ssw6750** [comment]
감사합니다!!!
