### ISSUE TITLE
[LAB-6] svg이미지 컴포넌트로 추가하기

### ISSUE THREAD

**Issue by realldk** [yamoo9/likelion-FEQA#112]
## 질문 작성자

이동경

## 문제 상황
CRA에서 svg를 컴포넌트로 추가할 수 있다는 글(https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs)을 보고 따라해봤는데  오류가 발생합니다. 

 위의 글에서 요구하는 `react-scripts@2.0.0 and higher, and react@16.3.0 and higher` 조건도 만족하는 것 같은데 어째서 안되는건지 궁금합니다.

```
import { ReactComponent as Logo } from './logo.svg';

function App() {
  return (
    <div>
      {/* Logo is an actual React component */}
      <Logo />
    </div>
  );
}
```
## 코드 검토 리소스

- [stackblitz.com 활용](https://stackblitz.com/edit/react-mkoiio?file=src/App.jsx)
해당 컴포넌트 부분에 주석처리를 해놓았습니다.

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
@realldk 님

확인 결과 Stackblitz 서비스에서 제공하는 CRA 템플릿 문제로 보입니다. 🤔
비슷한 서비스인 Code Sandbox의 CRA에서는 SVGR이 정상적으로 작동합니다.

[CRA with SVGR 데모](https://codesandbox.io/s/cra-with-svgr-spjp7w?file=/src/App.js)

<img width="1828" alt="" src="https://user-images.githubusercontent.com/1850554/221435165-b17a7a9e-02c3-45cd-970d-04b7805a52ed.png">

참고로 사진 파일은 SVG 포멧으로 변경할 경우 용량이 매우 커지기 때문에 성능 관점에서 문제가 됩니다.
사진 파일은 JPG 또는 PNG 포멧을 사용해야 합니다.

**Comment by realldk** [comment]
아 Stackblitz 문제였군요. 
사진 파일은 jpg 또는 png 포맷사용하기.
감사합니다 ^~^
