### ISSUE TITLE
[LAB-6] jsx 파일을 js형식으로 바꿔주는(컴파일) 도구

### ISSUE THREAD

**Issue by realldk** [yamoo9/likelion-FEQA#113]
## 질문 작성자

이동경

## 문제 상황

수업을 통해서 처음에는 babel로 환경설정을 했었고, CRA와 Vite에서는 따로 한 게 기억이 잘 안나는데 이 두 가지 패키지들은 설치만하면 자동으로 jsx파일을 js형식으로 컴파일 해주는 건가요?

**Comment by yamoo9** [comment]
네 맞습니다. @realldk님

React 개발 환경 구성은 "직접 구성하는 방법" 그리고 "툴체인을 활용하는 방법"이 있습니다.

Babel, Webpack 등과 같은 도구를 사용해 사용자가 직접 개발 환경을 구성하는 방법이 있고,
CRA, Vite 등과 같은 도구를 사용해 이미 갖춰진 개발 환경을 사용하는 방법이 있습니다.

React를 쉽게 시작하는 방법은 CRA 또는 Vite 같은 도구를 사용하는 것입니다.

**Comment by realldk** [comment]
이해했습니다! 감사합니다.
