### ISSUE TITLE
[LAB-2] tabindex 에 대하여

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#114]
## 질문 작성자

오승택

## 문제 상황
https://github.com/yamoo9/likelion-react/commit/915f395d7f04d9098ce32d6673ab45d827b5039b

![image](https://user-images.githubusercontent.com/109938280/221594608-9897f054-cb8b-4878-a1a1-398d29299f8d.png)

- 복습을 하던 도중 tabindex에 관하여 궁금해서 질문 드립니다 . 제가 알기로는 tabindex : -1 은 focusable ( 자바스크립트로 조작) 라고 설명을 해주셨는데요. 
``` javascript
if (targetElement) {
      // 실제 DOM 요소 조작
      targetElement.setAttribute('tabindex', -1);
```
- 위 코드에서 왜 tabindex :  -1 을 주었는지 , 그리구 -1 을 주었을 때 tabIndex={0} 이 왜 조건이 먹는지 궁금하여 질문을 드립니다

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
## 질문

남겨주신 질문을 파악하면 다음과 같습니다.

1. 왜 `tabindex : -1`을 주었나요? 
2. `-1`을 주었을 때 `tabIndex={0}` 왜 이 조건이 먹는지 궁금합니다.

```js
if (targetElement) {
  targetElement.setAttribute('tabindex', -1);
}
```

## 답변 1

대상 요소(target element)는 기본적으로 초점 이동이 가능하지 않은 `<div>` 요소입니다. 그러므로 JavaScript를 통해서만 초점 이동이 가능하도록 하기 위함 입니다. `-1` 값을 설정하면 JavaScript가 아닌, 사용자의 탭(tab) 키 탐색으로는 초점이 이동하지 않습니다.

```html
<div class="targetElement" tabindex="-1"> ... </div>
```

tabindex 속성 값에 따른 초점 이동 이해를 돕기 위한 DEMO [tabindex 속성에 대한 이해](https://jsbin.com/nepojacuta/edit?html,output)를 직접 실행해 이해 하길 바랍니다.

## 답변 2

질문을 이해할 수 없어 오히려 질문드려야 할 듯 하네요. "`-1`을 주었을 때 `tabIndex={0}`" 이 설정이 어디에 적용되었다는 건가요?

```js
if (targetElement) {
  targetElement.setAttribute('tabindex', -1);
}
```
