### ISSUE TITLE
[LAB-2] 고차컴포넌트에 대하여

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#115]
## 질문 작성자

오승택

## 문제 상황

- 커밋 기록을 보다가 질문이 있어 작성합니다 !
https://github.com/yamoo9/likelion-react/commit/915f395d7f04d9098ce32d6673ab45d827b5039b

![image](https://user-images.githubusercontent.com/109938280/221629193-1b2a39b0-9140-4d3c-bfb8-a222ef315c5f.png)

여기서 forwardRef 를 사용하여서 ref 가 props 를 받을 수 있게끔 사용을 해주었다는게 제가 이해한게 맞을까요 ?

또한 forwardRef 가 지금 고차 컴포넌트(HOC) 랑 비슷하게 쓰여진 걸까요 아니면 고차 컴포넌트 그 자체일까요 ? 제가 알기로는 with 을 붙여야만 

고차 컴포넌트 라고 쓰이는거 같은데.. 쓰임새가 고차 컴포넌트랑 매우 비슷하여 질문합니다 !

**Comment by yamoo9** [comment]
## 질문

1. forwardRef를 사용해 ref 가 props 를 받을 수 있게끔 사용을 해주었다는게 제가 이해한게 맞을까요 ?
2. forwardRef가 지금 고차 컴포넌트(HOC) 랑 비슷하게 쓰여진 걸까요? 아니면 고차 컴포넌트 그 자체일까요?<br/> 제가 알기로는 with 을 붙여야만 고차 컴포넌트 라고 쓰이는거 같은데.. 쓰임새가 고차 컴포넌트랑 매우 비슷하여 질문합니다 !

## 답변 1

Ref 전달하기([forwardRef](https://ko.reactjs.org/docs/forwarding-refs.html))는 컴포넌트가 전달받은 `ref`를 내부에 포함하는 요소에 전달하는 기능을 말합니다. 

```js
import { forwardRef } from 'react';

const MyInput = forwardRef(function MyInput(props, ref) {
  // ...
});
```

`forwardRef(render)` 함수가 실행되면 React 컴포넌트를 반환합니다. 
반환된 컴포넌트는 일반적인 React 컴포넌트와 달리 두 번째 인자로 `ref`를 전달 받습니다.

두 번째 `ref` 인자는 `React.forwardRef`를 통해 호출될 컴포넌트를 정의 했을 때에만 생성됩니다. 
일반 함수나 클래스 컴포넌트는 `ref` 인자를 받지도 않고 `props`에서 사용할 수도 없습니다.

```js
import { forwardRef, useId } from 'react';

const MyInput = forwardRef(function MyInput({ label, ...restProps }, ref) {
  const id = useId();
  return (
    <div className="MyInput">
      <label htmlFor={id}>{label}</label>
      <input ref={ref} {...restProps} id={id} />
    </div>
  );
});
```

## 답변 2

`forwardRef()` 함수는 전달 받은 컴포넌트에 기능(ref 전달)을 추가 하여 **고차 컴포넌트(HOC)를 반환**합니다.
즉, `forwardRef()`는 **고차 컴포넌트를 반환하는 함수**입니다. 아래 그림을 참고하세요.

<img width="200" alt="" src="https://user-images.githubusercontent.com/1850554/221649651-ec2399fe-1445-458c-ad09-496369a81df5.png">

그리고 고차 컴포넌트를 반환하는 함수의 경우, 관례적으로 이름 앞에 `with` 접두사를 붙이는 것일 뿐 이 규칙은 절대적 이지 않습니다.

아래 작성된 코드 예시는 표시(visible) 상태를 가지는 고차 컴포넌트를 반환하는 withVisibleState 함수입니다.

```js
import React from 'react';

export function withVisibleState(Component) {
  class WithVisibleState extends React.Component {
    state = { visible: true };

    handleVisible = () => {
      this.setState({ visible: true });
    };
    handleInvisible = () => {
      this.setState({ visible: false });
    };

    render() {
      const { visible } = this.state;
      return (
        <Component
          visible={visible}
          onVisible={this.handleVisible}
          onInvisible={this.handleInvisible}
          {...this.props}
        />
      );
    }
  }

  return WithVisibleState;
}
```

withVisibleState 함수를 사용해 WithVisibleStateHeadline 고차 컴포넌트를 작성하는 예시 코드는 다음과 같아요.

```jsx
import { withVisibleState } from "./withVisibleState";

export function Headline({ visible, onVisible, onInvisible, children, ...restProps }) {
  return (
    <div {...restProps} style={{ minHeight: 110, minWidth: 400, marginBottom: 80 }}>
      <button
        type="button"
        onClick={() => (visible ? onInvisible() : onVisible())}
      >
        {visible ? 'invisible' : 'visible'}
      </button>
      {visible && <h2>{children}</h2>}
    </div>
  );
}

export const WithVisibleStateHeadline = withVisibleState(Headline);
```

구현된 DEMO [고차 컴포넌트(Higher-order Component)](https://stackblitz.com/edit/vitejs-vite-etbqwb?file=src%2FApp.jsx,src%2FWithVisibleStateHeadline.jsx,src%2FwithVisibleState.jsx&terminal=dev) 코드를 참고해보세요.
