### ISSUE TITLE
[LAB-12] 스택블리츠 프로젝트를 깃헙 저장소와 연결했을 때 발생하는 문제

### ISSUE THREAD

**Issue by sykang013** [yamoo9/likelion-FEQA#116]
## 질문 작성자

강수영

## 문제 상황

- 리액트 과제 제출 후, 스택블리츠를 만져보던 중 프로젝트를 깃헙 저장소에 연결하는것이 있어 수행해보았습니다. 그 후 정확한 타이밍은 잘 모르겠지만 아래와같은 문제가 발생했는데, 원인을 잘 모르겠습니다. 깃헙 레포 연결 중 뭔가 꼬인걸까요?

- 문제1. 프로젝트를 스택블리츠에서 오픈 한 경우, 잘 나오던 제품 사진이 나오지 않습니다.
![image](https://user-images.githubusercontent.com/113448786/221898872-5337218a-4f96-445a-b214-5c9d2df732ca.png)

- 문제2. 프로젝트를 깃헙레포에서 압축파일로 다운받고 `vsc`에서 `npm run start`로 오픈한 경우, 사진도 뜨지 않지만(ㅠㅠ)` a11y.css`가 작동되지 않는것 같습니다.
  <img width="358" alt="image" src="https://user-images.githubusercontent.com/113448786/221900922-2f23f112-578c-47a8-9ff9-be1f1fadb13e.png">

## 코드 검토 리소스
- [stackblitz.com 활용](https://stackblitz.com/edit/react-pgwc2u)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 macOS
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요 @sykang013 님. 고생이 많으십니다.
이 건은 stackbliz 의 cra 구현과 실제 cra가 달라서 발생하는 문제로 보여요. 임포트하실때 문제가 생긴건 아닌것 같습니다.
(stackbliz 가 생각하는 cra는 과거에 머물러 있는데, 실제 cra는 업그레이드가 되어 있는 등)
그래서 아래와 같은 해결방법을  가져와 보았습니다.

> 문제1. 프로젝트를 스택블리츠에서 오픈 한 경우, 잘 나오던 제품 사진이 나오지 않습니다.

cra로 이미지를 표시하려면, [webpack의 도움을 받아 이미지 경로를 주입받거나](https://create-react-app.dev/docs/adding-images-fonts-and-files/), public 폴더의 이미지를 불러오는 방법이 있습니다.
그런데  스택블리츠는 [webpack의 도움을 받아 이미지 경로를 주입받는 방법](https://create-react-app.dev/docs/adding-images-fonts-and-files/)에서 에러가 발생하는군요.. 번거로우시겠지만 public 폴더에 이미지를 두시고, 그것을 불러오도록 수정하시는게 좋겠습니다.

> 문제2. 프로젝트를 깃헙레포에서 압축파일로 다운받고 vsc에서 npm run start로 오픈한 경우, 사진도 뜨지 않지만(ㅠㅠ) a11y.css가 작동되지 않는것 같습니다.

[css module의 문서에 따르면.. css 모듈 안에서 외부 css를 임포트하려면 조금 특수한 문법을 사용해야 하는 모양입니다.](https://github.com/css-modules/css-modules#composing-from-other-files)
그런데 stackbliz는 `@import` 로 가져온 css classe 들도 모듈에 있었던 것처럼 가져와주네요?(뭐지?)
아래와 같은 코드로 cra 와 stackbliz용 cra 모두에 호환되는 코드를 작성해보는건 어떨까 생각합니다.
```css
/*a11y 임포트 [s]*/
@import '../../a11y.css';

.a11y {
  composes: a11y from "../../a11y.css";
}
/*a11y 임포트 [e]*/
```

도움이 되었기를 바랍니다. 화이팅!
