### ISSUE TITLE
[LAB-17] setState 함수의 실행에 관하여

### ISSUE THREAD

**Issue by nahee09** [yamoo9/likelion-FEQA#117]
## 질문 작성자

김나희

## 문제 상황
야무쌤께서 이슈에서 stateful, stateless를 설명하시며 첨부해주셨던 코드입니다. 

[ToggleButton.js]
```javascript
import { useState } from "react";

export default function ToggleButton(props) {
  const [toggleState, setToggleState] = useState(props.on);

  const handleToggle = () => {
    setToggleState((toggleState) => !toggleState);
    console.log("a", toggleState);
    props.onToggled?.(toggleState);
    console.log("b", toggleState);
  };
  
  console.log("c", toggleState);

  return (
    <button
      type="button"
      className={`ToggleButton ${toggleState ? "on" : ""}.trim()`}
      onClick={handleToggle}
    >
      {toggleState ? props.offText : props.onText}
    </button>
  );
}

ToggleButton.defaultProps = {
  on: false,
  onText: "ON",
  offText: "OFF"
};
```

[App.js]
```javascript 
import "./styles.css";
import ToggleButton from "./ToggleButton";

export default function App() {
  return (
    <div className="App">
      <ToggleButton
        onToggled={(toggleState) => {
          // 버튼이 토글 되면 상위 컴포넌트에서 토글 상태를 확인할 수 있습니다.
          console.log(toggleState);
        }}
      />
    </div>
  );
}

```
이 코드를 실행시켜서 **버튼을 클릭해보면** 
```javascript 
  const handleToggle = () => {
    setToggleState((toggleState) => !toggleState);
    props.onToggled?.(toggleState);
  };
```
제 생각에는 이 부분에 의하여 setToggleState함수가 먼저 실행돼서 toggleState의 기본값인 false가 true로 바뀐 다음,  props.onToggled?.(toggleState);가 실행되어 **콘솔창에 true가 나올줄 알았습니다. 하지만 false가 나오더군요.** 
그래서 console.log를 곳곳에 끼워넣어 값을 확인해봤는데 왜 아래처럼 나오는지 잘 모르겠습니다. 설명해주실 수 있을까요? 

[초기 실행 결과]
<img width="99" alt="image" src="https://user-images.githubusercontent.com/119389649/221927630-aea246cf-c36f-4e69-bba6-b85f16af2607.png">

[버튼 클릭 결과]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/119389649/221927778-81a9fefc-994a-421f-982c-1ab5aa0e666b.png">

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

https://codesandbox.io/s/funny-sky-msl69z?file=/src/index.js

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요 @nahee09 님. ^^
react.js 는 `setState` 함수(=예제에서는 `setToggleState` 함수)가 실행되면 컴포넌트를 다시 그리도록 만들어져 있습니다.
그래서 바로 아랫줄에서 `props.onToggled?.(toggleState);` 를 호출하는 시점에는 값이 바뀌지 않은 것입니다.
원하시는 대로 구현을 하시려면, `props.onToggled?.(!toggleState);` 처럼 값을 반대로 지정해 주어야 할 것 같습니다.

제가 문제를 잘 이해했길 바랍니다.
참고로, 현업에서 QA를 할 경우의 팁이긴 한데.. [기대결과] 와 [실제결과]를 대조되도록 문장을 다시 써 주시면 도움이 될 것 같습니다.
콘솔창에 출력되는 정보가 여러개라 확인이 좀 어렵군요.

**Comment by yamoo9** [comment]
## 질문

setToggleState 함수가 먼저 실행돼서 `toggleState`의 기본값인 `false`가 `true`로 바뀐 다음
`props.onToggled?.(toggleState)`가 실행되어 콘솔창에 `true`가 나올줄 알았습니다. 하지만 `false`가 나오더군요.

그래서 `console.log`를 곳곳에 끼워넣어 값을 확인해봤는데 왜 아래처럼 나오는지 잘 모르겠습니다. 
설명해주실 수 있을까요?

[초기 실행 결과]

<img src="https://user-images.githubusercontent.com/119389649/221927630-aea246cf-c36f-4e69-bba6-b85f16af2607.png" width="120" />

[버튼 클릭 결과]

<img src="https://user-images.githubusercontent.com/119389649/221927778-81a9fefc-994a-421f-982c-1ab5aa0e666b.png" width="300" />

## 답변

아래 코드는 사실 문제가 있습니다. 왜냐하면 **React의 상태 변경은 비동기(async)로 처리되기 때문**입니다.

```jsx
const handleToggle = () => {
  setToggleState((toggleState) => !toggleState);
  props.onToggled?.(toggleState);
};
```

### 문제 원인에 대한 이해

생각해보면 **상태 변경은 비동기로 처리되는 것이 효과적입니다.** 

동기(sync)적으로 상태를 업데이트 하려 한다면? 여러 번 상태 변경이 요구될 때, 
스택(stack)에 쌓인 렌더링을 순차적으로 실행해야 하므로 비 효율적입니다.

그래서 리액트는 **여러 상태 변경 요구사항을 비동기로 가장 효과적인 때에 맞춰 실행합**니다.
그러므로 `setToggleState()` 아래 위치한 `toggleState`는 **업데이트 되기 이전 상태 값**입니다.

아래 추가한 주석을 참고해주세요.

```jsx
const handleToggle = () => {
  // [👨🏻‍💻 개발자] toggleState 값을 true → false로 변경해 
  // [🤖 리액트] 비동기로 상태를 업데이트 할 것입니다.
  setToggleState((toggleState) => !toggleState);
  // [🤖 리액트] 변경되기 전인 현재 상태 값을 전달해 실행합니다.
  props.onToggled?.(toggleState);
};
```

### 문제 해결의 KEY

그럼 이 문제를 어떻게 해결하면 좋을까요? 🤔

해결 방법은 **useEffect 훅의 종속성 배열(dependency list)**에 있습니다.
사실 이 문제의 요구사항은 **상태가 변경되면 변경된 상태를 상위 컴포넌트에 알리고 싶다**입니다.
즉, 핵심은 **상태 변경을 감지하여 콜백한다**인 거죠.

이해를 돕기 위해 남긴 아래 남긴 주석을 참고해보세요.

```jsx
const [toggleState, setToggleState] = useState(on);

useEffect(
  // 이펙트 콜백
  () => {
    console.log('1. toggleState 변경 됨:', toggleState)
    props.onToggled?.(toggleState)
  }, 
  // [🤖 리액트]
  // toggleState 또는 props.onToggled 값이 변경되면
  // 이펙트 콜백을 실행합니다.
  [toggleState, props.onToggled]
);

function handleToggle() {
  setToggleState((toggleState) => !toggleState)
}
```

### 문제 해결 DEMO

답변한 상황 이해를 돕기 위해 작성된 [ToggleButton 상태 DEMO](https://codesandbox.io/s/togglebutton-state-exm522?file=/src/ToggleButton.js)를 참고하고 상황을 확인해보길 바랍니다. 😃
