### ISSUE TITLE
[LAB-4] 웹팩 관련 질문있습니다.

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#118]
## 질문 작성자

서석원

## 문제 상황
[React Refresh 구성](https://euid.notion.site/React-Refresh-0d4110dc2fc14a59881007386e3ed58a)을 따라하기가 어렵습니다.
노션에서는 server config에 devConfig를 map()으로 돌리는 로직을 사용하는데 현재 저의 세팅으로는 어떻게 로직을 작성해야 할지 모르겠습니다.
그리고 React Refresh 구성하지 않는 현재 설정에서도 코드가 바뀔 때 마다 자동 새로고침을 해주는데 React Refresh가 정확히 무슨 효과인지 잘 모르겠습니다.
![q02-1](https://user-images.githubusercontent.com/73629761/222140619-cf44651d-6d13-4c67-82a2-3bb0f4409878.PNG)
![q02-2](https://user-images.githubusercontent.com/73629761/222140631-c9f2c413-0c15-401d-b8e5-c73a3b0a3213.PNG)

## 코드 검토 리소스
[웹팩 설정 레포지토리](https://github.com/ssw6750/webpackscaffolding-boilerplate)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요. @ssw6750 님. 
최근에 나오는 프레임워크엔 기본적으로 탑재된 기능이라 다룰 일이 없을줄 알았는데, 덕분에 저도 공부를 많이 했습니다.
[자세한 코드는 보내드린 PR을 확인해주세요.](https://github.com/ssw6750/webpackscaffolding-boilerplate/pull/1/files)

> 노션에서는 server config에 devConfig를 map()으로 돌리는 로직을 사용하는데 현재 저의 세팅으로는 어떻게 로직을 작성해야 할지 모르겠습니다.

더 좋은 방법이 있을 수 있겠지만, 저는 [이렇게 복잡한 설정파일을 다룰 때는 타입스크립트의 도움을 받는 것을 추천하고 싶습니다.](https://github.com/ssw6750/webpackscaffolding-boilerplate/pull/1/files#r1121989667)
타입스크립트의 자동완성 기능을 빌려오시면 코드를 잘못 작성할 확률이 낮아집니다.

> 그리고 React Refresh 구성하지 않는 현재 설정에서도 코드가 바뀔 때 마다 자동 새로고침을 해주는데 React Refresh가 정확히 무슨 효과인지 잘 모르겠습니다.

기존에 구현된 자동 새로고침은 liveReload 기능이 동작한 결과물입니다. 페이지 전체가 새로고침 됩니다.
<img src="https://user-images.githubusercontent.com/1357198/222200116-4e4c3a30-fea4-4bc4-8f37-67bab59b0f31.gif" width="50%">

이것이 React Refresh 의 효과입니다. 패이지 전체가 새로고침 되지 않습니다.
<img src="https://user-images.githubusercontent.com/1357198/222200326-e1c88670-d14e-4dbc-a8ab-07921e67bd75.gif" width="50%">

**Comment by ssw6750** [comment]
아하 타입스크립트가 여기서도 도움을 주는군요!
적용해보겠습니다. 답변 감사드립니다! !
