### ISSUE TITLE
[LAB-14] 데이터가 많을 수록 useState보다 useRef 사용을 먼저 고려하나요?

### ISSUE THREAD

**Issue by jh1109** [yamoo9/likelion-FEQA#119]
## 질문 작성자

노주희

## 문제 상황

- 오늘(3/2) react 기초 특강 때 useState와 useRef를 사용해서 배경색 바꾸는 기능을 구현했는데요.
- 성능 차이를 보여주셨을 때 useRef가 리렌더링 하지 않으니 확실히 성능이 좋은 것을 확인했습니다.
- (그래서 가능하면 최대한 useRef을 사용해서 기능을 구현시키는 게 좋은 거겠구나! 라는 생각이 들었는데요.)
- 데이터가 많을 수록 그 차이가 더 심해질 것 같은데, 데이터가 많을 수록 useState보다 useRef 사용을 먼저 고려하나요?

첨부한 사진은 수업 때 명령형으로 작성한 코드입니다.
![useRef](https://user-images.githubusercontent.com/117807467/222464855-520fde2b-8194-4dc6-8b75-97fe156ca1b5.png)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요. @jh1109 님! 상당한 고급 기술을 배우셨군요..!
제가 아는 선에서 첨언을 하자면...

> (그래서 가능하면 최대한 useRef을 사용해서 기능을 구현시키는 게 좋은 거겠구나! 라는 생각이 들었는데요.)

너무 좋은 지점에 도달하셔서 조언을 남기지 않을 수가 없네요!
사견입니다만, react.js 는 홈페이지 첫 화면에서 기본적으로 선언형 라이브러리임을 명시하고 있으므로(=철학을 밝히고 있으므로)
(철학이라는 것이 옳고 그름을 판단하는 기준이 된다는 것을 고려하자면)우선은 선언형으로 개발을 하는게 좋다고 생각합니다.
그래서 저는 아래와 같은 경우에 `useRef`를 사용하는 것이 좋다는 기준을 가지고 있습니다.
1. 성능을 고려해야 할 경우
2. `<canvas />`, `<video />` 처럼 명령형 api로만 제어하는 컨테이너를 사용하는 경우


> 데이터가 많을 수록 그 차이가 더 심해질 것 같은데, 데이터가 많을 수록 useState보다 useRef 사용을 먼저 고려하나요?

네 맞습니다!
저는 수천건 ~ 수만건의 배열 데이터를 수시로 업데이트하는 datagrid 같은 것에서 useRef로 제어하는 코드를 본 적이 있습니다.
보여주신 예제처럼 빈번한 업데이트가 일어날 수 있는 케이스에도 고려를 해 봐야 할것 같습니다.

하지만 `useRef`를 사용하면 맥락이 좀 복잡해지는 단점이 있습니다.
(동작을 파악하기 위해 `useRef`의 근원과 예상 동작을 찾아 해매야 함)
코드가 길어지면 이게 유지보수를 어렵게 만드는 근원이 되니 컴포넌트를 아주 잘게 쪼개려는 노력(=컴포넌트를 일반화하려는 노력)을 해 주면 좋을것 같습니다.
(`useRef`를 남발한.. 300줄이 넘는 코드를 본 적이 있음)

**Comment by yamoo9** [comment]
안녕하세요 주희님 ^^

재원 멘토님께서 자세히 이야기 해주셔서 잘 이해 되셨을 거 같아요.
그래서 저는 첨부된 이미지의 코드 중 문제가 될 수 있는 부분을 말씀드려볼께요.

명령형 프로그래밍 예시를 다룬 ChangeBackgroundImperative 컴포넌트가 현재 관리하는 상태가 없어 문제가 안될 수 있지만, 만약 예시가 아니라 실제 컴포넌트 코드에서 선언형과 명령형을 섞어 사용했을 때 useEffect 훅의 종속성 배열(dependency List)은 꼭 신경써주셔야 해요! 

상태가 변경될 경우 컴포넌트는 리-렌더링 되고, useEffect 훅의 종속성 배열이 설정되지 않으면 이펙트 콜백(effect callback)은 반드시 실행 되요. 그럼 내부에 이미 연결된 이벤트 핸들링 코드가 반복되는 문제가 발생해요. 😥

```jsx
useEffect(() => {
  colorInputRef.current.addEventListener('input', (e) => {
    boxRef.current.style.backgroundColor = e.target.value;
  });
});
```

마운트 시점에 한 번만 이벤트가 연결되어야 하는데 리-렌더링 될 때 마다 불필요하게 이벤트가 연결되는 거죠. 하지만 아래처럼 종속성 배열을 설정만 하면 컴포넌트 리-렌더링과 상관없이 이벤트가 반복 연결되지 않아요. 😃

```jsx
useEffect(() => {
  colorInputRef.current.addEventListener('input', (e) => {
    boxRef.current.style.backgroundColor = e.target.value;
  });
}, []);
```

나아가 연결한 이벤트는 컴포넌트가 언 마운트 될 때 연결 해제해주는 것이 좋겠죠? 리액트에서 명령형 프로그래밍을 사용할 때 클린업 함수를 사용해서 이벤트 연결까지 해제해주는 습관 꼭 들이길 바랍니다. 😊

```jsx
useEffect(() => {

  const handleChangeColorInput = (e) => {
    boxRef.current.style.backgroundColor = e.target.value;
  };

  colorInputRef.current.addEventListener('input', handleChangeColorInput);

  // 클린업
  return () => colorInputRef.current.removeEventListener('input', handleChangeColorInput);

}, []);
```

**Comment by jh1109** [comment]
말씀해주신 내용 바탕으로 useState와 useRef 사용에 대해 고민해보겠습니다!!
선언형과 명령형, useEffect 클린업 부분 개념이 모호했는데 리마인드 되었습니다. 감사합니다 :)
