### ISSUE TITLE
🛎️ 중첩함수의 this에 대해 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#12]
## 문제 상황

중첩 함수나 메소드 내의 일반 함수에서 this는 전역을 가리키는데, 이 원리에 대해서 궁금합니다.
제가 나름대로 **추측**을 해봤는데 피드백 해주시면 감사하겠습니다.

1. **메소드 내의 일반 함수** 
t7의 this는 일반함수이기 때문에 바인딩할 객체를 찾아야 하는데 객체를 통해 호출된 것이 아니고 함수에서 호출했기 때문에
바인딩할 객체가 없어 결국 전역객체를 가리키게된다.

2. **중첩 함수**
tt1은 전역에서 호출했기 때문에 전역을 가리키고
tt2는 함수에서 호출했기 때문에, 바인딩할 객체를 찾지 못해 전역객체를 가리킨다.
![중첩함수](https://user-images.githubusercontent.com/73629761/210800233-758d6ddc-ab8b-4bf1-927b-0d1f72d8e062.PNG)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.4.0)

**Comment by yamoo9** [comment]
## 중첩된 일반 함수의 this

JavaScript 월드에서 **객체의 메서드가 아닌 함수를 호출하면 대부분의 브라우저에서 전역 객체(Window)를 가리키게 됩니다.**

화살표 함수가 등장하기 이전까지의 모든 함수는 고유한 `this` 값을 정의했습니다.

- 생성자 함수인 경우, 생성된 인스턴스(객체)를 가리킴
- 객체의 메서드인 경우, 메서드를 소유한 객체를 가리킴
- 엄격 모드(strict mode)인 경우에는 `undefined`

하지만 이런 방식은 객체 지향 프로그래밍 스타일과 잘 맞지 않았습니다.
그런 불편함을 화살표 함수가 해결해주었습니다. 화살표 함수에는 `this`가 없습니다. 
화살표 함수를 포함하는 객체 값이 사용됩니다. ( #13 답글 참고)
