### ISSUE TITLE
[LAB-4] ESLint 웹팩(Webpack) 구성 질문있습니다.

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#120]
## 질문 작성자

서석원

## 문제 상황

현재 웹팩에 타입스크립트 환경을 적용하고 있습니다.
제가 타입스크립트에 익숙하지 않아서 에러를 대처하기가 어려워 여러 질문을 올립니다.

q1. 해당 에러를 해결하는 방법을 모르겠습니다. 린트 문제인것 같은데,, 환경 설정을 아무렇게나 시도하는 것보단 질문하는게 좋다고 판단하였습니다.
![q03-1](https://user-images.githubusercontent.com/73629761/222485497-a577238c-9b02-4ad3-aa14-a0e2c2a775a1.PNG)

q2. 해당 사진처럼 '~' is not defined로 나오는 에러는 타입지정을 안해서 나타나는 에러인가요? 만약 그렇다면 세부 환경 코드들을 다 타입을 지정해줘야 하는건가요..? 만약 그렇다면 어떻게 고쳐야 할지 파일만 하나만 예시로 보고 싶습니다..!  
![q03-2](https://user-images.githubusercontent.com/73629761/222486266-f3c35aa8-8cc1-4231-86fb-342a5de1e538.PNG)

q3. [css 모듈 구성](https://euid.notion.site/CSS-22d3e0d9e84045d5a146d3f9815e215a)을 보고 타입스크립트 환경을 구성했는데, 이제 모듈css를 어떻게 적용해야 하는지 모르겠습니다. 예시를 알려주시면 감사하겠습니다.
![q03-3](https://user-images.githubusercontent.com/73629761/222487732-77c63d87-594e-43c4-8937-bbaf72850d97.PNG)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

[타입스크립트 웹팩 설정 레포](https://github.com/ssw6750/webpack-scaffolding-TypeScript)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요. 님. 와우.. 어려운 작업에 도전하고 계시네요.
마침 도와드릴 수 있는 상황이라 다행입니다.
이런 류의 도전은 중도에 포기하면 정말 죽도 밥도 안 되는 것이라..
[자세한 내용은 보내드린 PR을 확인해주세요.](https://github.com/ssw6750/webpack-scaffolding-TypeScript/pull/1/files)

> q1. 해당 에러를 해결하는 방법을 모르겠습니다. 린트 문제인것 같은데,, 환경 설정을 아무렇게나 시도하는 것보단 질문하는게 좋다고 판단하였습니다.

네 맞습니다. 이 에러는 eslint 의 import 라는 플러그인이 활성화되지 않아서 발생하는 에러입니다.
[플러그인을 설치하시고](https://github.com/ssw6750/webpack-scaffolding-TypeScript/pull/1/files#r1123527844), [활성화 해 주세요.](https://github.com/ssw6750/webpack-scaffolding-TypeScript/pull/1/files#r1123526545)

> q2. 해당 사진처럼 '~' is not defined로 나오는 에러는 타입지정을 안해서 나타나는 에러인가요? 만약 그렇다면 세부 환경 코드들을 다 타입을 지정해줘야 하는건가요..? 만약 그렇다면 어떻게 고쳐야 할지 파일만 하나만 예시로 보고 싶습니다..!

네 맞습니다. '~' is not defined로 나오는 에러는 타입을 일일히 지정해줘야 해요.
이 지점이 상당히 귀찮긴 한데, 자바스크립트의 모자란 부분을 매꿔주는 것이라 어쩔수가 없습니다.
다행히도 이 에러는 eslint가 실행환경을 파악하지 못해서 발생하는 에러라 손이 덜 가겠네요 ㅎㅎ
`window.$` , `process.env` 등을 사용하고자 하는 상황에서는 다르게 대처해야 합니다.
조만간 그런 상황을 마주할 수 있기를 바랍니다. ^^
이 경우에는 [이 프로젝트가 어떤 환경에서 동작하는지 eslint에게 알려주면 해결됩니다.](https://github.com/ssw6750/webpack-scaffolding-TypeScript/pull/1/files#r1123525715)

> q3. [css 모듈 구성](https://euid.notion.site/CSS-22d3e0d9e84045d5a146d3f9815e215a)을 보고 타입스크립트 환경을 구성했는데, 이제 모듈css를 어떻게 적용해야 하는지 모르겠습니다. 예시를 알려주시면 감사하겠습니다.

[`typeRoots` 설정에 오타가 있었네요.](https://github.com/ssw6750/webpack-scaffolding-TypeScript/pull/1/files#r1123531995)
그리고 [`typescript-plugin-css-modules` 를 잊지 말고 설치해 주어야 하겠습니다.](https://github.com/ssw6750/webpack-scaffolding-TypeScript/pull/1/files#r1123529000)

**Comment by ssw6750** [comment]
정말 감사합니다...!! 이럴때 도전해보는거죠..!!
