### ISSUE TITLE
[LAB-1] 공식문서에서 말하는 컴포넌트 합성에 대해서 알고 싶습니다.

### ISSUE THREAD

**Issue by kyoungholee** [yamoo9/likelion-FEQA#121]
## 질문 작성자

이경호

## 문제 상황

3월 3일 Prop drilling을 해결하기 위해 ContextAPI를 이용해 Provider를 이용하면 쉽게 해결 할 수 있다고 배웠습니다. 하지만 Provider를 자주 사용 하게 되면 Provider 지옥에 빠질 수도 있고, 공식문서에서도 Prop drilling를 피하기 위한 목적이라면 Component Composition(컴포넌트 합성)을 사용하라고 하는데  컴포넌트합성에 대해서 잘 모르겠습니다. 아무리 공식문서를 읽어도 잘 이해가 되질 않네요 ㅠㅠ. 설명 및 간단한 예제 코드도 부탁드립니다. 

![컴포넌트 합성](https://user-images.githubusercontent.com/65242726/222700825-02676f1d-7c37-45c4-ba3f-353b481616eb.PNG)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요. @kyoungholee 님. 굉장히 심오한 주제를 가지고 오셨네요.
이전 류의 주제는 글로 설명하면 엄청 지루한데.. 잘 전달이 되길 바랍니다.
이해를 돕기 위해 공식문서에서 예로 든 `<Avatar />` 를 가지고 설명을 해 보겠습니다.

# 문제
우리는 `<Avatar />` 라는 컴포넌트를 구현해야 합니다.
<img src="https://user-images.githubusercontent.com/1357198/222714068-3a26f328-614b-456b-ad20-0678078b96ec.png" width="144">

---

# Props Drilling 으로 구현하기
`<Avatar />` 는 `user` 라는 props 를 받습니다.
`<Avatar />` 는 `user` 를  `<Name>`과 `<Image />` 라는 컴포넌트에게 나누어주고 있습니다.
전형적인 props drilling 입니다.
[코드로 구현하면 이런 모습이 될 수 있겠네요.](https://codesandbox.io/s/avartar-1-oz6sxn)
```jsx
const Name = ({ name }) => {
  return <label>{name}</label>;
};

const Image = ({ pic }) => {
  return <img style={{ width: 144 }} src={pic} alt="사진" />;
};

const Avatar = ({ user }) => {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: 8
      }}
    >
      <Image pic={user.pic} />
      <Name name={user.name} />
    </div>
  );
};

export default function App() {
  const user = {
    name: "슬비님",
    pic: "pic.png"
  };

  return <Avatar user={user} />;
}
```

---

# context api 로 props drilling 해소하기
props drilling이  눈에 거슬리니 context api 로 구현을 해 봅시다.
[그러면  코드가 이런 모습이 되겠네요.](https://codesandbox.io/s/avartar-2-5r1wqv)
재활용이 힘들어지고 코드가 좀 복잡해졌지만, 나쁘지 않습니다.

```jsx
import { createContext, useContext } from "react";

const AvatarContext = createContext();

const AvatarContextProvider = ({ children }) => {
  const user = {
    name: "슬비님",
    pic: "pic.png"
  };

  return (
    <AvatarContext.Provider value={user}>{children}</AvatarContext.Provider>
  );
};

const Name = () => {
  const { name } = useContext(AvatarContext);

  return <label>{name}</label>;
};

const Image = () => {
  const { pic } = useContext(AvatarContext);

  return <img style={{ width: 144 }} src={pic} alt="사진" />;
};

const Avatar = () => {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: 8
      }}
    >
      {/* props drilling 해소! */}
      <Image />
      <Name />
    </div>
  );
};

export default function App() {
  return (
    <AvatarContextProvider>
      {/* props drilling 해소! */}
      <Avatar />
    </AvatarContextProvider>
  );
}
```

---

# 컴포넌트 합성 이용하기
애시당초 props 가 파고들어간다고해서 props drilling 이라는 이름이 붙었다고 했습니다.
컴포넌트가 각자의 책임만 다 하게 구현하면 파고들어갈 이유가 없지 않을까요?
`props`가 컴포넌트 내부로 파고 들어가지 않는다면 context api를 사용하지 않아도 되겠네요?
[그러면  코드가 이런 모습이 됩니다.](https://codesandbox.io/s/avartar-3-kjq2h0)

안에 무엇이 들어오든 프로필 레이아웃을 그리는 것에만 관심이 있는 `<Avatar />` 를 구현했습니다.
그리고 그 안에 그림을 표시하는 것에만 관심이 있는 `<Image />`, 이름을 표시하는 것에만 관심이 있는  `<Name />` 를 넣었습니다.
관심사를 철저하게 분리하면(=컴포넌트의 역활을 일반화하면) 요구사항을 단순하게 구현할 수 있습니다.

각자의 역활에만 충실한 컴포넌트를 조합해서 사용하면 유지보수성을 끌어올릴 수 있겠군요.
어느 쪽의 코드가 눈에 더 잘 들어오시나요?
```jsx
// 이름을 표시하는 일에만 관심이 있음(사실은 이름이 아니어도 상관이 없음).
const Name = ({ name }) => {
  return <label>{name}</label>;
};

// 그림을 표시하는 일에만 관심이 있음.
const Image = ({ pic }) => {
  return <img style={{ width: 144 }} src={pic} alt="사진" />;
};

// 레이아웃을 표시하는 일에만 관심이 있음. 안에는 무엇이 들어와도 상관하지 않음
const Avatar = ({ children }) => {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: 8
      }}
    >
      {children}
    </div>
  );
};

export default function App() {
  const user = {
    name: "슬비님",
    pic: "pic.png"
  };

  return (
    <Avatar>
      <Image pic={user.pic} />
      <Name name={user.name} />
    </Avatar>
  );
}
```

**Comment by shoveller** [comment]
글을 다 적고나니 HTML/CSS 에서 말하는 Container/Wrapper 와 비슷하면서 일맥상통하는 면이 있군요..

**Comment by kyoungholee** [comment]
멘토님의 자세한 설명 너무 감사드립니다!!! 확실히 혼자 이해하려고 했을 때보다 더 이해할 수 있었던 것 같습니다~!! 이제 좀 알게된 것 같습니다~!! 감사합니다~ 😊 주말 잘 보내세요~
