### ISSUE TITLE
[LAB-11] 컴포넌트에서 props를 받을 때 사용하는 구조분해할당 문법에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by to06109** [yamoo9/likelion-FEQA#122]
## 질문 작성자

최예송

## 문제 상황
```js
export function usePhotos({ limit = 20, page = 1 } = {}) {
  return useFetch(
    `${import.meta.env.VITE_PHOTOS_API}?_page=${page}&_limit=${limit}`
  );
}
```
2월 28일 수업시간 질의응답에서 다뤘었는데 완벽히 이해되지 않아서 질문드립니다. 

컴포넌트에서 props를 받을 때 위 코드에서처럼 객체 구조분해 할당과 합성 등을 이용해 받을 수 있다고 하셨는데,
`{ limit = 20, page = 1 } = {}` 에서 `={}` 이 부분을 왜 사용하는 것인지 궁금합니다. 
개인적으로 추론한 바로는 리액트에서 default값을 지정해주는 문법처럼 `함수 인자로 받는 props의 default 타입? 을 객체로 지정해준다` 의 의미가 아닐까 생각했는데 맞을까요?

**Comment by shoveller** [comment]
안녕하세요! @to06109 님. 

> 함수 인자로 받는 props의 default 타입? 을 객체로 지정해준다 의 의미가 아닐까 생각했는데 맞을까요?

네 거의 틀림이 없습니다.
아래의 코드를 브라우저의 개발자 도구에 붙여넣고 실행해 보시겠어요?
```js
var 함수 = ({ 갯수 = 20 }) => {
    return 갯수
}

함수() // Uncaught TypeError: Cannot read properties of undefined (reading '갯수')
함수(1) // 20
함수(2) // 20
함수({}) // 20

// {} 은 { 갯수 = 20 } 의 기본값!
var 안전함수 = ({ 갯수 = 20 } = {}) => {
    return 갯수
}
안전함수() // 20
```

파라미터에 `{ 갯수 = 20 }` 를 지정해 준 이유는,  `함수` 를 호출할 때 `갯수를 담은 객체`를 인자로 넘기지 않아도 에러가 나지 않게 막기 위해서입니다.
그런데 이 조차도 객체든 뭐든 인자로 넘겨야 의도한대로 동작을 합니다.
질문에서 언급하신대로 `={}` 은 `props`의 `defaultProps` 처럼 기본값을 지정하는 기능을 구현하기 위해 사용한 것입니다.
그것도 자바스크립트 문법만 사용해서 구현한 가치있는 코드로 보입니다.

**Comment by to06109** [comment]
헉 default값도 뭐든 인자로 넘겨줘야 적용이 되는거였군요
이해했습니다 자세한 설명 감사합니다!!
