### ISSUE TITLE
[LAB-4] forwardRef 안 함수선언문을 썼을 때 defaultProps 사용여부

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#123]
## 질문 작성자

김하연

## 문제 상황
1. 수업중에 displayName을 통해서 이름을 명시적으로 바꿔줬었습니다!
근데 이 방식 말고 함수 선언문을 쓰면 그 함수이름으로 추론할 수 있었습니다.
[](url)
이때 함수선언문을 썼기 때문에 defaultProps 를 바깥에 쓰지 못하고 
구조분해 할당을 통해서 안에서 받아줘야 한다고 이해했습니다.
근데 제가 실습을 하면서 보니 바깥쪽에 defaultProps를 써도 아무 문제 없이 반영 되는 것 같은데 제 코드에 오류가 있는 것일까요?
``` js
import { forwardRef } from "react";
import classes from "./A11yHidden.module.css";

export const A11yHidden = forwardRef(function A11yHidden(
  { as: ComponentName, focusable, className, ...restProps },
  ref
) {
  const combinedClassNames = `${classes.srOnly} ${
    focusable ? classes.focusable : ""
  } ${className}`.trim();

  return (
    <ComponentName ref={ref} className={combinedClassNames} {...restProps} />
  );
});

//A11yHidden.displayName = "A11yHidden";

A11yHidden.defaultProps = {
  as: "span",
  className: "",
  focusable: false,
};
```
<img width="244" alt="스크린샷 2023-03-05 오전 3 58 21" src="https://user-images.githubusercontent.com/111109573/222923951-b8a5c093-405e-4452-ba15-7c638b9c1876.png">

---

2. 그리고 `function A11yHidden(props, ref){}` 이렇게 써줬는데
개발자도구에서 확인했을 때 `A11yHidden2` 로 나오는 이유가 뭘까요..?
<img width="212" alt="스크린샷 2023-03-05 오전 3 52 02" src="https://user-images.githubusercontent.com/111109573/222923713-53ad5e73-31ef-4e94-80c0-74cf14ddd112.png">

제가 쓴 코드

```js
export const A11yHidden = forwardRef(function A11yHidden(
  { as: ComponentName, focusable, className, ...restProps },
  ref
) {

  const combinedClassNames = `${classes.srOnly} ${
    focusable ? classes.focusable : ""
  } ${className}`.trim();

  return (
    <ComponentName ref={ref} className={combinedClassNames} {...restProps} />
  );
});
```

혹시몰라서 노드모듈 지우고 압축한 파일 넣었습니다..!
[study-react 2.zip](https://github.com/yamoo9/likelion-FEQA/files/10889415/study-react.2.zip)

**Comment by shoveller** [comment]
안녕하세요. @hayeonn2 님. 밤늦게까지 공부하시느라 수고가 많으셔요.

> 함수선언문을 썼기 때문에 defaultProps 를 바깥에 쓰지 못하고
구조분해 할당을 통해서 안에서 받아줘야 한다고 이해했습니다.
근데 제가 실습을 하면서 보니 바깥쪽에 defaultProps를 써도 아무 문제 없이 반영 되는 것 같은데 제 코드에 오류가 있는 것일까요?

아 이 지점은 조금 오해가 있는것 같아요.
`defaultProps` 는 리액트의 함수형 컴포넌트가 제공하는 기본기능입니다.
따라서 함수 선언식으로 선언한 리액트 컴포넌트와 함수 표현식으로 선언한 리액트 컴포넌트 모두에서 사용할 수 있어요.

참고로 구조분해할당으로 초깃값을 설정하는 기능은 react.js 가 출시되고도 한참 뒤에 자바스크립트 지체에 추가된 기능입니다.
이것도 언어 수준에서 지원하는 기능이므로 함수 선언식으로 선언한 리액트 컴포넌트와 함수 표현식으로 선언한 리액트 컴포넌트 모두에서 사용할 수 있어요.

[간단한 예제를 만들어 보았습니다.](https://codesandbox.io/s/recursing-fire-6hd790?file=/src/App.js:0-675)
```jsx
function 함수선언({ children }) {
  return <div>{children}</div>;
}

함수선언.defaultProps = {
  children:
    "함수선언식으로 만든 컴포넌트에 react.js의 고유기능을 사용해 초깃값 설정하기"
};

const 함수표현 = ({ children }) => {
  return <div>{children}</div>;
};

함수표현.defaultProps = {
  children:
    "함수표현식으로 만든 컴포넌트에 react.js의 고유기능을 사용해 초깃값 설정하기"
};

function 함수선언2({
  children = "함수선언식으로 만든 컴포넌트에 자바스크립트 문법만으로 초깃값 설정하기"
} = {}) {
  return <div>{children}</div>;
}

const 함수표현2 = ({
  children = "함수표현식으로 만든 컴포넌트에 자바스크립트 문법만으로 초깃값 설정하기"
} = {}) => {
  return <div>{children}</div>;
};

export default function App() {
  return (
    <>
      <함수선언 />
      <함수표현 />
      <함수선언2 />
      <함수표현2 />
    </>
  );
}
```

> 그리고 function A11yHidden(props, ref){} 이렇게 써줬는데
개발자도구에서 확인했을 때 A11yHidden2 로 나오는 이유가 뭘까요..?

그것은 `forwardRef` 를 기준으로 안쪽과 바깥쪽에 선언한 컴포넌트의 이름이 모두 `A11yHidden` 이기 때문인것 같아요
개발자도구는 안쪽과 바깥쪽에 선언한 컴포넌트 둘 중에서 하나의 이름만 표시하려고 하는데, 
안쪽과 바깥쪽에 선언한 컴포넌트의 `displayName` 이 `undefined` 이고 함수의 이름이 같으면 2를 붙여주도록 만들어진것 같네요.
아래의 코드로 테스트를 해 보시겠어요?
```jsx
import {forwardRef} from 'react'

const 너의이름은 = forwardRef(function 너의이름은() {
  return <span>hello</span>
})

function App() {
  console.log('너의이름은', 너의이름은.displayName);

  return <너의이름은 />
}
```

**Comment by yamoo9** [comment]
안녕하세요 @hayeonn2 님 😃

@shoveller 멘토님께서 답변을 주셨습니다. 😊

수업 내용 중 발생한 질문이니 만큼 저도 간략하게 답변드려봅니다.

[forwardRef](https://beta.reactjs.org/reference/react/forwardRef)에 전달되는 함수 컴포넌트의 개발 도구에서 표시 이름은 선언된 함수 이름 또는 [displayName](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging)으로 설정할 수 있다고 말씀드렸습니다. 그리고 수업에서 [defaultProps](https://beta.reactjs.org/reference/react/Component#static-defaultprops)와 [Destructuring assignment](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) 방법으로 컴포넌트의 초깃값을 설정할 수 있음을 이야기 드렸죠. forwardRef가 반환하는 것은 결국 React 컴포넌트이고, 실제 이 컴포넌트가 사용 됨에 따라 forwardRef 외부에서도 `defaultProps` 설정이 가능합니다. 

즉, 하얀님 코드에 문제는 없습니다. (답변 1)

```jsx
import clsx from 'clsx';
import { forwardRef } from 'react';
import classes from './A11yHidden.module.css';

export const A11yHidden = forwardRef(function A11yHidden(
  { as: ComponentName, focusable, className, ...restProps },
  ref
) {

  const combinedClassNames = clsx(
    classes.srOnly,
    { [classes.focusable]: focusable },
    className
  );

  return (
    <ComponentName ref={ref} className={combinedClassNames} {...restProps} />
  );
});

A11yHidden.defaultProps = {
  as: 'span',
  className: '',
  focusable: false,
};
```

그리고 선언된 함수 이름을 fowardRef가 반환한 함수의 개발 도구 표시 이름(displayName)으로 설정 하려면 forwardRef가 포함하는 함수의 이름이 표시 이름이 되므로 아래와 같이 코드를 변경 작성할 수 있겠습니다. (답변 2)

```jsx
import clsx from 'clsx';
import { forwardRef } from 'react';
import classes from './A11yHidden.module.css';

export const FowardA11yHidden = forwardRef(function A11yHidden(
  { as: ComponentName, focusable, className, ...restProps },
  ref
) {

  const combinedClassNames = clsx(
    classes.srOnly,
    { [classes.focusable]: focusable },
    className
  );

  return (
    <ComponentName ref={ref} className={combinedClassNames} {...restProps} />
  );
});

FowardA11yHidden.defaultProps = {
  as: 'span',
  className: '',
  focusable: false,
};
```

그러면 개발 도구에서 정상적으로 표시됩니다.

<img width="466" alt="" src="https://user-images.githubusercontent.com/1850554/222938765-460596e2-fe85-48be-8022-c16e6ff2e9d3.png" />

**Comment by hayeonn2** [comment]
우와 감사합니다!!!!! 🙇‍♀️👍🏻
