### ISSUE TITLE
[LAB-4] 웹팩(Webpack) 스캐폴딩 관련 질문 있습니다. deprecated,  peer dependencies

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#124]
## 질문 작성자

서석원

## 문제 상황

웹팩 스캐폴딩 pnpm 통합 설치과정에서 warning이 발생해서 질문드립니다.
해당 사진의 경고들의 의미가 무엇이며, 어떻게 대처해야 하는지 피드백해주시면 감사하겠습니다.
![q1](https://user-images.githubusercontent.com/73629761/223803891-4121c663-16d4-43f6-85e0-95096f0f19ec.PNG)
![q2](https://user-images.githubusercontent.com/73629761/223803897-9c381a32-de0f-4029-af3f-ba49f8058c35.PNG)

 

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

[스캐폴딩 레포](https://github.com/ssw6750/webpack-scaffolding-TypeScript)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
## [WARN] deprecated

말 그대로 종속성 모듈이 더 이상 지원되지 않거나 혹은 설치된 이전 버전을 업그레이드 하라는 경고 메시지입니다.

출력된 경고를 읽어보면 모던 ECMAScript의 내장 함수 지원으로 더 이상 이 라이브러리를 사용할 필요가 없다고 안내하는 내용 이거나, 설치된 버전 대신 더 높은 버전으로 설치하라는 내용, 지원하는 Node.js 버전은 현재 버전과 호환 문제가 있을 수 있음을 안내하는 내용입니다.

<img src="https://user-images.githubusercontent.com/73629761/223803891-4121c663-16d4-43f6-85e0-95096f0f19ec.PNG" alt />

## [WARN] Issues peer dependencies found

설치된 Storybook 버전이 6.5.16이고 Storybook에서 필요로 하는 피어(peer) 종속성 모듈이 유실(missing)되었거나, 맞지 않는(unmet) 버전 임을 경고합니다. 그리고 설치된 Storybook 6버전은 React 17 버전까지만 호환되는데 사용자가 설치한 React 버전이 18.2.0이라 Storybook과 호환 문제가 발생할 수 있다고 안내하는 내용입니다.

<img src="https://user-images.githubusercontent.com/73629761/223803897-9c381a32-de0f-4029-af3f-ba49f8058c35.PNG" alt />

## 이슈 대응 방법

ERROR가 아니라 WARN인 점에서 스캐폴딩 결과물 구동에 문제는 없을 것으로 보입니다. 
그럼에도 경고 메시지가 신경 쓰인다면? 

경고 메시지를 검토해 deprecated 종속성 모듈 버전을 찾아 문제가 발생하지 않는 버전으로 대체해야 합니다. 하지만 직접 설치한 종속성 모듈도 아니고, 사용하는 라이브러리에서 필요로 하는 모듈이라 직접 해결하는 것은 권장하고 싶지 않습니다. 이런 경우 사용하는 라이브러리가 최신 버전인지, 현재도 관리되고 있는 상태인지, 다른 대체 라이브러리는 없는 지 등을 검토해볼 필요가 있습니다.

그리고 Storybook 호환 문제는 현재 사용 중인 React 버전을 17로 낮추거나, 아니면 Storybook을 7 버전(현재 Beta)으로 올려야 합니다.
버전 호환 문제로 고생해서 해결한 후기 [[NPM] PEER DEPENDENCY? RC5?](https://k9e4h.tistory.com/149)를 참고해서 읽어보셔도 좋을 것 같습니다.

<img src="https://user-images.githubusercontent.com/1850554/223873993-64f4e241-f3b6-4ff1-a84f-7921ccdd4021.png" width="600" alt />

**Comment by ssw6750** [comment]
아하..! 고치려면 고생좀 해야겠군요.. 피드백 감사합니다!!
