### ISSUE TITLE
[LAB-4] React Router 동적 세그먼트 에러 원인을 알고 싶습니다.

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#125]
## 질문 작성자

서석원

## 문제 상황

라우팅에서 동적 세그먼트 로직이 작동이 안됩니다.
- productDetail/:id

경로가 잘못되었으면 notFound가 떠서 경로문제가 아닌 다른에러로 보입니다. 
웹펙 설정 문제인것 같기도 한데,,, 잘 모르겠습니다.
피드백 해주시면 감사하겠습니다..!!!
![q2-1](https://user-images.githubusercontent.com/73629761/224036750-6d16b0a3-c5f3-4f61-8cc6-c3db431b083b.PNG)
![q2-2](https://user-images.githubusercontent.com/73629761/224036783-d9112ab0-633d-4318-8835-802ab15c3289.PNG)
![q2-3](https://user-images.githubusercontent.com/73629761/224036804-fd1c232d-505a-469d-849b-51e0787831c8.PNG)

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

[레포지토리 브랜치 setting](https://github.com/LikeLion-FE-React-Project04/project-repo/tree/setting)

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## React Router 동적 라우팅 설정

setting 브랜치 프로젝트를 내려받아 테스트 해보니 구성에 문제가 있었어요.
**문제 원인은 라우트 동적 세그먼트 설정과 ProductDetail 컴포넌트에서 전달 받는 설정이 다른 데 있었습니다.**

라우트 동적 세그먼트 설정 | 컴포넌트 파라미터 설정
--- | ---
`productDetail/:id` | `params.productId`

두 설정 값이 달라 React Router는 정상적으로 라우팅 하지 못하고 Not Found 컴포넌트를 렌더링 한 것이죠.
이 설정 값을 하나로 일관되게 구성해야 정상적으로 작동합니다. 여기서는 `productId`로 통일하겠습니다.

라우트 동적 세그먼트 설정 | 컴포넌트 파라미터 설정
--- | ---
`productDetail/:productId` | `params.productId`

### index.jsx

변경된 코드가 반영된 `index.jsx` 파일입니다. 아래 하이라이팅 된 부분을 살펴보세요.

<img width="807" alt="" src="https://user-images.githubusercontent.com/1850554/224180613-001756e5-c25b-4c02-8bda-9a1f916f6c69.png">


### Home.jsx

`Home.jsx` 파일에 동적 라우팅 되는 페이지로 이동하는 링크를 추가합니다. `productId`는 임의로 `9`를 입력해보겠습니다.

<img width="899" alt="" src="https://user-images.githubusercontent.com/1850554/224179137-267058bb-4cc8-48ff-a212-72e3276f26d8.png">

### ProductDetail.jsx

`ProductDetail.jsx` 파일에서는 `loader` 함수 코드를 작성한 부분과 `useParams`, `useLoaderData` 훅을 사용한 부분을 확인하세요. 참고로 `useLoaderData` 훅을 사용해서 컴포넌트가 필요로 하는 데이터를 서버에서 가져 왔으므로 `useParams` 훅은 필요한 경우만 사용합니다.

<img width="957" alt="" src="https://user-images.githubusercontent.com/1850554/224179287-fcc192e7-f25a-49c3-a04a-23a9379fbc29.png">

## 수정한 가이드 파일 다운로드

가이드 한 코드를 참고하기 쉽게 `src` 폴더를 압축해 첨부합니다. 😊

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/10937045/src.zip)

**Comment by ssw6750** [comment]
파라미터도 맞추고, 아하 링크를 걸어줘야 했군요..! 감사합니다!!

**Comment by ssw6750** [comment]
저 콘솔에 나는 오류는 Suspense를 안감싸줘서 나는 오류였습니다! 감삼합니다!!
