### ISSUE TITLE
[LAB-11] Uncaught ReferenceError: utilsService is not defined 오류

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#126]
## 질문 작성자

오승택

## 문제 상황

![image](https://user-images.githubusercontent.com/109938280/224370827-6981bd7b-8736-4b22-8695-fd3058926636.png)

안녕하세요 ?  vite 환경설정을 끝내고 팀원들과 테스트해본 결과 저만 이런 오류의 메시지가 뜨네요ㅠ

setting.json 도 설정을 맞춰보고, 안맞춰서도 실행이 되는데 저런 오류가 계속 뜹니다.

구글링도 해보고 팀원들의 도움도 받아보고 다른 환경셋팅에서 깃 클론을 받아서 실행을 해본 결과 저의 환경셋팅 문제인거 같습니다.

window 에서도 정상적으로 잘 되구요. mac 에서도 정상적으로 잘 되는데, 저의 로컬환경에서만 저런 오류가 발생합니다.

심지어 환경셋팅이 다른 랩실의 팀원들도 git clone 을 받아서 실행해본 결과 다른 사람들은 에러가 뜨지 않았습니다. 

![image](https://user-images.githubusercontent.com/109938280/224375373-cb7cb053-f63e-4ed7-92b8-1677591e3d15.png)
혹시나 해서 수업시간에 했던 파일도 돌려봤는데요 똑같은 에러가 뜹니다.

![image](https://user-images.githubusercontent.com/109938280/224376710-3f713847-45ce-41f3-8d3d-b299c172b52b.png)

파이어 폭스에서는 또 오류가 발생하지 않습니다 !!!!

## 프로젝트 저장소 URL

- 저장소 URL : https://github.com/likeLion-FE4-RP11/Asparagus
- main 브랜치
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (macOS)
- Node.js 정보 ( v18.12.1 )
- 라이브러리 정보 (React v18.2.0)

**Comment by yamoo9** [comment]
## 문제 원인

해당 오류는 아마도 Vite + React 앱 문제가 아니라, Chrome 웹 브라우저에 설치된 Chrome 확장(extensions) 문제일 거에요. 
그렇게 짐작한 이유는 다음과 같습니다.

1. 다른 팀원 심지어 타 랩실 팀원과 달리, 승택님 로컬 환경에서만 오류가 발생한다.
2. 승택님 Chrome 웹 브라우저에서만 오류가 발생하고, Firefox에서는 발생하지 않는다.

## 문제 검증

일반적으로 Chrome 웹 브라우저에 설치된 확장은 비공개(secret) 창에서는 활성 상태가 아닙니다. 
그러므로 비공개 창에서 Vite + React 앱을 띄웠을 때 오류가 발생하지 않는다면? 
Chrome 확장이 문제 원인 임을 검증할 수 있죠.

<img width="357" alt="" src="https://user-images.githubusercontent.com/1850554/224421066-4ca744d6-59ce-4460-8cde-7949e9b903ef.png" />

비공개 창을 띄운 후, 구동된 개발 서버의 로컬호스트 URL을 주소 창에 붙여넣고 Console 패널을 확인해보세요.

## 문제 해결

만약 검증 결과 Chrome 확장 문제로 확인된다면? Vite + React 앱의 문제가 아닙니다.
문제가 되는 확장을 찾아 삭제하면 해결됩니다. 😃

**Comment by 5wintaek** [comment]
답변 감사합니다 야무썜 ! 아무것도 건들지 않구 아침에 다시 한번 구글 크롬으로 실행을 해봤는데 실행이 잘 되네요 ! 시크릿 모드에서도  실행이 잘 됩니다 !  

만약에 이런 문제가 한번 더 발생한다면 익스텐션을 하나씩 찾아 없애보도록 하겠습니다 !
