### ISSUE TITLE
[LAB-12] Storybook 실행 시, process is not defined 에러 

### ISSUE THREAD

**Issue by sykang013** [yamoo9/likelion-FEQA#127]
## 질문 작성자

강수영 

## 문제 상황

- 1) 팀 공동저장소를 개인 브랜치로 fork 후, develop 브랜치에서 새 브랜치 'stbtest02'로 checkout 하였습니다.
  -  스케폴딩시 설치되어있던 스토리북은 버젼 6.5였습니다.
- 2) 기존 설치되어있던 스토리북 6.5 버젼을 `npm uninstall storybook` 으로 언인스톨하였습니다.
- 3) `npx storybook@next init` 으로 스토리북 버젼 7을 설치했습니다.
- 4) 그 후 권장에 따라 `npm run storybook` 을 실행했는데, 브라우저 화면에 컴포넌트가 직접적으로 보여지는 부분이 계속 에러가 납니다. console창에서의 오류 메시지를 보면 rumtime 에러인 것 같은데, 정확히 어떤 부분이 문제인지, 어떻게 해결해야하는지도 잘 모르겠습니다. (검색을 해도 당최 갈피가 잡히지 않네요 ㅠㅠ) 

![image](https://user-images.githubusercontent.com/113448786/224481129-5d57a054-48cf-40d3-9ceb-d1253a769922.png)

## 프로젝트 저장소 URL

- [공동저장소를 fork해온 개인 저장소](https://github.com/sykang013/together/tree/stbtest02)  (브랜치명 stbtest02)

## 환경 정보

- 운영체제 정보 ( macOS )
- Node.js 정보  ( v18.14.1 )
- 라이브러리 정보 
- ( storybook@7.0.0-rc.1. )
- ( react@18.2.0 )

**Comment by yamoo9** [comment]
## 문제 상황

Storybook v6에서 v7(Beta)로 업그레이드 한 후 Storybook 구동 시 `process is not defined `오류가 발생합니다.

<img src="https://user-images.githubusercontent.com/113448786/224481129-5d57a054-48cf-40d3-9ceb-d1253a769922.png" alt />

## 문제 원인

`process` 객체는 Node.js 런타임 환경에서 접근 및 사용 가능합니다. 하지만 Vite는 기본적으로 ES 모듈 환경을 사용합니다.
프로젝트의 `package.json` 파일을 보면 `type` 설정이 `module`인 것을 확인 할 수 있을 것입니다.

```json
{
  "type": "module",
  "name": "together"
}
```

즉, 이 문제는 **구동된 Storybook 앱에서 `process` 객체를 찾을 수 없어 발생한 오류**입니다.

## 문제 해결

문제 해결 방법은 Vite의 define 공유 옵션(shared option)을 사용해 `process.env`의 대체 값을 설정하는 것입니다. ([참고](https://vitejs-kr.github.io/config/shared-options.html#define))
프로젝트의 `vite.config.js` 파일에 `define` 공유 옵션 설정을 아래와 같이 추가하면 정상적으로 Storybook 앱이 구동됩니다.

```js
export default defineConfig({
  // ...
  define: {
    'process.env': {},
  },
});
```

<img width="1165" alt="" src="https://user-images.githubusercontent.com/1850554/224516662-127d7108-bf51-460b-bd9e-ca67178b4fa1.png">
