### ISSUE TITLE
[LAB-11] VS Code 자동완성 문제 (a.k.a 스니펫 위치 설정)

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#128]
## 질문 작성자

오승택

## 문제 상황

![image](https://user-images.githubusercontent.com/109938280/224487865-75081565-7867-4402-930c-fa0445a46c49.png)

안녕하세요. 자동완성기능에 대해서 궁금한게 있어서 질문을 드립니다.

jsx 파일에서 className 이나 onClick 같은 이름을 지어줄떄 자동으로 완성되는 코드가 뜨질 않아서 질문을 드립니다.

![image](https://user-images.githubusercontent.com/109938280/224487971-f7625180-b29e-41d2-8a46-72e4cf19ef2f.png)

위에 사진을 설치되어 있는 익스텐션 중 스니펫과 관련있는 것들만 추려서 올린 사진입니다. 

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 상황

JSX 사용 시, 아래 그림처럼 `className` 또는 `onClick`과 같은 prop 이름이 자동 제안되지 않는다면? 
아마도 스니펫 제안 위치가 `top`으로 설정되어 있을 것입니다.

<img width="1100" alt="" src="https://user-images.githubusercontent.com/1850554/224515509-0237dbd1-4332-4627-8f89-8115f9f0eff1.png" />

## 문제 해결

먼저 VS Code → Manage (⚙️) → Settings(`Cmd + ,`) 인터페이스를 띄웁니다.

<img width="327" alt="" src="https://user-images.githubusercontent.com/1850554/224515837-7361fbd5-5ba4-4734-8081-f319c33082bc.png">

"snippetSuggesions"을 검색합니다. 그리고 `top` 값 대신 기본 값인 `inline`으로 설정하세요. ([참고](https://code.visualstudio.com/docs/editor/intellisense#_snippets-in-suggestions))

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1850554/224515757-83acac8c-9b3a-4121-856f-78e1e7b0c1f6.png">

설정 후에는 `className` 또는 `onClick`과 같은 prop 이름이 바로 제안될 것입니다. 😃

<img width="1081" alt="" src="https://user-images.githubusercontent.com/1850554/224515665-1d42d28f-283f-4d25-87e8-249e3eff8339.png" />

**Comment by 5wintaek** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/109938280/224535673-642ee6ac-63a9-43a7-9bd4-57a551cce02d.png">

알려주신대로 설정을 바꿔보았는데요 ! 그래도 뜨질 않네요ㅠㅠ 원래는 top 으로 설정했었을떄도 잘 떳었다가 어느순간 갑자기 뜨질 않아서요 !

**Comment by yamoo9** [comment]
> <img alt="image" width="593" src="https://user-images.githubusercontent.com/109938280/224535673-642ee6ac-63a9-43a7-9bd4-57a551cce02d.png">
> 
> 알려주신대로 설정을 바꿔보았는데요 ! 그래도 뜨질 않네요ㅠㅠ 원래는 top 으로 설정했었을떄도 잘 떳었다가 어느순간 갑자기 뜨질 않아서요 !

그렇다면 화면 공유해서 직접 증상을 보고 답변 드리는 것이 낳을 듯 하네요. 시간 되실 때 화면 공유하고 이야기 나눠봅시다. 🤔

**Comment by 5wintaek** [comment]
> > <img alt="image" width="593" src="https://user-images.githubusercontent.com/109938280/224535673-642ee6ac-63a9-43a7-9bd4-57a551cce02d.png">
> > 알려주신대로 설정을 바꿔보았는데요 ! 그래도 뜨질 않네요ㅠㅠ 원래는 top 으로 설정했었을떄도 잘 떳었다가 어느순간 갑자기 뜨질 않아서요 !
> 
> 그렇다면 화면 공유해서 직접 증상을 보고 답변 드리는 것이 낳을 듯 하네요. 시간 되실 때 화면 공유하고 이야기 나눠봅시다. 🤔

지금도 가능합니다 ! 아니면 내일 오전에 잠깐 시간내주실수 있나요 !

**Comment by yamoo9** [comment]
> > > <img alt="image" width="593" src="https://user-images.githubusercontent.com/109938280/224535673-642ee6ac-63a9-43a7-9bd4-57a551cce02d.png">
> > > 알려주신대로 설정을 바꿔보았는데요 ! 그래도 뜨질 않네요ㅠㅠ 원래는 top 으로 설정했었을떄도 잘 떳었다가 어느순간 갑자기 뜨질 않아서요 !
> > 
> > 
> > 그렇다면 화면 공유해서 직접 증상을 보고 답변 드리는 것이 낳을 듯 하네요. 시간 되실 때 화면 공유하고 이야기 나눠봅시다. 🤔
> 
> 지금도 가능합니다 ! 아니면 내일 오전에 잠깐 시간내주실수 있나요 !

디스코드 화상 공유해서 답변 드렸습니다. 😃
