### ISSUE TITLE
[LAB-17] storybook이 @: ./src 절대경로를 못읽습니다.

### ISSUE THREAD

**Issue by hyunwleeee** [yamoo9/likelion-FEQA#129]
## 질문 작성자

이현우 

## 문제 상황

npm run start의 경우는 원하는 결과가 나오지만,    
npm run storybook의 컴파일결과 다음 사진과 같이 오류가 일어나고 있습니다.    
  
<img width="1348" alt="스크린샷 2023-03-12 오후 4 26 25" src="https://user-images.githubusercontent.com/55472696/224530682-63913a6f-6f1f-4e30-9e16-b8d08869758d.png">

## 프로젝트 저장소 URL
- branch: feature/6-make-atomic-components
- [문제의 깃허브 소스](https://github.dev/NatureTeam/NatureKarly/tree/feature/6-make-atomic-components)

## 환경 정보

- 운영체제 정보 macOS
- Node.js 정보 v19.6.0

**Comment by yamoo9** [comment]
## 문제 상황

Storybook은 정상 구동되지 않고, React 앱은 정상 구동됩니다.

## 문제 원인

**설치된 Storybook v6이고, 사용된 Storybook 문법은 v7(Beta)입니다.** 
즉, 문제 원인은 **잘못된 사용법**에 있습니다.

## 문제 해결

**수업 시간에 다룬 Storybook은 v7(Beta) 입니다.** 

v6을 설치하고 사용하려면 v6 문법을 사용해야 합니다. v6 문법을 사용하려면 [공식 문서](https://storybook.js.org/docs/react/writing-stories/introduction)를 참고하세요. 
참고로 v6은 절대 경로를 사용해야 할 경우 직접 `.storybook/main.js` 파일에 구성을 추가해야 합니다. ([참고](https://storybook.js.org/docs/react/builders/vite#configuration))


Storybook v7로 정상 구동되는 ZIP 파일을 첨부합니다. 
압축 파일을 다운로드 받아 확인한 후, 참고해 구동되도록 설정해보세요.

[NatureKarly__confirm_by_yamoo9.zip](https://github.com/yamoo9/likelion-FEQA/files/10950381/NatureKarly__confirm_by_yamoo9.zip)

아래 스크린샷은 정상 구동되는 Storybook 애플리케이션 화면입니다.

<img width="1077" alt="" src="https://user-images.githubusercontent.com/1850554/224534748-47cc7fe6-9fce-4c0f-abb0-4293a964bd18.png">

**Comment by hyunwleeee** [comment]
감사합니다 야무쌤!!
