### ISSUE TITLE
🛎️ 화살표 함수에서의 this에 대해 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#13]
## 문제 상황
범 쌤의 수업시간에서 화살표 함수에서 this는 상위에 있는 this를 빌려올 수 있다고 들었습니다.
저는 이 과정을 "스코프 체인과 동일하게 찾는구나" 라고 생각했는데 이게 맞는지 궁금합니다.

스코프체인이 맞다면 "아래 사진의 코드에서 화살표 함수 t1에서의 this는 호출스택에 따라 다른 스코프의 this를 탐색하고 결국 (test2를 가리키는) t4의 this를 this로 사용한다." 라고 생각했습니다.
그런데 결과를 보면 t1의 this는 전역객체를 가리킨다고 나옵니다.

이 부분에 대해서 피드백 부탁드립니다!!

![this의스코프체인](https://user-images.githubusercontent.com/73629761/210806241-55119110-8f78-44ef-acff-973c071c88df.PNG)

![호출스택](https://user-images.githubusercontent.com/73629761/210807664-39681ed5-f128-4db1-9a08-de86011e734a.PNG)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.4.0)

**Comment by yamoo9** [comment]
## 화살표 함수의 this

화살표 함수는 자신의 `this`가 없습니다. 대신 화살표 함수를 둘러싸는 렉시컬 범위(lexical scope)의 `this`가 사용됩니다. 
화살표 함수는 일반 변수 조회 규칙(normal variable lookup rules)을 따릅니다. 현재 범위에서 존재하지 않는 `this`를 찾을 때, 
화살표 함수는 바로 바깥 범위에서 `this`를 찾는것으로 검색을 끝내게 됩니다.

- `test2.t3()`가 실행될 때 `t3` 안에 중첩된 `t4()` 화살표 함수가 실행되면 현재 범위에서 `this`를 찾으므로 test2 객체를 가리킵니다.
- t4 화살표 함수 안에서 `test.t1()`이 실행되면 test 객체가 위치한 영역에서 바깥 범위의 `this`를 찾으므로 Window 객체를 가리킵니다.

```js
let test = {
  t1: () => console.log(this), // Window { }
};

let test2 = {
  t3() {
    let t4 = () => {
      test.t1();
      console.log(this); // { t3: ƒ }
    }
    t4();
  }
}

test2.t3();
```

test 함수 코드를 아래와 같이 변경하면 `t1()` 화살표 함수가 실행되었을 때 `this`는 test 객체를 가리키게 됩니다.

```js
let test = {
  t5() {
    let t1 = () => console.log(this); // { t5: f }
    t1();
  }
};

let test2 = {
  t3() {
    let t4 = () => {
      test.t5();
      console.log(this); // { t3: ƒ }
    }
    t4();
  }
}

test2.t3();
```

참고 [Arrow functions, MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
