### ISSUE TITLE
[LAB-20] Storybook 설치 error 문제

### ISSUE THREAD

**Issue by ghost** [yamoo9/likelion-FEQA#130]
## 질문 작성자

정보화

## 문제 상황

- storybook을 설치하기위해 VS code로 설치하려하는데, storybook 설치하려하면 에러가 뜨고, 
스토리북이 설치가 되지 않습니다.  스토리북 버전을 살펴봐도 없다고 뜹니다. 
프로젝트 분들이랑 동시에 설치를 해보았는데, 다른분들은 모두 정상적으로 설치를 하였습니다.

![stroybook-error](https://user-images.githubusercontent.com/108967196/224532262-aa486415-b8e2-41f7-94dc-8e0866bc6afc.png)

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
https://github.com/bellaru2022/Monstera
- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.
- main 입니다.
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
해당 문제 확인을 위해 저장소에서 프로젝트를 내려 받아 테스트해봤지만, 문제는 없었습니다.
이런 경우 직접 @bellaru2022 님 컴퓨터 화면을 공유해서 문제를 확인하고 답변 드리겠습니다.
