### ISSUE TITLE
[LAB-8] CRA 스케폴딩 진행을 체크 받고 싶습니다!

### ISSUE THREAD

**Issue by rlawlsdn263** [yamoo9/likelion-FEQA#131]
## 질문 작성자

김진우

## 문제 상황

야무쌤과의 팀 리더 미팅에서 나온 답변을 토대로 CRA 스케폴딩을 진행했습니다. 
하지만 올바르게 했는지 체크를 받고 싶어서 글을 올려봅니다.

현재 CRA 환경 변수와 리코일 디버깅을 위한 라이브러리와 관련된 설정은 아직 진행되지 않았습니다.

- 절대 경로 설정
- styled-components 디버깅
- styled-components 스타일 리셋
- 리액트 라우터 설치
- Recoil 설치

### 기술스택

- CRA
- Styled-Components
- Recoil
- React Router
- Firebase

### 절대 경로 설정하기

절대 경로는 craco로 설치해 진행을 했습니다.

1. craco 설치

```jsx
npm i @craco/craco
```

2. craco.config.js 파일 생성

![image](https://user-images.githubusercontent.com/79128016/224539084-2df8d10a-d453-47a8-8ea7-68788c1f6f60.png)

```jsx
const path = require("path");

module.exports = {
  webpack: {
    alias: {
      "@": path.resolve(__dirname, "src/"),
      "@components": path.resolve(__dirname, "src/components"),
    },
  },
};
```

alias의 값에서 절대 경로를 설정해줬습니다.

3. package.json 파일 수정

```jsx
"scripts": {
  "start": "craco start",
  "build": "craco build",
  "test": "craco test",
  "eject": "react-scripts eject"
},
```

package.json의 scripts 명령어를 다음처럼 craco로 변경해줬습니다.

### 스타일 컴포넌츠 디버깅

스타일 컴포넌츠는 CRA에서 디버깅 이슈가 있기 때문에 babel-plugin-macros를 설치해 해결했습니다.

1. styled-components 설치

```jsx
npm i styled-components
```

2. babel-plugin-macros 설치

```jsx
npm install babel-plugin-macros
```

3. .bablerc 파일 생성

```jsx
{ 
   "plugins": ["babel-plugin-styled-components"]
}
```

root 위치에 .bablerc 파일을 생성하고 다음 코드를 넣어줬습니다.

### Styled-Components Reset하기

 1. styled-reset 설치

```jsx
npm i styled-reset
```

2. Global Style 만들고 reset 적용해주기

```jsx
// 글로벌 스타일 만들기 위한 createGlobalStyle 불러오기
import { createGlobalStyle } from "styled-components";

// 스타일 초기화를 위한 reset 불러오기
import reset from "styled-reset";

// 글로벌 스타일 만들기, reset 사용해서 스타일 초기화하기
const GlobalStyles = createGlobalStyle`
	${reset}

	/*
		글로벌 스타일 영역
	*/

`;
```

### 리액트 라우터 설치

```jsx
npm i react-router
```

![image](https://user-images.githubusercontent.com/79128016/224537180-fa234cc7-e141-4660-8b80-679145741de2.png)

### 리코일 설치

```jsx
npm i recoil
```

## 프로젝트 저장소 URL

https://github.com/likelion-project-octo/likelion-saja

## 환경 정보

- Windows
- Node.js v18.12.1
- 라이브러리 정보

```jsx
  "dependencies": {
    "@craco/craco": "^7.1.0",
    "babel-plugin-macros": "^3.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router": "^6.9.0",
    "react-scripts": "5.0.1",
    "styled-components": "^5.3.8",
    "styled-reset": "^4.4.5",
    "recoil": "^0.7.7",
  }
```

**Comment by yamoo9** [comment]
## 프로젝트 스캐폴딩

@rlawlsdn263 님께서 수행한 스캐폴딩은 다음과 같습니다.

- [x] 절대 경로 설정 (with CRACO)
- [x] styled-components 디버깅
- [x] styled-components 스타일 리셋
- [x] React Router 설치
- [x] Recoil 설치

## 스캐폴딩 검토

현 단계의 CRA + CRACO 스캐폴딩을 검토한 결과를 이야기 해봅니다.

### 절대 경로 설정

[CRACO의 절대 경로 설정](https://craco.js.org/docs/configuration/webpack/) 방법대로 잘 진행해주셨습니다. 😃

다만, CRACO 구성 파일의 절대 경로 설정을 아래와 같이 간소하게 작성할 수 있습니다.

**craco.config.js**

```js
const { resolve } = require('node:path');

module.exports = {
  webpack: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
};
```

그리고 `jsconfig.json` 파일을 추가해주면 좋습니다. 절대 경로 방법으로 파일 탐색 시 '@/'만 입력했을 때 하위 에셋이 VS Code에 표시됩니다.

<img width="660" alt="" src="https://user-images.githubusercontent.com/1850554/224571061-2e75f1e5-6cca-4a84-ae7d-9cd063019be5.png">

**jsconfig.json**

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["./src"]
}
```

## styled-components 디버깅

[styled-components 디버깅을 위한 Babel 플러그인 구성](https://styled-components.com/docs/tooling#usage) 또한 잘 진행해주셨어요.

하지만 샘플 코드로 포함된 예시는 디버깅 이름이 정상적으로 표시되지 않습니다. (`styled.div`)

<img width="708" alt="" src="https://user-images.githubusercontent.com/1850554/224571179-b959fc22-c950-48bd-889c-ad118cdc3f07.png">

'styled-components/macro'에서 styled 모듈을 추출해 사용해야 정상적으로 디버깅 이름이 개발 도구에 표시됩니다 (`App__Container`)

```jsx
import styled from 'styled-components/macro';

const Container = styled.div`
  width: 100px;
  height: 50px;
  background: green;
  color: white;
`;
```

<img width="762" alt="" src="https://user-images.githubusercontent.com/1850554/224571317-5d525787-1000-4f0d-9682-62551d030bb6.png">

### 그 외 기타 구성

문제 없이 잘 수행해주셨습니다. 😀

- [x] styled-components 스타일 리셋
- [x] React Router 설치
- [x] Recoil 설치

그런데 public 디렉토리는 정리가 안되었네요.

`public/index.html` 파일의 주 언어 설정도 한국어로 변경해야 하고, 
메타 코드 및 문서 제목, noscript 콘텐츠 모두 [로컬라이제이션](https://www.lionbridge.com/ko/blog/content-transformation/what-is-software-localization-and-who-needs-it/) 해주셔야 해요.

그리고 서비스에 맞는 파비콘(favicon)도 디자인해서 변경해주세요. 😊

**Comment by rlawlsdn263** [comment]
감사합니다 야무쌤!!! ❤
