### ISSUE TITLE
[LAB-4] 버튼 정가운데에 텍스트를 위치시키는 방법과 line-height에 대해서 궁금합니다

### ISSUE THREAD

**Issue by SeoMiYoung** [yamoo9/likelion-FEQA#132]
## 질문 작성자
서미영

## 문제 상황
![image](https://user-images.githubusercontent.com/112063987/224536767-b70bd636-76b4-43b7-b05a-a9a608d0aa5f.png)
![image](https://user-images.githubusercontent.com/112063987/224535378-6b854492-5707-48c2-a7ee-54e13a8b8a3c.png)
![image](https://user-images.githubusercontent.com/112063987/224536656-3189bedc-2c99-4a3e-bc95-75aa8d20fee0.png)
위 사진에서 '카카오톡 문의', '1:1 문의', '대량주문 문의' button는 모두 동일한 class(.inquiryBtn)가 적용되어 있습니다.
위의 사진들처럼 마크업과 css를 적용했는데, 제가 생각한 결과와 다르게 나왔습니다. 
저는 '카카오톡 문의', '1:1 문의', '대량주문 문의'라는 텍스트 내용이 버튼의 정가운데에 위치할것이라고 예상했지만,
실제 결과는 두번째 사진에서 보이는것과 같이 정가운데를 기준으로 약간 올라가서 텍스트가 위치해 있는것을 확인할 수 있었습니다.

팀원분들과 이 문제에 대해서 고민해본 결과, line-height가 원인일수도 있겠다는 이야기가 나왔습니다.
저희팀은 예전에 슬비쌤께서 수업자료로 사용하신 normalize.css를 가져다가 사용하고 있는데,
그 normalize.css에는 line-height: 1.15;로 설정되어있기 때문입니다.

![test](https://user-images.githubusercontent.com/112063987/224538330-87d2aec1-aaf9-42dc-835e-b7ddbdf49b4a.gif)

바로위에 첨부한 움짤처럼, line-height값이 1일때와 1.15일때는 미세하지만 차이를 보이는걸 알 수 있습니다.
line-height가 1일때보다는 1.15일때가 약간 올라갑니다. 
그래서 제가 예상한 결과보다 텍스트가 약간 올라가서 위치하지 않았을까라고 추측을 했습니다.

그래서 line-height:1.15; 적용을 취소시키기 위해 line-height: normal;을 적용했습니다.
그랬더니 다음 사진과 같은 결과가 나왔습니다.

![image](https://user-images.githubusercontent.com/112063987/224538470-f548b8d6-2fbb-468d-9a8c-47ad6bcfbd24.png)
'카카오톡 문의'버튼은 제가 원하는 결과대로 정 가운데에 텍스트가 위치했지만,
'1:1 문의'와 '대량주문 문의'버튼은 아직도 정가운데를 기준으로 약간 위쪽으로 글자가 치우쳐있음을 확인할 수 있었습니다. 
세 버튼에 모두 같은 class를 적용했는데,
왜 일부버튼은 문제가 해결이 되고, 일부 버튼들은 해결되지 않은걸까요?

질문을 정리하자면 다음과 같습니다.
1. 슬비쌤께서 제공해주신 normalize.css에 line-height값이 왜 1.15로 설정되어있는지 궁금합니다
2. 세 버튼에 같은 class를 설정했는데, 왜 공통 class에서 line-height를 1.15 => normal로 바꿨을때
    첫번째 버튼만 텍스트가 정가운데에 오고, 나머지 버튼들은 그대론지...

## 환경 정보
- 운영체제 정보: 윈도우
- Node.js 정보: v18.14.0
- 라이브러리 정보 => 리액트 라이브러리 버전 확인법을 모르겠어요ㅠ

**Comment by yamoo9** [comment]
## 답변 1.

[Normalize CSS](https://necolas.github.io/normalize.css/8.0.1/normalize.css) 주석에도 나와 있듯이 모든 브라우저의 정확한 기본 행간(line-height) 값이 1.15이기 때문입니다.

```css
/**
 * 1. Correct the line height in all browsers.
 * 2. Prevent adjustments of font size after orientation changes in iOS.
 */

html {
  line-height: 1.15; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
}
```

W3C 웹 표준 [CSS 문서](https://www.w3.org/TR/CSS22/visudet.html#leading)를 살펴보면 `line-height` 속성 기본 값은 `normal`이며 `1.0` ~ `1.2` 사이 값을 권장한다고 작성되어 있습니다. 이를 각 브라우저 제조사(Chrome, Firefox, Edge 등)마다 기본 값을 달리 선택할 수 있으므로 Normalize CSS는 이 값을 `1.15`로 통일한 것입니다.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/1850554/224544239-430521fb-cc82-4e41-b2b4-2e126c3efb2a.png">


## 답변 2.

문제가 되는 프로젝트 저장소 URL을 포함해야 확인하고 답변할 수 있습니다.
그냥 이미지만으로 문제 원인을 파악할 수 없습니다. 저장소 URL을 포함해주세요.

**Comment by seulbinim** [comment]
야무쌤이 벌써 line-height에 대한 답변을 잘 해주셨네요.
저장소 URL과 브랜치 정보를 알려주시면
테스트 해보고 답변 드릴 수 있도록 하겟습니다.

**Comment by SeoMiYoung** [comment]
오오 벌써 답변을 해주셨군요 ㅠㅠ 
앞으로 질문올릴때 label이나 저장소 등을 신경써서 올리겠습니다. 
답변 감사합니다.

제 깃헙 저장소 URL: https://github.com/SeoMiYoung/project-repo
브랜치 정보: feat/#10

입니다!!
감사합니다!!

**Comment by seulbinim** [comment]
미영님이 알려주신 저장소의 브랜치를 클론하여 확인한 결과
세 개의 버튼 모두 동일한 스타일이 적용된 것을 확인했습니다.
그럼 좋은 밤 보내세요~

<img width="501" alt="스크린샷 2023-03-13 오전 12 24 40" src="https://user-images.githubusercontent.com/7028746/224556309-35e3b73d-bcac-4a3d-b1b0-754382ea0b4f.png">
(개인 디엠으로도 설명드렸으니 추후에 동일한 문제가 발생할 경우 다시 질문 주세요~)

**Comment by SeoMiYoung** [comment]
넵 답변해주셔서 감사합니다!!! 선생님도 좋은밤 보내세요!!
