### ISSUE TITLE
[LAB-20] Storybook에서 Link 컴포넌트 테스트 하는 방법이 궁금합니다.

### ISSUE THREAD

**Issue by kimzeze** [yamoo9/likelion-FEQA#134]
## 질문 작성자

김도현

## 문제 상황

- storybook으로 button, input, 등 기본 컴포넌트를 만들고 있었습니다.
- Link 컴포넌트를 만들고 storybook에서 확인 시 첨부된 사진과 같은 오류가 발생하였습니다.
- storybook에서만 오류가 발생하고 실제로 컴포넌트를 사용하면 정상적용 되는 것을 확인하였습니다.
- stoybook에서 link 컴포넌트를 확인할 수 있는 방법이 있을까요?

<img width="1473" alt="스크린샷 2023-03-13 11 19 24" src="https://user-images.githubusercontent.com/96248861/224593267-a5651a27-14ce-4e23-8897-84194a45ec76.png">
<img width="659" alt="스크린샷 2023-03-13 11 20 05" src="https://user-images.githubusercontent.com/96248861/224593372-ac603932-e172-4595-8238-2c4437572846.png">
<img width="816" alt="스크린샷 2023-03-13 11 20 25" src="https://user-images.githubusercontent.com/96248861/224594224-f7930e4a-eb68-4846-94e8-e00d0ee06110.png">

## 프로젝트 저장소 URL

- https://github.com/kimzeze/Monstera

## 환경 정보

- 운영체제 정보 : MacOS
- Node.js 정보 : 18.12.1
- 라이브러리 정보
- vite 4.1.0
- storybook 7.0.0.-beta62
- react 18.0.27

**Comment by yamoo9** [comment]
## Storybook v7 + React Router v6

Storybook과 React Rotuer는 별개의 도구이고, React Router를 기본적으로 지원하지 않습니다.

## Storybook 애드온

Storybook에서 React Router의 Link 컴포넌트를 사용하려면 [storybook-addon-react-router-v6](https://storybook.js.org/addons/storybook-addon-react-router-v6) 애드온 설치가 필요합니다.

### 애드온 설치

애드온 패키지를 설치합니다. 설치 과정에서 오류가 발생하면 `--legacy-peer-deps` 옵션을 추가해 다시 설치를 시도합니다.

```sh
npm i -D storybook-addon-react-router-v6 --legacy-peer-deps
```

`--legacy-peer-deps` 옵션 사용 대신, `.npmrc` 파일을 활용할 수 있습니다. (https://github.com/yamoo9/likelion-FEQA/issues/145#issuecomment-1468863490)

### 애드온 구성

`.storybook/main.js` 파일을 열어 설치한 애드온을 구성합니다.

```js
const config = {
  addons: [
    // ...
    'storybook-addon-react-router-v6',
  ],
};
```

### 데코레이터 구성

`.storybook/preview.js` 파일에 애드온 패키지로부터 withRouter 고차 함수를 추출하여 글로벌 decorators, parameters를 설정합니다.

```js
import { withRouter } from 'storybook-addon-react-router-v6';

// ...

export const decorators = [
  withRouter
];

export const parameters = {
  reactRouter: {
    routePath: '/',
  },
};
```

### 컴포넌트 파일

Link 컴포넌트 코드를 아래와 같이 수정합니다.
참고로 Link 컴포넌트 이름이 중복 되므로 React Router의 Link 컴포넌트 이름은 다른 이름으로 변경해야 합니다.

```jsx
import PropTypes from 'prop-types';
import { Link as ReactRouterLink } from 'react-router-dom';
import './link.css';

export const Link = (props) => {
  return <ReactRouterLink to={props.path}>{props.label}</ReactRouterLink>;
};

Link.propTypes = {
  path: PropTypes.number.isRequired,
  label: PropTypes.string.isRequired,
};
```

### 스토리 파일

Link 컴포넌트 스토리 파일을 작성합니다.

```js
import { Link } from './Link';

export default {
  title: 'Example/Link',
  component: Link,
  tags: ['autodocs'],
};

export const HomeLink = {
  args: {
    to: '/',
    label: '홈 페이지로 돌아가기',
  },
};
```

### 구동된 Storybook 앱

모든 설정이 마무리 되면 정상적으로 Storybook 앱이 렌더링 됩니다. 😃

<img width="917" alt="" src="https://user-images.githubusercontent.com/1850554/224605431-7986991b-3f4e-42cc-8236-eecd67dbfb5e.png">

## 가이드 파일

가이드 한 내용이 포함된 ZIP 파일 첨부합니다. 내려 받아 확인해보세요. 😉

[Monstera-develop_confirm-by-yamoo9-v0.0.1.zip](https://github.com/yamoo9/likelion-FEQA/files/10961976/Monstera-develop_confirm-by-yamoo9-v0.0.1.zip)

**Comment by kimzeze** [comment]
감사합니다 👍  
말씀하신 **decorators, parameters를 설정** 은 혹시 `.storybook/main.js`에 적어주신 코드를 넣으면 되는걸까요?

**Comment by yamoo9** [comment]
> 감사합니다 👍 말씀하신 **decorators, parameters를 설정** 은 혹시 `.storybook/main.js`에 적어주신 코드를 넣으면 되는걸까요?

<s>네 맞아요</s> 🙂 
아닙니다. `.storybook/preview.js` 파일에 넣어주세요. ^^;

**Comment by kimzeze** [comment]
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/96248861/224692620-bfd0bc49-be9d-4360-aced-c1ecf9fcaa93.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/96248861/224692665-45b5ac9a-cf52-43cf-8c8b-ba659f04a853.png">


main.js에 decorators, parameters를 추가했을 때 위와 같은 오류로 storybook 자체가 실행되지 않는데 찾아봐도 잘모르겠습니다 ㅠㅠ
말씀해주신대로 변경한 것들은 [여기](https://github.com/kimzeze/Monstera/tree/develop) 의 develop 브랜치에 적용되어 있습니다

**Comment by yamoo9** [comment]
## 문제 원인

@kimzeze 님 😅 
제가 글로벌 데코레이터 코드를 작성할 파일을 잘못 말씀 드렸어요. 죄송합니다.
정상 작동되도록 하려면 `.storybook/preview.js` 파일에 작성해야 합니다.

## 가이드 파일

문제를 해결한 가이드 파일을 첨부합니다. 😄
다운로드 받아 확인해보세요.

[Monstera-develop_confirm-by-yamoo9-v0.0.2.zip](https://github.com/yamoo9/likelion-FEQA/files/10962176/Monstera-develop_confirm-by-yamoo9-v0.0.2.zip)

## 설치 가이드

참고로 다른 팀원이 설치 시, [storybook-addon-react-router-v6](https://storybook.js.org/addons/storybook-addon-react-router-v6) 종속성 모듈 호환 문제가 발생할 수 있어요.

### 재 설치 준비

재 설치를 위해 기존 node_modules, package-lock.json 파일을 삭제합니다.

```sh
rm -rf node_modules package-lock.json
```

### 설치

그리고 다시 종속성 모듈을 설치하는 명령을 실행합니다.

```sh
npm install
```

설치에 문제가 없다면 아래 화면처럼 표시됩니다.

<img width="838" alt="" src="https://user-images.githubusercontent.com/1850554/224838179-6f8dbe75-48dc-4052-a76c-194b7b61df69.png">

### 설치에 실패할 경우

만약, 설치에 실패하면 `--legacy-peer-deps` 옵션을 설정해 설치합니다.

```sh
npm install --legacy-peer-deps
```

그리고 storybook-addon-react-router-v6 종속성 모듈을 다시 설치해야 합니다.

```sh
npm i storybook-addon-react-router-v6 --legacy-peer-deps
```

> `--legacy-peer-deps` 옵션 사용 대신, `.npmrc` 파일을 활용할 수 있습니다. (https://github.com/yamoo9/likelion-FEQA/issues/145#issuecomment-1468863490)

### Storybook 앱 구동

문제 없이 설치가 수행되었다면 Storybook을 구동하는 명령을 실행합니다.

```sh
npm run storybook
```

<img width="1319" alt="" src="https://user-images.githubusercontent.com/1850554/224838461-191be225-0688-4d9f-b15c-df6be4a2db13.png">

Storybook 앱이 구동된 후, Link 컴포넌트 스토리를 확인해 봅니다. 문제 없이 출력될 거에요. 😄

<img width="917" alt="" src="https://user-images.githubusercontent.com/1850554/224838582-ffae4aa3-a845-4f2c-97e3-1951f2b4bced.png">

**Comment by kimzeze** [comment]
넵 말씀하신대로 수정하니 Link 컴포넌트가 storybook에서 원하는대로 정상 동작합니다 !
답변 정말 감사합니다 :)
