### ISSUE TITLE
[LAB-19] 각 로컬 브랜치에서 pull 할 때 생성된 merge커밋을 PR에 포함하지 않으려면?

### ISSUE THREAD

**Issue by djswns7** [yamoo9/likelion-FEQA#135]
## 질문 작성자

박원준

## 문제 상황

제목과 같이 Organization에서 브랜치가 업데이트 될 때, 각 팀원의 로컬에서는 자주 코드를 동기화하게 되는데,
업데이트 된 코드를 반영하기 위해 upstream 저장소에서 pull 할 때 merge 커밋이 발생하고
해당 커밋들이 pr 이후에 공동 저장소의 커밋 기록에도 남아서 보기가 나빠서 
이를 더이상 나타나지 않게 하고 싶은데 방법이 있는지 궁금합니다

![image](https://user-images.githubusercontent.com/72201211/224596310-33c50f24-3af7-4cbd-873d-255f68080e3c.png)
![image](https://user-images.githubusercontent.com/72201211/224597019-38835f42-6d39-40e0-ae06-8cb63f4d33ff.png)

**Comment by yamoo9** [comment]
## Pull Requests — Allow squash merging

[PR에 대한 커밋 Squash 구성](https://docs.github.com/ko/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests)을 사용해보시겠어요?

테스트 해보지는 않았습니다만, 요구한 기능(merge 커밋 PR에서 미 포함) 대신 브랜치의 커밋 이력을 한데 모아 병합 할 수 있습니다.
기본 Merge 버튼을 사용하는 대신, Squash Merging 되도록 구성을 변경한 후 PR하여 결과를 확인해보세요.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/1850554/224615322-79e842f2-19ec-484e-b0ea-fd788b554091.png">

## 참고

Merge, Squash & Merge, Rebase & Merge 차이점에 대해 확인해보세요. 😊

[GitHub의 Merge, Squash and Merge, Rebase and Merge 정확히 이해하기](https://meetup.nhncloud.com/posts/122)

**Comment by djswns7** [comment]
생각했던 것과는 약간 다르게 작동하긴 했지만 이 부분을 알아보면서, squash merge 와 rebase merge 방식을 이해하고, PR에 의한 커밋 기록방식에 대해 더 잘 이해하게 되었습니다. 감사합니다.

상황에 따라 로컬영역에서 pull 사용시에 --rebase 옵션을 활용해서 merge커밋생성 자체를 안 할 수도 있는 것 같은데 약간 연습해보고 사용해 보겠습니다
