### ISSUE TITLE
[LAB-17] Storybook 구동 오류 (확인 결과: 컴퓨터 이름에 한글이 포함 되서 발생)

### ISSUE THREAD

**Issue by semin99** [yamoo9/likelion-FEQA#136]
## 질문 작성자

장세민

## 문제 상황

![image](https://user-images.githubusercontent.com/87403695/224603961-b28e084c-37ae-4d81-9ef5-ee34ebb03832.png)

 Storybook v6 -> v7 로 버전 업그레이드 후 storybook이 실행되지않는 현상이 있습니다.

## 코드 검토 리소스
https://github.com/semin99/NatureKarly/tree/develop

## 환경 정보
- Windows
- Node.js v19.7.0

**Comment by shoveller** [comment]
안녕하세요. @semin99 님.
보내주신 develop 브랜치를 내려받아서 실행해 봤는데, 실행에 문제가 없는것 같습니다?
위의 에러 메시지는 `.storybbok/main.js` 가 없다고 알리고 있는데, develop 브랜치에는 `.storybbok/main.js`가 있단 말이지요?
node_modules 를 지우고 다시 설치하는것도 해 보셨을까요?
![스크린샷 2023-03-13 오후 1 31 55](https://user-images.githubusercontent.com/1357198/224610020-c11b780c-ab86-4538-bf90-42f217bd8749.png)

**Comment by yamoo9** [comment]
## 문제 원인

해당 문제는 디스코드로 화면 공유해서 확인한 결과 **Windows 운영체제를 사용하는 컴퓨터 이름에 한글이 포함되었기 때문**입니다.

## 문제 해결

**프로젝트 디렉토리를 다른 드라이브(D)로 옮겨 확인**해보니 문제 없이 Storybook 앱이 구동되었습니다. 🤔

**Comment by semin99** [comment]
감사합니다!!
