### ISSUE TITLE
[LAB-2] Github PR 시 오류 질문 요청드립니다!

### ISSUE THREAD

**Issue by leejh4197** [yamoo9/likelion-FEQA#138]
## 질문 작성자
유하리
## 문제 상황
github 질문 드립니다! 
저희조는 develop 브랜치를 하나 두고 각자 브랜치를 파서 기능별로 작업을 하고 있습니다. 기능별 구현이 끝나서 develop에 PR하는 도중 특정 브랜치에서만 최신화된 develop브랜치 pull 을 못받아오는 상황이 발생하여 도움을 요청드립니다!
방으로 와주세요!

**Comment by seulbinim** [comment]
안녕하세요 하리님
[LAB-2]실에 방문하여 해결해 드렸습니다.
조언 드렸던 것 처럼 각자의 브랜치를 원격으로 먼저 Push 를 한 후 Pull Request를 생성하시면 됩니다.
이때 feature/hari/login-register 브랜치를 보낼 때 -f 옵션을 추가해서 강제로 푸시를 해서 문제를 해결했습니다.
도움이 되셨기를 바라며 남은 프로젝트도 화이팅 하시기 바랍니다. ^^
