### ISSUE TITLE
[LAB-4] 모달창을 관리하기 위한 쿠키가 생각한대로 작동이 잘 안됩니다

### ISSUE THREAD

**Issue by SeoMiYoung** [yamoo9/likelion-FEQA#139]
## 질문 작성자
서미영

## 문제 상황
안녕하세요. 파이널 프로젝트에서 저희팀은 마켓칼리를 선택했습니다.
저는 지금 마켓컬리의 MAIN페이지에 띄워지는 모달창을 구현하고 있는데요,
![image](https://user-images.githubusercontent.com/112063987/224939098-6acbac94-9bb2-42d2-889c-b7e9b9edd2b0.png)

이 부분에 대해서 마크업및 CSS는 모두 완료된 상황이고,
'오늘 하루 안 보기'버튼을 쿠키를 사용해서 구현하려고 하다가 도저히 해결할 수가 없어 질문드립니다.

현재 저는
pages/Home/Home.jsx 에다가 Mainmodal이라는 컴포넌트를 넣어주고 있는데요,
제가 생각하는대로 작동이 안됩니다.

문제설명)
![image](https://user-images.githubusercontent.com/112063987/224945906-fad77c39-970f-4394-97e6-9185f849dd7b.png)
위의 사진은 npm start로 띄운 화면의 모습입니다.

위의 상태에서, 오늘 하루 안보기 버튼을 클릭하면, 다음 사진과 같이 쿠키가 생성됩니다.
![image](https://user-images.githubusercontent.com/112063987/224946385-bf5d5a3c-00bf-480c-8096-1a00a426cbf8.png)
이렇게 만료일이 하루뒤인 시점으로 생성됩니다.

그러면, 다시 리로딩을 했을때,
![image](https://user-images.githubusercontent.com/112063987/224950358-506a8921-c3b2-4c01-ba33-b89a80a56f13.png)
 window.addEventListener('DOMContentLoaded', function () { ~ 가 실행되고,
getCookie('modalClose')를 통해 특정 name의 쿠키가 있음을 확인하는데,
getCookie('modalClose')는 value[2]를 반환하므로, if문은 true가 됩니다.
그러면 isModalOpen이라는 state가 false가 되어, 리랜더링 될 때 모달창이 다시 뜨면 안된다고 생각했습니다.

그러나, 쿠키가 있든말든 창을 다시 리로드할때마다 팝업창이 계속 뜹니다.

혹시 제가 잘못 생각하고 짜고 있는지 확인해주시면 감사하겠습니다.

## 프로젝트 저장소 URL
https://github.com/SeoMiYoung/project-repo

브랜치명: feat/#11

## 환경 정보
- 운영체제 정보: 윈도우
- Node.js 정보: v18.14.0

**Comment by yamoo9** [comment]
## 문제 상황

설정된 쿠키 값을 읽어 모달 다이얼로그를 하루만 표시하도록 설정해야 합니다.

## 문제 해결

먼저 getCookie 유틸리티 함수를 작성합니다.

```jsx
function getCookie(name) {
  let cookieName = document.cookie
    .split(';')
    .find((c) => c.trim().startsWith(`${name}=`));

  if (cookieName) {
    return cookieName.split('=').map((v) => decodeURIComponent(v.trim()))[1];
  }
}
```

Home 컴포넌트 내부에 useLayoutEffect 훅을 사용해 'modalClose' 쿠키 값이 존재하는 지 여부를 확인합니다.
존재할 경우, setModalOpen(false)를 실행해 모달 다이얼로그가 표시되지 않도록 설정합니다.

```jsx
import { useState, useLayoutEffect } from 'react';

function Home() {
  const [isModalOpen, setModalOpen] = useState(true);

  useLayoutEffect(() => {
    let modalCloseValue = getCookie('modalClose');

    if (modalCloseValue && modalCloseValue?.includes('T')) {
      setModalOpen(false);
    }
  }, []);

  return (
    <>
      <div>Home</div>
      <Footer />
      {isModalOpen ? <Mainmodal setModalOpen={setModalOpen} /> : null}
    </>
  );
}
```

## 처리 결과

화면에 표시된 모달 다이얼로그 "오늘 하루 안보기"를 클릭하면 새로고침 했을 때 더 이상 표시되지 않습니다.

![Mar-14-2023 18-34-18](https://user-images.githubusercontent.com/1850554/224958429-4c0d593d-3c9b-4558-8df2-38d18ca2dc82.gif)

## 가이드 파일

첨부된 src 디렉토리 압축 파일을 내려받아 참고하세요. 😌

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/10966741/src.zip)

**Comment by SeoMiYoung** [comment]
야무쌤 답변해주셔서 정말 감사드립니다.
답변해주신걸 토대로 추가 질문을 해도 괜찮을까요?

[추가질문1] useLayoutEffect를 사용하신 이유가 궁금합니다.
저는 처음에 useEffect를 사용할 생각을 했었는데요,
저는 useLayoutEffect를 랜더링 되기 전에 실행되고, useEffect는 랜더링된 이후에 실행되는것으로 알고있는데요,
인터넷에 찾아보니깐, 사용자에게 노출되는 DOM을 변형시킬때는 깜빡거림 현상을 막기 위해? useEffect대신에 useLayoutEffect를 사용한다는 식으로 나와있더라구요.
그런데, 정확한 이유를 모르겠어서 확인받고 싶어서 질문합니다!

[추가질문2] 개념이 조금 헷갈려서 질문드립니다.
useLayoutEffect 는 Dependency Array가 [] 로 설정되어있잖아요?
 즉, 이 경우에는 첫 랜더링에서만 동작하겠다는 뜻인데,
첫 랜더링이라는게, 페이지에 접속을 한 이후 딱 처음만 랜더링 한다는 의미이죠?

음..그러니깐, 
![image](https://user-images.githubusercontent.com/112063987/225174962-ee9b88b0-5c78-47be-9dd8-84c84e21d12d.png)
이런 새로고침을 누를때마다
setState가 다시 설정되고, useLayoutEffect도 다시 실행되는거죠?

[추가질문3]
![image](https://user-images.githubusercontent.com/112063987/225175303-61a26034-ea6f-477c-a870-a040280e85e2.png)
야무무쌤께서 getCookie함수를 만들때 
;로 split하고, find하고 그러는 방식으로 쿠키의 이름을 찾아냈는데요,
document.cookie 의 형태가 어떤식으로 나오길래 저렇게 뽑아내는건지 궁금해서 콘솔로 찍어보려고 했습니다.
![image](https://user-images.githubusercontent.com/112063987/225175459-cc5fb755-1e5d-4c5b-a61e-07056dd957c8.png)
그래서 이렇게 console.log로 쿠키값을 출력해보려고 했는데,

![image](https://user-images.githubusercontent.com/112063987/225175648-d5f5031c-022b-4e4f-b612-06945ec2481f.png)
콘솔창을 열어보면 아무것도 출력되어 있지 않습니다.
만약에 쿠키가 있다면,
![image](https://user-images.githubusercontent.com/112063987/225178061-f7a6b5c1-2182-4471-b2c6-c10953774a7b.png)
이렇게 출력되는 것 같습니다.

야무쌤께서 .split(';') 를 쓰셔서, 아마 원래 쿠키에는 ;들이 포함되어 있는 형태인 것 같은데,
그걸 확인하고 싶으면 어떻게 해야될까요?

답변해주시면 감사하겠습니다!!

**Comment by yamoo9** [comment]
> 야무쌤 답변해주셔서 정말 감사드립니다. 답변해주신걸 토대로 추가 질문을 해도 괜찮을까요?
> 
> [추가질문1] useLayoutEffect를 사용하신 이유가 궁금합니다. 저는 처음에 useEffect를 사용할 생각을 했었는데요, 저는 useLayoutEffect를 랜더링 되기 전에 실행되고, useEffect는 랜더링된 이후에 실행되는것으로 알고있는데요, 인터넷에 찾아보니깐, 사용자에게 노출되는 DOM을 변형시킬때는 깜빡거림 현상을 막기 위해? useEffect대신에 useLayoutEffect를 사용한다는 식으로 나와있더라구요. 그런데, 정확한 이유를 모르겠어서 확인받고 싶어서 질문합니다!
> 
> [추가질문2] 개념이 조금 헷갈려서 질문드립니다. useLayoutEffect 는 Dependency Array가 [] 로 설정되어있잖아요? 즉, 이 경우에는 첫 랜더링에서만 동작하겠다는 뜻인데, 첫 랜더링이라는게, 페이지에 접속을 한 이후 딱 처음만 랜더링 한다는 의미이죠?
> 
> 음..그러니깐, ![image](https://user-images.githubusercontent.com/112063987/225174962-ee9b88b0-5c78-47be-9dd8-84c84e21d12d.png) 이런 새로고침을 누를때마다 setState가 다시 설정되고, useLayoutEffect도 다시 실행되는거죠?
> 
> [추가질문3] ![image](https://user-images.githubusercontent.com/112063987/225175303-61a26034-ea6f-477c-a870-a040280e85e2.png) 야무무쌤께서 getCookie함수를 만들때 ;로 split하고, find하고 그러는 방식으로 쿠키의 이름을 찾아냈는데요, document.cookie 의 형태가 어떤식으로 나오길래 저렇게 뽑아내는건지 궁금해서 콘솔로 찍어보려고 했습니다. ![image](https://user-images.githubusercontent.com/112063987/225175459-cc5fb755-1e5d-4c5b-a61e-07056dd957c8.png) 그래서 이렇게 console.log로 쿠키값을 출력해보려고 했는데,
> 
> ![image](https://user-images.githubusercontent.com/112063987/225175648-d5f5031c-022b-4e4f-b612-06945ec2481f.png) 콘솔창을 열어보면 아무것도 출력되어 있지 않습니다. 혹시 제가 뭘 잘못 입력한걸까요?
> 
> 답변해주시면 감사하겠습니다!!

## 추가 답변 1.

useLayoutEffect의 이펙트 콜백이 useEffect 보다 빠른 시점에 실행됩니다.
사용자에게 잠시라도 모달 다이얼로그가 표시 되길 원하지 않으니 useLayoutEffect를 사용했습니다.

## 추가 답변 2. 

아닙니다. 종속성 배열이 비어 있으므로 최초 마운트 시 1회만 useLayoutEffect의 이펙트 콜백이 실행될 뿐입니다.
그럼에도 모달 다이얼로그가 안 보이는 이유는 `isModalOpen` 상태가 변경 됨에 따라 컴포넌트가 다시 렌더링 될 때 
조건에 따라 다이얼로그가 표시되지 않기 때문입니다. useLayoutEffect의 이펙트 콜백이 다시 실행된 것은 아닙니다.

## 추가 답변 3.

콘솔 패널에 `document.cookie` 라고 입력하면 쿠키 값이 출력됩니다. 내부에 세미콜론(`;`)이 포함된 것을 확인할 수 있을 거에요.

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/1850554/225182565-6d7258bd-3a03-4635-ba24-b4fede2b1611.png">

**Comment by SeoMiYoung** [comment]
추가답변 2에 대해 추가 질문있습니다.
useLayoutEffect의 이펙트 콜백이 다시 실행된것은 아니라고 하셨는데,
![image](https://user-images.githubusercontent.com/112063987/225197782-fc0107e3-be09-4f5b-9318-5d79cf897a0f.png)
지금 사진을 보시면,
useLayoutEffect에서 쿠키가 있는지 없는지 getCookie를 통해 확인하고 있는걸 확인할 수 있습니다.
저는 개인적으로 새로고침을 할때마다 getCookie를 통해 쿠키의 존재를 확인해야된다고 생각했는데,
새로고침을 할때마다 useLayoutEffect가 실행되는건 아니라고 답변해주셔서 이해가 안갔습니다.
혹시 추가설명을 해주실 수 있나요?

또한, 
저희 팀에서
![image](https://user-images.githubusercontent.com/112063987/225198529-202976df-3fb5-4cd5-9826-564ccd4525a9.png)
이 부분에서 파란색박스 부분을 유틸함수로 빼서 관리하면 어떻겠냐는 이야기가 나왔었는데요,
파란색 박스 안에는 isModalOpen이라는 state가 설정되어있습니다.
이 부분을 유틸함수로 빼서 관리하는게 효율적일까요?
사실 저는 getCookie같은 함수는 유틸함수로 관리해본적이 있지만,
state와 useLayoutEffect를 유틸함수로 빼는건 조심스럽습니다.

어떻게 생각하시는지 의견이 궁금합니다!

**Comment by yamoo9** [comment]
> 

## 답변 1.

새로고침 할 때 마다 getCookie 확인은 매번 이뤄집니다. 왜냐하면 새로고침 할 때마다 마운트가 1회 일어나기 때문이죠.
새로고침 할 때마다 useLayoutEffect 훅의 이펙트 콜백은 실행됩니다. React가 리-렌더링 될 때는 더 이상 작동하지 않지만요.

## 답변 2.

커스텀 훅으로 내보내 재 사용할 수 있어요. 유틸리티 함수가 아니라.
커스텀 훅은 React 내장된 훅을 포함하는 특별한 함수로 use 접두사로 시작해야 합니다. ([참고](https://ko.reactjs.org/docs/hooks-custom.html))

**Comment by SeoMiYoung** [comment]
오오오 정말 너무 답변 감사드립니다. 
궁금했던점이 싹 해결되네요 ㅎㅎ!!
