### ISSUE TITLE
[LAB-4] React Router로 링크 연결 시, 외부링크 연결 방법에 대해 궁금합니다

### ISSUE THREAD

**Issue by SeoMiYoung** [yamoo9/likelion-FEQA#140]
## 질문 작성자
서미영

## 문제 상황
이전 바닐라 프로젝트에서는 링크 연결시, <a>태그의 href를 사용해서 연결했습니다.
그러나, 이번 React 프로젝트에서는 <Link>의 to를 사용해서 연결하고 있는데요,

페이지내의 이동은 <Link>를 통해 구현할 수 있지만,
(예를 들면, SignIn페이지로 이동하려면, to="/SignIn"이렇게 연결 => localhost:3000/SignIn으로 연결됨 )
만약 이동하려는 페이지가 네이버 같은 외부링크일때,
to="www.naver.com" 이렇게 넣으면,
localhost:3000/www.naver.com
이렇게 연결됩니다.

당연히 연결되지 않습니다.
혹시, 리액트 라우터를 이용하면 외부링크연결이 불가능한것인가요..?
이럴경우 어떻게 해야될까요?
답변해주시면 감사하겠습니다.

참고로, 제가 외부링크와 연결하려고 하는곳은 바로,
Footer.jsx의 다음 사진에 나와있는 부분입니다.
![image](https://user-images.githubusercontent.com/112063987/224954827-4b007fb4-945c-4550-a27b-34b22b83b046.png)

## 프로젝트 저장소 URL
https://github.com/SeoMiYoung/project-repo
브랜치: feat/#10

## 환경 정보
- 운영체제 정보: 윈도우
- Node.js 정보: v18.14.0

**Comment by yamoo9** [comment]
## 문제 상황

React Router 사용 시, 외부 링크하는 방법을 알고 싶습니다.

## 문제 해결

React Router의 Link 컴포넌트는 외부 링크하는 방법을 제공하지 않으므로 Link 컴포넌트를 래핑 하는 컴포넌트를 설계합니다.
편의를 위해 래핑한 컴포넌트를 Link로 이름 지었습니다. 다른 이름으로 설정해도 무방합니다. 

```jsx
import { Link as ReactRouterLink } from 'react-router-dom';

function Link({ to, label, children, ...restProps }) {
  if (/^https?:\/\//.test(to)) {
    return (
      <a
        aria-label={label}
        href={to}
        rel="noreferrer noopener"
        target="_blank"
        title={label}
      >
        {children}
      </a>
    );
  } else {
    return (
      <ReactRouterLink to={to} {...restProps}>
        {children}
      </ReactRouterLink>
    );
  }
}
```

이제 커스텀 Link 컴포넌트를 사용해 링크 주소가 http로 시작하는 주소를 설정하면 새 탭에서 링크가 열리게 됩니다.

```jsx
<div className={styles.footerCompanySns}>
  <Link label="컬리 네이버 블로그 바로가기" to={instagramUrl}>
    <Blog alt="" />
  </Link>
  <Link label="컬리 페이스북 바로가기" to={facebookUrl}>
    <Facebook alt="" />
  </Link>
  <Link label="컬리 인스타그램 바로가기" to={naverBlogUrl}>
    <Instagram alt="" />
  </Link>
  <Link label="컬리 네이버포스트 바로가기" to={naverPostUrl}>
    <Naver alt="" />
  </Link>
  <Link label="컬리 유튜브 바로기" to={youtubeUrl}>
    <Youtube alt="" />
  </Link>
</div>
```

## 구현 결과

이제 SNS 링크를 클릭하면 새 탭에서 열립니다. 😄

![Mar-14-2023 18-57-38](https://user-images.githubusercontent.com/1850554/224964732-28aac890-de3f-4431-a9db-a18f66e9ce5d.gif)

## 가이드 파일

가이드 코드가 첨부된 압축 파일을 다운로드 받아 확인해보세요.

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/10966969/src.zip)

**Comment by SeoMiYoung** [comment]
야무쌤의 자세한 설명덕분에 많이 알아갑니다. 감사합니다. 
혹시 답변해주신것에 대한 추가 질문을 할 수 있을까요?

추가질문1) if (/^https?:\/\//.test(to)) 이런 정규표현식 표현으로 외부링크를 판별한 것 같은데,
지금 야무쌤께서 코드를 주셔서 그렇지만, 알려주시지 않았다면, 사용하지 못했을 것 같습니다. 
혹시 정규표현식은 어떻게 알고 가져다가 써야할까요? 겉으로 보기에는 문자기호같고..어디서 정보를 얻어야할지 잘 모르겠거든요..

추가질문2) 코드중에서, 
![image](https://user-images.githubusercontent.com/112063987/224990330-1c1204ef-5a00-4a21-862d-bebb9a4061bb.png)
이런식으로 children을 {'  '}와 'help@karlycorp.com'를 넣어준거잖아요?
근데 'help@karlycorp.com'이건 제가 <a>태그로 링크를 걸어주려고 넘겨준건 알겠는데,
{'  '}는 왜 넘겨준거일까요??

답변해주시면 감사하겠습니다.

**Comment by yamoo9** [comment]
@SeoMiYoung 님 추가 질문에 답변 드립니다. 🙂

## 추가 답변 1.

[정규 표현식](https://ko.javascript.info/regular-expressions)을 공부한 후, 기본적인 것은 직접 작성할 수 있는 힘을 길러야 해요. 

하지만 너무 어려운 정규 표현식 작성은 어려울 수 있어요. 예를 들어 현장에서 개발 중 급하게 정규 표현식을 사용해야 하는데 
아직 공부가 덜 되었고 물어보기도 어려운 상황이라면 [Google 검색](https://bit.ly/3ZKElPd)의 힘을 빌려 복사/붙여넣기 마공을 사용할 수도 있겠죠 ^^;

## 추가 답변 2.

JSX 내부에서 `{' '}` 표현은 공백을 의미해요. 위 코드의 경우 Prettier에 의한 자동 포멧팅으로 공백 표현이 들어갔을 확률이 높습니다.
불필요한 공백이라면 제거해도 됩니다.

```jsx
<Link to="/" className={styles.nonMemberEmail}>
  help@karlycorp.com
</Link>
```

**Comment by SeoMiYoung** [comment]
오오 야무쌤 정말 도움 많이 되었습니다~! 답변 감사해요!!
