### ISSUE TITLE
[LAB-03] Vite 환경변수(.env) 설정에 대한 질문입니다. (with Kakao Map)

### ISSUE THREAD

**Issue by Juhee-Hwang** [yamoo9/likelion-FEQA#141]
## 질문 작성자

황주희

## 문제 상황

- kakao map API 연결을 위해 script 추가하고 src에 들어갈 API KEY를 .env 파일에 추가했습니다.
- VITE를 사용하여 빌드했기 때문에 환경변수를 import.meta.env로 불러오기까지도 성공했습니다.
- 아래 이미지를 보시면 script 태그가 head태그 내부에 잘 들어가있는 것을 볼 수 있습니다. 
- <img width="555" alt="스크린샷 2023-03-14 오후 7 55 50" src="https://user-images.githubusercontent.com/33420714/224980018-76626623-e98b-4969-b8c3-c21f4dc9b64a.png">

- 근데 제대로 되지 않아서 무엇이 문제일까 생각했을때 index.html의 경로가 public폴더가 아니여서 그런가 하는 생각이 들었습니다.
- 혹시 index.html 경로를 수정하면 해결이 될까요...?

- 아래는 오류 메세지입니다.
<img width="1392" alt="스크린샷 2023-03-14 오후 7 53 53" src="https://user-images.githubusercontent.com/33420714/224979582-7c14e847-1dbe-4752-bd9d-5e636663461b.png">

## 프로젝트 저장소 URL

[car-zip/origin repo](https://github.com/Juhee-Hwang/car-zip/tree/feature/%2320)
`feature/#20` 브랜치입니다.

[car-zip.zip](https://github.com/yamoo9/likelion-FEQA/files/10967483/car-zip.zip)

[카카오맵 API 가이드 링크](https://apis.map.kakao.com/web/guide/) 입니다.

## 환경 정보

- 운영체제 정보 macOS
- Node.js 정보 v18.12.1
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 환경 변수 파일 부재

환경 변수 파일을 첨부한 ZIP 압축 파일 안에서 찾을 수 없습니다. 
이런 유형의 오류는 발급받은 API KEY를 공유해주셔야 테스트가 가능합니다.
발급받은 API KEY 외부 공개가 우려된다면? 디스코드를 통해 파일 공유해주세요.

## 문제 원인

index.html 파일에 직접 Kakao 지도 스크립트 코드를 삽입해야 정상 작동합니다.

```html
<!DOCTYPE html>
<html lang="ko-KR">
  <head>
    <!-- ... -->
    <script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=발급받은_KAKAO_API_KEY"></script>
  </head>
  <body>
    <!-- ... -->
  </body>
</html>
```

동적 삽입의 경우 Kakao 지도 API 스크립트를 호출하지 못합니다. (확인 결과)

<img width="985" alt="" src="https://user-images.githubusercontent.com/1850554/225133771-e37b46ae-0bc9-4474-8c8a-1bcc69ee6938.png">




KakaoMap 컴포넌트 코드는 다음과 같이 작성합니다.

```jsx
import { useRef, useLayoutEffect } from 'react';

export default function KakaoMap() {
  const mapRef = useRef(null);

  useLayoutEffect(() => {
    const mapContainer = mapRef.current;

    const options = {
      center: new kakao.maps.LatLng(33.450701, 126.570667),
      level: 3,
    };

    const map = new kakao.maps.Map(mapContainer, options);
  }, []);

  return (
    <>
      <div ref={mapRef} style={mapStyle} />
    </>
  );
}

const mapStyle = { width: 500, height: 400 };
```

그러면 정상적으로 지도가 화면에 표시됩니다.

<img width="1057" alt="" src="https://user-images.githubusercontent.com/1850554/225132923-fa0ad969-dbd5-47f0-9735-b69dfa2902ac.png">

## 환경 변수 API 키 → index.html 설정

index.html 파일에 삽입된 API 키를 환경 변수로 설정 하려면? 아쉽게도 Vite는 기본적으로 그런 기능을 제공하지 않습니다.
그럼에도 환경 변수를 사용해 API 키를 사용하려면? [vite-plugin-html-env](https://www.npmjs.com/package/vite-plugin-html-env) 플러그인을 설치해 사용할 수 있습니다.

```sh
npm i -D vite-plugin-html-env
```

vite.config.js 구성 파일에 설치한 플러그인을 설정합니다. ([참고](https://github.com/lxs24sxl/vite-plugin-html-env#usage))

```js
import htmlEnv from 'vite-plugin-html-env';

export default defineConfig({
  plugins: [
    htmlEnv({
      prefix: '%',
      suffix: '%',
    }),
   // ...
  ],
  // ...
});
```

설정을 마쳤다면 `index.html` 파일에서 `.env` 파일의 환경 변수를 사용할 수 있습니다.

```html
<script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=%VITE_KAKAOMAP_API_KEY%"></script>
```

## 가이드 파일

가이드 한 내용이 포함된 ZIP 파일을 첨부합니다.

[car-kakao-map-confirm-by-yamoo9.zip](https://github.com/yamoo9/likelion-FEQA/files/10973694/car-kakao-map-confirm-by-yamoo9.zip)

## React 용 Kakao Maps SDK 라이브러리

참고로 [react-kakao-maps-sdk](https://www.npmjs.com/package/react-kakao-maps-sdk) 라이브러리를 사용해 React 앱에 Kakao 지도를 렌더링 할 수 있어요. 
Kakao에서 공식적으로 제공하는 라이브러리는 아니지만, 사용을 고려할 수 있습니다. ([API 문서](https://react-kakao-maps-sdk.jaeseokim.dev/) 참고)

<img width="1297" alt="" src="https://user-images.githubusercontent.com/1850554/225135044-c70b9770-89de-4be9-b550-e036a80bc7ff.png">

**Comment by Juhee-Hwang** [comment]
아하..! 플러그인 설치하고 해보니 되네요!! 감사합니다 야무쌤 ㅠㅠ
이와 별개로 한가지 여쭤보고 싶은게 있는데요..!
혹시 index.html의 경로를 지금 경로가 아닌 public 폴더 안에 넣는다면 어떤 설정들을 수정해주어야 하나요?
어제 폴더 구조 바꿔보려다가 실패해서요ㅠㅠ

**Comment by yamoo9** [comment]
> 아하..! 플러그인 설치하고 해보니 되네요!! 감사합니다 야무쌤 ㅠㅠ 이와 별개로 한가지 여쭤보고 싶은게 있는데요..! 혹시 index.html의 경로를 지금 경로가 아닌 public 폴더 안에 넣는다면 어떤 설정들을 수정해주어야 하나요? 어제 폴더 구조 바꿔보려다가 실패해서요ㅠㅠ

Vite는 CRA와 달리 public 폴더 안에 index.html 을 넣으면 작동하지 않아요. 현 상태에서 작업하는 것을 권장합니다. ^^

**Comment by Juhee-Hwang** [comment]
아하 맞네요..!! 네넵 알겠습니다 :) 감사합니다!
