### ISSUE TITLE
[LAB-8] CRA(JavaScript 번들러 개발 환경)에서 이미지 불러오기 관련 질문입니다.

### ISSUE THREAD

**Issue by rodwnl** [yamoo9/likelion-FEQA#142]
## 질문 작성자

이경주

## 문제 상황
![image](https://user-images.githubusercontent.com/88178123/224992664-8161525a-6734-49d9-98df-60d6fdfd2493.png)
위와 같이 img 경로를 src에 바로 기입하면 이미지가 뜨지 않아서

![image](https://user-images.githubusercontent.com/88178123/224992856-d8af07e8-bf1b-4d33-8337-6edba2f5cc6f.png)
![image](https://user-images.githubusercontent.com/88178123/224992920-1daaa750-3b11-4114-bd22-bc8d9954b367.png)
이미지를 import 시키고 값을 넣으면 이미지가 뜨더라구요.

해결은 했지만 궁금한 점이 있어서 질문드립니다. 
이미지를 불러올때 이와 같이 모든 이미지를 import 시키는 방법밖에 없나요?
자바스크립트 처럼 경로를 src에 넣으면 리액트에 표시되지 않는 이유는 무엇인가요?

## 환경 정보
- Windows

**Comment by yamoo9** [comment]
## JavaScript 번들러 환경과 에셋에 대한 이해

@rodwnl 님 팀에서 사용하는 툴체인은 [CRA(Create React App)](https://create-react-app.dev/docs/adding-images-fonts-and-files) 입니다. CRA는 내부적으로 [Webpack](https://webpack.kr/) 모듈 번들러를 사용해 
JavaScript 모듈 뿐만 아니라 CSS, Images, Fonts와 같은 정적 에셋을 한 데 묶는 번들(bundle) 과정을 수행합니다.

<img width="1075" alt="" src="https://user-images.githubusercontent.com/1850554/225116217-e51a5551-568d-4d33-b3a2-61599a08cb0a.png">

그러므로 **HTML에서 사용하는 것처럼 접근 가능한 주소만 작성해서 가져다 쓸 수 없습니다.** 
이런 특성은 React 뿐만 아니라, Vue도 동일합니다. 즉, 번들러로 구성되는 프론트엔드 개발 환경의 공통사항입니다. ([참고](https://euid.notion.site/8453d9faffe44ecc9045c3d6d4718fbf))

```jsx
import BannerImg from '@/assets/banner01.svg';
```

그리고 JSX는 HTML이 아니므로 JSX의 문법을 사용해 데이터를 보간(interpolation)해야 합니다.

```jsx
<img src={BannerImg} alt="동네가게 바로가기 배너" />
```

## public 디렉토레 정적 에셋 활용 방법

public 디렉토리에 정적 이미지를 포함한 후 가져다 쓸 수 있습니다. ([참고](https://euid.notion.site/Public-9e788c5657064bfe86fe8eaecc20aa94))

예를 들어 public 디렉토리 내부에 `assets/banner01.svg` 파일이 위치한다면 JSX 코드를 다음과 같이 작성할 수 있습니다.
이렇게 사용할 경우 import 구문을 사용하지 않고 이미지 경로를 문자 값으로 바로 쓸 수 있습니다.

```jsx
<img src='/assets/banner01.svg' alt="동네가게 바로가기 배너" />
```

다만, 이런 방식으로 번들러 개발 환경에서 이미지를 사용할 경우 다음 사항을 감수해야 합니다.

- public 디렉토리 내부 파일은 압축, 번들링 되지 않습니다.
- 누락 된 파일이 있을 경우 컴파일 과정에서 호출되지 않으며 404 오류를 발생 시킵니다.
- 출력 파일 이름에 콘텐츠 해시가 포함되지 않아, 브라우저에서 이전 버전을 캐싱 하므로 파일이 변경될 때 마다 파일 이름을 변경해야 합니다.

## 안전하게 public 정적 에셋을 사용하려면?

그리고 public 디렉토리 위치는 구성 설정에 따라 변경될 수 있으므로 다음과 같이 사용해야 안전합니다. ([참고](https://create-react-app.dev/docs/using-the-public-folder#adding-assets-outside-of-the-module-system))

```jsx
<img src={`${process.env.PUBLIC_URL}/assets/banner01.svg`} alt="동네가게 바로가기 배너" />
```

유틸리티 함수를 만들어 사용하면 좀 더 편리하게 작성할 수 있습니다.

```js
export const getPublic = (path = '') => `${process.env.PUBLIC_URL}/${path}`;
```

유틸리티 함수를 사용하면 안전하게 public 디렉토리의 에셋 호출이 가능해집니다. 😃

```jsx
import { getPublic } from '@/utils';

<img src={getPublic('assets/banner01.svg')} alt="동네가게 바로가기 배너" />
```
