### ISSUE TITLE
[LAB-13] Swiper 라이브러리 사용 시, 이미지 조절(중앙 배치) 문제

### ISSUE THREAD

**Issue by chaewon0128** [yamoo9/likelion-FEQA#143]
## 질문 작성자

함채원

## 문제 상황
![Mar-14-2023 23-33-04](https://user-images.githubusercontent.com/119389600/225034327-6da79877-611e-4813-8e59-834ca192a3f8.gif)

안녕하세요.
 타잉 사이트 랜딩 페이지 중 메인 슬라이더(티빙에만 있는 재미) 부분을 스와이퍼 라이브러리를 사용해 제작하는 중 문제가 생겨 질문 남깁니다.
 스와이퍼 기능 중 ``centeredSlides``  를 사용해 active 콘텐츠가 중앙에 위치하게 설정한 상태인데

```
.swiper-slide {
    flex-basis: 904px;
} // 각 슬라이드 컨텐츠 width 사이즈 904px로 변경하기 위해 사용
```
슬라이드 사이즈 조절한 이후 active 컨텐츠가 중앙이 아닌 사이드로 옮겨간 상태입니다. (위의 첨부한 이미지 참고 부탁드립니다)

컨텐츠 사이즈를 904px로 맞추면서 중앙으로 위치 시킬수 있는 방법이 있을까요? 

## 프로젝트 저장소 URL
github push 전 상태라 이미지로 대체해서 올립니다. 

-  jsx
<img width="842" alt="image" src="https://user-images.githubusercontent.com/119389600/225036868-dd025a85-ed63-432a-9bd2-103e2dc54a20.png">

- css
<img width="578" alt="image" src="https://user-images.githubusercontent.com/119389600/225037052-ece1d48f-9226-49ff-a6e2-b109922076bf.png">

## 환경 정보

- 운영체제 정보 (macOS)
- 라이브러리 정보 ("swiper": "9.1.0")

**Comment by yamoo9** [comment]
## 이슈 테스트를 위한 파일 첨부

@chaewon0128 님. 질문에 답변 하려면 스크린샷 만으로는 부족합니다.

아직 GitHub 저장소에 push 하기 전이라 말씀주셨으니, 
node_modules 디렉토리를 제외한 나머지 파일을 압축해 첨부해주세요.

문제 해결 가이드 작성은 압축 파일이 올려졌을 때 검토한 후 가능합니다.

## 관련 이슈 레퍼런스

[Recentering centeredSlides after viewport resize](https://github.com/nolimits4web/Swiper/issues/1731) 이슈와 비슷한 상황입니다.

이슈 작성자인 shuuki는 추후 문제 해결을 위해 스타일을 수정했다고 말합니다. (https://github.com/nolimits4web/Swiper/issues/1731#issuecomment-363363478)
반면 ehinter는 `spaceBetween` 값을 `0`으로 설정해 문제를 해결했다고 말합니다. (https://github.com/nolimits4web/Swiper/issues/1731#issuecomment-366348051)

## Swiper 공식 문서 레퍼런스

화면 크기 별 다른 매개 변수를 설정할 수 있습니다. 중단점에서 모든 매개 변수를 변경할 수 있는 것은 아니며, 
`slidesPerView`, `slidesPerGroup`, `spaceBetween`, `grid.rows`와 같이 다른 레이아웃과 로직이 
필요하지 않은 매개 변수만 변경할 수 있습니다 . `loop`, `effect` 와 같은 매개 변수는 변경 설정할 수 없습니다.

<img width="786" alt="" src="https://user-images.githubusercontent.com/1850554/225148499-e38a1098-e918-4a62-b39b-aa3719e12525.png">

중단점 마다 변경 가능한 매개 변수를 사용해 조정해보는 것도 방법일 수 있습니다. 😃

```js
const swiper = new Swiper('.swiper', {
  // ...
  // 반응형 웹 중단점 설정
  breakpoints: {
    // >= 320px
    320: {
      slidesPerView: 2,
      spaceBetween: 20
    },
    // >= 480px
    480: {
      slidesPerView: 3,
      spaceBetween: 30
    },
    // >= 640px
    640: {
      slidesPerView: 4,
      spaceBetween: 40
    }
  }
});
```

## ⚠️ Swiper React 컴포넌트 이슈

Swiper React 컴포넌트 향후 제거될 가능성이 높습니다. 😱 대신 [Swiper Element](https://swiperjs.com/element) 로 마이그레이션 하는 것을 권장합니다. 
가능하다면 이번 프로젝트에서 Swiper React 대신 Swiper Element로 마이그레이션 해보세요. 🙄

<img width="580" alt="" src="https://user-images.githubusercontent.com/1850554/225149341-514c2238-83f8-41a6-aa4a-c78f8092b7e4.png">

**Comment by chaewon0128** [comment]
답변 감사합니다.   
``slidesPerView= auto`` ``spaceBetween = 0`` 으로 해당 이슈 해결 하였습니다. Swiper Element 사용은 조원들과 논의 해보겠습니다.
