### ISSUE TITLE
[LAB-17] Storybook 파일(js)에서 args의 children(jsx)으로 쓸 때 오류가 발생하는 이유

### ISSUE THREAD

**Issue by nahee09** [yamoo9/likelion-FEQA#144]
## 질문 작성자

김나희

## 문제 상황

Container.jsx에서 Container 컴포넌트를 만든 뒤 Container.stories.js를 만들었습니다. 그런데 children에 Button컴포넌트를 불러와 넣으니 오류가 뜹니다.
- Container.jsx

```javascript
import { string, node, oneOf } from 'prop-types';

import classes from './Container.module.css';

export function Container({
  as: Component,
  className,
  children,
  align,
  width,
  ...restProps
}) {
  const combineClassNames =
    `${classes[align]} ${classes[width]} ${className}`.trim();

  return (
    <Component className={combineClassNames} {...restProps}>
      {children}
    </Component>
  );
}

Container.defaultProps = {
  as: 'div',
  className: '',
  align: 'center',
  width: 'widthLarge',
};

Container.propTypes = {
  as: string,
  className: string,
  children: node,
  align: oneOf(['center', 'left', 'right']),
  width: oneOf(['widthSmall', 'widthMedium', 'widthLarge']),
};
```

- Container.stories.js (children에 Button 컴포넌트를 넣었을 때)

```javascript
import { Container } from './Container';
import { Button } from '../Button/Button';

export default {
  title: 'Components/Container',
  component: Container,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Container 컴포넌트는 하위 요소를 감쌀 수 있고 왼쪽, 중앙, 오른쪽 정렬을 할 수 있습니다.',
      },
    },
  },
  args: { ...Container.defaultProps },
};

/* -------------------------------------------------------------------------- */

export const ContainerGuide = {
  args: {
    align: 'center',
    children: <Button>버튼</Button>,
  },
};
```

- 오류 화면 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/119389649/225036521-7afe0bd8-173e-49a0-8410-bb3ad844ec2f.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/119389649/225036611-5d773039-aa91-42ca-8496-76ab9ebd7f00.png">

다만, Container.stories.js파일에서 children에 문자나 숫자를 넣으면 잘 됩니다.

- Container.stories.js (children에 문자를 넣었을 때)
```javascript 
import { Container } from './Container';
import { Button } from '../Button/Button';

export default {
  title: 'Components/Container',
  component: Container,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Container 컴포넌트는 하위 요소를 감쌀 수 있고 왼쪽, 중앙, 오른쪽 정렬을 할 수 있습니다.',
      },
    },
  },
  args: { ...Container.defaultProps },
};

/* -------------------------------------------------------------------------- */

export const ContainerGuide = {
  args: {
    align: 'center',
    children: '버튼',
  },
};
```

- 잘 나오는 화면
<img width="871" alt="image" src="https://user-images.githubusercontent.com/119389649/225038331-045211af-85c7-4b4e-abcc-c5a1998b5a9c.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/119389649/225038399-d8527cac-e82c-4216-a419-6d269c01b9c9.png">

## 프로젝트 저장소 URL
https://github.com/nahee09/NatureKarly/tree/hotfix/15-container-design 
hotfix/15-container-design 브랜치를 보시면 됩니다. 

## 환경 정보

- 운영체제 정보 : Windows
- Node.js 정보 : v19.7.0

**Comment by yamoo9** [comment]
## 문제 원인

문제 원인은 터미널에 출력된 오류 메시지가 잘 알려 줍니다. 오류 내용을 읽어보면 JSX 문법은 `.js` 확장자 파일에서 지원하지 않는다는 말입니다.

<img width="1185" alt="" src="https://user-images.githubusercontent.com/1850554/225120119-01af4a8c-5c3c-4267-b1b4-6ec42adc7411.png">

## 문제 해결

문제 해결 방법도 오류 메시지가 알려 줍니다. 파일 확장자를 `.js` → `.jsx`로 변경하면 됩니다. 그래야 JSX를 지원합니다. 안내받은 방법대로 확장자만 변경해도 Storybook은 정상적으로 Container 컴포넌트를 표시합니다. 😃

<img width="1202" alt="" src="https://user-images.githubusercontent.com/1850554/225120985-1cb96c1c-3135-4530-b639-cdd8fe97ac8d.png">

**Comment by nahee09** [comment]
jsx로 바꾸니까 잘 되네요!! 감사합니다, 야무쌤~!!
