### ISSUE TITLE
[LAB-20] storybook addon 설치 이후 다른 라이브러리와 충돌이 발생합니다

### ISSUE THREAD

**Issue by kimzeze** [yamoo9/likelion-FEQA#145]
## 질문 작성자

김도현

## 문제 상황

- [134번](https://github.com/yamoo9/likelion-FEQA/issues/134) issue로 storybook에서 link 컴포넌트 테스트 하기 위해서 storybook addon을 설치하여 정상 동작확인하였습니다.
- 애드온 설치 이후 컴포넌트 제작을 위해 swiper 와 mui 설치 시도 중 첨부된 사진과 같은 오류가 계속 발생하였습니다. 
- 일단 설치를 위해 ` --legacy-peer-deps` 를 추가하니 설치하는데에는 성공했습니다.
- npm install을 하면 같은 오류가 계속 발생하였습니다
- 무언가 버전이 맞지 않아서 충돌이 난다고 추측했지만 해결이 어려워서 이슈를 남겼습니다

<img width="918" alt="스크린샷 2023-03-15 01 36 20" src="https://user-images.githubusercontent.com/96248861/225076565-76fd459a-7820-4be9-8be6-5807368c3cbb.png">

## 프로젝트 저장소 URL

- https://github.com/kimzeze/Monstera/tree/develop
- [develop] branch

## 환경 정보

- 운영체제 정보 : MacOS
- Node.js 정보 : 18.12.1

- vite 4.1.0
- storybook 7.0.0.-beta62
- react 18.0.27
- storybook addon 7.0.0-beta.62

**Comment by yamoo9** [comment]
## 문제 상황

종속성 모듈 간 호환성 문제로 패키지 설치가 정상적으로 이뤄지지 않습니다. 😥

## 문제 해결

`.npmrc` 파일을 프로젝트 루트 위치에 추가한 다음 아래와 같이 작성합니다. ([참고](https://davinchicoder.tistory.com/entry/%EC%97%90%EB%9F%AC%EB%85%B8%ED%8A%B8-NPM-install-error-force-legacy-peer-deps-feat-npmrc%EB%A1%9C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0))

<img width="460" alt="" src="https://user-images.githubusercontent.com/1850554/225138942-0b9e023a-4069-461b-bda4-2199537e8ae9.png">



.npmrc 파일 이름은 "NPM Runtime configuration"의 줄임 입니다.

**.npmrc**

```py
legacy-peer-deps=true
```

이 파일을 작성하는 이유 중 하나는 특정 라이브러리가 더 이상 유지보수 되지 않아, 
버전 업그레이드가 안되는 상황인 경우 이 방법을 사용해 설치 오류 없이 성공적으로 설치할 수 있기 때문입니다.

그리고 NPM 설치 명령을 수행하면 정상적으로 모든 패키지가 설치됩니다.

<img width="600" alt="" src="https://user-images.githubusercontent.com/1850554/225139181-5dbe6ef0-870d-4a5f-b63f-6cd0eb7f28e0.png">
