### ISSUE TITLE
[LAB-12] package-lock.json 충돌 시 merge 방식

### ISSUE THREAD

**Issue by senasoon** [yamoo9/likelion-FEQA#146]
## 질문 작성자

박세은

## 문제 상황

저희 팀의 경우 팀 organization에서 각자 fork를 해서 개인 저장소에서 작업 후 organization에서 develop 브랜치의 최신 상태를 받아오고 개인 저장소 develop에 작업 브랜치를 merge 시키고 개인 저장소 develop을 push하여 PR을 날리는 방식을 사용하고 있습니다.

프로젝트 중 스토리북을 재설치하기 위해 작업자가 branch를 새로 생성해 설정 후 develop 브랜치와 merge하는 과정에서 package-lock.json이 충돌했습니다. 이때는 기존에 있던 파일인 organization develop 브랜치의 package-lock.json 파일만 저장하는 것으로 문제를 해결했습니다.

두 번째로 타입스크립트를 프로젝트에 설정하기 위해 작업자가 branch를 새로 생성해 설정 후 develop 브랜치와 merge하는 과정에서 package-lock.json이 충돌했습니다. 이 과정에서 문제를 해결하다가 작업 과정에서 업데이트된 pacakage-lock.json 파일을 discard했고 현재는 다시 npm i를 해 설치를 했습니다.

merge를 하기 전 **package-lock.json이 충돌할 때 보통 merge를 어떤 방식으로 해결**하는지 궁금증이 생겨 질문을 남기게 되었습니다. 

답변 부탁드립니다. 감사합니다!

## 프로젝트 저장소 URL

https://github.com/senasoon/together

브랜치 : `refactor/#30`

## 환경 정보

- macOS
- Node v18.12.1

**Comment by yamoo9** [comment]
## 문제 상황

프로젝트 협업 과정에서 `package-lock.json` 파일로 인한 Git 충돌(conflict) 문제 해결 방법이 궁금합니다.

## 문제 해결

아쉽게도 NPM은 `package-lock.json` 충돌 이슈와 관련한 토론에 대해 확인해보겠다는 답변만 줬습니다.(https://github.com/npm/feedback/discussions/777)

현재 이 문제 해결 방법 중 하나로 패키지 설치 시 `--package-lock-only` 옵션을 설정하는 것입니다.
다른 방법은 [npm-merge-driver](https://github.com/npm/npm-merge-driver)를 설치하는 것입니다.

추후 공식적으로 이 문제가 해결되기를 바랍니다. 😃

## 레퍼런스

- [Solving conflicts in package-lock.json](https://tkdodo.eu/blog/solving-conflicts-in-package-lock-json)
- [Npm 거슬리는 pacakge-lock.json?](https://dschci.tistory.com/108)
- [package-lock.json 충돌 원인과 해결 방법](https://velog.io/@forestin_s2/package-lock.json-%EC%B6%A9%EB%8F%8C-%EC%9B%90%EC%9D%B8%EA%B3%BC-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95)
