### ISSUE TITLE
[LAB-14] 프로젝트 함수 구현중 클로저? 질문

### ISSUE THREAD

**Issue by hamjongseok** [yamoo9/likelion-FEQA#147]
## 질문 작성자

함종석 

## 문제 상황

안녕하세요 

프로젝트를 진행하기위한 함수를 작성하는도중 이해되지않는 현상이 있어서 질문을 남깁니다. 
<img width="657" alt="스크린샷 2023-03-15 오전 11 07 40" src="https://user-images.githubusercontent.com/82271040/225186288-92752977-40c7-486c-b460-a538d9354e3d.png">
<img width="657" alt="스크린샷 2023-03-15 오전 11 08 17" src="https://user-images.githubusercontent.com/82271040/225186407-dccc8db2-7753-41e3-8511-62e913517acb.png">

이렇게 위에가 하나의 함수입니다. 
checkName이라는 함수는 input에서 입력받은 모프리스트를 인자로 넘기고 
JSON 파일에 같은 이름이면 조건으로 들어와서 객체를 배열에 push하고  
alpha 아스키코드를 +1씩해주고 함수입니다.
이때 JSON파일은 morphList.forEach((item) <-  morphList입니다 .

<img width="464" alt="스크린샷 2023-03-15 오전 11 13 21" src="https://user-images.githubusercontent.com/82271040/225187092-581cce34-c79f-4cc6-a592-336e4ff384f5.png">
이런식의 형태로 구성이되어있습니다. 

<img width="464" alt="스크린샷 2023-03-15 오전 11 10 23" src="https://user-images.githubusercontent.com/82271040/225186704-4dd70c03-b992-45eb-950d-95b64a312383.png">
checkName함수를 실행시키는 메인함수부분과 alphaValues입니다. 

제가 질문을 드린것은 리스트 1 [오레오]  리스트2 [카라멜 헷 오레오] 라고 가정할때 
오레오와 카라멜은 열성유전자로 위의 함수에서 첫번째 else if에 들어가게되어 

첫번째 오레오는 소문자 a, +1후에 두번째 카라멜은 소문자 b를 부여받게됩니다. 
이때 +1이 되어서 alpha의 lowercase는 99를 가리키고 있고 
헷 오레오는 당연히 c를 부여받게될줄알았는데. 첫번째 리스트 1에서 오레오에게 a를 부여해준것을 기억하는지 
헷오레오 에게도 a를 부여합니다.   

<img width="665" alt="스크린샷 2023-03-15 오전 11 17 18" src="https://user-images.githubusercontent.com/82271040/225187596-9fc6b132-053a-4c8f-adf2-2919761f206a.png">

콘솔로그로 찍어본결과 
이렇게 알파코드부분을 보시면 헷 오레오에 c가 아닌 a 가 나오며 

<img width="373" alt="스크린샷 2023-03-15 오전 11 17 58" src="https://user-images.githubusercontent.com/82271040/225187680-23745911-d534-4e16-9997-a10b92788d22.png">

lowercase는 c를 가리키고있음에도 오레오에 a를 할당한것을 기억하고 a를 줄수 있는 이유가 너무 궁금합니다.
추측하는거로는 첫번째 모프리스트에 오레오 a를 준것을 기억하는것같은데.. 클로저부분인가 싶기한데 잘모르겠습니다.   

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
@hamjongseok 님 

이미지 말고 함수 코드와 테스트 가능한 데이터를 올려주시면 검토하여 만족할 만한 답변을 드릴께요. 글만으로는 맥락 파악이 쉽지 않네요. 😅

**Comment by hamjongseok** [comment]
파일이 한두가지가 아니라서 저코드만으로는 실행 자체가 불가능해서요 ㅠ 어떻게해야할까요 ?

**Comment by yamoo9** [comment]
> 파일이 한두가지가 아니라서 저코드만으로는 실행 자체가 불가능해서요 ㅠ 어떻게해야할까요 ?

그럼 테스트 가능하도록 프로젝트를 node_modules 빼고 압축해서 올려주시겠어요? 검토해서 답변드리겠습니다.
어떤 문제이든 상황을 직접 봐야 알 수 있으니까요. 😅

**Comment by hamjongseok** [comment]
선생님께 보여주려 코드 정리도중에 문제를 해결하였습니다 !!  감사합니다 !
