### ISSUE TITLE
[LAB-8] styled-reset으로 인한 전역 폰트 스타일 초기화

### ISSUE THREAD

**Issue by rlawlsdn263** [yamoo9/likelion-FEQA#148]
## 질문 작성자

김진우

## 문제 상황

![image](https://user-images.githubusercontent.com/79128016/225192258-7ad741eb-c104-4cc6-b3d1-0ae928488448.png)

![image](https://user-images.githubusercontent.com/79128016/225192168-2f57e860-20da-4ab5-815f-e05168ae34a9.png)

![image](https://user-images.githubusercontent.com/79128016/225192415-1153e5ad-880b-4548-8fd6-d22bc059af01.png)

전역으로 font-family를 설정해주고 싶어 index.html에 CDN으로 폰트를 가져와서 삽입해줬습니다. 이후에 styled-components의 createGlobalStyle을 만들어 안에 font-family를 넣어줬습니다. 하지만 styled-reset으로 인해 font가 inherit으로 되어있어 GlobalStyle.jsx에서는 추가로 설정한 font-family나 다른 설정들이 먹히지 않는 것이 발견됐습니다.

![image](https://user-images.githubusercontent.com/79128016/225192697-0976975c-347e-45ed-bb12-ccb4c057f06e.png)

컴포넌트 내부에서 font-family를 설정해주면 잘 동작하는 게 파악되는데 이렇게 되면 불필요하게 매번 font 스타일을 하나씩 넣어줘야하기 때문에 너무 번거로울 것 같은데 어떻게 하면 될까요?

## 프로젝트 저장소 URL

https://github.com/likelion-frontendo/likelion-saja

## 환경 정보

- Windows 
- Node.js 18.12.1

**Comment by seulbinim** [comment]
안녕하세요 진우님
font-family 선언을 지정할 선택자를 *, &::before, *::after가 아닌
html, body{
    font-family: Pretendard;
}
로 설정하시면 문제가 해결되리라 생각합니다.

**Comment by yamoo9** [comment]
## 문제 해결

문제 원인이 스타일 우선 순위라서, `GlobalStyle.jsx` 파일 코드를 아래와 같이 변경해보세요.

```jsx
import {createGlobalStyle} from "styled-components";
import reset from "styled-reset";

export const GlobalStyle = createGlobalStyle`
  ${reset}
  
  body {
    box-sizing: border-box;
    font-family: "Pretendard Variable", Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, "Helvetica Neue", "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", "Malgun Gothic", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif;
    
    * {
      box-sizing: inherit;
      font-family: inherit;

      &::after, 
      &::before {
        box-sizing: inherit;
        font-family: inherit;
      }
    }
  }
`;
```

그러면 스타일 우선 순위 문제를 해결할 수 있습니다. 😌

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/1850554/225196284-0af45bca-1a25-4f9d-94cb-8b4660059086.png">
