### ISSUE TITLE
[LAB-19] 'git pull' 명령 사용 후에도 특정 파일이 누락 된 채로 업데이트가 되는 문제(오류 메세지 발생 안함)

### ISSUE THREAD

**Issue by djswns7** [yamoo9/likelion-FEQA#149]
## 질문 작성자

박원준

## 문제 상황
지난번 이슈(프로젝트 이전)에 올렸던 상황이 발생해서 상황 설명과 함께 다시 질문드립니다. 
https://github.com/yamoo9/likelion-FEQA/issues/97

현재 팀원 중 소 정님이 공동리포지토리 업데이트 상황을 동기화하기 위해 git pull 을 하는 과정에서  
사진 1
![image](https://user-images.githubusercontent.com/72201211/225225206-6b268493-c6b5-46b7-a668-f535737de144.png)
위 사진과 같이 pull 작업이 정상적으로 이루어졌음에도 불구하고(Conflict도 예상 한 파일이 충돌한거라 문제가 있는건 아니었습니다)  
pull 명령 이후에 예를들어 파일이 A, B, C 가 가져와져야 하는 상황에서 A, B 만 pull이 되었고 누락된 C 에 대해서는 VS코드에 표시된 git log 상에는 별다른 언급이 없었습니다.  
사진 1에서 원래대로 라면 App.jsx 파일이 자동 merge가 되든, conflic이 발생하던 해야 하는데 아무런 변화가 나타나지 않았고,  
App.jsx 파일 외에도 (모든 파일이 아닌) 몇몇 파일( firebase 유틸 함수 관련 파일 )이 누락된 것이 확인되었습니다.

이를 해결하기 위해 브랜치 추적을 초기화해서 (저희 팀은 git branch 전략을 사용하고 있습니다) 개인 깃헙과 공동 깃헙을 각각 추적시켰다 풀었다 하면서 pull을 해보기도 하고,  
공동 저장소에 새 변경사항을 만들고( 새  pr 승인 후) 다시 pull도 해 보았으나 앞선 누락파일은 그대로 가져와지지 않는 문제가 발생하여서 질문드립니다.

현재는 일단 작업을 지체할 수 없어서 문제 발생한 분의 로컬 변경사항을 백업하고 기존 fork해온 저장소 삭제 후 다시 fork-clone 과정 후 작업 중이고 추가로 발생한 문제는 없습니다

## 프로젝트 저장소 URL

- https://github.com/Bob-Lion/React-Web-Market
- develop 브랜치

## 환경 정보

- 운영체제 정보 : 이번 이슈는 Mac에서 발생했으나 지난번 프로젝트에서 같은 현상이 Window에서도 발생하는 걸 확인했습니다

**Comment by seulbinim** [comment]
원준님 
아까 제가 해당 저장소를 포크하고 클론했을 때 소정님과 동일한 상황이 발생했고
다시 저장소를 지우고 멤버로 등록 된 후 다시 포크를하고 클론했을 대는 정상적으로 코드가 반영되었습니다.
이후 서브 아이디 2개로 동일한 작업을 진행해 봤을 때
이미 정상적인 코드가 한번 받아진 후부터는 문제가 발생하지 않았습니다.
처음 콜라브레이터로 등록되지 않은 이슈가 아닐까 생각했는데 그 문제는 아닌 것 같습니다.
일단 야무쌤이 멘토링 끝나신 후 포크 후 클론해 보셨을 때 App.jsx 파일에 동일한 문제가 발생하는지 확인해 보는 것이 필요할 것 같습니다.
지속적으로 해당 문제는 점검을 해보도록 하겠습니다.

감사합니다.
