### ISSUE TITLE
🛎️ 클로저의 실제 사용 예

### ISSUE THREAD

**Issue by shoveller** [yamoo9/likelion-FEQA#15]
[STD2 - 2주차 멘토링 2번째 질문](https://likelion.notion.site/1-f42db4f5dfc143d78632a77f2b10e85a)

저희 팀이 클로저에 대해서 이해는 했는데
현업에서 실제로 사용하시는지
사용하신다면 간단한 예제를 들어서 한번만 설명 부탁드립니다.

**Comment by yamoo9** [comment]
## 안내

재원 멘토님이 답변할 글이 많은 듯 하여 관련 질문에 대신 답변합니다. 😃

## 클로저 실용 예시

클로저를 처음 학습할 때 개념은 이해했어도 어디에 사용해야 할까 고민될 수 있습니다.
실용적인 클로저 사용 목적을 "**메모이제이션**([memoization](https://ko.wikipedia.org/wiki/%EB%A9%94%EB%AA%A8%EC%9D%B4%EC%A0%9C%EC%9D%B4%EC%85%98))"에 염두에 두고 생각해봅시다. 🤔

### 메모이제이션

메모이제이션은 컴퓨터 프로그램이 동일한 계산을 반복해야 할 때, 
이전에 계산한 값을 메모리에 저장함으로써 동일한 계산의 반복 수행을 제거하여 
프로그램 실행 속도를 높이는 방법을 말합니다.

### 피보나치 수

먼저 **계산에 많은 시간과 비용을 사용하는 함수를 작성**합니다.
[피보나치 수(Fibonacci number)](https://news.samsungdisplay.com/23402)를 반환하는 함수가 예로 적당하겠네요.

![](https://user-images.githubusercontent.com/1850554/211128331-5a451e55-2fca-4651-9435-686d323341f3.png)

수학자들은 피보나치 수열을 공식 `F(n+2)` = `F(n+1) + F(n)`으로 만들었습니다. 
즉, `n+2` 번째 항의 피보나치 수는 `n+1` 번째와 `n` 번째 피보나치 수의 합과 같습니다.

위 공식을 JavaScript 함수로 표현하면 아래와 같습니다. (재귀 호출 활용)

```js
function fibonacci(n = 0) {
  return n < 1 ? 0 : n < 3 ? 1 : fibo(n - 2) + fibo(n - 1);
}
```

보다 큰 피보나치 수를 계산하려면 시간 비용이 급격히 늘어납니다.
아래 계산 결과 값과 시간을 확인해보세요. ([console.time](https://developer.mozilla.org/ko/docs/Web/API/console/time) API 활용)

```js
fibonacci(24); // 46368   →   0.676 ms
fibonacci(28); // 317811   →   5.016 ms
```

한 번 계산하는데 이렇게 많인 시간이 필요하다면?
[스레드(thread)](https://ko.wikipedia.org/wiki/%EC%8A%A4%EB%A0%88%EB%93%9C_(%EC%BB%B4%ED%93%A8%ED%8C%85))가 하나인 JavaScript 월드에서는 계산이 완료될 때까지 어떤 일도 진행이 안됩니다.

프로그램 처리를 기다리는 시간이 길어질 수록 사용자는 초조하고 답답해질 것입니다. 😥
이런 경우에 **메모이제이션을 사용하면 프로그램 실행 속도를 높일 수 있습니다.**

### 클로저를 활용한 메모이제이션 함수

자! 이제 **클로저를 활용해 메모이제이션을 구현한 함수**를 작성합니다.
memo 함수는 내부에 외부에서 접근 불가능한 캐시(cache) 객체를 포함합니다. ([IIFE](https://developer.mozilla.org/ko/docs/Glossary/IIFE) 활용)
그리고 클로저 함수 _memoized를 반환합니다.

```js
const memo = (() => {
  const _cache = {};
  
  const _memoized = (key, value) => {
    if (!key) {
      throw new SyntaxError(`key 입력이 필요합니다.`);
    }
    if (value) {
      _memoized.showLog && console.log('value 값을 메모(memo)합니다.');
      _cache[key] = value;
    }

    _memoized.showLog && console.log('메모(memo)된 value 값을 반환합니다.');
    return _cache[key];
  }

  _memoized.showLog = false;

  return _memoized;
              
})();
```

### 메모이제이션을 사용할 경우 처리 속도

작성한 memo 함수를 사용해 
계산 시간이 많이 필요한 프로그램 처리 속도를 
얼마나 개선할 수 있는 지 확인해봅시다. 😃

1. 먼저 메모이제이션 로그를 활성화 합니다.
2. 메모할 키, 값을 입력해 `memo()` 함수를 실행합니다.
3. 메모된 키만 입력해 `memo()` 함수를 다시 실행합니다.

```js
// [1]
memo.showLog = true;

// [2]
console.time();
memo('피보나치 30', fibonacci(30));  // 계산 시간 : 13.319 ms
console.timeEnd(); 

// [3]
console.time();
memo('피보나치 30');  // 계산 시간 : 0.083 ms
console.timeEnd();
```

**계산에 소요된 시간 결과 값을 보니 반복되는 동일 계산 처리 속도가 
엄청나게 향상(약 13초 → 약 0.08초)된 것을 볼 수 있습니다.** 😆

## 사용자 인터페이스(UI) 설계에서의 클로저 활용

아래 코드 예시는 [#11 답변 2](https://github.com/yamoo9/likelion-FEQA/issues/11#issuecomment-1372349074)에서 다룬 코드입니다.

아래 작성한 함수는 문서 요소 객체에 이벤트를 연결하는 것을 도와주는 addEvent 함수입니다.
내부에 클로저를 사용한 점을 눈여겨 봐주세요.

```js
const addEvent = (element, type, handler) => {
  element.addEventListener(type, handler);
  return function removeEvent() {
    element.removeEventListener(type, handler);
  };
};
```

아래는 addEvent 함수를 사용해 문서 요소에 이벤트를 연결하는 코드 예시입니다.

```js
const saveButton = document.querySelector('.saveButton');
addEvent(saveButton, 'click', (e) => { console.log('.saveButton 요소 클릭'); });
```

아마도 굳이 addEvent 함수를 만들어 저렇게 이벤트를 연결해야 할까 싶을 수 있습니다.
아래처럼 바로 연결해도 문제없이 작동하니까요.

```js
document.querySelector('.saveButton')
  .addEventListener('click', (e) => { console.log('.saveButton 요소 클릭'); });
```

하지만 위 코드는 연결된 이벤트를 제거할 수 없습니다.
**동일한 이벤트 핸들링 참조가 있어야 제거가 가능하기 때문이죠.**

그러므로 이코드는 다음과 같이 변경해야 제거가 가능합니다.

```js
const saveButton = document.querySelector('.saveButton');
const handleClick = (e) => { console.log('.saveButton 요소 클릭'); };
saveButton.addEventListener('click', handleClick);

setTimeout(() => {
  saveButton.removeEventListener('click', handleClick);
}, 4000);
```

그렇다면 addEvent 함수를 사용하면 어떻게 될까요?
별도로 이벤트 핸들러를 참조하는 변수를 작성하지 않아도 됩니다.
**addEvent 함수가 반환하는 클로저 함수 removeEvent를 변수에 참조했다가
필요한 시점에 실행하면 연결된 이벤트가 제거될테니까요. 😃**

```js
const saveButton = document.querySelector('.saveButton');
const removeEvent = addEvent(saveButton, 'click', (e) => { console.log('.saveButton 요소 클릭'); });

setTimeout(removeEvent, 4000);
```

또는 아래와 같이 **이벤트 위임 유틸리티 함수를 작성하는데 클로저를 활용할 수도 있습니다. 🤨**

```js
function on(type, selector, handler) {
  const isMatch = (target) => target.matches(selector) || target.closest(selector);
  const listener = (e) => { if ( isMatch(e.target) ) { handler(e); } };
  document.body.addEventListener(type, listener);
  return () => document.body.removeEventListener(type, listener);
}

const off = on('click', '.app', (e) => { console.log('.app 요소 클릭') }); 

setTimeout(off, 4000);
```
