### ISSUE TITLE
[LAB-11] git pull할때 발생되는 how to reconcile divergent branches에 관한 오류

### ISSUE THREAD

**Issue by seovee** [yamoo9/likelion-FEQA#150]
## 질문 작성자

김진섭

## 문제 상황

상황은 git-flow방식으로 VSC에서 pull로 가져와 충돌을 해결 후 merge진행중이었습니다.

1. VSC에서 충돌 해결을 위해 **최신화된 develop**을 **개인feature브랜치**로 pull 사용 시 아래처럼 오류가 발생합니다.
<img width="675" alt="스크린샷 2023-03-15 오전 10 49 53" src="https://user-images.githubusercontent.com/18073169/225235599-d47a4c9a-0dd7-498f-8e18-6e9cc5563f14.png">

2. Hint 해결방법 3가지도 실행해 보았지만, 아래와 같은 문구만 나타납니다.
![오류2](https://user-images.githubusercontent.com/18073169/225236269-0b02bd05-977e-4566-9622-6fd7516bfb76.png)

구성원중 2명은 문제 없이 Pull이 잘되고, 3명은 같은 증상이 나타납니다. 
그래서 3명은 github로 충돌해결 했지만, VSC에서도 사용하고 싶어 질문드립니다.

## 프로젝트 저장소 URL

- https://github.com/likeLion-FE4-RP11/Asparagus.git
- 각 feature브랜치 -> develop
- merge할때 생기는 문제라 파일이 현재는 따로 없습니다

## 환경 정보

- macOS
- Node.js v19.7.0.
- React v18.0.2 / vite v4.1.0

**Comment by seulbinim** [comment]
안녕하세요 진섭님 
해당 이슈는 힌트를 보시면 git pull을 실행하는 세가지 방법 중 하나를 선택하라고 나와 있습니다.
기본 값이 fastforward 인 상황이므로 merge나 rebase 중 하나를 지정해서 자동 병합을 시도하고
자동 병합이 안 될 경우 충돌 상황을 만들 수 있습니다. 
이때 merge 방식을 사용하려면 git config pull.rebase false를 입력해서 해결할 수 있습니다.

진희님의 경우 여러 명령어를 입력하면서 테스트 해보시는 와중에 git config pull.ff only 옵션이 적용되어서
자동 병합이 되지 않았던 이슈입니다.
해당 사항은 config 파일에 pull 관련 명령을 --unset 명령을 통해 삭제한 후 다시 등록해서 해결해 드렸습니다.

정리 
Merge 방식
git config pull.rebase false

Rebase 방식
git config pull.rebase true

FastForward 방식(기본 값)
git config pull.ff only

---------------------------
git config 파일에 등록 된 pull 방식을 삭제하고자 할 경우
git config --unset pull.ff only

**Comment by seovee** [comment]
감사합니다😃
