### ISSUE TITLE
[LAB-16] dialog 태그를 이용한 모달 다이얼로그 컴포넌트 구현

### ISSUE THREAD

**Issue by no-support** [yamoo9/likelion-FEQA#151]
## 질문 작성자

노지원

## 문제 상황

안녕하세요 야무쌤님, 지난 번 피드백 때 z-index를 사용하지 않는 방식으로 모달을 구현하는 것을 본 적이 있다고 했는데요. 제가 그 때 참고 사이트를 잘못 공유드린 것 같습니다. 제가 그 때 봤던 영상은 아래 사이트들입니다.

https://www.youtube.com/watch?v=cNfpkKUYAyo
https://www.youtube.com/watch?v=RO40Opyizeg
https://www.youtube.com/watch?v=TAB_v6yBXIE&t=3s

그래서 혹시 리액트에서도 이런 방법으로 모달을 구현할 수 있을까 해서 시도 중입니다.

문제는 프로젝트 기본 환경 설정 후 바로 App.js에서 아래와 같이 코딩 후 구동하면 문제 없이 진행되는데요,

```
import "./styles.css";
import { useEffect, useRef } from "react";

export default function App() {
  const buttonRef = useRef();
  const dialogRef = useRef();

  useEffect(() => {}, []);

  return (
    <div className="App">
      <button
        onClick={(e) => {
          dialogRef.current.showModal();
        }}
        ref={buttonRef}
      >
        show modal
      </button>
      <dialog
        ref={dialogRef}
        onClose={() => {
          console.log(dialogRef.current.returnValue);
        }}
      >
        hello! I'm a modal!
        <form method="dialog">
          <button value="close">close</button>
          <button value="confirm">confirm</button>
        </form>
      </dialog>
    </div>
  );
}
```

또 다른 방식으로 아래와 같이 state를 상태에 따라 모달창이 여닫히는 방식으로 짜봤더니, 모달창이 이미 열린 상태로 페이지가 로딩되며, 한두 번 닫힌 후에는 다시 열리지 않는 문제가 발생하고 있습니다.
```
import "./App.css";
import { useEffect, useRef, useState } from "react";

export default function App() {
  const [state, setState] = useState(false);
  const dialogRef = useRef();

  const handleClick = (e) => {
    console.log("handleClick execute...");
    setState((prev) => true);
  };
  useEffect(() => {
    console.log("useEffect execute...");
    if (state) {
      console.log("dialogRef.current.showModal");
      dialogRef.current.showModal();
    }
    return () => {
      console.log("dialogRef.current.close");
      dialogRef.current.close();
    };
  }, [state]);
  return (
    <div className="App">
      <button onClick={handleClick}>show modal</button>

      <dialog ref={dialogRef}>
        <form method="dialog">
          <button value="close">close</button>
          <button value="confirm">confirm</button>
        </form>
      </dialog>
    </div>
  );
}
```

정리하면 portal 기법(?)을 사용하지 않고 dialog를 이용한 모달 구현이 가능할지 여부와, 두 번째 코드에서 발생하는 문제들의 원인에 대해 알고 싶습니다..!

## 코드 검토 리소스
첫 번째 코드 실행 환경 링크입니다.
https://codesandbox.io/s/react-dialog-ref-55kfnm?file=/src/App.js
두 번째 코드 실행 환경 링크입니다.
https://codesandbox.io/s/react-dialog-state-8vrke5?file=/src/App.js

**Comment by no-support** [comment]
추가로 저 방식이 아닌 portal 방식이 더 정석적(?)인 방법일지, 저 방식이 처음엔 쉬워보이지만 예를 들면 모달 내 컴포넌트가 복잡해지면 나중에 더 어려운 구현방식일지 이런 것도 궁금합니다..!

**Comment by yamoo9** [comment]
## 답변 1.

React의 [Portals](https://beta.reactjs.org/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal) 기술이 아니어도, HTML [`<dialog>`](https://developer.mozilla.org/ko/docs/Web/HTML/Element/dialog) 요소를 사용해 모달 다이얼로그를 구현할 수 있습니다.
`<dialog>` 요소는 화면에 표시된 순간 DOM의 '최상위 레이어'에 추가되므로 `z-index`에 영향을 받지 않는 것을 확인되었습니다.
그러므로 `<dialog>` 요소를 사용해 구현해도 무방해보입니다. 😃 

## 답변 2.

2번째 코드를 Fork 하여 React 방식으로 제어할 수 있도록 구성해봤습니다. 아래 링크를 참고해보세요.

[React + HTML `<dialog>` 요소 제어](https://codesandbox.io/s/react-dialog-state-forked-czzp8b?file=/src/App.js)

<br/>

<img width="560" src="https://user-images.githubusercontent.com/1850554/225261411-2a1cf99b-ddd8-4d83-93f1-d0f0be6238e0.gif" alt />
