### ISSUE TITLE
[LAB-5] React 반응형에서 글자크기 줄이는 법

### ISSUE THREAD

**Issue by seoohyeon** [yamoo9/likelion-FEQA#152]
## 질문 작성자

김서현

## 문제 상황
![image](https://user-images.githubusercontent.com/38703262/225314639-90086980-0fdc-426f-b4d9-3b0f5af35fee.png)
![image](https://user-images.githubusercontent.com/38703262/225315279-1bad204e-9fdc-4409-97ae-58783bb1a29b.png)

반응형으로 프로젝트 진행중에, 버튼 안 글자크기가 줄어들지 않아 질문을 남깁니다.
해당 캡처본처럼 clamp나 rem, em 다 써보았으나 뷰크기를 조절한다고 해서 글자크기가 반응형처럼 줄어들지는 않았습니다.
조언 부탁드립니다.

## 프로젝트 저장소 URL
https://github.com/React-Project-lab5/React-Project-lab5  
- develop브랜치  
- 현재 파일 위치 : 
![image](https://user-images.githubusercontent.com/38703262/225315605-5214e965-ac2f-4c45-86a3-051db93e10e0.png)

## 환경 정보
Windows
- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by seulbinim** [comment]
안녕하세요 서현님
버튼의 크기에 따라 글자크기가 조정되기를 원하신다면 clamp() 함수를 사용하시면 됩니다.
clamp() 함수의 경우 최소값, 기준값, 최대값을 지정할 수 있어 유연한 타이포 그래피  설정이 가능합니다.
아래 링크에서 사용방법을 살펴보시기 바랍니다.
https://web.dev/i18n/ko/min-max-clamp/

알려드렸던 clamp()함수를 사용했는데 제대로 동작하지 않는다고 피드백을 주셔서
코드펜에 코드 예시를 만들어봤으니  살펴보시기 바랍니다. 
https://codepen.io/seulbinim/pen/YzOLZVJ

-----
LAB5 팀 방문해서 문제 해결해 드렸습니다. (min-width 속성 활용)
