### ISSUE TITLE
[LAB-13] 새로고침시 초기값으로 초기화 되는 이슈

### ISSUE THREAD

**Issue by chaewon0128** [yamoo9/likelion-FEQA#153]
## 질문 작성자

함채원

## 문제 상황

![Mar-15-2023 23-41-39](https://user-images.githubusercontent.com/119389600/225345935-f09691c6-83d9-4436-8e75-732d859456aa.gif)

안녕하세요.
firebase의 firestore database 에 있는 데이터 정보를 가져오는 중 오류가 발생하여 문의 드립니다..
야무쌤이 올려주신 useReadData와 useEffect 훅을 사용해서 데이터 값을 받아오는 것은 성공하였는데,

새로고침시 데이터 값이 초기값인 null 로 초기화 됩니다..

조언 부탁드립니다.

## 프로젝트 저장소 URL
- [깃헙저장소](https://github.com/chaewon0128/LAB13-PROJECT/blob/feature/chaewon/renderpage-main-slide/src/components/RenderMainSlide/RenderMainSlide.jsx)

- 브랜치명 :  feature/chaewon/renderpage-main-slide

## 환경 정보

- 운영체제 정보 ( macOS)

**Comment by yamoo9** [comment]
## ⚠️ utils 디렉토리가 없습니다.

프로젝트 저장소 자료를 내려받아 테스트 하려 했으나, 다음과 같은 오류가 표시됩니다. 😥

<img width="918" alt="" src="https://user-images.githubusercontent.com/1850554/225441690-5f9fd4fd-4dab-4ac2-99e2-cdf9d8a6d788.png">

문제 원인은 utils 디렉토리가 저장소에 없기 때문이에요. utils 저장소에 데이터를 올린 후 다시 질문 남겨주세요. 🙂
문제 상황을 테스트 하려면? 먼저 문제 상황이 재현되어야 합니다.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/1850554/225442047-051627b8-0b8a-43dc-ae17-43b962d88654.png">

**Comment by chaewon0128** [comment]
방금 해당 부분 push 하였습니다! 다시 확인 부탁드립니다.

**Comment by yamoo9** [comment]
## 문제 현상에 대한 이해

@chaewon0128 님

새로고침 시, 초기화 되는 건 자연스러운 현상입니다. 
클라이언트(웹 브라우저) 환경에 데이터를 보존하려면 로컬 스토리지를 사용해야 합니다.
아래는 로컬 스토리지를 사용해 사용자 웹 브라우저에 데이터를 보존한 경우를 보여줍니다.

![1](https://user-images.githubusercontent.com/1850554/225482899-159b7826-0c47-441e-b34d-19da70a476c9.gif)

여러분 팀은 Recoil을 사용한다고 이야기 되었지만, 아직 설정 전인듯 하군요.
아래 코드는 Recoil을 사용해 로컬 스토리지에 상태를 보존한 예시 코드입니다.

```jsx
import { useLayoutEffect } from 'react';
import { atom, useRecoilState } from 'recoil';
import useReadData from '../../utils/firebase/firestore/useReadData';

const localStorageEffect = key => {
  return ({ setSelf, onSet }) => {
    const savedValue = localStorage.getItem(key);

    if (savedValue !== null) {
      setSelf(JSON.parse(savedValue));
    }

    onSet((newValue, _, isReset) => {
      isReset
        ? localStorage.removeItem(key)
        : localStorage.setItem(key, JSON.stringify(newValue));
    });
  };
};

const imageState = atom({
  key: 'imageState',
  default: null,
  effects: [localStorageEffect('imageState')],
});

export default function RenderMainSlide() {
  const [images, setImages] = useRecoilState(imageState);
  const { readData, data } = useReadData('image');

  useLayoutEffect(() => {
    (async () => {
      if (!data && !images) {
        await readData();
        setImages(data);
      }
    })();
  }, [data, images, readData, setImages]);

  console.log(images);

  return (
    <div className="mainSlide">
      <h2>Main Slide Guide</h2>
    </div>
  );
}
```

## Recoil Persist 라이브러리

Atom Effects 대신, [recoil-persist](https://www.npmjs.com/package/recoil-persist) 라이브러리를 활용해도 좋습니다. 😃

## 가이드 파일

가이드 코드는 아래 ZIP 파일을 다운로드 받아 분석해보세요.

[LAB13-PROJECT-feature-chaewon-renderpage-main-slide-confirm-by-yamoo9.zip](https://github.com/yamoo9/likelion-FEQA/files/10985706/LAB13-PROJECT-feature-chaewon-renderpage-main-slide-confirm-by-yamoo9.zip)
