### ISSUE TITLE
[LAB-7] 페이지 콘텐츠에 따른 화면 밀림 현상(스크롤바 표시 유무)

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#154]
## 질문 작성자

김하연

## 문제 상황
스크롤바가 생기면 헤더 부분이 왼쪽으로 밀리는 현상이 발생합니다.
- 메인 페이지
<img width="1416" alt="스크린샷 2023-03-16 오전 12 06 53" src="https://user-images.githubusercontent.com/111109573/225352462-01b31b12-a099-4b46-9bd4-d0c65d0156b7.png">

- 로그인 페이지
<img width="1418" alt="스크린샷 2023-03-16 오전 12 07 13" src="https://user-images.githubusercontent.com/111109573/225352574-6d58c925-0a92-4032-bb8e-26fad7829180.png">

https://mainichibenkyo.tistory.com/410
정보를 찾아보니 브라우저 상의 문제라고 적혀있습니다.. 
레이아웃을 동일하게 만들기 위해서 임의로 세로 스크롤을 만드는 방법을 알았습니다.
이런식으로 하면 사용자에게 혼란을 불러올 수 있다고 생각했는데  임의로 세로 스크롤을 줘도 되나요?

```
body {
  overflow-y: scroll;
} 
```

다른 사이트들을 찾아봤을 때 로그인, 회원가입 부분을 저런 방식으로 처리한 곳이 몇가지 있어서..
이런 방식으로 레이아웃을 동일하게 가져가도 되는지 궁금합니다. 
예시 : https://lukt.co.kr/login?back_url=Lw%3D%3D&used_login_btn=Y

## 프로젝트 저장소 URL
https://github.com/Likelion-lucky7/DECO/tree/test

test 브랜치에 있습니다!

**Comment by yamoo9** [comment]
## 더 나은 사용자 경험(UX)

@hayeonn2 님이 질문주신 방법은 저도 사용하는 방법입니다. 😊 
사용자 인터페이스(UI) Y축이 페이지 전환에 따라 흔들리면? 사용자 경험(UX)에 좋지 않죠!

**흔들리는 애플리케이션 인터페이스 Y 축**

![](https://user-images.githubusercontent.com/1850554/225436737-1605a48d-6fae-4ed9-b8a2-4793b6cdf848.gif)

**흔들리지 않는 애플리케이션 인터페이스 Y 축**

![](https://user-images.githubusercontent.com/1850554/225436933-d5734907-58e2-4e0f-b080-f6953e5542e9.gif)

<br/>

그런 이유로 [특정 메뉴에서 전체 화면이 왼쪽/오른쪽으로 밀리는 이유](https://mainichibenkyo.tistory.com/410) 글에서 말하는 의견에 저는 동의하지 않습니다.

> "스크롤 바를 무조건 생기게 하면 스크롤이 안되는데도 스크롤 바가 있어 사용자의 혼란을 초래 하므로 잘못된 생각이다."

<br/>

<img width="340" alt="" src="https://user-images.githubusercontent.com/1850554/225439098-e6ea9716-be72-445a-8d4b-cb778ba5607f.png" align="right" />

스크롤 바 트랙(track)이 화면에 항상 표시 되더라도, 썸브(thumb)가 표시 되지 않으니 사용자가 혼란스러워 할 일도 없고, 오히려 Y축이 흔들리지 않아 더 나은 사용자 경험을 제시한다고 생각합니다. 😃

<br/>
