### ISSUE TITLE
[LAB-8] tabIndex 표시가 안보입니다

### ISSUE THREAD

**Issue by zerocalorie1226** [yamoo9/likelion-FEQA#157]
## 질문 작성자

조성찬

## 문제 상황

- 버튼을 제외하고 Link로 된 요소들이 tab은 인식이 되는데 테두리가 안보입니다 
![image](https://user-images.githubusercontent.com/65861663/225525870-2012d773-319f-4f64-a4fa-9fa64e200a4a.png)

## 프로젝트 저장소 URL

- https://github.com/zerocalorie1226/likelion-saja
- feature/soungchan/home 브랜치로 봐주세욤

## 환경 정보

- Windows

**Comment by seulbinim** [comment]
초점이 안보이는 경우 개발자 도구에서 CSS 관련 속성 outline 속성에 0 또는 none 등의 값이 있는지 먼저 확인해 보시기를 권해 드립니다.

**Comment by zerocalorie1226** [comment]
해결됐습니다!! 감사합니다!!!!!💜
