### ISSUE TITLE
[LAB-9] fileReader 사용중인데 이미지배열을 어떻게 렌더링해야할지 모르겠어요.

### ISSUE THREAD

**Issue by qorbaxk** [yamoo9/likelion-FEQA#158]
## 질문 작성자

백승연

## 문제 상황

- 파일리더를 이용하여 사진을 첨부시 여러장의 사진을 미리보기로 보여주는 작업을 진행하고 있습니다.
- 첨부한 이미지들의 스트링데이터를 배열에 넣어, 배열을 순회하며 값을 렌더링하고 싶습니다.
- 하지만 배열에 데이터가 들어가는 것은 확인이 되나, 보여지지는 않고있습니다. 
- 어디서 코드를 잘못 짠건지 알고싶어요.
- 
![스크린샷 2023-03-16 162422](https://user-images.githubusercontent.com/97217443/225543857-e3771755-26fb-4615-9bea-3667a8635f5b.png)
![스크린샷 2023-03-16 162428](https://user-images.githubusercontent.com/97217443/225543864-35d0365a-2c71-4e13-88a2-ed4f5fefc4bb.png)
![image](https://user-images.githubusercontent.com/97217443/225543976-0f8c4fec-48c4-4d8a-87d4-aa1447ad4ceb.png)

## 프로젝트 저장소 URL

- [공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.](https://github.com/qorbaxk/withPet-client/tree/feature/diary)
- feature/diary 브랜치 입니다.

## 환경 정보

-Windows
- Node.js v18.12.1
- react: 18.2.0

**Comment by qorbaxk** [comment]
어.. 제가 코드를 잘못짰더라고요.. 해결하였습니다.. ! 죄송합니다!

**Comment by yamoo9** [comment]
> 어.. 제가 코드를 잘못짰더라고요.. 해결하였습니다.. ! 죄송합니다!

<img align="right" src="https://user-images.githubusercontent.com/1850554/225562987-315f45f2-741c-4ce1-87c5-2d626a74fdf6.gif" height="200"/>

@qorbaxk님 스스로 해결 하셨다니 멋져요! 😃 
방금 해결된 코드를 글로 작성 중 이었지만 삭제합니다.

오른쪽 화면은 제가 작성했던 코드로 구현된 파일 업로드 미리보기 입니다.

<details>
  <summary>onFileChange</summary>

  ```tsx
  const onFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { files } = e.target
    const filesLength = files?.length ?? 0
  
    if (filesLength === 0) return
  
    if (images.length + filesLength > MAX_UPLOAD_FILES_COUNT) {
      return alert('최대 4개 사진만 첨부할 수 있습니다.')
    }
  
    if (files) {
      Array.from(files).forEach(file => {
        if (/\.(jpe?g|png|gif)$/i.test(file.name)) {
          const reader = new FileReader()
          reader.onload = e => {
            const { result } = e.target as FileReader
            setImages(prev => [...prev, result as string])
          }
          reader.readAsDataURL(file)
        }
      })
    }
  }
  ```
</details>

**Comment by qorbaxk** [comment]
코드가 훨씬 깔끔하고 좋은 것 같습니다. 참고해보도록 할게요! 감사합니다!!
