### ISSUE TITLE
[LAB-8] React Swiper 관련 질문

### ISSUE THREAD

**Issue by rodwnl** [yamoo9/likelion-FEQA#159]
## 질문 작성자

이경주

## 문제 상황

현재 메인 배너를 기본 스와이프에서 자동넘김(Autoplay)만 추가해서 구현하려는 상황입니다. 
Swiper 공식 홈페이지에 react 가이드와 똑같이 따라했는데 배너 네개가 하나씩 나오는 것이 아닌 배너 네개가 한 세트로 넘겨지고 있습니다. 혹시 놓친 곳이 있다면 알려주세요...!!

참고한 스와이프가 제공하는 기본 코드
https://codesandbox.io/p/sandbox/6cbhtd?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A27%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A27%7D%5D
![image](https://user-images.githubusercontent.com/88178123/225629006-d0312944-f1c7-426d-9c2c-e4bf71c5851d.png)

배너 스와이프에 작성한 코드
![image](https://user-images.githubusercontent.com/88178123/225629154-b834d0ed-ce9e-45c1-a2e2-ec7d0a33689a.png)
![image](https://user-images.githubusercontent.com/88178123/225629305-2d9181b8-350c-4fc4-893c-bbb3cf80893d.png)

현재상황
![image](https://user-images.githubusercontent.com/88178123/225629525-fc039fa1-3499-4807-85b1-9cf30bf68c48.png)

## 프로젝트 저장소 URL
https://github.com/rodwnl/SAJA-Market/tree/feature/kyoungju/home

\src\pages\Home\MainBanner.jsx 에 코드 작성되어 있습니다

## 환경 정보

- 운영체제 : Windows

**Comment by yamoo9** [comment]
## 문제 상황 이해

@rodwnl 님이 참고한 Swiper 기본 코드는 `swiper/css` 스타일 코드를 불러옵니다.
이 스타일 코드를 불러오지 않으면 슬라이드 콘텐츠가 정상적으로 슬라이드 되지 않습니다.

<img width="1527" alt="" src="https://user-images.githubusercontent.com/1850554/225754142-29027a02-42a1-4d9e-9e44-3f9f57aa4d94.png">

반면 @rodwnl 님이 작성한 Swiper 코드는 `swiper/css` 스타일 코드를 불러오지 않았습니다.
그런 이유로 배너 4개가 한 세트가 되는 경험을 한 것으로 보입니다. 😅

<img width="1266" alt="" src="https://user-images.githubusercontent.com/1850554/225754457-0998dc0c-a2df-4d52-95cd-81ac265f29a2.png">

확인해봐주세요. 😃

**Comment by rodwnl** [comment]
해결했습니다 감사합니다!!😍
