### ISSUE TITLE
[LAB-3] 데이터들을 어떻게 관리해야 할 지 그림이 그려지지 않습니다

### ISSUE THREAD

**Issue by hardy-is-cat** [yamoo9/likelion-FEQA#160]
## 질문 작성자

조정현

## 문제 상황

- 현재 저희 프로젝트에 필요한 데이터는 크게 주차장 정보, 고객의 리뷰, 고객의 즐겨찾기 정보 이 세가지입니다.

- 주차장 정보는 api를 이용해서 받아오기로 했고, 인증키가 유효하지 않다던 문제는
'관련부처에서 인증키가 자동으로 발급은 되었으나 해당 인증키가 동작하기 위해 관리자의 승인이 따로 있어야 한다'
는 답변을 받아 승인 요청 문의를 따로 넣어놓았습니다. 처리에 2,3일 정도가 걸린다고 합니다ㅠㅠ

- 다음으로 필요한 리뷰 데이터는
아래 사진과 같이 마이페이지, 주차장의 상세페이지에 노출되어야 하는데,
이 리뷰 데이터를 어떻게 관리해야할지 감이 잡히지 않는 상태입니다.
리뷰만 따로 모여있는 json 파일을 만들어야 할 지, 회원 데이터베이스에 넣어야 할 지,
이걸 다시 마이페이지와 주차장 상세페이지에서는 어떻게 불러와야 할 지 감이 잡히지 않습니다...
<div style="display:flex;">
<img width="294" src="https://user-images.githubusercontent.com/76080643/225789029-c093639c-d51f-4ec3-beae-f51b0684f31a.png">
<img width="294" src="https://user-images.githubusercontent.com/76080643/225789154-19a4e623-4ba7-4fc0-83c3-91d127864865.png">
</div>

- 위와 같이 고객의 즐겨찾기 목록 또한 필요한데,
즐겨찾기는 마이페이지의 즐겨찾기 탭에서 확인이 가능해야 하고,
주차장의 상세페이지에서도 제목(주차장명) 옆에서 확인이 가능해야 합니다.

이 모든 데이터를 어떻게 관리하고, 어떻게 필요한 곳에 적용해야 할 지 그림이 그려지지 않는 상태인데,
11시에 멘토링이 예정되어 있어서 미리 정리하여 질문 남겨봅니다. 조언 부탁드립니다.

**Comment by yamoo9** [comment]
## 문제 검토

@hardy-is-cat 님 🙂 
오늘 팀 멘토링이 종료된 후, 답변을 정리해 작성하겠습니다.

**Comment by yamoo9** [comment]
## 프로젝트에서 관리가 필요한 정보

프로젝트에서 다음의 정보를 관리해야 합니다.

- 주차장 정보
- 고객의 리뷰
- 고객의 즐겨찾기 정보

### 주차장 정보

사용 가능한 API 키 발급 후, 데이터 요청/응답 결과를 확인해보세요. 😌

### 고객의 리뷰

로그인 된 고객의 마이 페이지, 주차장 상세 페이지에서 동일한 리뷰가 사용됩니다.
그러니까 리뷰 데이터는 마이 페이지, 주차장 상세 페이지와 상관없이 하나여야 합니다.
다만 리뷰 데이터는 리뷰를 남긴 작성자의 고유 식별자(uid) 값을 보관해야 합니다.

```js
reviews: [
  { 
    id: 'Dsdkvjdijwdjwis',
    displayName: '조정현',
    review: '주차 면이 넓어서 좋아요 ...',
    like: 0,
  },
  { 
    id: 'Rdijwdjwsdkvjis',
    displayName: '박현우',
    review: '주차 면이 좁아요 ...',
    like: 2,
  },
  { 
    id: 'Dsdkvjdijwdjwis',
    displayName: '조정현',
    review: '주차 면이 좁지만 나쁘지 않아요. ...',
    like: 5,
  },
  // ...
]
```

#### 마이 페이지 리뷰

데이터베이스의 reviews에서 로그인 된 사용자 고유 식별자(uid)와 일치하는 `id`를 가진 리뷰만 필터링 한 후, 화면에 렌더링 해야 합니다. 예를 들어 `uid` 값이 `Dsdkvjdijwdjwis`인 데이터만 필터링해 가져온 응답 결과입니다.

```jsx
reviews: [
  { 
    id: 'Dsdkvjdijwdjwis',
    displayName: '조정현',
    review: '주차 면이 넓어서 좋아요 ...',
    like: 0,
  },
  { 
    id: 'Dsdkvjdijwdjwis',
    displayName: '조정현',
    review: '주차 면이 좁지만 나쁘지 않아요. ...',
    like: 5,
  },
]
```

아래 예시는 로그인 한 사용자 정보입니다.

```js
{
  uid: 'Dsdkvjdijwdjwis',
  displayName: '조정현',
  // ...
}
```

#### 주차장 상세 페이지 리뷰

주차장 상세 페이지의 리뷰가 로그인 된 사용자가 작성한 것만 보여야 한다면? 
위에서 기술한 방법으로 uid 값과 일치하는 데이터만 요청/응답 받아 화면에 출력합니다.

반면 서비스를 이용하는 모든 사용자의 리뷰를 표시하는 것이라면? 
데이터베이스에 reviews 중 일부(예: 10개)만 요청/응답 받아 화면에 출력합니다. 

### 고객의 즐겨찾기 정보

로그인 한 고객의 즐겨찾기 정보는 아래처럼 데이터베이스에 저장된 고객의 즐겨찾는 주차장 ID만 배열로 관리합니다.

```js
{
  uid: 'Dsdkvjdijwdjwis',
  displayName: '조정현',
  favoriteParkingLotId: [
    'Uicklsjkjvijwdkjfk',
    'Aikijwdjvjkjfkckls',
    'Jjikivjkjwdcklfsjk',
  ],
  // ...
}
```

그리고 데이터베이스에는 주차장 정보도 저장되어 있어야 합니다. 아래처럼 말이죠.

```js
parkingLots: [
  {
    id: 'Aikijwdjvjkjfkckls',
    name: '마포 공영 주차장',
    tags: ['공영', '전기차 충전소', '화장실'],
    address: '서울 서대문구 충정로 60 10층',
    // ...
  },
  // ...
]
```

그러면 로그인 한 사용자 정보에서 즐겨찾기 한 주차장 ID와 주차장 ID가 일치할 경우 
즐겨찾기 아이콘 인디케이터가 활성 표시가 되도록 설정합니다.

## 정리

간단하게 질문에 답변해본 데이터베이스의 구조입니다. 잘 이해 되었을까요? 
확인해보시고, 이해 여부에 대해 피드백 주시면 더 쉽게 설명드릴 수 있을지 노력해보겠습니다. 🤔
