### ISSUE TITLE
[LAB-4] Dependency array에 따른 useEffect의 실행흐름이 궁금합니다.

### ISSUE THREAD

**Issue by PracticeKJY** [yamoo9/likelion-FEQA#162]
## 질문 작성자

김종엽

## 문제 상황
(질문의 관심사가 프로젝트 진행이 아닌 react의 이해인 것 같아 React Q/A로 올렸습니다.)

안녕하세요! 리액트 파이널 프로젝트 4조에 속해있는 김종엽이라고 합니다.
멘토링에서 진행됬던 질문이였는데, 추가적인 이해가 필요하여 이슈에 올립니다..

<b>상황1. 첫 렌더링 시점</b>
![image](https://user-images.githubusercontent.com/119389577/225829680-7f75dd5a-5d4e-478d-8fb3-49a54f26bcb9.png)

![image](https://user-images.githubusercontent.com/119389577/225829544-b69447f9-de55-4d07-9b31-6b4d0eeef082.png)

첫 렌더링 시점엔, 1,2의 흐름으로 콘솔창에 찍힌 것을 이해 할 수 있었습니다.
<br>

<b> 상황2. 리 랜더링 됬을 때   (Case1. 21번째 줄의 [ ]을 넣지 않은 상황) </b>
       
![2023-03-17 15;32;13](https://user-images.githubusercontent.com/119389577/225830228-72f08b10-310f-4ff6-8589-d17e535794bf.gif)

![image](https://user-images.githubusercontent.com/119389577/225830630-3fdebbc0-dc08-4ff1-9876-591f49f78aa7.png)

오늘 하루 안보기의 버튼을 누르고 리랜더링 됐을 때, 콘솔에 찍힌 3번째줄(rerendering false)와 4번째줄 (effect callback T)는 이해가 되는데  <b>마지막 5번째줄의 rerendering false는 어디서 나왔는지 이해가 잘 되지 않습니다... </b>

머리에 물음표를 띄우고 있는 4명의 아기새( 서(미영+석원)님, 문진기님, 저)에게 느낌표가 뜰 수 있게 조언을 해주실 수 있을까요...??

## 코드 검토 리소스

https://github.com/PracticeKJY/react-project-kally/tree/miyoungTest

<br>
위의 코드는 Home.jsx에 있습니다.

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
## 문제 상황

"오늘 하루 안보기" 버튼을 누르고 리-렌더링 되었을 때, 콘솔에 찍힌 3번째줄(`rerendering false`)와 4번째줄 (`effect callback T`)는 이해가 되는데 마지막 5번째 줄의 `rerendering false`는 어디서 나왔는지 이해가 잘 되지 않습니다...

머리에 물음표를 띄우고 있는 4명의 아기새( 서(미영+석원)님, 문진기님, 저)에게 느낌표가 뜰 수 있게 조언을 해주실 수 있을까요...??

<br />

## 문제 연구 및 풀이

질문을 통해 useEffect 훅을 사용할 때 **"왜 종속성 배열을 설정하는 것이 중요한가?"에 대한 깨달음의 시간이 있었을 것** 같습니다.

<br />

### 종속성 배열을 설정한 useEffect 훅의 흐름

종속성 배열을 설정한 경우 컴포넌트는 **1회 렌더링, 1회 리-렌더링** 합니다.

<img src="https://user-images.githubusercontent.com/1850554/225845352-58637627-e7e7-4a06-9973-b39cb609526c.png" alt />

<br />

### 종속성 배열을 설정하지 않은 useEffect 훅의 흐름

하지만 종속성 배열을 설정하지 않은 경우, **1회 렌더링, 2회 리-렌더링**을 수행합니다.

<img src="https://user-images.githubusercontent.com/1850554/225844600-034a65a5-0562-49e3-9ada-fc65d0797f64.png" alt />

<br />

### 질문의 핵심

질문의 핵심은 종속성 배열을 설정하지 않았을 때 "왜 2번째 리-렌더링이 발생하는가?" 입니다. 그리고 2번째 리-렌더링이 된다면? 
이론에 따랐을 때 useEffect의 이펙트 콜백 함수 또한 다시 실행되어야 할 텐데, 리-렌더링만 수행될 뿐 이펙트 콜백은 실행되지 않습니다.

> "2번째 리-렌더링"은 "3회차 렌더링"을 말합니다. (렌더링 → 리-렌더링 → 리-렌더링)


### 추론된 원인

개인적인 추론 입니다만, 처리된 결과(현상)를 두고 봤을 때 **useEffect 훅 내부에서 조건 처리되는 부분에서 이전 `isCheckModalOpen`과 현재 `isCheckModalOpen` 값이 동일한 경우에도 setCheckModalOpen 업데이트 함수를 사용해 컴포넌트 업데이트를 시도하긴 하므로 컴포넌트는 다시 렌더링 되지만, useEffect의 이펙트 콜백은 재실행 되지 않는 것으로 보입니다.**

처리 결과를 두고 정리하면 다음과 같습니다.

- useEffect 훅의 종속성 배열이 설정되지 않은 경우
- 이전 상태와 현재 상태 값이 동일할 지라도 상태 업데이트 함수를 실행한 경우, 컴포넌트 리-렌더링 됨
- 이펙트 콜백의 경우, 이전 상태와 현재 상태 값이 동일한 경우 실행되지 않음

```jsx
if (modalCloseValue && modalCloseValue?.includes('T')) {
  console.log(
    `React에 상태 업데이트 요청 → 리-렌더링 ${renderCount}회차 예약`
  );
  console.log(
    `%cisCheckModalOpen 이전/현재 상태 값은 "${
      prevIsCheckModalOpenRef.current === isCheckModalOpen
        ? '같다'
        : '다르다'
    }"`,
    'color: #d61257; font-weight: 900'
  );

  let checkModalOpenValue = false;

  setCheckModalOpen(checkModalOpenValue);
  prevIsCheckModalOpenRef.current = checkModalOpenValue;
}
```

이어서 가설 증명을 위해 `checkModalOpenValue` 상태의 이전/현재 값이 다를 경우에만 상태 업데이트 함수가 실행되도록 설정해봤습니다.

```jsx
if (prevIsCheckModalOpenRef.current !== checkModalOpenValue) {
  setCheckModalOpen(checkModalOpenValue);
}
```

결과는 가설대로 2번째 리-렌더링을 발생시키지 않았습니다. 
즉, "상태 업데이트 함수가 실행되면 설사 그 값이 동일 참조인 경우라 할지라도 컴포넌트 리-렌더링이 발생할 수 있다"입니다.
단, useEffect 훅의 종속성 배열이 설정되지 않은 경우에 한해서이지만요.

<img src="https://user-images.githubusercontent.com/1850554/225876721-26fc0f44-cb1b-480d-8e47-750b214ad2b8.png" alt />

## 테스트 코드

테스트 한 Home.jsx 코드 전문입니다. 아래 코드를 붙여넣고 결과를 확인해보세요. 🙂

<details>
  <summary>Home.jsx</summary>

  ```jsx
  import { useState, useEffect, useRef } from 'react';
  import { Mainmodal } from './Mainmodal/Mainmodal';
  
  let renderCount = 0;
  
  function Home() {
    const [isCheckModalOpen, setCheckModalOpen] = useState(true); // [1, 4]
    const prevIsCheckModalOpenRef = useRef(null);
  
    useEffect(() => {
      let modalCloseValue = getCookie('modalClose');
  
      console.groupCollapsed(
        `%cuseEffect 훅 내부: ${renderCount}회차 진행`,
        'color: #104edf'
      );
      console.table({ '이펙트 콜백': modalCloseValue }); // [3, 7]
      console.groupEnd();
  
      if (modalCloseValue && modalCloseValue?.includes('T')) {
        console.log(
          `React에 상태 업데이트 요청 → 리-렌더링 ${renderCount}회차 예약`
        );
        console.log(
          `%cisCheckModalOpen 이전/현재 상태 값은 "${
            prevIsCheckModalOpenRef.current === isCheckModalOpen
              ? '같다'
              : '다르다'
          }"`,
          'color: #d61257; font-weight: 900'
        );
  
        let checkModalOpenValue = false;
  
        if (prevIsCheckModalOpenRef.current !== checkModalOpenValue) {
          setCheckModalOpen(checkModalOpenValue);
        }
  
        prevIsCheckModalOpenRef.current = checkModalOpenValue;
      }
    });
  
    ++renderCount;
    console.log(`${renderCount}회차 isCheckModalOpen = ${isCheckModalOpen}`);
  
    // [2, 5]
    console.groupCollapsed(
      `%c컴포넌트 Body: ${renderCount}회차 렌더링`,
      'color: #371abc'
    );
    console.table({
      '렌더링 모드 ': renderCount === 1 ? 'rendering' : 'reRendering',
      '모달 열린 상태 여부 ': isCheckModalOpen,
      '렌더링 횟수': renderCount,
    });
    console.groupEnd();
  
    return (
      <>
        <div>Home</div>
        {isCheckModalOpen ? <Mainmodal setModalOpen={setCheckModalOpen} /> : null}
      </>
    );
  }
  
  function getCookie(name) {
    let cookieName = document.cookie
      .split(';')
      .find((c) => c.trim().startsWith(`${name}=`)); // modalClose찾기
  
    if (cookieName) {
      // 쿠키이름에 해당하는 T반환
      return cookieName.split('=').map((v) => decodeURIComponent(v.trim()))[1];
    }
  }
  
  export default Home;
  ```
</details>

## 정리

이번 질문으로 인해 React의 useEffect 훅, 이펙트 콜백의 실행 흐름에 대해 다시 한 번 생각해볼 수 있었습니다.
일반적으로 알려진 훅의 흐름 외에도 상태 업데이트 함수가 실행될 경우 일어날 수 있는 일들을 직접 확인하기도 했습니다.
물론, 권장되지 않는 상황에서 보여진 결과라 이것이 React의 버그(bug)인지, 아니면 특정 상황에서만 발생하는 현상인지 알 수 없습니다.

그럼에도 일반적으로 알려진 이론을 그대로 수용하지 않고, 의문을 가지고 질문 주신 여러분께 감탄합니다. 😃
덕분에 현상에 대해 확인하고 정리할 수 있는 시간이 되었습니다. 감사합니다. 😌

**Comment by PracticeKJY** [comment]
![image](https://user-images.githubusercontent.com/119389577/225886323-4ecc5ffe-0c7c-4c13-a15f-6efce025de7e.png)

오늘도 3개의 깨달음을 얻었습니다... 정말로정말로 감사합니다 야무썜... useLocation ,useEffect, Dependency array... 꼭 제껄로 만들겠습니다.. 정말 감사합니다 감사합니다
