### ISSUE TITLE
[LAB-14] 함수안에서 콘솔 로그로 상태값을 확인하면 왜 이전 값이 뜨나요?

### ISSUE THREAD

**Issue by jh1109** [yamoo9/likelion-FEQA#163]
## 질문 작성자

노주희

## 문제 상황
기능 구현에 대한 문제는 해결했습니다.
해결 과정에서 왜 이런 문제가 발생했는지 이해 되지 않아서 질문 남깁니다.

- 검색창 기능 구현 중 input에 값을 입력했다가 값을 모두 지웠을 때
- 이전 상태값 기준으로 기능이 동작하는 문제를 확인했습니다.
- 검색창 input 값에 onChange 이벤트를 설정하였고,
- 함수 코드는 아래와 같습니다.
```
const changeInputValue = useCallback(
    (e) => {
      setInputValue(e.target.value);
      if (e.target.value !== '') {
        const filterMorph = fattailMorph.filter((morph) =>
          morph.korName.includes(inputValue),
        );
      }
      console.log(inputValue);
    },
    [inputValue],
  );
  ```
- console.log(inputValue)로 상태 값을 확인하면 오레오를 입력했을 때 그 전 상태인 '오레'가 콘솔창에 뜨는 것을 확인할 수 있습니다.
![검색창 트러블 슈팅 문제상황1](https://user-images.githubusercontent.com/117807467/225940249-a291c518-1565-44c9-9c7d-c34a6f798b7f.PNG)
- input창에 값을 모두 지웠을 때 '오'때문에 드롭박스에 오레오가 뜨는 문제가 발생합니다.
![검색창 트러블 슈팅 문제상황2](https://user-images.githubusercontent.com/117807467/225941159-acc94ab8-ae3d-4c7b-905c-907276ab4629.PNG)
- 콘솔창 외에 크롬 개발자 도구에서 컴포넌트 상태 값을 확인했을 때는 input 창에 입력한 값이 바로바로 최신화되어 inputValue가 바뀌는 것을 확인했습니다.
- 콘솔창에 뜨는 inputValue는 무시하고, 크롬 개발자 도구 상태 값만 고려한다고 하면
- **정상적으로 상태값이 바뀌고 있는 것이니 상태 값이 ''이 되었을 때 드롭다운에 아무것도 뜨지 않아야 하는데 왜 이런 문제가 발생했던 걸까요?**

## 문제 해결한 방법
- 함수 안에 작성한 것이 문제라고 판단되어 inputValue 값을 업데이트해주는 코드는 showFilterDropBox 함수를 새로 만들어 상태를 업데이트 시켰습니다. 작성한 코드는 아래와 같습니다.
```
  const changeInputValue = useCallback(
    (e) => {
      setInputValue(e.target.value);
      console.log(inputValue);
    },
    [inputValue],
  );
  const showFilterDropBox = () => {
    if (inputValue === '') {
      setFilterDropbox(false);
    } else {
      setFilterDropbox(true);
      const filterMorph = fattailMorph.filter((morph) =>
        morph.korName.includes(inputValue),
      );
      setMorphList(filterMorph);
    }
  };
  useEffect(showFilterDropBox, [inputValue]);
```
- 위와 같은 방법으로 기능 구현 문제는 해결했지만,
- **왜 콘솔창에는 이전 상태값이 나오는지?** 
- **함수도 왜 이전 상태값을 기준으로 동작했는지 궁금합니다.**
 

## 프로젝트 저장소 URL
fork로 작업을 진행중이라 개인 저장소로 공유드립니다.
- https://github.com/jh1109/MofMof
- 작업 브랜치 : dev-morphCalc-input
- 작업 파일명 : MorphInputContainer.jsx

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2) : CRA 툴 체인을 사용하고 있습니다.

**Comment by yamoo9** [comment]
## 상태 업데이트 지연 현상에 대한 이해

@jh1109 님 주어진 문제 해결 멋지게 잘 하셨어요~ 👍

이 이슈는 이전 질문(**상태 업데이트 지연 처리 현상**)에서 다룬 바 있어요. 
[답변 글](https://github.com/yamoo9/likelion-FEQA/issues/117#issuecomment-1449394354)을 읽고, 주희님이 경험한 현상과 비교해 이해해보세요. 😀

**Comment by jh1109** [comment]
감사합니다~!
