### ISSUE TITLE
[LAB-20] storybook이 잘 작동하다가 에러메시지가 계속 나옵니다. 

### ISSUE THREAD

**Issue by ghost** [yamoo9/likelion-FEQA#164]
## 질문 작성자

정보화

## 문제 상황

안녕하세요 선생님
스토리북이 잘 작동했었는데,
작업을 이것저것 하면서 스토리북을 열려고하니깐 에러가 계속 생깁니다.

혼자 다시 clone해오고 폴더도 다시 만들어서 해보고
구글링해서 본대로 rm -rf node_modules package-lock.json 하고 npm도 다시 깔아보고
이것저것 시도하다가,
오래 걸리고 더 꼬이는 것만 같아서 질문 드립니다.

감사합니다.

<에러 메시지 창>

![질문2](https://user-images.githubusercontent.com/108967196/225954128-73195785-05c5-4468-a600-88bc053eb4c7.png)

![질문1](https://user-images.githubusercontent.com/108967196/225954095-cbe07e63-b926-4b5b-87b5-b0919794f70d.png)

## 프로젝트 저장소 URL

- https://github.com/bellaru2022/Monstera.git
- develop 브랜치입니다.

## 환경 정보

- 운영체제 정보 : window
- Node.js 정보 : 18.15.0
- 라이브러리 정보 (예: React v18.0.2)
npm : 9.5.0

**Comment by yamoo9** [comment]
## 문제 원인

@bellaru2022 님이 겪은 오류는 에셋 위치가 올바르지 않아 발생한 문제에요. 
아래 오류 메시지를 읽어보면 **"monstera_icon.svg 이미지 파일을 호출하는 데 실패"** 했다고 안내하고 있어요.

> Faild to resolve import "../../assets/monstera_icon.svg"

<img width="1347" alt="" src="https://user-images.githubusercontent.com/1850554/226043394-d37d31bf-ff96-4e4b-aec1-db55258d60b0.png">

## 문제 해결

VSCode 에디터에서 에셋 경로를 입력해보면 `assets` 폴더가 아니라, `assets/images` 폴더 안에 모든 이미지가 포함되어 있어요.

<img width="480" alt="" src="https://user-images.githubusercontent.com/1850554/226042648-b3a31534-09b4-4a76-8614-70aed119d9f6.png">

어떤 이유로 폴더 경로를 이전과 다르게 바꿔서 발생한 문제일 수도 있어요. 아마도 🙂
정리하면 Storybook 앱이 **에셋 경로만 올바르게 바꿔주시면 정상적으로 구동**될 거에요. 😊 (아래 스크린샷 참고)

<img width="996" alt="" src="https://user-images.githubusercontent.com/1850554/226039198-9bd09d36-cadf-4f4d-b2e0-4a4dfe71acc5.png">

## 참고

혹시 패키지 재 설치 과정 중에 "호환 문제가 의심되는 종속성 모듈 설치 오류"가 발생하면 [이전 답변 글](https://github.com/yamoo9/likelion-FEQA/issues/145#issuecomment-1468863490)을 참고해 해결해보세요. 😌

**Comment by ghost** [comment]
확인하였습니다 감사드립니다 선생님!! :)
