### ISSUE TITLE
[LAB-4] label의 위치가 원하는대로 배치가 안됩니다

### ISSUE THREAD

**Issue by SeoMiYoung** [yamoo9/likelion-FEQA#165]
## 질문 작성자
서미영

## 문제 상황
안녕하세요. 
제가 현재 만들어야 할 시안은 다음과 같습니다.
![image](https://user-images.githubusercontent.com/112063987/226096979-7fa0923e-4295-4a6c-9c80-0107c4158b9d.png)

그러나, 
![image](https://user-images.githubusercontent.com/112063987/226097026-3c2eac4f-fdd2-4d16-95f5-d8aabff50f2c.png)
자꾸 '내용'이라는 label이
위쪽으로 올라오지 못하고, 위의 사진처럼 위치하게 됩니다 ㅠㅠ

오랜시간 동안 고민해보았지만 아직까지 해결하지 못해서 고민끝에 질문드립니다.
혹시 css와 관련해서 어떤점이 문제인지 도움을 얻을 수 있을까요..?
감사합니다.

## 프로젝트 저장소 URL
https://github.com/SeoMiYoung/project-repo

브랜치 정보: feat/#96
관련 폴더: components/ProductDetailPopUp

## 환경 정보
운영체제 정보: 윈도우
Node.js 정보: v18.14.0

**Comment by yamoo9** [comment]
@SeoMiYoung 님

마크업을 좀 변경하고, Flexbox 레이아웃을 활용해보세요. 
슬비쌤과 함께 공부 했던 것을 떠올려 보면 잘 구성하실 수 있을 거에요. 🤔

<img width="813" alt="image" src="https://user-images.githubusercontent.com/1850554/226099345-c857be52-276b-4287-931e-5414248f36c6.png">

아래 스크린샷은 참고하되, 직접 미영 님께서 구현해보세요. 😌

<img width="1251" alt="" src="https://user-images.githubusercontent.com/1850554/226099327-0950bc71-67ac-4f90-af1c-1d33ff5c9648.png">

**Comment by seulbinim** [comment]
안녕하세요 미영님^^
저는 해당 프로젝트를 클론해서 패키지를 설치했는데 npm start가 실행이되지 않고 오류가 발생하고 있어 코드를 바로 체크해보지는 못했습니다.
그러나 아무쌤이 벌써 답을 주셨으니 마크업 구조를 다시 고민하신 후 flex를 잘 적용해 보세요.
다만 수업시간 언급했던 것처럼 fieldset 요소갸 Flex Container가 될 경우 버그가 있던 사례가 있었는지라 div 요소를 Flex Container로 사용해 보시면 어떨까 싶습니다.
UI를 만들면서 느끼시겠지만 결국 마크업 구조를 어떻게 설계할 것인가가 매우 중요하답니다.
웹접근성 관점에서도 마크업은 정말 중요한 부분인구요.
쉽지 않겠지만 한 단계씩 성장하는 과정이라고 느끼고 화이팅 하시기 바랍니다.

그럼 행복한 주말 보내세요~

**Comment by SeoMiYoung** [comment]
야무쌤, 슬비쌤 답변해주셔서 정말 감사합니다. 조언해주신 내용을 바탕으로 계속 시도해보고 있습니다! 
더 나은 코드를 짜도록 노력하겠습니다!!
