### ISSUE TITLE
[LAB-7] Recoil을 통한 input 리-렌더링. 그리고 성능 vs. 사용자 경험

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#166]
## 질문 작성자

김하연

## 문제 상황
리코일을 통해 상태관리를 하려고 합니다.
`titleState.js` 안에 `atom`을 만들어주고 
그것을 `WriteInput.jsx` 에 불러와서 `useRecoilState` 를 이용해 받아왔습니다. 
이를 통해 부모인 `QuestionWrite.jsx` 전체가 렌더링 되는건 막을 수 있었습니다.
현재 상태는 `WriteInput` 에 있는 것들만 렌더링이 되고 있는 상태입니다.

제가 궁금한 점은 밑과 같이 값을 입력할 때 마다 인풋창이 렌더링 되고 있는데
글자 하나를 입력할때마다 렌더링이 되는 것이 맞나요..?
아니면 이 부분을 debounce를 통해 또 막아줘야 하는지 궁금합니다..

![Mar-19-2023 01-25-38](https://user-images.githubusercontent.com/111109573/226119234-0af46fd2-ab4e-4097-afbf-3a93c773ee23.gif)

## 프로젝트 저장소 URL
https://github.com/Likelion-lucky7/DECO/tree/question-write-post%2330

브랜치는 `question-write-post#30` 입니다!

**Comment by yamoo9** [comment]
## 문제 상황

값을 입력할 때 마다 인풋창이 렌더링 되고 있는데 글자 하나를 입력할때마다 렌더링이 되는 것이 맞나요?
아니면 이 부분을 debounce를 통해 또 막아줘야 하는지 궁금합니다.

## 문제 분석 및 해설

"맞고 틀리다"는 개념이 아니라, **관점에 따라 다르게 적용할 수 있습니다.**

### 성능(Performance) 관점

React의 상태 업데이트에 따른 컴포넌트 리-렌더링은 자연스러운 현상입니다.
의도와 상관없이 불 필요한 리-렌더링이 발생하는 것이 문제인 것이죠.

하지만 입력 필드처럼 사용자 입력을 수십차례 받는 경우 리-렌더링 또한 수십차례 처리됩니다.
아무래도 수십차례 리-렌더링 되는 것보다 수차례 리-렌더링 되는 것이 성능 면에서는 낫죠.

그래서 성능 향상을 목적으로 사용자 입력에 따른 리-렌더링 처리를 완화(debounce)할 수 있습니다.
아래는 debounce를 사용한 결과로 리-렌더링 처리 횟수가 줄었으니 확실히 성능 관점에서는 낫습니다.

<img src="https://user-images.githubusercontent.com/1850554/226143505-901fbe96-34ab-41f9-83a3-cec3411e6b7e.gif" alt width="600" />

### 사용자 경험(UX) 관점

앞서 성능 관점에서 이야기를 했지만, 이상한 점을 느꼈을 겁니다. 🤔
잘 모르겠다면 아래 debounce를 사용하지 않은 결과를 확인해 봅니다. 
어떤가요? 비교해보니 이상한 점이 느껴지나요?

<img src="https://user-images.githubusercontent.com/1850554/226143625-194d4072-e526-4a23-9e5c-2a0577d60266.gif" alt width="600" />

네. 맞습니다. 사용자 경험 관점에서 입력할 때마다 입력한 글자 수가 오른쪽에 업데이트 되어야 하죠.
그런데 성능 관점에서 리-렌더링 횟수를 줄인 예에서는 실시간 업데이트가 아니라, 입력이 마무리 될 때 업데이트 합니다.
성능 관점에서는 좋을 수 있지만, 사용자 관점에서는 어색한 상황이 아닐 수 없습니다. 🙄

> 어라? 입력 중인데 왜 아직 1이지? 아.. 이제 업데이트 되었다! 48자 입력 했구나.

이상하죠? 사용자는 입력에 따라 즉각적인 반응을 기대할 텐데 
정작 애플리케이션 인터페이스는 지연된 반응을 보여 당황스럽습니다. 😥

## 정리

개발자는 성능 저하를 막고, 보다 나은 사용자 경험 향상을 목적으로 노력해야 하는데
[이율배반(二律背反)](https://www.google.com/search?q=%EC%9D%B4%EC%9C%A8%EB%B0%B0%EB%B0%98&rlz=1C5CHFA_enKR884KR884&oq=%EC%9D%B4%EC%9C%A8%EB%B0%B0%EB%B0%98&aqs=chrome..69i57j0i131i433i512j46i433i512j46i512l3j69i61l2.1673j0j7&sourceid=chrome&ie=UTF-8)적인 이런 상황에서 어떤 선택을 해야 할 지 난감할 수 있습니다. 😥

제가 드릴 수 있는 답변은 "사용자 우선(User First)"입니다.
기술적 목적이 사용자 보다 먼저일 리 없잖아요? 😊

즉, 해당 이슈의 경우 **"사용자 경험이 우선"되어야 합니다.**

<br />
