### ISSUE TITLE
[LAB-8] firebase img 저장 경로 설정

### ISSUE THREAD

**Issue by zerocalorie1226** [yamoo9/likelion-FEQA#167]
## 질문 작성자

조성찬

## 문제 상황

![image](https://user-images.githubusercontent.com/65861663/226121690-5e2af93f-b6ba-4c6b-92c0-612f22b24e2d.png)
![image](https://user-images.githubusercontent.com/65861663/226121694-5dd53a0b-8a8e-49d4-be88-849212e88b5d.png)

storage에 이미지를 올렸는데 이미지 url로 https:~ 이게 맞는지 아니면 저장소 위치를 적어야하는지 잘 모르겠습니다.

## 환경 정보

- window

**Comment by yamoo9** [comment]
@zerocalorie1226 님 😊
Storage에 업로드 된 이미지의 `imgUrl` 값인 `https://`로 시작하는 경로를 사용해야 합니다.
Storage에서 이미지의 URL을 가져오는 방법은 [getDownloadURL 전체 코드 예시](https://firebase.google.com/docs/storage/web/download-files?hl=ko#full_example)을 참고하세요. 😀
