### ISSUE TITLE
[LAB-12] 스토리북 절대경로 및 에러 문제

### ISSUE THREAD

**Issue by sykang013** [yamoo9/likelion-FEQA#168]
## 질문 작성자

강수영

## 문제 상황
- 문제상황이 두 가지 입니다. 
### 첫번째 문제: 스토리북에서 절대 경로가 먹히지 않습니다.
![image](https://user-images.githubusercontent.com/113448786/226123789-637da98f-67b3-4ffe-ae1a-25f4259d336f.png)
- 스토리북 버젼은 7.0.0-rc.3 입니다.
- 이슈번호#129 를 참고삼아 스토리북 버젼 확인 및 예제로 주신 마켓칼리의 압축을 풀어 .storybook안의 main.js, preview.js 를 살펴보고,  vite.config.js의 절대경로 설정을 살펴보았지만 크게 짚이는 점을 찾을 수 없었습니다. 
- 절대경로로 작업 하면 아래 이미지와 같은 오류가 발생하고, 컴포넌트와 엮여있는 모든 경로를 상대경로로 수정하면 렌더링이 정상적으로 됩니다. 
![image](https://user-images.githubusercontent.com/113448786/226123905-bd505134-58b7-4758-944e-866ec45ff13c.png)
<br>

### 두번째 문제: 스토리북의 console창에서만 뜨는 에러.
- vsc코드에서 파일을 save할 때 마다/새로고침 할 때 마다 아래와 같은 에러메시지가 뜨는데 원인이 짚이지 않습니다. 우측에 떠있는 에러 링크를 클릭해도 마치 노드모듈스 같은 느낌의(이렇게 밖에 표현이 안되네요 😭 )파일이 떠 어떻게 에러 원인을 파악할 수 있는지 감도 잡히지 않습니다. `npm run start`는 콘솔에 아무 에러도 뜨지 않는것을 보니 스토리북이 독립적인 환경이라 발생하는 문제 같습니다만, 조언해주실 수 있을까요?  
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/113448786/226131333-5458364e-effa-4ea0-b19b-54aa4e5089a4.png">

## 프로젝트 저장소 URL
- 브랜치명 : `feature/#13`
- https://github.com/sykang013/together/tree/feature/%2313 

## 환경 정보

- 운영체제 정보 (macOS)
- Node.js 정보 (v18.14.1)
- 라이브러리 정보 (React v18.0.2)
- 기타 정보
  - storybook@7.0.0-rc.3
  - storybook-addon-react-router-v6@0.3.1

**Comment by yamoo9** [comment]
## 답변 1. Storybook 절대경로 구성

Storybook v7(Beta)부터 사용자의 Vite 앱 구성과 동일한 Storybook 앱을 구성한다고 안내 했지만, 확인 결과 절대 경로 설정은 그렇지 않은 것으로 보입니다. 부디 공식 v7에서는 이 문제가 해결되기를 바랍니다. 결과적으로 Storybook v7(Beta)에서도 이전 버전과 마찬가지로 사용자가 Storybook 앱의 구성을 설정해야 합니다. ([참고](https://storybook.js.org/docs/7.0/react/builders/vite#configuration))

`.storybook/main.js` 파일을 열고 Storybook 구성(config) 객체에 viteFinal 메서드를 추가 설정합니다.

```js
import { mergeConfig } from 'vite';
import { resolve } from 'node:path';

const config = {
  // ...
  core: {
    builder: '@storybook/builder-vite',
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      resolve: {
        alias: {
          ...config.resolve.alias,
          '@': resolve(__dirname, '../src'),
        },
      },
    });
  },
  // ...
};
```

<details>
  <summary><code>.storybook/main.js</code> 코드 (참고)</summary>
  
  ```js
  import { mergeConfig } from 'vite';
  import { resolve } from 'node:path';
  
  /** @type { import('@storybook/react-vite').StorybookConfig } */
  const config = {
    stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
    addons: [
      '@storybook/addon-links',
      '@storybook/addon-essentials',
      '@storybook/addon-interactions',
      '@storybook/addon-a11y',
      'storybook-addon-react-router-v6',
      '@storybook/addon-styling',
    ],
    core: {
      builder: '@storybook/builder-vite',
    },
    async viteFinal(config) {
      console.log(config);
      return mergeConfig(config, {
        resolve: {
          alias: {
            ...config.resolve.alias,
            '@': resolve(__dirname, '../src'),
          },
        },
      });
    },
    framework: {
      name: '@storybook/react-vite',
      options: {},
    },
    docs: {
      autodocs: 'tag',
    },
  };
  
  export default config;
  ```
</details>

<br />

설정 이후부터는 절대 경로를 사용할 수 있습니다.

<img width="920" alt="" src="https://user-images.githubusercontent.com/1850554/226145176-d6e4cb4b-a983-4b91-a684-cf1801ac6a87.png">

보다시피 Storybook 앱이 오류 없이 정상적으로 렌더링 합니다. 😃

<img width="1161" alt="" src="https://user-images.githubusercontent.com/1850554/226145165-60decfc6-7df8-41f5-8549-8a831bd7373b.png">

## 답변 2. Invalid prop theme 오류

해당 오류 내용을 살펴보면 React.Fragment 컴포넌트는 `key`, `children` prop만 가질 수 있는데 `theme` prop이 포함 되서 React가 경고하는 것입니다. 하지만 이 경고가 의아한 점은 개발 코드에서 React.Fragment 또는 Fragment 컴포넌트가 사용된 적이 없다는 것입니다.

> Warning: Invalid prop `theme` supplied to `React.Fragment`. 
> React.Fragment can only have `key` and `children` props.

<img width="1161" alt="" src="https://user-images.githubusercontent.com/1850554/226145324-327a21e4-8c5f-4bd9-b93d-1d014b7ef10f.png">

네. 맞습니다. 이 경고는 Storybook 내부(코어 또는 애드온 등) 설정에 따른 문제로 현재 컨텍스트에서 발생한 이슈가 아닙니다.
아마도 React.Fragment 컴포넌트에 `theme` prop을 설정하는 실수를 한 것으로 보입니다. 😅

Storybook으로 인해 발생한 이 경고가 신경 쓰인다면? 현재 컨텍스트에서만 발생한 이슈만 출력되도록 설정합니다.

<img width="1051" alt="" src="https://user-images.githubusercontent.com/1850554/226145517-de7d7b3d-1610-4e3b-bacb-b340f045f702.png">

그러면 Console 패널이 깔끔해진 것을 볼 수 있습니다. 😊

<img width="1161" alt="" src="https://user-images.githubusercontent.com/1850554/226145581-22892679-7370-4823-b9ee-ddb27ade7eff.png">

**Comment by sykang013** [comment]
감사합니다 야무쌤!! 주신대로 해보니 잘 작동됩니다!!! 최고입니다 🥹🥹🥹👍👍👍
