### ISSUE TITLE
🛎️ this의 사용 용도가 무엇인가요?

### ISSUE THREAD

**Issue by shoveller** [yamoo9/likelion-FEQA#17]
[STD2 - 2주차 멘토링 4번째 질문](https://likelion.notion.site/1-f42db4f5dfc143d78632a77f2b10e85a)

경우에 따라 window를 바인딩할 때도 있고 값을 바인딩하는 경우가 있는데 어떤 차이가 있는지 궁금합니다.
this가 어떤 경우에 사용이 되는지도 궁금합니다.

**Comment by yamoo9** [comment]
## 안내

재원 멘토님이 답변할 글이 많은 듯 하여 관련 질문에 대신 답변합니다. 😃

## this 바인딩이 사용되는 예시

이해를 돕기 위해 간단한 예를 살펴봅시다.
"새"와 "인간"을 [추상화](https://namu.wiki/w/%EC%B6%94%EC%83%81%ED%99%94#s-2.1)한 객체를 작성합니다.

```js
const bird = {
  type: '새',
  flyToTheSky() { console.log(`${this.type} 하늘을 날다.`); }
};

const human = {
  type: '인간',
  writeBook() { console.log(`${this.type} 도서에 기록하다.`) }
};
```

새는 하늘을 날 수 있고, 사람은 도서에 기록할 수 있습니다.
각 객체가 고유한 자신만의 능력을 가진 것이죠.

실제 세계에서 사람은 스스로 하늘을 날 수 없습니다.
그리고 새는 도서에 기록할 수 없습니다.

하지만 JavaScript 프로그래밍 세계에서는 그것이 가능합니다.
`this` 바인딩(binding)을 사용하면요. 😌

사람이 하늘을 날 수 있다면 얼마나 좋을까요?
그 바람을 프로그래밍으로 구현하면 다음과 같이 작성합니다.

```js
bird.flyToTheSky.call(human); // "인간 하늘을 날다."
```

![](https://user-images.githubusercontent.com/1850554/211131653-799486d5-9ad8-45dd-87ba-1360184738d1.png)

오! 바람이 이루어졌네요. **인간이 하늘을 날 수 있는 능력(기능)을 가졌습니다!**
물론 JavaScript 프로그래밍 세계에서만이지만요. 😄

그럼 새의 능력(기능, 함수)을 빌려쓰지 않고 인간이 바로 날 수 있을까요?

```js
human.flyToTheSky();
```

안되겠죠. 인간은 날 수 있는 능력(기능)을 가지고 있지 않으니까 다음과 같이 오류가 발생합니다.

![](https://user-images.githubusercontent.com/1850554/211131698-ee4cb0c7-97af-4de2-8c85-eace91c9475a.png)

이해하기 쉽도록 인간과 새의 예를 들어봤는데요.
이처럼 **특정 객체가 가진 능력을 임시로 빌려쓰고 싶을 때 `this` 바인딩을 활용할 수 있어요.**

예를 들어 문서에서 찾은 요소 집합(NodeList) 객체는 배열과 유사한 유사 배열 객체입니다.
그래서 배열(Array) 객체의 능력을 사용할 수 없죠. 하지만 this 바인딩을 사용하면 마치 배열 객체인 것처럼
배열을 능력을 마음껏 사용할 수 있습니다. 😃

아래 코드는 수집된 요소 집합 객체가 마치 배열 객체인 것처럼 `slice` 메서드 능력을 빌려 사용했습니다.

```js
document.querySelectorAll('link'); // NodeList(3) [link, link, link]
Array.prototype.slice.call(document.querySelectorAll('link'), 1); // (2) [link, link]
```

배열 객체의 `slice` 메서드를 빌려쓰지 않고, 가지지 않는 `slice` 메서드를 사용하려 시도하면 
아래와 같이 오류가 발생합니다. 😅

```js
// Uncaught TypeError: document.querySelectorAll(...).slice is not a function
document.querySelectorAll('link').slice(1);
```

위에 설명한 내용을 아래 이미지를 참고해 이해해보세요.

![](https://user-images.githubusercontent.com/1850554/211131880-8902e08e-ed53-46a7-ae25-80a645c7dd83.png)


## this가 사용되는 경우 → [객체 지향 프로그래밍](https://namu.wiki/w/%EA%B0%9D%EC%B2%B4%20%EC%A7%80%ED%96%A5%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D)

`this`는 객체 지향 프로그래밍에서 유용하게 사용됩니다.

일반적으로 객체는 속성 또는 메서드를 가집니다.
이해가 용이하도록 간단한 객체를 작성합니다.

"하주호" 학생 정보를 객체로 추상화합니다.
이 객체는 이름과 나이 정보를 가지고, 그 값을 반환하는 기능(함수)를 가집니다.

```js
const studentJuho = {
  name: '하주호',
  age: 16,
  getName() {
    return this.name;
  },
  getAge() {
    return this.age;
  }
}
```

객체 내부에 작성된 기능(함수) 코드를 살펴보면 `this`가 사용되는 것을 볼 수 있습니다.
객체의 메서드(함수) 안에 사용된 `this`는 객체를 가리킵니다. 아래 이미지를 참고해보세요.

![](https://user-images.githubusercontent.com/1850554/211130789-b6043542-7513-4f52-acef-92648fcb5b4d.png)

우리는 객체를 중심으로 설계하는 프로그래밍 방식을 JavaScript를 사용해 구현해봤습니다.
이 경우 `this`의 쓰임새가 중요해지죠.

간단하게 다룬 예제다 보니 굳이 `getName`, `getAge` 기능(함수)를 작성해야 하나 싶을 수 있습니다.
다음과 같이 코드를 작성해도 학생의 이름과 나이를 출력할 수 있으니까요.

```js
studentJuho.name; // '하주호'
studentJuho.age; // 16
```

맞아요. 간단한 예제다 보니 기능(함수) 구현이 무의미해보일 수 있습니다.
그럼 이어서 **학생 이름과 나이를 바로 접근할 수 없도록 외부로부터의 접근을 막고,
`getName`, `getAge` 기능(함수)로만 접근할 수 있도록 프로그래밍 해볼까요?**

이런 경우 클래스 방식(또는 프로토타입 방식)을 사용해 객체를 생성하는 생성자를 구성할 수 있습니다.

```js
class Student {
  #name;
  #age;
  constructor(name, age) {
    this.#name = name;
    this.#age = age;
  }
  getName() { return this.#name; }
  getAge() { return this.#age; }
}
```

이제 클래스를 사용해 "하주호" 학생 정보를 가진 객체를 생성할 수 있습니다.

```js
const juho = new Student('하주호', 16);
```

자 그럼 생성된 객체를 통해 이름(name) 정보에 접근해봅시다.
이제 앞서 다룬 간단한 객체 예와 달리 이름 정보에 바로 접근할 수 없는 것을 알 수 있습니다.
오직 `getName()` 메서드만이 정보 값을 반환합니다.

```js
console.log(juho.name); // undefined
console.log(juho.getName()); // '하주호'
```

클래스 내부에 정의된 `#name`은 비공개(private)이므로 클래스 외부에서는 접근이 불가능해요.
그러므로 직접 접근을 시도할 경우 오류가 발생합니다.

```js
// 🚨 Uncaught SyntaxError: Private field '#name' must be declared in an enclosing class
console.log(juho.#name); 
```

아래 첨부된 이미지를 참고해보세요.

![](https://user-images.githubusercontent.com/1850554/211131140-3b4e33de-b577-429d-826d-f51be625397a.png)
