### ISSUE TITLE
[LAB-5] Typescript 함수 타입 지정 

### ISSUE THREAD

**Issue by seoohyeon** [yamoo9/likelion-FEQA#172]
## 질문 작성자

김서현

## 문제 상황  
- typescript를 작업중에, 타입 설정하는데 고민이 생겨 남깁니다.  
- 아래 사진과 같은 함수를 할당해주려는데 onChange의 타입을 어떻게 나타내야 할지 모르겠습니다.  
  onChange?: () => void로 해주니 경고창이 뜹니다.
![image](https://user-images.githubusercontent.com/38703262/226181076-da3f73d0-90db-4a62-8ec2-08df1331e9b4.png)
![image](https://user-images.githubusercontent.com/38703262/226181134-5ae21211-5891-456b-ad63-900709ddcf97.png)  

- 아래는 onChange 타입을 선언해준 파일의 코드입니다.
![image](https://user-images.githubusercontent.com/38703262/226181285-5d5f6f1e-64b2-4225-988b-f521482f52a5.png)

- 아래는 onChange 경고창 입니다.
![image](https://user-images.githubusercontent.com/38703262/226181192-9dfaa9ec-341e-4eb5-85d8-6ae9dba4bebf.png)

## 프로젝트 저장소 URL

https://github.com/React-Project-lab5/React-Project-lab5  
develop브랜치  

- 현재 파일 위치 
![image](https://user-images.githubusercontent.com/38703262/226177945-644d01be-4b88-4b28-9698-bf2b88b6d11f.png)

## 환경 정보

- 운영체제 : Windows
- Node.js : v16.14.0
- 라이브러리 : React v18.2.0

**Comment by yamoo9** [comment]
## 타입 확인

TypeScript가 경고한 `onChange` prop에 마우스를 올려보면 어떤 타입이 필요한 지 친절하게 알려 줍니다.

<img width="482" alt="" src="https://user-images.githubusercontent.com/1850554/226182705-01ac0b86-35e5-49d0-b2d6-b2bc49e6aef5.png">

네. DebouncedFunc 타입이 필요함을 알려주고 있네요. 🙂

```tsx
DebouncedFunc<(event: any) => void>
```

## 타입 설정

lodash 패키지에서 DebouncedFunc 타입을 추출한 다음 아래와 같이 설정합니다.

<img width="420" alt="" src="https://user-images.githubusercontent.com/1850554/226182803-5fe779be-a882-4c1e-9717-42c6e53df6d9.png">

```tsx
import { DebouncedFunc } from 'lodash';

interface Props {
  maxWidthValue: string | number;
  heightValue: string | number;
  labelText: string;
  placeHolder: string;
  isA11yHidden: boolean;
  className?: string;
  type?: string;
  onChange?: DebouncedFunc<() => void>;
}
```

그러면 더 이상 TypeScript 경고가 출력되지 않을 거에요. 😃

<img width="500" alt="" src="https://user-images.githubusercontent.com/1850554/226182917-2c9261bc-c422-4dfb-aa99-eba80db9e883.png">
