### ISSUE TITLE
[LAB-8] Firebase 같은 컬렉션 값의 정보 불러오기 관련

### ISSUE THREAD

**Issue by rodwnl** [yamoo9/likelion-FEQA#174]
## 질문 작성자

이경주

## 문제 상황
현재 Products의 userId로 Users에 id와 똑같은 사람의 location을 가져오려고 하는 상황입니다.
![image](https://user-images.githubusercontent.com/88178123/226232566-5f13f002-aaaa-4123-886c-6a419e30a2b0.png)
![image](https://user-images.githubusercontent.com/88178123/226232603-51f9f7cc-21f2-4025-80d5-7895c88d47af.png)
(userId의 jinu로 Users에 id가 jinu인 데이터의 location을 가져오려는 상황)

![image](https://user-images.githubusercontent.com/88178123/226232718-b56d9771-57a2-4faf-a504-bd3c15fb08f9.png)
![image](https://user-images.githubusercontent.com/88178123/226232790-d9e3158e-fe30-40b7-b716-5f2944db9d90.png)
![image](https://user-images.githubusercontent.com/88178123/226234171-1cd87ecc-bc08-4583-8fce-f3027c3b2a22.png)

현재 코드에서 productList의 콘솔 결과입니다. Products의 데이터를 잘 가져온 것을 확인할 수 있고 화면에 location 부분을 제외한 데이터를 UI에 잘 표시하고 있습니다.

![image](https://user-images.githubusercontent.com/88178123/226233368-f0e34eff-06f1-4b70-9421-6902da31cd66.png)
그리고 위의 코드에서 파란색 부분이 제가 Products의 userid와 User에 id가 같은 것을 찾아 location을 추가한 것입니다.

![image](https://user-images.githubusercontent.com/88178123/226233402-779fd9c1-2ff3-4a95-851b-3522e94d4f9c.png)
![image](https://user-images.githubusercontent.com/88178123/226233548-a7bdacb5-6d22-4245-8d0f-639681340081.png)
콘솔결과를 보면 location이 추가된 것을 알 수 있습니다

![image](https://user-images.githubusercontent.com/88178123/226233601-a95720f9-c09e-4526-8cd1-43c592117d8f.png)
근데 문제는 화면에 렌더링 되지 않습니다.

현재 상황에서 궁금한 점은 두가지입니다.
**1. location을 추가하기 전 console.log의 배열과 location을 추가한 후의 console.log의 배열 순서가 다릅니다 (위의 사진을 보면) 왜 배열의 순서가 달라진 것인지 궁금합니다**
![image](https://user-images.githubusercontent.com/88178123/226232790-d9e3158e-fe30-40b7-b716-5f2944db9d90.png)
![image](https://user-images.githubusercontent.com/88178123/226233402-779fd9c1-2ff3-4a95-851b-3522e94d4f9c.png)
**2. 값은 제대로 추가된 것 같은데 화면에 왜 렌더링 되지 못하는지 모르겠어서 알려주시면 감사하겠습니다.**

## 프로젝트 저장소 URL
https://github.com/rodwnl/SAJA-Market/tree/feature/kyoungju/home

## 환경 정보
- Windows

**Comment by yamoo9** [comment]
## 문제 해결

### 답변 1.

Firestore 쿼리(query)에 정렬([orderBy](https://firebase.google.com/docs/firestore/query-data/order-limit-data?hl=ko#order_and_limit_data))을 추가해 데이터 패치 하면 정렬된 순서로 데이터를 가져올 수 있습니다.

### 답변 2.

비동기 처리가 모두 완료되기 전에 상태 업데이트를 시도하기 때문에 정상적으로 화면에 렌더링 되지 않습니다. [Promise.all](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)을 사용해 비동기 처리가 모두 완료될 때 특정 일을 수행하도록 하는 코드가 필요합니다. 아래 작성된 useProducts 훅 코드를 살펴보세요. 코드를 크게 건드리지 않는 선에서 요구사항을 충족할 것입니다. 😃

```jsx
import {app} from "@/firebase/app";
import {getFirestore, collection, getDocs, where, query} from "firebase/firestore";
import React, {useState, useEffect} from "react";
import {Product} from "@/components";

export function UseProductList() {
  const {isLoading, products} = useProducts();

  if (isLoading) {
    return <div role="alert">로딩 중...</div>;
  }

  return (
    <div className="productContainer">
      {products.map((product, index) => (
        <Product
          key={index}
          imgUrl={product.imgUrl}
          title={product.title}
          price={product.price}
          location={product.location}
          interest={product.interest} 
        />
      ))}
    </div>
  );
}
```

```jsx
function useProducts() {
  const [products, setProducts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const db = getFirestore(app);
    const productsRef = collection(db, "Products");

    getDocs(productsRef)
      .then((querySnapshot) => {
        const queryPromises = [];
        const products = [];

        querySnapshot.forEach((doc) => {
          const product = {id: doc.id, ...doc.data()};
          const userId = product.userId;
          products.push(product);

          const queryPromise = new Promise(async (resolve, reject) => {
            const usersSnapshot = await getDocs(query(collection(db, "Users"), where("id", "==", userId)));
            resolve(usersSnapshot.docs);
          });

          queryPromises.push(queryPromise);
        });

        Promise.all(queryPromises)
          .then((userDocs) => {
            const users = [];
            userDocs.forEach(([doc]) => {
              users.push({id: doc.id, ...doc.data()});
            });
            return users;
          })
          .then((users) => {
            return users.map((user) => {
              return {...products.find((product) => product.userId === user.id), location: user.location};
            });
          })
          .then((usersWithProductInfo) => {
            setProducts(usersWithProductInfo);
            setIsLoading(false);
          });
      })
      .catch((error) => {
        console.log("Error getting documents: ", error);
        setError(error);
      });
  }, []);

  return {isLoading, error, products};
}
```

## 가이드 파일

첨부된 가이드 파일을 내려받아 검토해보세요.

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/11014116/src.zip)

**Comment by rodwnl** [comment]
덕분에 해결했습니다 감사합니다!! 근데 비동기 처리가 모두 완료되기 전에 상태 업데이트를 시도하기 때문에 화면에 렌더링 되지 않았다는 말은 이해했습니다만 사실 코드를 짤때 어디서부터 비동기 처리가 완료 되기전에 실행이 되는지 아직 구분이 어렵습니다 ㅠㅠ 이런걸 알려고 할떈 우선 코드를 짜고 렌더링이 되지 않을 시에 비동기 방식으로 돌리는 방식으로 가야하는걸까요? 아니면 렌더링되는 순서를 개발자 도구에서 볼 수 있나요?

**Comment by yamoo9** [comment]
> 덕분에 해결했습니다 감사합니다!! 근데 비동기 처리가 모두 완료되기 전에 상태 업데이트를 시도하기 때문에 화면에 렌더링 되지 않았다는 말은 이해했습니다만 사실 코드를 짤때 어디서부터 비동기 처리가 완료 되기전에 실행이 되는지 아직 구분이 어렵습니다 ㅠㅠ 이런걸 알려고 할떈 우선 코드를 짜고 렌더링이 되지 않을 시에 비동기 방식으로 돌리는 방식으로 가야하는걸까요? 아니면 렌더링되는 순서를 개발자 도구에서 볼 수 있나요?

렌더링 순서를 개발자 도구에서 확인할 수 있는 기능은 별도로 제공하지 않아요. 
그러므로 이런 유형의 문제 해결을 위한 경험이 중요합니다. 이번에 경험을 해보셨으니 
다음 번 유사한 문제가 발생한 경우 이번 경험을 떠올릴 수 있을 거에요. 

실무에 가면 그런 경험을 매일 하게 될 거에요. 
그런 경험을 쌓다보면 시니어가 되는 것이겠죠. 😊
