### ISSUE TITLE
[LAB-19] useState의 set함수를 실행할 때 await를 줄 순 없는건가요?

### ISSUE THREAD

**Issue by djswns7** [yamoo9/likelion-FEQA#176]
## 질문 작성자

박원준

## 문제 상황

firebase 관련 커스텀 훅을 사용해보던 중 useCreateData에 의해 전달받은 docId가 createData 함수 실행 직후 변경된 docId가 아닌 하나 전 docId가 출력되는 걸 보고 확인해보니 createData 내부 로직 상에서  setDocId 함수가 비동기적으로 실행이 되기 때문임을 알게 되었습니다. 이를 해결해보기 위해 useDreateData 함수 내부의 setDocId 함수 직전에 await 키워드를 넣어보거나, createData 함수 앞에 await를 넣어봤지만 setDocId가 비동기적으로 실행되는 건 그대로여서 이걸 해결할 수 있는 방법이 있는지 궁금하여 질문드립니다.

예전 다른 질문 중 https://github.com/yamoo9/likelion-FEQA/issues/117 이 이슈와 거의 흡사한 문제인데 해당 이슈에서 알려주신 방법도 약간 헷갈려서 그 내용을 현재 프로젝트에 적용하려니 자꾸 꼬이네요...ㅜㅜ

![image](https://user-images.githubusercontent.com/72201211/226259157-31765630-c617-4e0a-a816-558c6fbf3e9a.png)

![image](https://user-images.githubusercontent.com/72201211/226259331-bf42eeb7-8736-4acb-b1f0-ea454428ca7e.png)

**Comment by yamoo9** [comment]
@djswns7 님 
문제 상황이 현재 GitHub 저장소에 push 되어 있나요? 
확인을 위해 저장소(및 브랜치), 확인할 파일 위치를 알려주시면 검토해 해결 방법을 안내하겠습니다.

**Comment by djswns7** [comment]
> @djswns7 님 문제 상황이 현재 GitHub 저장소에 push 되어 있나요? 확인을 위해 저장소(및 브랜치), 확인할 파일 위치를 알려주시면 검토해 해결 방법을 안내하겠습니다.

테스트 파일로 연습해본 거라 GitHub 저장소에는 없는데 따로 보내거나 개인 저장소 브랜치 하나를 파서 올릴까요?

**Comment by yamoo9** [comment]
> > @djswns7 님 문제 상황이 현재 GitHub 저장소에 push 되어 있나요? 확인을 위해 저장소(및 브랜치), 확인할 파일 위치를 알려주시면 검토해 해결 방법을 안내하겠습니다.
> 
> 테스트 파일로 연습해본 거라 GitHub 저장소에는 없는데 따로 보내거나 개인 저장소 브랜치 하나를 파서 올릴까요?

테스트 파일을 압축(`node_modules` 디렉토리 제거 및 `.env` 포함)한 후 첨부해주세요. 
첨부 자료 다운로드 받아 테스트 후 답변 드리겠습니다. 😀

**Comment by yamoo9** [comment]
테스트 파일이 첨부되지 않아 이미지의 코드를 직접 쳐야 했습니다. 😥
아래 작성된 코드 예시처럼 useEffect 훅을 사용하면 상태가 업데이트 되었을 때 이펙트 콜백이 실행됩니다. 참고해보세요.

```jsx
import { useState, useEffect, useCallback } from 'react';

export function useCreateData(collectionKey) {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [docId, setDocId] = useState('');

  const createData = useCallback(
    async (data) => {
      const collectionRef = collection(db, collectionKey);

      setIsLoading(true);

      try {
        const { id } = await addDoc(collectionRef, data);
        setDocId(id);
      } catch (error) {
        setError(error);
      } finally {
        setIsLoading(false);
      }
    },
    [collectionKey],
  );

  useEffect(() => {
    console.log(docId); // ← docId 상태 업데이트 되면 이펙트 콜백 실행
  }, [docId]);

  return useMemo(() => ({
    isLoading,
    error,
    createData,
    docId,
  }),
  [error, isLoading, createData, docId])
}
```

**Comment by djswns7** [comment]
계속 기다리고 계실 줄 몰랐어요 죄송합니다... 요청하신 파일 혹시 몰라 늦게라도 첨부드립니다.
[React-Web-Market.zip](https://github.com/yamoo9/likelion-FEQA/files/11018980/React-Web-Market.zip)

스크린샷에 보여드렸던 파일은 useCreateData.js와 FireTest.jsx 파일입니다

**Comment by yamoo9** [comment]
첨부된 파일을 내려받아 테스트 하려 했으나, FireTest.jsx 파일이 보이지 않네요. 😥

<img width="1285" alt="" src="https://user-images.githubusercontent.com/1850554/226491720-25157965-b436-49c9-ac2c-817f56a9677b.png">

하여 이미지를 보고 FireTest.jsx를 타이핑해봤습니다. 😳
아래 코드를 참고해 테스트 해보세요. `docId` 값이 없데이트 되면 Console 패널에 업데이트 된 값이 출력될 것입니다. 😃

```jsx
const { createData, docId } = useCreateData('myCollection');

const [createData, setCreateData] = useState(null);

async function handleCreateData() {
  const data = {
    name: '생성할 데이터',
    isSample: true,
  };

  createData(data);
}

useEffect(() => {
  console.log(docId); // ← docId 상태 업데이트 되면 이펙트 콜백 실행
}, [docId]);
```

**Comment by djswns7** [comment]
두번이나....감사합니다!😅
