### ISSUE TITLE
[LAB-9] 파이어베이스 구글 로그인 에러

### ISSUE THREAD

**Issue by chaehaeun** [yamoo9/likelion-FEQA#179]
## 질문 작성자

채하은

## 문제 상황
- 파이어베이스 소셜로그인 기능을 구현하려고 합니다.
- 소셜로그인 아이콘 버튼 컴포넌트를 만들어서 프롭스로 'google'과 같은 문자열을 넘겨 해당 소셜로그인 함수가 실행되고,
- 스토어에 로그인 상태와 유저 정보가 저장되기를 원했지만... 에러를 해결하지 못하고 있습니다.

## 작업 진행 상황
![image](https://user-images.githubusercontent.com/103991310/226292013-200ffcb1-a634-4b81-8943-1875a86b5236.png)

에러
![image](https://user-images.githubusercontent.com/103991310/226292161-900d04cf-96cf-47de-a193-3068ced1137e.png)

검색해보니 파이어베이스에서 도메인 구성을 하지 않았거나 OAuth 공급자가 추가된 후에 변경된 경우에 생길 수 있는 에러라는 말이 있어 확인해보아도 파이어베이스 콘솔에 적혀있는 authDomain 값과 로컬 env 파일에 작성되어있는 REACT_APP_AUTH_DOMAIN의 값이 동일합니다.

무엇이 원인인지 찾지 못하겠어 질문 올립니다.

## 프로젝트 저장소 URL
https://github.com/chaehaeun/withPet-client.git

## 환경 정보
- 운영체제 정보 : Windows

**Comment by yamoo9** [comment]
## 문제 원인 추론

아마도 Google 프로바이더 사용 설정이 안된 것이 아닌가 생각됩니다. 🤔
Firebase 인증 설정에서 [Google 프로바이더 설정](https://euid.notion.site/Firebase-7ee3583c3d5b4b29b1e03106b1a93567#52897a4ece004673945e87259a876ff2)이 되어 있는 지 확인해보세요.

### Google 인증 프로바이더 사용 설정

**새 제공업체 추가** 버튼을 클릭한 다음 Google을 선택합니다.

<img src="https://euid.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F6f1d7c2b-3c38-4dd1-91f3-9be20e327740%2FUntitled.png?id=9f416f97-766c-4f41-8576-04c99ec670a5&table=block&spaceId=9fd79029-980d-4acb-bd78-d3d7e327cf8a&width=2000&userId=&cache=v2" alt width="600" />

**Google 사용 설정 체크 상태를 활성화** 한 후, **저장 버튼을 눌러 사용을 승인**합니다.

<img src="https://euid.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F57eca227-c2d1-433d-ba88-6efa1aa0ffbb%2FUntitled.png?id=ee771291-1967-4597-b3fc-e2c6a48364d5&table=block&spaceId=9fd79029-980d-4acb-bd78-d3d7e327cf8a&width=2000&userId=&cache=v2" alt width="600" />

**Comment by chaehaeun** [comment]
![image](https://user-images.githubusercontent.com/103991310/226332127-ca3e8f94-8617-4183-bf38-bde2b9b1361c.png)

활성화는 되어있는 상태입니다!!

**Comment by yamoo9** [comment]
> ![image](https://user-images.githubusercontent.com/103991310/226332127-ca3e8f94-8617-4183-bf38-bde2b9b1361c.png)
> 
> 활성화는 되어있는 상태입니다!!

@chaehaeun 님. 
그렇다면 Firebase 구성 정보를 가진 `.env` 파일 첨부 그리고 저장소의 어떤 브랜치 인지 알려주세요. 확인해보겠습니다.

**Comment by yamoo9** [comment]
## Firebase 구성 재 검토

Firebase 구성을 제 계정 정보로 바꾸니 정상 작동합니다. 사용 중인 `.env` 파일과 구성이 동일한 지 검토해보세요.

![](https://user-images.githubusercontent.com/1850554/226338605-af95d45f-dc30-4315-ba06-9b27f9878dfe.png)

아래 스크린샷은 정상 작동 됨을 보여 줍니다. Google 공급자 팝업 다이얼로그 표시부터 Redux 상태 업데이트까지 잘 됩니다. 😀

<img width="1295" alt="" src="https://user-images.githubusercontent.com/1850554/226337784-169861fd-a597-4716-bc03-83484c64aba5.png">


<img width="640" alt="image" src="https://user-images.githubusercontent.com/1850554/226337581-2f857b79-aad0-466c-98f8-2444e4504a7d.png">
