### ISSUE TITLE
[LAB-15] forwardRef 사용 시 styled-component가 적용되지 않습니다.

### ISSUE THREAD

**Issue by hungerbk** [yamoo9/likelion-FEQA#181]
## 질문 작성자

강보경

## 문제 상황

기존에 UserSignUpInput 이라는 컴포넌트를 사용하여 UserBirth라는 컴포넌트를 구현했습니다.
UserSignUpInput 컴포넌트와 UserBirth라는 컴포넌트 모두 스타일을 styled-component 입력하였고, UserBirth에 적용한 스타일이 잘 반영되는 것을 확인했습니다.

다른 기능 구현을 위해 UserSignUpInput에 forwardRef 사용하니 그 뒤로는 UserBirth에 적용한 스타일이 반영이 되지 않았습니다.
(현재는 UserSignUpInput를 사용하지 않고, 별도로 input에 스타일을 적용한 상태입니다.)

원래 styled-component로 스타일을 적용할 때는 동일한 속성 값을 지정하면 안 되는 것인지 (forwardRef로 수정한 뒤에도 UserBirth에 background-color 속성을 적용했을 때는 반영이 되었습니다.)

아니면 forwardRef를 사용해서 적용되지 않게 되었는지 궁금합니다.

<img width="396" alt="스크린샷 2023-03-20 오후 11 15 44" src="https://user-images.githubusercontent.com/43366461/226388619-5de9230e-f32b-4198-8895-caae0e51bd3f.png">
<img width="1053" alt="스크린샷 2023-03-20 오후 11 16 02" src="https://user-images.githubusercontent.com/43366461/226388689-96434fae-bd59-442b-989f-6838b0d3b3cd.png">

스타일이 적용됐을 때의 뷰와 UserSignUpInput 컴포넌트

<img width="600" alt="스크린샷 2023-03-20 오후 11 14 50" src="https://user-images.githubusercontent.com/43366461/226388847-f994ac41-1010-4a02-b910-ae306e867596.png">
<img width="1077" alt="스크린샷 2023-03-20 오후 11 16 22" src="https://user-images.githubusercontent.com/43366461/226388916-8c625563-7b63-4ae4-bc7f-0896eb14c426.png">

스타일이 적용되지 않았을 때의 뷰와 UserSignUpInput 컴포넌트

<img width="317" alt="스크린샷 2023-03-21 오전 12 38 37" src="https://user-images.githubusercontent.com/43366461/226391257-36a5ade1-2df6-42f0-8a89-600b7a2c2b82.png">

UserBirth에 적용한 스타일
기존에는 styled(UserSignUpInput)으로 적용했습니다.

<img width="562" alt="스크린샷 2023-03-21 오전 12 39 34" src="https://user-images.githubusercontent.com/43366461/226391522-845b296b-4abb-46c8-ab37-92647611b206.png">

UserSignUpInput에 적용한 스타일

## 프로젝트 저장소 URL

https://github.com/hungerbk/final-project/tree/develop

develop 브랜치

## 환경 정보

- 운영체제 정보: macOS
- Node.js 정보: v18.12.1
- 라이브러리 정보: React v18.2.0

**Comment by yamoo9** [comment]
## 문제 원인

@hungerbk 님.
styled-components 라이브러리의 스타일 컴포넌트는 모두 기본적으로 [forwardRef](https://react.dev/reference/react/forwardRef) 되어 있습니다. (참고: [Refs](https://styled-components.com/docs/advanced#refs))

<img width="459" alt="" src="https://user-images.githubusercontent.com/1850554/226484307-1712e902-d946-48eb-89ee-a0319894380c.png">

## 문제 해결

예를 들어 아래처럼 Input **스타일 컴포넌트가 정의된 경우, `forwardRef()`로 감싸지 않아도 사용하지 않아도 됩니다.**

```jsx
const Input = styled.input`
  padding: 0.5em;
  margin: 0.5em;
  color: palevioletred;
  background: papayawhip;
  border: none;
  border-radius: 3px;
`;
```

스타일 컴포넌트는 모두 `ref` 속성을 바로 사용할 수 있습니다. 
여기서 `ref`에 연결되는 DOM 요소는 스타일 컴포넌트인 인풋(`styled.input`)입니다.

```jsx
function Form(props) {
  const inputRef = React.useRef(null);

  const handleHoverToFocus = () => {
    this.inputRef.current.focus();
  };

  return (
    <Input
      ref={this.inputRef}
      placeholder="마우스를 올리면 초점이 이동됩니다. 😃"
      onMouseEnter={handleHoverToFocus}
    />
  );
}
```

<img src="https://user-images.githubusercontent.com/1850554/226484007-37a2e32a-1149-4fcc-a768-f91403eb2cd4.gif" alt width="220" />
