### ISSUE TITLE
[LAB-12] 스토리북 조작사항 실시간 미반영과, GSAP 작동타이밍에 관한 문제

### ISSUE THREAD

**Issue by sykang013** [yamoo9/likelion-FEQA#184]
## 질문 작성자

- 강수영

## 문제 상황
- 문제 상황이 두 개 입니다.

### 1️⃣  첫번째 문제: 스토리북의 컴포넌트 조작이 실시간 반영되지 않습니다.
- 스토리북을 처음 깔았을 때는 분명 타이핑,컬러피커 같은 값 조작이 실시간으로 반영되었던 것 같은데, 어느순간 반영되지 않고 있습니다. 현재는 값을 조작한 후 다른 페이지를 클릭하는 등을 수행해야 반영된 수정사항이 보여집니다.
- ![Mar-21-2023 02-06-13](https://user-images.githubusercontent.com/113448786/226415214-55b3534b-c4eb-4a6e-853a-12ce685c2531.gif)

### 2️⃣ 두번째 문제 : 새로고침시 GSAP 애니메이션이 실행되지 않습니다. 
- GSAP을 이용한 애니메이션을 적용했는데([이 예제와 같이 사용자가 페이지에 들어간 순간/새로고침된 순간 작동되어야합니다.](https://www.tving.com/onboarding)), 브라우저 새로고침시 애니메이션이 작동하지 않습니다. 스토리북이랑 같은 선상의 문제일까요? 커뮤니티에서도 딱히 예제를 찾을 수 없었습니다.
- 아래 GIF는, VSC내의, GSAP코드가 있는 파일(`ScrollSectionTitle.jsx`) 내에서 `cmd+s` 를 한 케이스입니다. 이 경우, 애니메이션이 작동 됨이 보여집니다.
![Mar-21-2023 01-59-14](https://user-images.githubusercontent.com/113448786/226413686-482addec-f88c-4f63-93d6-e8fed2040be5.gif)

- 아래 GIF는, 브라우저의 새로고침을 클릭한 케이스입니다. 이 경우, GSAP 애니메이션이 작동하지 않습니다.(autoplay로 설정해놓은 리액트 슬릭 슬라이더는 작동됩니다)
![Mar-21-2023 01-59-35](https://user-images.githubusercontent.com/113448786/226413637-91cf22af-54a5-4641-98db-3b60fafe6dd7.gif)

### 3️⃣ 그 밖에 다른 질문 : (채널이 맞지 않다면 나눠서 올리거나, 멘토링 시간에 질문드리겠습니다!😄 )
- 스토리북 환경구성에서  React Slick, GSAP과 같은 라이브러리를 설치하면(벌써부터 험난할듯한) 움직임이 있는 컴포넌트 또한 구현이 되나요? 그런 애니메이션(?) 컴포넌트들 또한 스토리북으로 관리하는것이 효율적일까요? 스토리북 공홈에서 [GSAP과 관련된 integration](https://storybook.js.org/addons/@mediamonks/muban-storybook-addon-transition/)을 발견하긴 했는데, 제가 원하는 내용은 아닌듯 하고, 신뢰도도 낮아보입니다.

## 프로젝트 저장소 URL
- 브랜치명 : `feature/#13`
- GSAP 이용한 랜딩 페이지 로컬호스트: `http://localhost:3000/landing`
- 저장소 주소 : https://github.com/sykang013/together/tree/feature/%2313
- 압축파일 : [아카이브.zip](https://github.com/yamoo9/likelion-FEQA/files/11021335/default.zip)

## 환경 정보
- 운영체제 정보 (macOS)
- Node.js 정보 (v18.14.1)
- 라이브러리 정보 (React v18.0.2)
- 기타 정보
  - storybook@7.0.0-rc.3
  - storybook-addon-react-router-v6@0.3.1
  - gsap@3.11.4

**Comment by yamoo9** [comment]
## 답변 1. withRouter 글로벌 데코레이터 이슈

정확한 원인은 [storybook-addon-react-router-v6](https://storybook.js.org/addons/storybook-addon-react-router-v6) 제작자에게 문의해야 알 수 있을 듯 합니다만, 현재 상황만 봐서는 글로벌 설정된 withRouter 데코레이터로 인해 props 업데이트가 안되는 것으로 보입니다. 🥲

아래 영상을 보면 글로벌 withRouter 데코레이터를 제거한 후, 테스트 했을 때 정상적으로 업데이트 되는 것을 확인할 수 있습니다.

<img src="https://user-images.githubusercontent.com/1850554/226496610-f2dfc9a8-e189-4818-af07-6fb70c4e4f7c.gif" alt />

그러므로 컴포넌트 또는 스토리 레벨에서 withRouter 데코레이터가 필요한 경우만 설정해 사용하는 것이 권장됩니다.

```jsx
import { Demo } from './Demo';
import { withRouter } from 'storybook-addon-react-router-v6';

export default {
  title: 'Demo/Demo',
  component: Demo,
  // 여기에 작성하면 컴포넌트(component) 레벨 데코레이터 입니다. 🌝
  decorators: [withRouter],
};

export const Primary = {
  args: {
    content: 'React Router 설정이 프리즈 한 듯 보입니다.',
  },
  // 여기에 작성하면 스토리(story) 레벨 데코레이터 입니다. 🌝
  decorators: [withRouter],
};
```


## 답변 2. Side Effects 이슈

GSAP은 실제 DOM 요소를 찾아 작동되는 라이브러리라서 사이드 이펙트(side effects) 처리가 필요합니다.
useLayoutEffect 또는 useEffect 훅을 사용해 GSAP 애니메이션 코드를 감싸야 합니다.

```jsx
import { useLayoutEffect } from 'react';

const ScrollSectionTitle = () => {
  useLayoutEffect(() => {
    gsap.fromTo(
      'section',
      { y: 100, opacity: 0 },
      { y: 0, opacity: 1, duration: 1.2, stagger: { each: 0.1, from: 'start' } }
    );

    gsap.fromTo(
      '.StMessageTitle span, a ',
      { y: 20, opacity: 0 },
      { y: 0, opacity: 1, duration: 0.8, stagger: { each: 0.1, from: 'start' } }
    );

    gsap.fromTo(
      '.StMessageAd span',
      { y: 20, opacity: 0 },
      { y: 0, opacity: 1, duration: 0.8, stagger: { each: 0.1, from: 'start' } }
    );
  }, []);

  return (
    <StScrollSectionTitle>
      <MessageTitle />
      <IconButton />
    </StScrollSectionTitle>
  );
};
```

그러면 문제 없이 GSAP 애니메이션이 적용됩니다. 😄

![1](https://user-images.githubusercontent.com/1850554/226494141-7cee695d-ec53-42a7-a59a-688a461446ad.gif)

## 답변 3. 외부 라이브러리 + Storybook

> 스토리북 환경 구성에서 React Slick, GSAP과 같은 라이브러리를 설치하면(벌써부터 험난할듯한) 움직임이 있는 컴포넌트 또한 구현이 되나요? 그런 애니메이션(?) 컴포넌트들 또한 스토리북으로 관리하는것이 효율적일까요?

Storybook은 독립적으로 컴포넌트 단위 테스트 할 수 있는 환경을 제공합니다.
그러므로 Storybook 앱에서도 외부 라이브러리는 정상 작동합니다. (별도 구성이 필요할 수는 있지만요 🥹)
다만, 프로젝트 일정 문제로 시간이 오래 소요될 경우 모든 컴포넌트를 Storybook에 구성할 필요는 없습니다. 😅
가능한 선에서 Storybook을 사용해 컴포넌트 테스트 해보길 바랍니다.

## 가이드 파일

가이드가 반영된 첨부 파일을 다운르도 받아 확인해보세요. 😄

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/11024160/src.zip)


## ⚠️ ~접근 권한~

~Firestore에 접근할 수 있는 권한이 없습니다. (`.env` 파일이 없기 때문)~

<img width="610" alt="" src="https://user-images.githubusercontent.com/1850554/226491084-4d259179-9520-49e4-800c-4379de059a40.png">

~`.env` 파일을 첨부해주시면 테스트 하여 문제 원인과 해결 방법에 대해 이야기 드릴께요. @sykang013 님 🙄~
