### ISSUE TITLE
[LAB-6] firestore의 페이지화

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#186]
## 질문 작성자

신선영

## 문제 상황

currentUser가 받은 메세지들을 아래 그림처럼 저장했는데, 
![image](https://user-images.githubusercontent.com/48400229/226518782-44e40926-afc3-4763-a802-8dd8b4e0d0e8.png)
저 한 user의 flowerList가 메세지들이고, 그 flowerList 필드를 페이지화 시키는 방법은 없을까요? 

저번에 알려주신 firestore의 페이지화 문서 링크에서 분석해보니 collection 안에 있는 documents의 각각 필드 안에 있는 속성들을 페이지화 하는 것이 아닌 필드(field)를 기준으로 문서(document)들을 페이지화 하는 것 같아서 질문을 드립니다!
![image](https://user-images.githubusercontent.com/48400229/226519152-47694dbb-bfa2-43b9-9bec-45795acf43dc.png)

위 경우에는 flowerList라는 collection을 따로 만드는 것이 좋을까요? 아니면 저 위의 방법으로 페이지화 시키는 방법이 있을까요?

## 프로젝트 저장소 URL

- [공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.](https://github.com/SSY1203/6lossom)
- feature 브랜치 입니다.
- [6lossom-feature (1).zip](https://github.com/yamoo9/likelion-FEQA/files/11025070/6lossom-feature.1.zip)
- env 파일입니다.
[env.zip](https://github.com/yamoo9/likelion-FEQA/files/11025075/env.zip)

## 환경 정보

- 운영체제 정보 (Windows)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 파악

Firestore 데이터 모델에서 `flowerList` 필드를 페이지 화 시키는 방법은 없을까요?
`flowerList`라는 collection을 따로 만드는 것이 좋을까요? 아니면 저 위의 방법으로 페이지 화 시키는 방법이 있을까요?

## 문제 해결

중첩된 컬렉션(nested collection)을 사용해 문제를 해결할 수 있습니다.
Firestore 데이터 모델을 다음과 같이 변경합니다.

```bash
# collection → document → collection
users > 2doa2TW187szxBwLzgCG > flowList
```

그러면 Firestore 공식 문서의 [쿼리 페이지 화](https://firebase.google.com/docs/firestore/query-data/query-cursors?hl=ko#paginate_a_query)를 구현할 수 있습니다.

### 데모

예를 들어 categoreies > sneakers > items 순으로 데이터 모델이 되어 있다고 생각해 봅시다.

![](https://user-images.githubusercontent.com/1850554/226533931-41fa203b-d6e8-4853-bf74-fe76e2ddebab.png)

그러면 다음과 같이 Firestore 데이터 모델의 중첩 컬렉션 데이터를 페이지네이션 할 수 있습니다.

<img src="https://user-images.githubusercontent.com/1850554/226542221-4c2e0777-0d64-4631-86cb-9ce5dcdb45e1.gif" alt width="400" />

아래 컴포넌트 코드 예시를 참고하세요.

<details>
  <summary>PaginationDemo</summary>

  ```jsx
  function PaginationDemo() {
    const [isLoading, setIsLoading] = useState(true);
    const [list, setList] = useState([]);
    const [lastVisible, setLastVisible] = useState(null);
    const [pageTotalCount, setPageTotalCount] = useState(0);
    const [hasNextPage, setHasNextPage] = useState(true);
  
    useLayoutEffect(() => {
      getPageTotalCount();
      queryPage(2);
    }, []);
  
    useLayoutEffect(() => {
      if (list.length === pageTotalCount) {
        setHasNextPage(false);
      } else {
        setHasNextPage(true);
      }
    }, [list.length, pageTotalCount]);
  
    const sneakerItemsRef = collection(db, 'categories/sneakers/items');
  
    const getPageTotalCount = async () => {
      const res = await getCountFromServer(
        query(sneakerItemsRef, orderBy('createAt'))
      );
  
      setPageTotalCount(res.data().count);
    };
  
    const queryPage = async (limitCount = 10) => {
      let q;
      if (!lastVisible) {
        q = query(sneakerItemsRef, orderBy('createAt'), limit(limitCount));
      } else {
        q = query(
          sneakerItemsRef,
          orderBy('createAt'),
          startAfter(lastVisible),
          limit(limitCount)
        );
      }
      const docSnapshot = await getDocs(q);
  
      if (isLoading) {
        setIsLoading(false);
      }
  
      const docs = docSnapshot.docs;
      queryData(docs);
    };
  
    const queryData = (docs) => {
      const listItems = [];
  
      docs.forEach((doc) => {
        listItems.push({ id: doc.id, ...doc.data() });
      });
  
      setList([...list, ...listItems]);
      let nextDoc = docs[docs.length - 1];
      if (nextDoc) {
        setLastVisible(nextDoc);
      }
    };
  
    return (
      <div
        style={{
          display: 'flex',
          gap: 20,
          flexFlow: 'column',
          alignItems: 'flex-start',
          padding: 40,
        }}
      >
        <h2>Pagination Firestore</h2>
        {isLoading ? (
          <div>LOADING...</div>
        ) : (
          <>
            <p>
              {list.length} / {pageTotalCount}
            </p>
            <button
              type="button"
              disabled={!hasNextPage}
              onClick={() => {
                queryPage(2);
              }}
            >
              Next
            </button>
            <ul>
              {list.map((item) => (
                <li key={item.id}>{item.name}</li>
              ))}
            </ul>
          </>
        )}
      </div>
    );
  }
  ```
</details>
 
## 가이드 파일

가이드 파일을 첨부합니다. 확인해보세요. 😊

[PaginationDemo.zip](https://github.com/yamoo9/likelion-FEQA/files/11025645/PaginationDemo.zip)
