### ISSUE TITLE
[LAB-5] 라우터 연결 문제 관련

### ISSUE THREAD

**Issue by HYBEN09** [yamoo9/likelion-FEQA#188]
## 질문 작성자

변혜빈

## 문제 상황

홈 화면에는 헤더와 푸터가 불러와 지지 않게 하고 
다른 페이지들은 헤더와 푸터가 불러와 지게 하고싶은데 
라우터 구성을 어떻게 해야될지 감이 잡히지 않아서 질문 올립니다..!

[렌더링 되는 **홈** 화면]

<img width="500" alt="스크린샷 2023-03-22 오전 12 34 28" src="https://user-images.githubusercontent.com/104710243/226663878-38e4fab1-6ba6-4bc4-8d12-d4e3cfb92a97.png">

[ 라우터 코드 ]
<img width="602" alt="스크린샷 2023-03-22 오전 12 34 28" src="https://user-images.githubusercontent.com/104710243/226658743-0bfc5cab-d0b7-49c9-9a34-9ff2459d3450.png">

[ LayOut 페이지 코드 ]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/104710243/226664490-1b7ddada-1cd4-4ab7-b273-27d0ecfb2168.png">

## 프로젝트 저장소 URL
[Lab5 - develop 브랜치]
https://github.com/React-Project-lab5/React-Project-lab5/tree/develop

[라우터 코드 위치]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/104710243/226665270-7eac82ee-bd21-43db-b477-0f4dbacf1a08.png">

[LayOut 페이지 코드 위치]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/104710243/226666885-3a598db3-7520-41a5-b3eb-2b86766a5c8c.png">

## 환경 정보

운영체제 : Windows
Node.js : v16.14.0
라이브러리 : React v18.2.0

**Comment by yamoo9** [comment]
## 문제 상황

홈 화면에는 헤더와 푸터가 불러와 지지 않게 하고
다른 페이지들은 헤더와 푸터가 불러와 지게 하고싶은데
라우터 구성을 어떻게 해야될지 감이 잡히지 않아서 질문 올립니다..!

## 문제 해결

레이아웃 컴포넌트에 BaseLayout을 추가합니다. 그리고 RootLayout 컴포넌트에서 헤더, 푸터를 제거합니다.

**Layout.tsx**

```jsx
import { Footer, Header } from '@/components';
import { Outlet } from 'react-router-dom';

export default function RootLayout() {
  return (
    <>
      <Outlet />
    </>
  );
}

export function BaseLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
```

그리고 App 컴포넌트를 열어 라우트 구성을 아래와 같이 수정해보세요. 😃

**App.tsx**

```jsx
import RootLayout, { BaseLayout } from './pages/Layout/Layout';

const router = createBrowserRouter([
  {
    path: '/',
    element: <RootLayout />,
    errorElement: <NotFound />,
    children: [
      { index: true, element: <Home /> },
      {
        path: 'mainPage',
        element: (
          <BaseLayout>
            <MainPage />
          </BaseLayout>
        ),
      },
      {
        path: 'recommend',
        element: (
          <BaseLayout>
            <Recommend />
          </BaseLayout>
        ),
      },
      {
        path: 'chat',
        element: (
          <BaseLayout>
            <Chat />
          </BaseLayout>
        ),
      },
      {
        path: 'myPage',
        element: (
          <BaseLayout>
            <MyPage />
          </BaseLayout>
        ),
      },
    ],
  },
]);
```

그러면 아래처럼 홈 페이지 이외의 나머지 페이지는 헤더와 푸터를 포함하게 됩니다.

**Home**

<img width="1904" alt="" src="https://user-images.githubusercontent.com/1850554/226746398-cb5094f6-a2a2-458b-a8ff-573f6d90807a.png">

**MainPage**

<img width="1904" alt="" src="https://user-images.githubusercontent.com/1850554/226746789-cc8a1f93-7516-4ad0-bb55-80bcead4353b.png">
