### ISSUE TITLE
[LAB-3] 데이터 및 파이어베이스 

### ISSUE THREAD

**Issue by choinamechoi** [yamoo9/likelion-FEQA#189]
## 질문 작성자

최영범

## 문제 상황

파이어베이스 관련 질문이 있어 문의 드립니다..

저는 랩 3조에 팀원으로 있고 

주차장 관련 서비스를 만들고있습니다.

- 필요한 데이터  :  하나의 좌표 기준으로 반경 ??m의 주차장 리스트 데이터

- 문제 원인 : 공공데이터 api 가 제공하는 기능에는 반경 ??m 의 주차장 리스트 데이터만 필터해서 뽑을수 있도록 하는 request(input) 이 없음.

- 생각한 해결방법 : 그냥 모든 주차장 리스트 데이터를 json 파일로 내 컴퓨터에 저장. 그  json 파일을 그냥 파이어베이스에 등록한 상태로 시작하자!

- 문제점 : 1. Storage 라는 빌드에 json 파일을 저장해두고 사용해도 되는지 
2.  Firestore Database 라는 빌드에 저장을 하려고 보니 key,value 값을 하나하나씩 추가를 해줘야되던데, json 파일 통째로 넣는 기능이 있을것같은데 공부를 위한 키워드를 제공해 주실수 있으신가요 ,,
감사합니다

## 프로젝트 저장소 URL
https://github.com/LikeLion-FE-Final-Project03/car-zip

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 분석

- 공공 API가 요청 방법을 제공하지 않아 필요한 정보를 활용하기 어려운 상황
- Firestore에 데이터 일괄 업로드 하는 방법

## 문제 해결 방법 제안

제기된 문제에 대해 의견 드립니다.

### JSON 파일 다운로드 → Firestore 업로드에 대한 의견

모든 JSON 파일 로컬 드라이브 저장 후, Firebase 데이터베이스로 업로드하는 것이 불가능한 것은 아닙니다. 
하지만 프로젝트 완료 기간이 얼마 남지 않은 시점에서 적절한가 논의가 필요하지 않을까 의견드립니다.
그리고 Storage에 이미지, 오디오와 같은 에셋 말고 JSON 파일을 올리는 것은 적절하지 않습니다.

### Firestore에 데이터 일괄 업로드

[useWriteBatchData.js](https://github.com/yamoo9/likelion-react/blob/10-firebase-service/firebase-db-storage/src/firebase/firestore/useWriteBatchData.js) 파일 코드를 참고해 JSON 파일을 읽어와 일괄 업로드 할 수 있습니다.
수업 시간에 일괄 업로드 한 파일인 [shopData.js](https://github.com/yamoo9/likelion-react/blob/10-firebase-service/firebase-db-storage/src/pages/DataBase/shopData.js) 코드를 참고해보세요. 😃
