### ISSUE TITLE
🛎️ for of 문의 사용처

### ISSUE THREAD

**Issue by shoveller** [yamoo9/likelion-FEQA#19]
[STD5 - 2주차 멘토링 4번째 질문](https://www.notion.so/2-1-7-f907e68b642c4cf0afa1b5be78d18dac)

```jsx
let list = [
  "01. 들어가며",
  "02. js의 역사",
  "03. 자료형",
  "04. 함수",
  "05. 배열",
]

let newList = [];
for(i = 0 ; i < list.length ; i++){
  newList.push(list[i].slice(4));
}

console.log(newList);
```

문자열 메소드 연습하며 풀어본 예제입니다

←———————————————-코드설명란——————————————————————>

임의의 배열 list 생성

빈 배열 newList 생성

반복문의 조건에 맞으면 임의의 배열에 4번째 단어부터 마지막 단어까지 넣어줌 

newList 출력

←———————————————-코드설명란——————————————————————>

배열은 for of문으로 바꿀수있다고 하던데(혹시 제가 잘못 알고있는지도 모르겠습니다) for of에 대해서도 다시 들을겸 변환이 가능한지 여쭙고 싶습니다

**Comment by yamoo9** [comment]
## 안내

재원 멘토님이 답변할 글이 많은 듯 하여 관련 질문에 대신 답변합니다. 😃

## for-of 문 활용

for문 대신, for-of 문을 사용하면 코드 작성이 더 쉽습니다.
아래 작성된 코드를 확인하세요.

```js
const newList = [];

for (let chapter of list) {
  newList.push(chapter);
}

console.log(newList); // ['01. 들어가며', '02. js의 역사', '03. 자료형', '04. 함수', '05. 배열']
```

## map 메서드 활용

위에서 다룬 것과 동일한 결과를 내려면 배열 객체의 map 메서드를 사용하는 것이 더 쉽습니다. 😆

```js
const newList2 = list.map(chapter => chapter); // ['01. 들어가며', '02. js의 역사', '03. 자료형', '04. 함수', '05. 배열']
```
