### ISSUE TITLE
[LAB-11] 상위 컴포넌트에서 하위 컴포넌트의 상태(state)를 변경하는 방법

### ISSUE THREAD

**Issue by to06109** [yamoo9/likelion-FEQA#190]
## 질문 작성자

최예송

## 문제 상황

- `components/Input/ImageUploadInput.jsx` : 이미지 파일을 업로드하는 input에 이미지를 넣으면 미리보기를 보여주는 컴포넌트입니다.
- `pages/UploadPage/UploadPage.jsx` : 이미지 업로드 페이지 입니다.

이미지 업로드 페이지에서  이미지 업로드 인풋 컴포넌트를 사용하고, 삭제버튼을 클릭하면 이미지 업로드 인풋 컴포넌트의 미리보기를 초기화하는 기능을 구현하는 중에 갈피를 잡지 못해서 질문드립니다. 

원래 제 코드에서는 `ImageUploadInput` 컴포넌트에서 file state를 관리하고 있고, 미리보기 이미지인 preview state는 file이 업데이트 될 때 결정되었습니다. 그리고 file state는 input에 파일이 들어왔을 때 업데이트 되었습니다. 
![image](https://user-images.githubusercontent.com/69625013/226790650-47d467f8-73de-4dee-ad0c-2cacf088fe57.png)
![image](https://user-images.githubusercontent.com/69625013/226790855-8f00a4bd-c1dd-4d9a-a876-457364371998.png)

이런 연관관계가 있어서 두 상태를 `ImageUploadInput` 컴포넌트에서 관리하도록 했었기 때문에 초기화 기능을 구현할 때 props drilling을 이용한 방법이 효율적이지 않다고 생각했는데, 이런 판단이 맞는지 궁금합니다!

일단은 UploadPage로 state를 끌어올려서(file, preview, onFileDrop을 props로 줬습니다) 미리보기를 지우는 것을 구현해 놓았는데 이 방법이 적절한 방법인지 궁금합니다. 이렇게하면 업로드 페이지의 코드가 너무 길어진다고 생각하는데 혹시 다른 방법이 있을까요?
(이 코드는 feature/upload-UploadPage 브랜치의 b07db436 커밋입니다. )

## 프로젝트 저장소 URL

- [깃허브 저장소](https://github.com/likeLion-FE4-RP11/Asparagus/tree/feature/upload-UploadPage)
- feature/upload-UploadPage 브랜치

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 해결

React가 제공하는 [useImperativeHandle](https://react.dev/reference/react/useImperativeHandle) 훅을 사용하면 하위 컴포넌트의 상태 변경을 상위 컴포넌트에서 수행할 수 있습니다. useImperativeHandle 훅은 [forwardRef](https://react.dev/reference/react/forwardRef) 고차 함수, [useRef](https://react.dev/reference/react/useRef) 훅과 함께 사용됩니다.

**하위 컴포넌트에 추가할 코드**

```jsx
useImperativeHandle(fileInputRef, () => ({
  initFilePreview,
}));

const initFilePreview = () => {
  setPreview(null);
  setFile(null);
};
```

**상위 컴포넌트에 추가할 코드**

```jsx
const imageInputRef = useRef(null);
  
const handleDelete = () => {
  imageInputRef.current.initFilePreview();
};
```

```jsx
<ImageUploadInput ref={imageInputRef} />
<DeleteButton style={deleteButtonStyle} onClick={handleDelete} />
```

구현된 결과는 다음과 같습니다.

![file-preview](https://user-images.githubusercontent.com/1850554/226805336-37e1c51e-f9ea-4b94-a3a8-12e4eec0c28a.gif)
