### ISSUE TITLE
[LAB-12] hover로 띄운 모달창 키보드로 접근

### ISSUE THREAD

**Issue by kyungseob7** [yamoo9/likelion-FEQA#191]
## 질문 작성자

변경섭

## 문제 상황

![Animation1](https://user-images.githubusercontent.com/119388929/226799516-ae6d42c4-6c0d-4683-8122-b85d6d32bf39.gif)

- 아까 멘토링 시간에 질문했던 내용입니다. hover를 할 시 모달창이 띄워집니다. 
- 모달이 띄워진 상태에서 마우스를 올려 놓고 할 경우에는 접근이 되지만
- 그렇지 않은 경우 키보드로 접근이 안됩니다.

키보드를 이용해서 접근을 하고 동작을 하고 싶은데 어떻게 하면 좋을까요? 검색 키워드도 알고 싶습니다!

## 프로젝트 저장소 URL

- 압축파일 남기겠습니다!

## 환경 정보

- 운영체제 (window)

**Comment by yamoo9** [comment]
## 문제 해결

StProfile 스타일 컴포넌트의 `:focus` 부분을 `&:focus-within`으로 변경하면 
초점 이동 되었을 때 모달 다이얼로그가 사라지지 않고 표시될 겁니다.

`:focus-within`에 대한 학습은 [MDN 문서](https://developer.mozilla.org/ko/docs/Web/CSS/:focus-within)를 참고하세요. 😃


```jsx
const StProfile = styled.div`
  // ...
  &:hover,
  &:focus-within {
    div {
      visibility: visible;
    }
  }
`;
```

결과는 아래와 같이 요구된 데로 키보드 접근이 가능합니다. 😄

![1](https://user-images.githubusercontent.com/1850554/226838279-b7fce8c9-70fb-409f-8008-3065b49b1462.gif)

**Comment by kyungseob7** [comment]
야무썬생님 감사합니다!
