### ISSUE TITLE
[LAB-12] React Router 리-렌더링 및 버벅거림

### ISSUE THREAD

**Issue by imironjin** [yamoo9/likelion-FEQA#194]
## 질문 작성자

임철진

## 문제 상황
App.jsx에 설정된 라우팅에 맞게 LandingPage에서 main버튼을 클릭 시, 
- 로그인이 되어있을 경우 MainPage로 다이렉트 되고, 
- 로그인이 안되어있을 때, main에 접근하려고 한다면 PrivateRoute.jsx 에 있는 코드를 토대로 LoginPage로 이동

이 과정에서 로그인이 되어있을 때, MainPage에 접근하게 되면, 버벅거림과 계속 리렌더링이 일어나게 되는데, 어느 부분이 문제인지 어떻게 해결하면 좋을지 해결법을 잘모르겠습니다.

![gif](https://user-images.githubusercontent.com/94541099/226805005-34b075fd-e9fd-4d52-9147-12f20c288a7f.gif)

## 환경 정보

- 운영체제 정보 (Windows)
- Node.js 정보 (v18.12.1)

**Comment by yamoo9** [comment]
## 문제 해결

아래 영상은 문제가 해결된 결과물을 보여 줍니다. 😊

https://user-images.githubusercontent.com/1850554/226902979-f938632d-dd3f-47e3-ae43-d1ac1b52bc21.mp4

문제 해결을 위해서는 아래 2개 파일을 수정해야 합니다. 참고 바랍니다. 

**useAuthState.js**

> isLoading 상태 부분 : `useState(false)` → `useState(true)`로 변경

```jsx
function useAuthState() {
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [user, setUser] = useState(null);

  useEffect(() => {
    setIsLoading(true);
    return onAuthStateChanged(
      auth,
      (currentUser) => {
        setUser(currentUser);
        setIsLoading(false);
      },
      (error) => {
        setError(error);
        setIsLoading(false);
      }
    );
  }, []);

  return useMemo(
    () => ({
      isLoading,
      error,
      user,
    }),
    [isLoading, error, user]
  );
}
```

**PrivateRoute.jsx**

```jsx
import { node } from 'prop-types';
import { Navigate } from 'react-router-dom';
import { useAuthState } from './firebase/auth';

const PrivateRoute = ({ children }) => {
  const { user, isLoading } = useAuthState();

  if (isLoading) {
    return <div>Loading</div>;
  }

  if (user) {
    return children;
  }

  return <Navigate to="/login" />;
};

PrivateRoute.propTypes = {
  children: node,
};

export default PrivateRoute;
```
