### ISSUE TITLE
[LAB-16] 프로젝트 성능 저하 질문

### ISSUE THREAD

**Issue by no-support** [yamoo9/likelion-FEQA#195]
## 질문 작성자

노지원

## 문제 상황
- 메인 페이지 첫 로드 시 속도가 너무 느립니다. 스타일 파일도 여러 번 호출되어 덮어씌워지는 듯한 느낌이 들고, 개인 컴퓨터의 문제일 수 있으나, 환경 설정 및 구현에 있어 성능을 많이 늦추는 요소가 있어서 그런 것인지 등 개선 방법을 알고 싶습니다.
![image](https://user-images.githubusercontent.com/50227723/226821328-107d6bc0-1694-4b6a-98ce-6c33de1dfdfa.png)

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소: https://github.com/LIKELION-REACT-16/Market-Karly/tree/develop
- develop 브랜치의 현재 소스를 첨부합니다.
[Market-Karly-develop.zip](https://github.com/yamoo9/likelion-FEQA/files/11037090/Market-Karly-develop.zip)

## 환경 정보

- 운영체제 정보 Windows10
- Node.js 정보 v18.13.0

**Comment by yamoo9** [comment]
## 문제 풀이

> 메인 페이지 첫 로드 시 속도가 너무 느립니다. 스타일 파일도 여러 번 호출되어 덮어씌워지는 듯한 느낌이 들고, 개인 컴퓨터의 문제일 수 있으나, 환경 설정 및 구현에 있어 성능을 많이 늦추는 요소가 있어서 그런 것인지 등 개선 방법을 알고 싶습니다.

## 빌드 결과

개발 중 화면 로딩 속도가 느려보일 수 있는데 이유는 빌드(최적화)가 수행되지 않았기 때문일 수 있습니다.
정확한 성능 진단을 위해 현재 개발된 프로젝트를 빌드한 결과를 살펴봐야 합니다.

```sh
npm run build
```

현재 프로젝트 빌드 결과를 보면 성능 느리지 않습니다. 99점! 😊

<img width="676" alt="" src="https://user-images.githubusercontent.com/1850554/226918212-d4ae73c7-8757-4537-8762-89c37dc0ee0e.png">

게다가 Performance 진단 결과 또한 DOMContentLoaded 0.3s, Load 0.4s 정도 나올 정도로 빠릅니다.

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/1850554/226921621-b7c6494d-83d8-421a-8fa1-fcf37ef0cb5c.png">

## 성능 진단 시 TIP!

React DevTools 확장 설정에서 사이트 엑세스 설정 값을 "클릭 시"로 변경하면 
성능 진단 과정에서 개발 도구 리소스는 제외되어 성능을 보다 정확하기 진단할 수 있습니다.

<img src="https://user-images.githubusercontent.com/1850554/226918944-c28af7d8-4673-4b6c-9aba-05d16853f54d.png" alt width="600" />
