### ISSUE TITLE
[LAB-11] 로그인 페이지 라우팅

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#197]
## 질문 작성자

오승택

## 문제 상황
저희 시안부터 보여드리겠습니다. 첫번째로 로그인 페이지 입니다.
<img width="740" alt="image" src="https://user-images.githubusercontent.com/109938280/226826644-9a1d7d07-89cb-4bcb-a57b-71aa9a41827a.png">

두번째 사진은 저희 메인페이지입니다. 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/109938280/226826762-4e40f3c9-a0a6-403b-8371-d2da9db456bc.png">

보시다시피 로그인 페이지와 메인페이지에 헤더,푸터가 각각 같지가 않아서 라우팅을 어떤식으로 진행을 해야할지 감이 안와 질문을 드립니다.

현재 App.js 파일에서 BaseLayout 이 전부 다 Route 를 감싸구 있습니다 
![image](https://user-images.githubusercontent.com/109938280/226827232-c1747b47-b8aa-4780-908a-d216eadc5964.png)

. BaseLayout 안에는 Header와 main , Footer 로 이루어져 있습니다.
![image](https://user-images.githubusercontent.com/109938280/226827279-9758e58e-d86a-4634-b85c-9e0dec46055b.png)

## 프로젝트 저장소 URL

- https://github.com/likeLion-FE4-RP11/Asparagus
- 브랜치 : feature/login-google-facebook
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
@5wintaek 님. 질문한 내용과 유사한 질문이 있었고 답변한 바 있습니다. 
https://github.com/yamoo9/likelion-FEQA/issues/188#issuecomment-1478613257 글을 참고해서 헤더, 푸터 표시 여부를 라우트에 따라 적용해 보세요. 😊
