### ISSUE TITLE
[LAB-14]  navigate로 여러 state 넘기는 과정에서의 오류 

### ISSUE THREAD

**Issue by hamjongseok** [yamoo9/likelion-FEQA#199]
## 질문 작성자

함종석 

## 문제 상황

<img width="477" alt="스크린샷 2023-03-22 오후 4 40 40" src="https://user-images.githubusercontent.com/82271040/226833235-302da0bb-4154-48d4-b8cc-bf963d6fa4c2.png">
<img width="477" alt="스크린샷 2023-03-22 오후 4 43 15" src="https://user-images.githubusercontent.com/82271040/226833741-7698367d-7433-41b4-b620-d9cba21937fa.png">

특정 조건에서 nacigate로 결과 페이지로 이동을할때 result의 값을  넘겨주고 
location을 이용하여 값을 받은후 정상적으로 코드가 작동을 하였습니다. 
하지만 기능구현에 있어서 부 모 리스트 , 두가지의 배열을 더 넘겨줘야 해서

 
<img width="477" alt="스크린샷 2023-03-22 오후 4 44 16" src="https://user-images.githubusercontent.com/82271040/226833919-c9149d1c-100a-4bf0-befd-5f218ba41707.png">

이렇게 넘기고 

<img width="477" alt="스크린샷 2023-03-22 오후 4 46 04" src="https://user-images.githubusercontent.com/82271040/226834315-2159139a-d8e1-483f-a1ee-875996bcd1ce.png">
이렇게 받고 찍어보면 
parentList 1,2 두개다 무시가되는것인지 

<img width="477" alt="스크린샷 2023-03-22 오후 4 46 51" src="https://user-images.githubusercontent.com/82271040/226834492-0e38097d-5347-48a4-b599-70beaf378008.png">

result값이 두개다에 들어가는 현상이 발생하였습니다. 
navigate: parentList1 을 하면 List1이 잘들어가는데 result만 넣게되면 다른 값에도 result의 값만 들어갑니다.. 

혹 구조분해할당을 해야하는건가? 싶어서 해도 되지않더라구요.. 

도저히 원인을 모르겠습니다.. 아니면 저 값들을 넘겨받을수 있는방법은 무엇이있을까요 ? 

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
@hamjongseok 님 아래처럼 `state`를 객체로 설정해 값을 넘겨보세요. 😊

```jsx
navigate(
  '/fattail-calcResult', 
  { 
    state: { 
      result, 
      parentList1, 
      parentList2 
    } 
  }
)
```

`state`에서 데이터를 추출할 때는 다음과 같이 사용할 수 있습니다.

```jsx
const  { result, parentList1, parentList2 } = location.state;
```

**Comment by hamjongseok** [comment]
아앗 ..!!!!!!! {} 하나 차이였네요 생각하지못했습니다 ㅠㅠㅠㅠ 감사합니다..........
