### ISSUE TITLE
🛎️ npm start 명령 실행 시 문제가 발생했어요.

### ISSUE THREAD

**Issue by najeeho9** [yamoo9/likelion-FEQA#2]
## 문제 상황

`package.json`에 등록된 `start` 명령을 실행할 때 오류 메시지가 아래와 같이 출력됩니다.

<img width="969" alt="npm start 오류 스크린샷" src="https://user-images.githubusercontent.com/107005120/209681372-4695f89a-b338-4c66-936a-fcab2676c7cf.png">

package.json 코드

```json
{
  "scripts": {
    "start": "run-p watch:* serve"
    "dev": "run-p watch:* serve:dev"
  }
}
```

## 환경 정보

- macOS 13.1(22C65)
- Node.js v16.15.0

**Comment by yamoo9** [comment]
**Failed to parse JSON data.** 
오류 메시지로 보아 JSON 문법 오류인 것으로 보입니다.

**Note: package.json must be actual JSON, not just JavaScript.** 
`package.json` 파일은 반드시 JSON 문법에 맞게 작성되어야 합니다.

`package.json` 파일에 문법 오류가 없는 지 살펴보길 바랍니다. 😃
아래 그림처럼 `package.json` 파일에 문법 오류가 있다면 정상적으로 명령이 실행되지 않으니까요.

<img width="702" alt="package.json 문법 오류" src="https://user-images.githubusercontent.com/1850554/209685608-fb9f5e3a-fc46-4a54-8d54-2b336b7f1b31.png">

> 💡 [ESLint 확장](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)을 사용한다면 오류 여부를 바로 확인할 수 있어 개발자 경험(DX)이 크게 향상됩니다.
<br/>
