### ISSUE TITLE
[LAB-4] portal을 사용하는데 왜 z-index를 조절해야되는지 이해가 안갑니다

### ISSUE THREAD

**Issue by SeoMiYoung** [yamoo9/likelion-FEQA#201]
## 질문 작성자
서미영

## 문제 상황
안녕하세요. LAB4의 서미영입니다.
![image](https://user-images.githubusercontent.com/112063987/226849945-e77fbce7-b125-4fd4-8748-6f66197ca1da.png)
저는 이번에 위의 사진에 나와있는 사용자가 디테일 페이지에서 '후기 작성하기', '문의하기'버튼을 눌렀을 때 뜨는 팝업창을 구현했습니다.

수업시간에 portal에 대해서 잠깐 선생님께서 언급했던 기억이 나서, 이번에 이 팝업창을 portal을 사용해서 구현해 보기로 했습니다.
참고로 팝업창을 구현한 폴더는 components/ProductDetailPopUp입니다.

저는 portal에 대해서는 자세히 모르지만, 
루트 내부가 아니라 루트 바깥쪽에서 마운트하고 싶을 때 portal을 쓴다고 알고있습니다.
그래서,
public/index.html에 
![image](https://user-images.githubusercontent.com/112063987/226874897-2dcefa14-ecdc-48bd-b644-24689b0ed7bb.png)
위의 사진에서 22번째의 리액트 루트밑에, 23번째 줄처럼 ```<div id="detailPortal"></div>``` 를 추가했고,
ProductDetailPopUpLayout.jsx에서, react-dom의 createPortal을 사용해서
id="detailPortal"인곳에 팝업창이 마운트되도록 연결해줬습니다.

그랬더니, 예상했던것처럼
![image](https://user-images.githubusercontent.com/112063987/226875968-80f9a201-b2e5-41e9-bf8d-577126747752.png)
```<div id="<%= rootId %>"></div>```가 아닌,
```<div id="detailPortal"></div>```에 팝업창이 들어가있는 걸 개발자 도구를 통해 확인할 수 있었습니다.
(팝업창을 혹시 확인하려고 하신다면, npm start => http://localhost:3000/detail => '문의하기'버튼 클릭)

지금부터 portal에 대한 궁금증이 생긴 과정을 설명드리겠습니다.
저희 팀은 ```<div id="<%= rootId %>"></div>```안에 ```components/DarkFilter```라는 공용 컴포넌트를 넣어줬는데요,
components/DarkFilter/DarkFilter.module.scss를 보시면, 다크필터의 z-index가 1100으로 설정된걸 확인할 수 있습니다.
![image](https://user-images.githubusercontent.com/112063987/226878151-d145d311-66c8-43f0-9ae5-a674f2929ef3.png)

만약에 팝업창(ProductDetailPopUp)에 z-index를 1100보다 높게 설정해주지 않는다면,
![image](https://user-images.githubusercontent.com/112063987/226878350-59b03749-2ae5-4f5e-84e6-5b3daa7168b6.png)
위 사진처럼 다크필터 밑에 팝업창이 위치하게 됩니다.

그래서 저희는 ProductDetailPopUp.module.scss에서 팝업창의 z-index를 1200으로 설정해줌으로써, 다크필터보다 팝업창이 더 위에 위치하게끔 만들었습니다.

여기서 궁금증이 생겼는데요, 저는 팝업창을 
```<div id="<%= rootId %>"></div>```가 아닌,
```<div id="detailPortal"></div>```에 넣어줬으므로,
팝업창은 ```<div id="<%= rootId %>"></div>```이 안에 있는 것들에 영향을 받지 않는다고 생각했습니다.

그러나 다크필터로 봤을 때 서로 영향을 받지 않는 건 아닌 것 같다는 생각이 들었습니다.

그래서 질문을 간단히 정리하자면 두가지 입니다.
1. 리액트 루트(```<div id="<%= rootId %>"></div>```) 내부가 아닌 외부에 새로운 루트를 통해 팝업창을 띄우게 되었을때, 각각의 루트는 서로 영향을 받는지 궁금합니다. (서로 영향을 안받는다고 생각했는데, 다크필터 적용을 통해 서로 영향을 받는 것 같아서 질문드립니다)
2. portal을 쓰긴 썼는데, 사실 뭐가 그렇게 유용한지 아직도 잘 모르겠습니다. 간단히라도 설명해주실 수 있을까요?

답변해주시면 감사하겠습니다!

## 프로젝트 저장소 URL
https://github.com/SeoMiYoung/project-repo
브랜치 정보: feat/#96

## 환경 정보
운영체제 정보: 윈도우
Node.js 정보: v18.14.0

**Comment by yamoo9** [comment]
## Portal 쓰임새에 대한 이해

React 공식문서 [Rendering a modal dialog with a portal](https://react.dev/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal)에서 제공하는 [Portal 예제](https://codesandbox.io/s/bmnxf0?file=/App.js&utm_medium=sandpack)를 확인해보세요.

App 컴포넌트 코드를 보면 clipping-container 클래스 스타일이 반영된 div 요소 내부에 2개의 컴포넌트가 포함되어 있습니다.

```jsx
function App() {
  return (
    <>
      <div className="clipping-container">
        <NoPortalExample  />
      </div>
      <div className="clipping-container">
        <PortalExample />
      </div>
    </>
  );
}
```

clipping-container 클래스 스타일 코드를 살펴보면 내부에 position, overflow 속성이 설정되어 있습니다.
이 설정으로 내부에 포함된 Modal 컴포넌트는 화면에서 잘려 표시될 수 있습니다.

```css
.clipping-container {
  /* ... */
  position: relative;
  overflow: hidden;
}
```

예상대로 NoPortalExample 컴포넌트는 화면에서 잘려 표시됩니다.
반면 ProtalExample 컴포넌트는 스타일에 영향을 받지 않고 정상적으로 화면 상단에 표시됩니다.

![](https://user-images.githubusercontent.com/1850554/226890234-30a3fa58-cad5-4433-afea-863c5df5897b.gif)

ProtalExample 컴포넌트는 Portal을 사용하였기에 position, overflow 스타일 설정과 상관 없이 자유롭게 화면 위에 표시되는 것입니다.
즉, **Portal을 사용하는 이유는 재사용성이 높은 컴포넌트인 만큼 특정 상황에서도 정상 작동되도록 구현할 수 있기 때문입니다.**

```jsx
function PortalExample() {
  const [showModal, setShowModal] = useState(false);
  return (
    <>
      <button onClick={() => setShowModal(true)}>
        Show modal using a portal
      </button>
      {showModal && createPortal(
        <ModalContent onClose={() => setShowModal(false)} />,
        document.body
      )}
    </>
  );
}
```

## 질문에 대한 답변

### 답변 1.

> 리액트 루트(`<div id="<%= rootId %>"></div>`) 내부가 아닌 외부에 새로운 루트를 통해 팝업창을 띄우게 되었을때, 각각의 루트는 서로 영향을 받는지 궁금합니다. (서로 영향을 안받는다고 생각했는데, 다크필터 적용을 통해 서로 영향을 받는 것 같아서 질문드립니다)

리액트 루트 내부에 position, overflow 등 스타일 속성이 특정 요소에 적용되었다면? Portal을 사용하지 않을 경우 잘려 표현될 수 있습니다. 하지만 @SeoMiYoung 님은 이를 경험하지 못했습니다. 그런 상황의 스타일이 루트 내부에 없었기 때문입니다. 만약 추후 유지보수 관점에서 position, overflow 등 스타일 속성이 특정 요소에 설정된다면 어떻게 될까요? 필연적으로 잘려 표현될 겁니다.

이런 **문제를 예방하기 위해 Portal을 사용하는 것**입니다. 😊

### 답변 2.

> portal을 쓰긴 썼는데, 사실 뭐가 그렇게 유용한지 아직도 잘 모르겠습니다. 간단히라도 설명해주실 수 있을까요?

앞서 작성한 "Portal 쓰임새에 대한 이해"에 대해 읽었다면 잘 이해되지 않았을까 싶습니다.

**Comment by SeoMiYoung** [comment]
답변 감사합니다.
나중에 그런 상황을 만나봐야 더 와닿을 것 같지만, 무슨 느낌인지 이해했습니다.
야무쌤께서 position, overflow등 스타일 속성이 특정 요소에 적용되었을때 Portal을 사용하지 않았을 경우 잘려 표현될 수 있다고 하셨는데요, 
저도 position속성을 사용했는데..(position:absolute) 이것만 가지고는 이런 상황을 경험할 수 없는건가요?
지금 잘려 표현될 수 있는 경우는 position과 overflow가 동시에 적용되었을때죠?

**Comment by yamoo9** [comment]
@SeoMiYoung 님

이후 상황은 React가 아니라, CSS 스타일에서 공부한 포지셔닝(Positioning)과 관련 있습니다.
position 설정(static 제외)과 z-index 설정, overflow 설정에 따라 잘려 표현되는 경험을 가질 수 있습니다.
**웹 브라우저에 렌더링 된 이후부터는 React를 벗어나 HTML, CSS의 이슈가 되는 것입니다.** 🤔

**Comment by SeoMiYoung** [comment]
야무쌤 정말 친절한 답변 감사합니다!!
