### ISSUE TITLE
[LAB-16] Prettier 적용 문제

### ISSUE THREAD

**Issue by donghyeon413** [yamoo9/likelion-FEQA#202]
## 질문 작성자

최동현

## 문제 상황

Pretttier 적용 문제

Pretttier 적용이 안되는 원인 파악과 해결이 되지 않아 선생님들께 도움을 받고 싶어서 질문 올립니다.

- 해결을 하기 위해 시도한 방법

1. 재설치
npm i prettier -D -E 와
npm i eslint-plugin-prettier eslint-config-prettier -D
설치
설치 후 다시 확인한 결과 설치한 것들의 버전만 바뀌고 Prettier 적용이 되지 않아 원복 했습니다.

2. 세팅 변경
Settings에서
format on save 검색 후
체크해제되어 있던 버튼을 체크했습니다.

세팅 변경 적용 이후
vs 코드 종료 후 재실행 하고
다시 저장했을 때 (첫 번째 저장할 때)
단 한 번만 Prettier가 작동이 되고
이후에는 Prettier가 작동이 되지 않습니다.

팀원들은 Prettier 문제없이 사용 중인데
저만 Prettier 가 안되는 이유가 무엇인지와 해결 방안을 제시해 주셨으면 합니다

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
- https://github.com/LIKELION-REACT-16/Market-Karly

- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.

- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
- [dong.zip](https://github.com/yamoo9/likelion-FEQA/files/11039118/dong.zip)

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Windows
- Node.js 정보 (예: v16.14.0)
- v18.15.0
- 라이브러리 정보 (예: React v18.0.2)
- 모르겠습니다
<img width="340" alt="image" src="https://user-images.githubusercontent.com/102843694/226880684-f48311c1-03e7-490e-9a01-53ffe250daf0.png">

**Comment by yamoo9** [comment]
## 문제 원인

화면을 공유해 확인한 결과, **VSCode 글로벌 설정(settings)에 에디터 기본 포멧터 설정이 없었기 때문**입니다.
글로벌 설정으로 기본 포멧터를 Prettier로 사용하도록 구성하니 정상적으로 자동 포멧팅 되는 것을 확인했습니다. ([참고](https://github.com/prettier/prettier-vscode#default-formatter))

```json
"editor.defaultFormatter": "esbenp.prettier-vscode"
```

<br />

~@donghyeon413 님 해당 이슈는 사용자 개발 환경에 따라 달라질 수 있어 직접 화면을 공유 확인한 후 답변해야 합니다.
내일 오전(3. 23) 8시 쯤 디스코드에 접속해 같이 확인해보면 어떨까 합니다. 피드백 부탁드립니다. 😊~
