### ISSUE TITLE
[LAB-12] Firefox 브라우저 svg 이미지가 나오지 않는 현상

### ISSUE THREAD

**Issue by imironjin** [yamoo9/likelion-FEQA#203]
## 질문 작성자

임철진

## 문제 상황

- 크로스 브라우징을 확인하던 도중 **Firefox** 브라우저에서 **Chrome, Edge** 브라우저와는 다르게 svg 이미지가 나오지 않는 현상이 발생하여 질문드립니다. 브라우저 콘솔창에는 별다른 오류도 나오지 않아 문제가 무엇인지 잘 모르겠습니다. 
- Firefox 브라우저 업데이트도 한 상황입니다. 
![image](https://user-images.githubusercontent.com/94541099/226921324-ca3a05f1-f47d-42d3-ad2a-cc0bbbf4be70.png)

## 프로젝트 저장소 URL

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/11040126/src.zip)

## 환경 정보

- Windows

**Comment by yamoo9** [comment]
## 문제 원인

**Firefox 웹 브라우저**는 다른 웹 브라우저와 달리, **SVG 파일에 문법 오류가 존재할 경우 화면에 정상적으로 표시하지 않습니다.**

<img width="1274" alt="" src="https://user-images.githubusercontent.com/1850554/227053466-7f0f1b20-8886-4461-a669-a112b9e94e8c.png">

프로젝트에 사용 중인 `sprite.svg` 파일의 맨 아래 세미콜론(`;`)이 삽입되어 있기에 화면에 표시되지 않았던 것입니다. 😱

<img width="880" alt="" src="https://user-images.githubusercontent.com/1850554/227052683-b0b44ac2-67ac-43db-8a1b-8f996fc2bd3c.png">

## 문제 해결

`sprite.svg` 파일에서 세미 콜론(`;`)을 삭제하면 Firefox 웹 브라우저에서 정상적으로 SVG 이미지가 표시됩니다. 😉

<img width="1274" alt="" src="https://user-images.githubusercontent.com/1850554/227053357-ed86e2f9-6118-4e0f-850b-e396d2cd8b2c.png">

**Comment by imironjin** [comment]
감사합니다!!👍
