### ISSUE TITLE
[LAB-11] 타이틀 컴포넌트 쏠림 현상 (CSS 레이아웃 이슈)

### ISSUE THREAD

**Issue by kyuran6** [yamoo9/likelion-FEQA#209]
## 질문 작성자

김진희

## 문제 상황

- 컴포넌트를 불러와서 메인 페이지 배치를 하고 있는 상황입니다
경로: src/pages/Home/Homepage

- CategoryTitle 컴포넌트가 뒤로 쏠려보이는 현상이 있습니다.
경로 : src/components/CategoryTitle

- 100%로 볼때도 배치가 이상하고

<img width="1425" alt="2023-03-22__16 43 20" src="https://user-images.githubusercontent.com/119389578/227113426-9857fea9-740c-4b32-bafa-8d2f33e0319a.png">

- 축소시에도 저렇게 뒤로 빠져서 붙어있습니다.
- 카테고리 컴포넌트를 재사용한 RecentImageTitle도 동일합니다.
- 계속 수정을 해봤지만 해결이 되지않아 질문합니다.

## 프로젝트 저장소 URL

- [공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.](https://github.com/likeLion-FE4-RP11/Asparagus)
- feature/main-MainSwiper
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
[Asparagus 2.zip](https://github.com/yamoo9/likelion-FEQA/files/11047548/Asparagus.2.zip)

## 환경 정보

- macOS
- Node.js v19.7.0
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## CSS 레이아웃 이슈

CategoryTitle 컴포넌트 요소가 한쪽으로 쏠린 이유는 너비를 100vw로 설정했기 때문입니다.
외부 컨테이너도 아니고 내부에 포함된 요소가 뷰포트 너비(viewport width)를 모두 사용하는 경우는 적절한 스타일이 아닙니다.

![](https://user-images.githubusercontent.com/1850554/227371683-c62a3c38-2d46-424b-99d9-590220f45cd5.gif)

Category 컴포넌트 요소에 왼쪽 마진 값을 고정 값으로 설정한 것 또한 적절한 레이아웃(배치)가 아닙니다.

![](https://user-images.githubusercontent.com/1850554/227371690-204b26b1-5ba5-41cb-917d-e71bbc6af864.gif)

각 컴포넌트 내부에 포함된 스타일이 문제 원인입니다.

<img width="1242" alt="" src="https://user-images.githubusercontent.com/1850554/227371295-e79826d1-d6e7-407e-ab09-348bbb6864f2.png">

## 문제 해결

CSS 레이아웃에 대한 이해와 활용 능력을 키워야 합니다. 😥
그리고 구현해야 할 디자인 시안을 함께 제공해야 디자인 분석 후 레이아웃 방법에 대해 제시할 수 있습니다.
슬비쌤(@seulbinim)과 함께 공부 했던 이전 학습 자료를 다시 살펴보시길 바랍니다. 😊

**Comment by kyuran6** [comment]
자세한 답변 정말 감사합니다!! 🥺👍
