### ISSUE TITLE
[LAB-10] firebase-tools 글로벌 설치가 안됩니다. (NPM 권한 이슈)

### ISSUE THREAD

**Issue by hyunzsu** [yamoo9/likelion-FEQA#212]
## 질문 작성자

현지수

## 문제 상황

- firebase 설치를 위해 'npm i firebase'를 터미널에 입력했습니다.
- firebase 가 설치가 되지 않은 것 같아서 `sudo npm install -g firebase-tools`도 입력하여 시도했습니다.
- firebase 설치 확인을 위해 `firebase --version` 또는 `firebase login`을 입력했을 때 정상동작하지 않습니다.
- 터미널에서 firebase를 입력했을 때 command not found의 오류가 발생합니다.
- 아래 오류 메세지 첨부하였습니다.
- .env 파일 세팅도 팀원과 동일하게 했으나 연결되지 않는 것 같습니다. 

<img width="1159" alt="스크린샷 2023-03-23 오후 5 03 25" src="https://user-images.githubusercontent.com/108773199/227140388-0fc150f4-8513-4434-b317-3a76457e9e5d.png">

<img width="576" alt="스크린샷 2023-03-23 오후 4 53 57" src="https://user-images.githubusercontent.com/108773199/227138779-f7388462-fe6b-430b-bbc9-b886ec344c43.png">

## 프로젝트 저장소 URL

- 공개

- https://github.com/likelion-lab10/godlife

## 환경 정보

- 운영체제 정보 macOS
- Node.js 정보 v18.14.1
-  "firebase": "^9.17.2",
    "react": "^18.2.0",

**Comment by yamoo9** [comment]
## 문제 상황

firebase-tools 설치 후, 정상적으로 확인되지 않습니다.

<img width="595" alt="" src="https://user-images.githubusercontent.com/1850554/227398221-94a517eb-dd92-4364-9f95-cc3449c6f86e.png">

## 문제 해결

해당 문제는 [NPM 권한 이슈](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)로 발생한 현상입니다. 
NPM 권한 문제 해결이 어려운 경우, [Firebase CLI](https://firebase.google.com/docs/cli?hl=ko#mac-linux-auto-script) 공식 문서에서 안내한대로 자동 설치 스크립트 명령으로 설치합니다.

```sh
curl -sL https://firebase.tools | bash
```

<img width="864" alt="" src="https://user-images.githubusercontent.com/1850554/227402262-676f0738-3ba1-40e9-b92a-249d9cc0ab36.png">

## 참고

- [Resolving EACCES permissions errors when installing packages globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)
- [Firebase CLI 참조](https://firebase.google.com/docs/cli?hl=ko#mac-linux-auto-script) [*](https://stackoverflow.com/a/72789116)
- [[Fixed] Firebase NPM errors](https://weekendprojects.dev/posts/fixed-firebase-npm-errors/)

<br />

~@hyunzsu 님 이 문제는 화면 공유를 통해 직접 확인해보는 것이 좋겠습니다. 🤔
내일 오전 8시 이후 연락 드릴께요. 가이드 방에서 안내 드린 후, 관련 이슈 내용은 추후 정리하겠습니다.~
