### ISSUE TITLE
[LAB-5] 버튼 클릭시 모달창 띄우는 방법 질문입니다.

### ISSUE THREAD

**Issue by binwoonki** [yamoo9/likelion-FEQA#215]
## 질문 작성자
빈운기

## 문제 상황
버튼 클릭하면 뜨는 모달창 하려는데 이 모달창이 컴포넌트입니다. (페이지가 아닙니다.) 
감이 전혀 안 잡혀서 그러는데 로직이나 구현방식에 대해서 방향성 제시좀 부탁드리겠습니다.
<원하는 상황 시연>
![Modal](https://user-images.githubusercontent.com/119389337/227230245-f68a06de-9198-4138-bef7-3e90f78a6369.gif)

(위에 gif 는 성공한게 아니라,,제가 구현하고 싶은 화면입니다.) 
로그인 버튼 클릭 시 보이는 UI 가 모달창으로 나오게 하려고 합니다.

## 프로젝트 저장소 URL
https://github.com/React-Project-lab5/React-Project-lab5
- develop branch

<img width="405" alt="스크린샷 2023-03-23 오후 11 14 22" src="https://user-images.githubusercontent.com/119389337/227231754-f1bdfbfe-2f3f-49cf-9197-57b43fdd0f43.png">

<img width="357" alt="스크린샷 2023-03-23 오후 11 14 26" src="https://user-images.githubusercontent.com/119389337/227231731-e7609583-7839-46ea-ab3a-1512e1d63b60.png">

<img width="344" alt="스크린샷 2023-03-23 오후 11 14 32" src="https://user-images.githubusercontent.com/119389337/227231717-de61cb43-aabc-41a6-b81c-20b1b36d0bd5.png">

<img width="416" alt="스크린샷 2023-03-23 오후 11 14 38" src="https://user-images.githubusercontent.com/119389337/227231702-3b6e00d9-a2d4-4592-b4de-a429b7a3f6df.png">

## 환경 정보

- 운영체제 정보  macOS
- Node.js 정보 v18.12.1
- 라이브러리 정보 React v18.0.2

**Comment by yamoo9** [comment]
##  모달 다이얼로그 구현 방식

React 수업 시간에 다룬 [Dialog 컴포넌트](https://euid.notion.site/0df1228fc4ce449f8eacb8a5e292b9bd#57df80608334470c841e66bf6b62b246) 학습 자료를 리마인드 하세요. 🥹

## 모달 다이얼로그 방향성

모달 다이얼로그 구현 질문(https://github.com/yamoo9/likelion-FEQA/issues/214#issuecomment-1481987207) 답변에서 다룬 모달 다이얼로그 코드를 분석해보세요. 😃

**아래 내용은 답변 내용 중 일부입니다.**

리액트 Props 전달 방법으로 상위 ←→ 하위 컴포넌트 간 상태 공유 및 상태 업데이트 방법을 사용해야 합니다. 
React 공식 문서 [Passing Event handlers as props](https://react.dev/learn/responding-to-events#passing-event-handlers-as-props)을 참고하세요.

![](https://user-images.githubusercontent.com/1850554/227378770-8a0ea7b0-2b23-48bc-b31b-740275e96fa9.gif)
