### ISSUE TITLE
[LAB-11] Firebase 소셜로그인 (Feat.Google) 

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#217]
## 질문 작성자

오승택

## 문제 상황

안녕하세요 LAB11 오승택 입니다

API 문서를 보고 구글 로그인 버튼에 이벤트를 주어 로그인이 완성되게 기능을 구현하였습니다. 하지만 문제점이 있습니다.

1. 사용자가 첫 Google 로그인 시도 후 다시 Google 로그인을 하였을 때 자동으로 로그인이 진행이됩니다.
**해결했던방법**
-> 캐시 및 쿠키를 지우고 난 후 다시 Google 로그인을 시도를 해봤는데 다시 자동으로 로그인이 됩니다.

![123](https://user-images.githubusercontent.com/109938280/227255828-7c3cdadd-b452-4022-b81a-3a467a00c8af.gif)

2. 사용자가 Google 버튼을 눌러 로그인을 완료한 후 firebase authentication 에 아이디와 비밀번호가 저장이 되지 않습니다. 혹시 이 문제는 useEffect를 사용하지 않아서 그런건가요 ? 

![image](https://user-images.githubusercontent.com/109938280/227257326-fbc203a6-0ccc-46ef-938c-486b8ff47b88.png)

![image](https://user-images.githubusercontent.com/109938280/227256316-b2f3eb6b-401a-41b5-a7e1-b9337c4d7f9a.png)

## 프로젝트 저장소 URL

- https://github.com/likeLion-FE4-RP11/Asparagus
- feature/login-google-facebook
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (macOS)
- Node.js 정보 (예: v18.12.1)
- 라이브러리 정보 (React v18.2.0)

**Comment by yamoo9** [comment]
## 답변 1. Firebase 인증은 기본적으로 지속됩니다.

> 사용자가 첫 Google 로그인 시도 후 다시 Google 로그인을 하였을 때 자동으로 로그인이 진행이됩니다.

**Firebase는 기본적으로 웹 브라우저 윈도우가 닫혀도 인증 상태가 유지됩니다.** 즉, 문제가 아닙니다. 🥹

인증 상태 지속성을 원하지 않을 경우, Firebase 인증 상태가 지속되는 방식을 지정할 수 있습니다. 
로그인 한 사용자가 직접 로그아웃 할 때까지 로그인 상태를 유지할 지, 브라우저 윈도우가 닫힐 때 로그아웃 할 지 
또는 페이지를 새로고침 하면 로그아웃 할 지 여부를 결정할 수 있습니다.

설정 방법은 제공한 학습 자료 [Firebase 인증 지속성](https://euid.notion.site/Firebase-7ee3583c3d5b4b29b1e03106b1a93567#91d03934dc754610a5ca21e75f7364ce)를 확인해 적용해보세요.

## 답변 2. 아이디 저장은 Firebase 인증과 관련이 없습니다.

> 사용자가 Google 버튼을 눌러 로그인을 완료한 후 firebase authentication 에 아이디와 비밀번호가 저장이 되지 않습니다. 혹시 이 문제는 useEffect를 사용하지 않아서 그런건가요 ?

Firebase 인증은 회원가입 또는 로그인 인증 과정에만 사용되며 인증 사용자의 고유 식별자(uid), 이메일(email)과 같은 정보를 제공합니다.
**비밀번호와 같이 민감한 개인 정보는 Firebase 콘솔에서 확인할 수 없습니다. (보안 이슈)**

<img width="964" alt="" src="https://user-images.githubusercontent.com/1850554/227386471-864f3fd1-6c91-41a8-8009-0834543bbda8.png">

그렇다면 회원 가입 시 제공 된 아이디(id), 사용자 이름(displayName)과 같은 정보는 어디에 저장해야 할까요?
Firestore 데이터베이스에 저장되어야 합니다. 즉, **회원가입 인증 → 데이터베이스(사용자 정보)에 저장되어야 합니다.**

<img width="1549" alt="" src="https://user-images.githubusercontent.com/1850554/227386566-00672956-0766-4b44-8a49-126c19a5fc2b.png">

<br />

수업 시간에 다룬 [useCreateAuthUser](https://github.com/yamoo9/likelion-react/blob/10-firebase-service/firebase-db-storage/src/firebase/firestore/README.md#usecreateauthuser) 훅이 그러한 일을 수행합니다. 
훅을 사용하는 대신 직접 "회원가입 인증 → 데이터베이스 저장"을 구현 하려면 [useCreateAuthUser 내부 로직](https://github.com/yamoo9/likelion-react/blob/10-firebase-service/firebase-db-storage/src/firebase/firestore/useCreateAuthUser.js#L20-L45)을 참고하세요.

## 레퍼런스

- [Google을 사용하여 인증](https://firebase.google.com/docs/auth/web/google-signin?hl=ko)
- [Firestore에 문서 설정](https://firebase.google.com/docs/firestore/manage-data/add-data?hl=ko#set_a_document)

**Comment by 5wintaek** [comment]
답변 감사합니다!!!!
