### ISSUE TITLE
🛎️ 코딩 테스트 실력을 키울 수 있는 팁이 있나요?

### ISSUE THREAD

**Issue by shoveller** [yamoo9/likelion-FEQA#22]
[STD5 - 2주차 멘토링 7번째 질문](https://www.notion.so/2-1-7-f907e68b642c4cf0afa1b5be78d18dac)

코딩 테스트 실력을 키울 수 있는 팁이 있는지 궁금합니다. 
현재는 혼자 문제를 풀어보고 다른 사람의 풀이를 보며 더 효율적인 코드가 있으면 따로 그 코드를 공부해보고 있는데, 이렇게 무작정 문제를 풀어보는 게 좋은 것인지 아니면 코딩 테스트용 문제 풀이 스킬을 알려주는 강의나 책을 참고하는 것이 좋을지 고민입니다. 🥲

**Comment by shoveller** [comment]
안녕하세요. 익명의 질문자님!
이미 효율적인 코드를 찾는 연습을 하고 계시다니 대단하시네요.
어쩌면 이미 상당한 수준에 오르셔서 제가 더 조언할 거리가 없을지도 모르겠습니다.
저도 코딩테스트가 어렵습니다.
하지만 다른 분들도 보실 수 있도록 제가 시행착오를 거쳐 체득한 테크닉을 몇가지 소개해 드리자면...

0. 코딩테스트는 실무 코딩과 전혀 다른 프로그래밍 장르라는걸 이해해야 합니다.
    - 실무에서는 라이브러리 함수 호출 한번으로 끝날 구현을 하나하나 이해해야 합니다(자바스크립트같은 고급언어 사용자에게는 특히 생소한 부분).
    - 대부분의 문제들이 메모리를 덜 쓰는 방식에 집중하므로 코딩테스트 전용 코딩 방식을 익혀야 합니다.
        - 변수 이름을 한글로 쓰면 도움이 됩니다.
        - `Array.prototype.map`, `Array.prototype.reduce` 대신 `for ~ of`, `for ~ in` 등의 반복문을 사용해야 합니다.

1. 정석적인 학습 루트가 있습니다.
코딩테스트에는 난이도 별 학습단계가 있습니다. 
반드시 이 단계를 따르셔야 중간에 좌절하지 않습니다.
    - [반복문](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Loops_and_iteration) -> 배열 메소드([Array.prototype](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array)) -> 정렬 알고리즘(버블정렬, 선택정렬, 삽입정렬, 병합정렬, 퀵정렬) -> 자료구조(스택, 큐, 트리, 그래프, 셋, 맵) -> 시간복잡도와 공간복잡도의 이해 -> 검색(이진탐색, 다이나믹 프로그래밍) -> 유형별 풀이(최대공약수/최소공배수, 순열/조합, DFS/BFS)
    
2. 동영상 강의가 도움이 됩니다.
이 장르에서는 역사와 전통이 있는 정보 올림피아드 계열 문제풀이가 도움이 됩니다.
제게는 정보 올림피아드 계열 선생님들의 강의가 도움이 되었습니다.

일단 제가 파악한 테크닉은 이정도가 되겠습니다.
도움이 되길 바랍니다.

**Comment by eeeyooon** [comment]
답변을 늦게 확인했습니다. 조언 무척 감사드립니다! 어떻게 코딩 테스트 준비를 해야 하는 지 감이 잡히는 것 같습니다. 🙇🏻‍♀️🙇🏻‍♂️

**Comment by shoveller** [comment]
안녕하세요! @eeeyooon 님.
#27 에서 식별자를 한글로 코딩하는 테크닉을 소개하고 있습니다.
이쪽도 한번 확인해 보셔요.
