### ISSUE TITLE
[LAB-6] white-space: nowrap을 줌에 따른 이미지 크기 

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#223]
## 질문 작성자

신선영

## 문제 상황

![image](https://user-images.githubusercontent.com/48400229/227445341-52c02cdb-d1c4-48c9-abaf-397e59db71d2.png)
![image](https://user-images.githubusercontent.com/48400229/227445443-13a0c2b3-3ba3-4a11-a520-be5a977b2da0.png)
![image](https://user-images.githubusercontent.com/48400229/227445663-b89978b3-1c8b-4e5e-b1a4-b0d823cce6d0.png)

위처럼 하면 아무 문제는 없는데, 아래처럼 span에 white-space:nowrap을 적용하게 되면 아래와 같이 이미지가 뒤죽박죽으로 크기가 제각각이 됩니다.

![image](https://user-images.githubusercontent.com/48400229/227445841-57ac043e-5de9-4ea2-b102-f4175692bf00.png)
![image](https://user-images.githubusercontent.com/48400229/227445874-92c32e77-5be4-4330-b91f-8d28f5e32a13.png)

이미지에는 변화를 주지 않았는데 왜 저럴까요ㅠ 좋은 해결 방법이 있을까요?

- 질문 내용을 자세하고 명확하게 풀어 이해할 수 있도록 작성합니다.
- 상황 이해를 돕기 위한 이미지 첨부가 필요한 경우 작성합니다. (권장)
- 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 프로젝트 저장소 URL

- [공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.](https://github.com/SSY1203/6lossom)
- develop 브랜치
- [6lossom-develop.zip](https://github.com/yamoo9/likelion-FEQA/files/11059175/6lossom-develop.1.zip)
- [env 파일](https://github.com/yamoo9/likelion-FEQA/files/11059178/env.zip)

## 환경 정보

- 운영체제 정보 (Windows)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 분석

span 요소에 `white-space: nowrap`을 적용하게 되면 이미지 크기가 일정하지 않는데 방법이 있을까요?

## 문제 해결

Flower.module.scss 파일을 열어 button 요소 스타일에 `width`, `height` 값을 설정해보세요. 😊

```scss
.flower {
  // ...
  button {
    // ...
    width: 108px;
    height: 100px;
  }

  span {
    font-size: 12px;
    white-space: nowrap;
  }
}
```

그러면 아래처럼 렌더링 됩니다.

<img src="https://user-images.githubusercontent.com/1850554/227472662-bc0f18ac-e7d7-4e24-9064-198311c18632.gif" width="600" alt />
