### ISSUE TITLE
[LAB-10] The top-level-await experiment is not enabled 에러관련 질문입니다.

### ISSUE THREAD

**Issue by hyunzsu** [yamoo9/likelion-FEQA#224]
## 질문 작성자

현지수

## 문제 상황

- 1. firebase 설치 이후 간단한 코드로 데이터를 불러오려고 했습니다.
- 2. 스크린샷과 같은 오류가 발생하여 찾아보았지만 더이상 진전이 없어서 질문드립니다.
![스크린샷 2023-03-24 오후 3 35 52](https://user-images.githubusercontent.com/108773199/227446346-ace94eb8-c4f8-42c7-8391-44f0ab1e00a7.png)

<img width="529" alt="스크린샷 2023-03-24 오후 3 35 59" src="https://user-images.githubusercontent.com/108773199/227446393-cd1b8b4e-c20d-4af0-a544-6114aab13866.png">

<img width="1432" alt="스크린샷 2023-03-24 오후 3 36 12" src="https://user-images.githubusercontent.com/108773199/227446422-97548ef1-c558-4606-a5c8-a14fb98ef8f6.png">

## 환경 정보

- Mac OS
- node 18.14.1
"firebase": "^9.17.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.8.2",
"react-scripts": "5.0.1",
 "web-vitals": "^2.1.4"

**Comment by hyunzsu** [comment]
[godlife.zip](https://github.com/yamoo9/likelion-FEQA/files/11059427/godlife.zip)
node_modules 제외한 프로젝트 파일 첨부합니다!

**Comment by yamoo9** [comment]
## 문제 상황

The top-level-await experiment is not enabled 에러가 발생합니다.

## 문제 해결

await를 async 함수 외부에서 사용할 수 없어 발생한 오류입니다.
사이드 이펙트이므로 useEffect 훅 내부에서 실행해야 합니다. 아래 이미지와 코드를 참고해보세요. 😊

![image](https://user-images.githubusercontent.com/1850554/227454004-efeb4f55-d975-4c63-9293-647a30d22fa9.png)

**CurrentChallengeContainer.jsx**

```jsx
import { CurrentChallengeCard } from 'components';
import { doc, getDoc } from 'firebase/firestore';
import { dbService as db } from 'fbase';
import { useEffect } from 'react';

function CurrentChallengeContainer() {
  useEffect(() => {
    const docRef = doc(db, 'challenges2', '1');

    (async () => {
      const docSnap = await getDoc(docRef);

      try {
        if (docSnap.exists()) {
          console.log('Document data:', docSnap.data());
        } else {
          console.log('No such document!');
        }
      } catch (error) {
        console.log('Error getting document:', error);
      }
    })();
  }, []);

  return (
    <div className="w-[390px] bg-background px-[28px]">
      <CurrentChallengeCard />
    </div>
  );
}

export default CurrentChallengeContainer;
```
