### ISSUE TITLE
[LAB-3] 파이어베이스를 이용한 배포에 사용중인 무료 커스텀 도메인 서비스를 이용해 보고자 합니다.

### ISSUE THREAD

**Issue by s-ja** [yamoo9/likelion-FEQA#226]
## 질문 작성자

안승지

## 문제 상황

- 현재 프로젝트에서 vite를 이용하여 테스트 빌드를 마쳤고, 그것을 터미널 `firebase deploy`를 이용해 테스트 배포와 호스팅을 해보았습니다.
- [결과](https://bold-caldron-244023.web.app/)

- 현재는 파이어베이스 프로젝트 이름으로 주소가 설정되어 있으나,
- [내.도메인.한국](https://xn--220b31d95hq8o.xn--3e0b707e/) 이 서비스를 이용해 생성한 무료 도메인을 연결해보고자 합니다. 

![image](https://user-images.githubusercontent.com/69342971/227529497-ad10e2d8-8b40-4019-ac82-a5ea4264c935.png)
![image](https://user-images.githubusercontent.com/69342971/227529547-30b733a1-2276-42aa-952b-fb3120885e85.png)

- 첫번째 이미지의 경우 커스텀 도메인을 파이어베이스 콘솔에 입력했을 때 나오는 화면이며, 이 키를 아래 내.도메인.한국 의 도메인 설정 화면 어디에 어떻게 입력하면 작동할까요?
- 
## 프로젝트 저장소 URL

- [프로젝트 저장소](https://github.com/LikeLion-FE-Final-Project03/car-zip)
- 코드에서의 문제가 아니라고 생각되어 때문에 코드 압축파일과 브랜치는 따로 입력하지 않았습니다.

## 환경 정보

- 운영체제 정보 (Windows, macOS 혼용중)
- Node.js 정보 (v18.15.0)
- 라이브러리 정보 (React 최신 버전)

**Comment by s-ja** [comment]
작성된 글을 확인하면서 든 추가적인 궁금증입니다..파이어베이스 라벨은 어떻게 추가하면 되는건가요?

**Comment by yamoo9** [comment]
## 문제 해결을 위한 참고

Firebase 공식문서 [커스텀 도메인 연결](https://firebase.google.com/docs/hosting/custom-domain?hl=ko)을 확인하여 진행해보세요. 공식문서 대로 진행하면 잘 연결될 것입니다. 😀

**Comment by yamoo9** [comment]
> 작성된 글을 확인하면서 든 추가적인 궁금증입니다..파이어베이스 라벨은 어떻게 추가하면 되는건가요?

저장소 호스트 또는 컨트리뷰터만 설정 가능해요 😁
