### ISSUE TITLE
🛎️ location.href에 값만 바꿨는데 어떻게 해당 url로 이동할 수 있는지 궁금합니다.

### ISSUE THREAD

**Issue by no-support** [yamoo9/likelion-FEQA#23]
location.href 외에도 css 스타일을 js로 바꾼다던지 할 때 함수를 쓰지 않고 해당 속성의 값을 직접적으로 바꾸는 경우가 많던데, 해당 속성값이 바뀐 것을 누가 어떻게 인지하고 바로 반영을 하는지 궁금합니다.

**Comment by yamoo9** [comment]
**웹 브라우저에 내장된 프로그램이 작성된 JavaScript 코드를 이해하고 처리합니다.**

웹 브라우저 개발자는 인터페이스 정의 언어([IDL](https://ko.wikipedia.org/wiki/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4_%EC%A0%95%EC%9D%98_%EC%96%B8%EC%96%B4))에 기술된 인터페이스(입력, 출력, 삭제 등)에 따라 프로그래밍 하여 기능을 구현합니다.
아래 이미지는 웹 브라우저의 [Location 인터페이스 IDL](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-location-interface) 입니다.

<img width="1268" alt="" src="https://user-images.githubusercontent.com/1850554/210953304-3bb736a3-69f4-4736-8113-3b1f0ef2dcc5.png">

웹 브라우저는 위 인터페이스에 따라 구현된 기능을 처리할 수 있습니다. 

웹 브라우저에 내장된 location 객체는 여러 기능을 처리하는데 
그 중 `href` 속성은 값을 출력하거나, 입력 시 웹 브라우저에 의해 처리됩니다. 

웹 브라우저에 내장된 프로그램은 Web API로 웹 개발자에 공개되고 
웹 개발자는 JavaScript 언어를 사용해 프로그램을 사용할 수 있습니다.

CSS 스타일이 JavaScript 코드에 의해 즉각 변경되는 것도 동일한 이유입니다.
다만 여기서 사용되는 Web API는 [CSSOM](https://w3c.github.io/csswg-drafts/cssom/#dom-elementcssinlinestyle-style)입니다. 

[CSSStyleDeclaration](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration) 인터페이스를 사용해 
스타일 값을 출력하거나, 사용자로부터 입력받아 처리합니다.

<img width="829" alt="" src="https://user-images.githubusercontent.com/1850554/210955061-d37763ab-82d5-46ea-a73b-b2786ce879b5.png">
