### ISSUE TITLE
[LAB-4] Github PR관련해서 질문있습니다!

### ISSUE THREAD

**Issue by SeoMiYoung** [yamoo9/likelion-FEQA#232]
## 질문 작성자
서미영

## 문제 상황
저희는 git-flow방식으로 branch를 관리하고 있습니다.
그래서 각자 fork를 해서 그 안에서 각자의 작업 브랜치를 생성하여 작업하고 있습니다.

저는 제 개인 브랜치(origin)인 feat/#96에서 팀의 organization(upstream)의 develop 브랜치로 PR을 날렸습니다.
그랬더니 자동으로 origin에 있던 커밋 기록들이 모두 올라왔습니다.

아직 merge를 하기 전이고 PR만 한 상태인데, 확인을 해보니,
![image](https://user-images.githubusercontent.com/112063987/227689732-ad6bb1d9-8d4d-4b09-84dd-364a6ffa5511.png)
두개의 commit기록이 포함된 걸 확인할 수 있었습니다.
그러나, 2번 커밋은 이슈와 관련이 있지만, 1번 커밋은 이슈와 관련이 없어서,
2번 커밋만 PR에 포함시키고 싶은 상황입니다.

이럴땐 어떻게 해야할까요?

## 프로젝트 저장소 URL
https://github.com/LikeLion-FE-React-Project04/project-repo/pulls

**Comment by yamoo9** [comment]
## 문제 해결을 위한 제안

커밋 기록을 정리해 PR 하려면 PR 전에 리베이스(rebase) 해보세요. ([참고](https://seosh817.tistory.com/240))
또는 [PR 커밋 Squash 구성](https://docs.github.com/ko/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests)을 사용해보세요.

유사한 이전 질문의 답변(https://github.com/yamoo9/likelion-FEQA/issues/135#issuecomment-1465537956) 글을 참고해보셔도 좋을 듯 합니다.

**Comment by SeoMiYoung** [comment]
답변감사합니다!!!!
