### ISSUE TITLE
[LAB-10] firebase 데이터가 전혀 뜨지 않는 문제 (과금: 할당량 사용 초과)

### ISSUE THREAD

**Issue by sm022** [yamoo9/likelion-FEQA#234]
## 질문 작성자

윤성민

## 문제 상황

fbase.js 코드는 문제가 없어 보이는데 
데이터가 아무것도 로드되지 않는 점으로 인해 이슈를 남깁니다.
![image](https://user-images.githubusercontent.com/77651050/227747335-be68d359-c9f0-4bbc-9320-50da13a6c54f.png)

현재 데이터가 뜨지 않는 점 이외에도 더미 데이터로 시험할 때는 잘 뜨던 필터 버튼까지 뜨지를 않고 있습니다.

제가 생성한 컴포넌트는 Category.jsx / ChallengeCard.jsx / ChallnegeFilter.jsx / ChallengeList.jsx / FilterButton.jsx가 있고 
그 밖의 컴포넌트는 공통 컴포넌트(BackButton.jsx, Navbar.jsx, CreateChallengeButton.jsx)에 속합니다. 

firebase 데이터를 받는 코드는  Category.jsx 와 ChallengeCard.jsx입니다. 코드도 같이 첨부하겠습니다

![image](https://user-images.githubusercontent.com/77651050/227748793-ed951f23-a7a3-47c7-bc01-a3cafef07441.png)
Category.jsx입니다 

![image](https://user-images.githubusercontent.com/77651050/227748826-f3ebec54-e67d-429a-bd97-176a647a181c.png)
ChallengeCard.jsx입니다

컴포넌트를 너무 많이 분리한 탓에 복합적으로 데이터를 불러올 때 이런 현상이 나타나는건지 궁금합니다.

처음엔 fbase.js에서 데이터를 로드하고 전달하는 로직을 짰지만 그럼 너무 복잡해질까봐 
useCategoryData.js라는 훅을 만들어 넘겼습니다. 코드도 같이 첨부하겠습니다
![image](https://user-images.githubusercontent.com/77651050/227747754-f0ee9076-64db-4438-834c-85092c9060eb.png)

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 [여기에](https://github.com/likelion-lab10/godlife) 남깁니다.
- filter/filter
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
[filter.zip](https://github.com/yamoo9/likelion-FEQA/files/11070453/filter.zip)

## 환경 정보

-  Windows
- Node.js v16.16.0
- React v8.12.1

**Comment by yamoo9** [comment]
## 문제 분석

개발 과정에서 과도한 리소스 요청으로 과금이 필요하다는 오류 메시지가 출력됩니다.

<img width="505" alt="" src="https://user-images.githubusercontent.com/1850554/227749039-632d9137-f522-44a8-9246-cdb4d5830988.png">

아마도 **Firebase에 반복 요청(useEffect 종속성 배열 설정 이슈)으로 할당량이 초과된 듯 보입니다.**
새로운 Firebase 프로젝트를 생성한 다음 인증, 데이터베이스, 스토리지를 설정하고 사용해야 합니다. 😥

그리고 Firebase v9, v8 API 문법이 모두 사용된 부분이 useCategoryData 훅 코드에서 보입니다. 😱

<img width="1436" alt="" src="https://user-images.githubusercontent.com/1850554/227749332-cf6703ce-c851-4456-9a9f-fbf2fe73f8fa.png">

challenges 콜렉션의 모든 문서를 불러오는데 [Firebase v8 API](https://firebase.google.com/docs/firestore/query-data/get-data?hl=ko#get_all_documents_in_a_collection)가 사용 되었습니다.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/1850554/227749377-9a12d246-bee3-4e4f-a9d5-f0d78aa5c81e.png">

## 문제 해결

먼저 거론한 이슈 해결 이후에야 Firestore에서 데이터를 불러와 화면에 렌더링 하는 코드를 검토해볼 수 있습니다. 🤔
우선 현재 이슈는 Closed 하겠습니다. 문제 분석이 가능해지면 새 이슈를 등록해주세요. 검토하여 해결 방법을 제시하겠습니다. 🙂
