### ISSUE TITLE
[LAB-17] 현재 에러가 나서 커밋이 안되는 상황입니다.

### ISSUE THREAD

**Issue by BORAVORAYOON** [yamoo9/likelion-FEQA#237]
## 질문 작성자

윤보라

## 문제 상황
- 커밋시 아래와 같은 에러가 뜨면서 커밋이 안되는 상황입니다.
- 여러 사람의 작업을 머지한 후 풀을 받은 후에 해당 에러가 발생했습니다.
<img width="604" alt="스크린샷 2023-03-26 오후 2 25 43" src="https://user-images.githubusercontent.com/108814429/227757268-a2bec400-51e1-49e7-b5ec-69d5daaceb71.png">

<임시방편으로 아래 방법을 사용했습니다.>
- 터미널에서 아래 명령어 실행 
- ```brew install dos2unix```
-  vscode에서 node_modules 폴더 삭제 후 아래 명령어 실행
- ```find . -type f -exec dos2unix {} \;```
- 명령어 실행 후 설치가 완료되면 커밋이 됩니다.

혹시 이것 외에 다른 방법이 있는지 궁금해서 이슈 남깁니다.

## 프로젝트 저장소 URL

- https://github.com/NatureTeam/NatureKarly.git
- develop 브랜치

## 환경 정보

- 운영체제 정보 : macOS
- Node.js 정보 : v19.1.0
- 라이브러리 정보 : React v18.2.0

**Comment by yamoo9** [comment]
## 문제 원인

문제 원인은 소스 코드의 개행 문자(줄바꿈) 처리가 OS에 따라 상이 하다는 것입니다. 윈도우는` \r\n`이고 유닉스 계열은 `\n`이 됩니다. 
즉, 서로 다른 OS를 사용하는 팀원 간 개행 문자 호환 문제가 발생됩니다. 에러 메세지 중 `\r`이 나오는 것으로 보아 윈도우에서 생성된 
소스 코드 중 마지막 문자의 줄바꿈 `\r\n`에서 `\n`만 인식하고 `\r`은 인식하지 못해서 생긴 오류라고 볼 수 있습니다.

## 문제 해결

Git 공식 문서 [Formatting and Whitespace](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace)를 참고하면 해결 방법을 안내합니다.

GitHub에서 소스 코드를 받아올 때, 윈도우 환경에서도 리눅스의 시스템을 사용할 수 있도록 설정합니다.
말 그대로 윈도우 기반에서 리눅스 환경과 호환이 잘 되도록 설정하는 것입니다.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1850554/227770483-5334457d-b578-44cf-94c2-5ef069698d44.png">

설정 명령은 아래와 같이 입력합니다.

```sh
git config --global core.autocrlf false
```


## 참고

해당 답변은 아래 내용을 참고하여 작성되었습니다.

- [/usr/bin/env: ‘sh\r’: no such file or directory 오류](https://bgpark.tistory.com/81)
- [8.1 Customizing Git - Git Configuration](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace)
