### ISSUE TITLE
🛎️ 호이스팅 시 초기화 

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#24]
## 문제 상황

호이스팅은 스코프 최상단으로 올라가는 현상까지는 이해했습니다 ! 

여기서 질문이 있습니다 ! 호깃 제가 이애한게 맞나 싶어서 글을 올립니다 !

-   var로 선언한 변수의 경우 호이스팅 시 undefined로 변수를 초기화합니다. 
 ->  var는 호이스팅될 때 초기화 된다는게 윈도우 전역에서 초기화

- 반면 let과 const로 선언한 변수의 경우 호이스팅 시 변수를 초기화하지 않습니다 
-> 호이스팅될떄 따로 초기화없이 선언만되는것이 윈도우 전역을 건드리지 않고 초기화 됨 

var 와 let 은 두개 다 undefiend 가 뜨는데 , let , const 도 undefiend 가 뜬다는것이 선언만 하고 리턴값으로 나온건가요 ? 초기화를 시키지않구 ?
![image](https://user-images.githubusercontent.com/109938280/210954579-5046dab0-7401-48be-ae33-45e42d025fa1.png)

**Comment by shoveller** [comment]
안녕하세요. @5wintaek 님. 아주 아카데믹한 질문을 주셨네요!
먼저, 예시로 들어주신 코드는 호이스팅과 관계가 없다는 말씀을 드리고 싶어요.
![1](https://user-images.githubusercontent.com/1357198/210956810-4173bd38-5702-48f5-8ac5-03c34d50b9fa.png)

그 증거로 아래의 코드를 제출합니다.
자바스크립트 엔진은 단지 문장의 실행 결과를 아래에 출력할 뿐입니다.
<img width="279" alt="2" src="https://user-images.githubusercontent.com/1357198/210956924-5b1b0ae2-01ad-4bd3-91e6-693c7f0a425b.png">

**Comment by 5wintaek** [comment]
@shoveller 감사합니다 재원쌤 !

**Comment by shoveller** [comment]
안녕하세요. @5wintaek 님. 도움이 되었다니 다행입니다. 
아래와 같이 약간만 수정을 하시면 될 것 같아요.

var로 선언한 변수의 경우 호이스팅 시 undefined로 변수를 초기화합니다.
-> var는 호이스팅될 때 초기화 된다는게 윈도우 전역에서 초기화(x)
-> var는 유효범위 최상단으로 호이스팅(초기화 되므로). 
      var 로 선언한 변수를 전역에 선언하면, 유효범위가 전역이므로 문서 최상단으로 호이스팅.

반면 let과 const로 선언한 변수의 경우 호이스팅 시 변수를 초기화하지 않습니다.
-> 호이스팅될떄 따로 초기화없이 선언만되는것이 윈도우 전역을 건드리지 않고 초기화 됨(x)
-> let과 const는 호이스팅이 되지 않음(초기화되지 않으므로)
