### ISSUE TITLE
[LAB-17] useReadData() 파이어베이스 커스텀 훅 사용법

### ISSUE THREAD

**Issue by semin99** [yamoo9/likelion-FEQA#240]
## 질문 작성자

장세민

## 문제 상황
![image](https://user-images.githubusercontent.com/87403695/227768447-f80eba66-2d3d-48dd-ac01-906f28645ed1.png)
useReadData() 커스텀 훅을 사용하려고하는데 데이터를 받아오지 못하고 있습니다. 어떻게 사용해야할까요?

## 프로젝트 저장소 URL
https://github.com/semin99/NatureKarly/tree/feature/56-productlist-components

**Comment by yamoo9** [comment]
## 문제 해결

먼저 잘못된 `useReadData.js` 파일의 모듈 불러오기를 수정합니다.

<img width="1134" alt="" src="https://user-images.githubusercontent.com/1850554/227776395-7553d6e4-ec2a-49fc-aa03-d7d48d24fd15.png">

`Product.jsx` 파일 코드를 아래와 같이 수정합니다.

```jsx
export function Product({ isSwiper }) {
  // ...

  const { readData, data } = useReadData('products');

  useEffect(() => {
    readData();
  }, [readData]);

  console.log(data);

  // ...
}
```

결과는 다음과 같이 Firestore에서 데이터를 잘 가져옵니다. 😊

<img width="560" alt="" src="https://user-images.githubusercontent.com/1850554/227776281-8f3b6e4f-76a1-47ba-af2e-97ba7be5b5a3.png">

## 가이드 파일

첨부된 가이드 파일을 다운로드 받아 확인해보세요.

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/11071599/src.zip)
