### ISSUE TITLE
[LAB-11] 쿼리를 두번 돌릴때 파이어베이스 'za2', Wa2 에러

### ISSUE THREAD

**Issue by kyuran6** [yamoo9/likelion-FEQA#241]
## 질문 작성자

김진희

## 문제 상황
- 구현하고자 하는 기능은 다음과 같습니다

![스크린샷 2023-03-26 시간: 23 00 06](https://user-images.githubusercontent.com/119389578/227780870-47347e14-a256-4462-bb8b-57e2c98440c2.png)
![스크린샷 2023-03-26 시간: 23 00 38](https://user-images.githubusercontent.com/119389578/227780889-ca5a0504-bba6-4a3a-9039-9a117b3bd397.png)

- 파이어스토어에서 특정 user_uid가 아니며, isAllow 값이 true인 category_uid를 categories 컬렉션에서 하나 가져옵니다 (첫번째 쿼리)

- 그 다음 images컬렉션에서 그 category_uid를 가진 이미지 중 3장을 보여줍니다 (두번째 쿼리)
- ![스크린샷 2023-03-26 시간: 23 14 35](https://user-images.githubusercontent.com/119389578/227781701-90da6fd7-98f8-4680-b10f-ddff716c1699.png)
![스크린샷 2023-03-26 시간: 23 02 14](https://user-images.githubusercontent.com/119389578/227780984-2090816f-a3d4-4d93-a38c-9864219497f2.png)

-  category_uid를 가져오는것까지는 성공했으나, 이미지가 보이진 않고 다음과 같은 에러가 뜹니다
![스크린샷 2023-03-26 시간: 23 03 24](https://user-images.githubusercontent.com/119389578/227781091-65f7b4f2-5357-4903-b69a-bdfd3bcb12eb.png)

## 프로젝트 저장소 URL

- [공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.](https://github.com/likeLion-FE4-RP11/Asparagus)
- feature/main-SeemoreImage
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
[Asparagus.zip](https://github.com/yamoo9/likelion-FEQA/files/11071829/Asparagus.zip)

## 환경 정보

- macOS
- Node.js v19.7.0
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 해결

- `getDoc` 함수가 아니라, `getDocs` 함수로 쿼리 요청합니다.
- [Promise.all](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)을 사용해 멀티 비동기 요청이 모두 완료되면 `moreImgArr` 상태 업데이트 합니다.

```jsx
const getCategories = async () => {
  // ...
  const moreImgListPromises = categoryList.map((item) => {
    const q2 = query(
      collection(db, 'images'),
      where('category_uid', '==', item)
    );

    // getDocs 함수를 사용해 2번째 쿼리 요청
    return getDocs(q2).then(({ docs }) => {
      return docs.map((doc) => doc.data().url);
    });
  });

  // Promise.all을 사용해 모든 비동기 요청이 완료되면 처리
  Promise.all(moreImgListPromises).then((datas) => {
    const urls = datas.reduce((urls, data) => [...urls, data[0]], []);
    setMoreImgArr(urls);
  });
};
```

HomePage 컴포넌트 JSX 영역 코드는 아래와 같이 수정합니다.

```jsx
<S.SeeMoreSection>
  {visible &&
    moreImgArr &&
    moreImgArr.map((url) => <SeeMoreImg key={url} src={url} />)
  }
</S.SeeMoreSection>
```

그러면 결과는 다음 영상과 같습니다. 😊

![1](https://user-images.githubusercontent.com/1850554/227783291-2eae00ae-c4c6-4b83-be8d-3d866b64d827.gif)

## 가이드 파일

첨부된 가이드 파일을 다운로드 받아 확인해보세요.

[src.zip](https://github.com/yamoo9/likelion-FEQA/files/11071933/src.zip)

**Comment by kyuran6** [comment]
답변 정말 감사합니다!
