### ISSUE TITLE
[LAB-10] firebase 데이터가 렌더링이 되지 않습니다

### ISSUE THREAD

**Issue by sm022** [yamoo9/likelion-FEQA#245]
## 질문 작성자

윤성민

## 문제 상황

저번에 답변 달아주신대로 firebase 9버전으로 바꿨더니 
더 이상의 과금 초과 메시지는 나오지 않지만 여전히 데이터는 전혀 뜨지 않고 있습니다.
![image](https://user-images.githubusercontent.com/77651050/227815103-11b9d55b-8ae6-47e1-a5c4-2e27881da27d.png)

과금 이슈 때문에 useCategoryData.js만 바꾼 상태라 밑의 내용은 저번과 같습니다

_제가 생성한 컴포넌트는 Category.jsx / ChallengeCard.jsx / ChallnegeFilter.jsx / ChallengeList.jsx / FilterButton.jsx가 있고 
그 밖의 컴포넌트는 공통 컴포넌트(BackButton.jsx, Navbar.jsx, CreateChallengeButton.jsx)에 속합니다._ 

_firebase 데이터를 받는 코드는  Category.jsx 와 ChallengeCard.jsx입니다. 코드도 같이 첨부하겠습니다_

![image](https://user-images.githubusercontent.com/77651050/227748793-ed951f23-a7a3-47c7-bc01-a3cafef07441.png)
Category.jsx입니다 

![image](https://user-images.githubusercontent.com/77651050/227748826-f3ebec54-e67d-429a-bd97-176a647a181c.png)
ChallengeCard.jsx입니다

_컴포넌트를 너무 많이 분리한 탓에 복합적으로 데이터를 불러올 때 이런 현상이 나타나는건지 궁금합니다._

_처음엔 fbase.js에서 데이터를 로드하고 전달하는 로직을 짰지만 그럼 너무 복잡해질까봐 
useCategoryData.js라는 훅을 만들어 넘겼습니다. 코드도 같이 첨부하겠습니다_

바뀐 코드입니다

![image](https://user-images.githubusercontent.com/77651050/227815877-a87ccaa8-b485-400c-822f-a232c88ac52b.png)

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 [여기에](https://github.com/likelion-lab10/godlife) 남깁니다.
- filter/filter
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
[filter_2.zip](https://github.com/yamoo9/likelion-FEQA/files/11073561/filter_2.zip)

## 환경 정보

-  Windows
- Node.js v16.16.0
- React v8.12.1

**Comment by yamoo9** [comment]
## 문제 분석

과금 할당량 초과 문제로 테스트 하지 못했던 질문 https://github.com/yamoo9/likelion-FEQA/issues/234 에 연결된 질문입니다.

## 문제 해결이 쉽지 않은 상황 안내

문제 질문과 동일한 상황을 확인할 수 없어, 디스코드로 화면 공유한 후 함께 문제를 분석해야 합니다.
어떤 상황인지 아래 화면 영상을 확인해보세요. 😳 여전한 과금 오류 문제가 발생합니다.

~그리고 가이드 방에서 시간될 때 멘토링을 진행해 봅시다. 디스코드로 DM 주세요. @sm022님~
가이드 방에서 멘토링 진행 후, 디버깅 방법을 안내하였습니다.

https://user-images.githubusercontent.com/1850554/227820798-acf3badb-5cfb-446b-a94e-7e8b5684639f.mp4

<br/>
