### ISSUE TITLE
[LAB-9] firebase 과도한 읽기 요청 횟수

### ISSUE THREAD

**Issue by chaehaeun** [yamoo9/likelion-FEQA#246]
## 질문 작성자

채하은

## 문제 상황
- 코드 어딘가에서 과도하게 읽기 요청이 들어가고 있는 것 같은데, 원인을 찾지 못하고 있습니다... 당장은 급한 대로 유료 업그레이드를 해놓았으나 이대로는 저의 계좌가 크게 위협 당할 것 같아 두렵습니다...
- 수직상승한 그래프는 새벽 동안 무한 루프에 빠져서 생긴 문제입니다..!
![image](https://user-images.githubusercontent.com/103991310/227820159-d78e4536-ea4a-4b2d-959c-434afc94f3ec.png)
![image](https://user-images.githubusercontent.com/103991310/227818065-253d7c69-4407-4fc9-8161-b76ec99ed540.png)
![image](https://cdn.discordapp.com/attachments/1045522192072441856/1089723637478735922/image.png)

## 프로젝트 저장소 URL
- [https://github.com/chaehaeun/withPet-client/tree/feature/story](https://github.com/chaehaeun/withPet-client.git)
[withPet-client-feature-story (1).zip](https://github.com/yamoo9/likelion-FEQA/files/11073741/withPet-client-feature-story.1.zip)

## 환경 정보
- 운영체제 정보 : window

**Comment by yamoo9** [comment]
## 문제 검토 방법 안내

https://github.com/yamoo9/likelion-FEQA/issues/245#issuecomment-1484345126 질문과 동일한 이슈로 이러한 문제 유형은 디스코드 가이드 방을 통해 
~화면 공유하여 문제를 해결하는 것이 좋습니다. DM 드리겠습니다. 🤔~
문제에 대해 논의하였습니다. 😃
