### ISSUE TITLE
🛎️ 함수에서 문자열과 배열을 함께 리턴하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by hungerbk** [yamoo9/likelion-FEQA#25]
## 문제 상황

스터디 4조 질문입니다.

두 배열의 합을 비교해서 합이 더 큰 배열을 리턴하는 함수를 만들었습니다.

이때, 배열과 그 배열의 합을 함께 출력하고 싶은데, 아래처럼 작성하면 배열이 문자로 바뀌어서 출력이 됩니다.

문자와 배열을 함께 출력할 수 있는 방법이 있을까요?

<img width="645" alt="스크린샷 2023-01-06 오후 5 07 14" src="https://user-images.githubusercontent.com/43366461/210957727-2bca204e-c62b-4c37-acc6-ae45cc06dbff.png">

**Comment by yamoo9** [comment]
> 다음에 질문 올린 땐 코드도 함께 올려주세요 😅

"문자와 배열을 함께 출력할 수 있는 방법"으로 다음과 같이 코드를 작성할 수 있어요.
원하는 **결과 값이 2개 이상의 정보를 가져야 하므로 배열 또는 객체를 반환하면 됩니다.**
결과는 다음과 같이 나오게 되요.

<img src="https://user-images.githubusercontent.com/1850554/210961745-006c94a1-be2b-4a27-a3ea-4aa16697273d.png" width="320" />

아래 작성된 코드에서 `return` 구문 부분을 확인해보세요. 😄

```js
let array1 = [3, 4, 5];
let array2 = [44, 5, 9];

function compare(arr1, arr2) {
  let num1 = arr1.reduce((acc, cur) => acc + cur, 0);
  let num2 = arr2.reduce((acc, cur) => acc + cur, 0);

  if (num1 > num2) {
    return [
      arr1, 
      `배열의 합: ${num1}`
    ];
  } else if (num1 < num2) {
    return [
      arr2, 
      `배열의 합: ${num2}`
    ];
  } else {
    return [num1 === num2, '두 배열의 합은 같다.'];
  }
}
```
