### ISSUE TITLE
[LAB-10] 카카오 로그인 firebase 커스텀 토큰

### ISSUE THREAD

**Issue by Majesty-jun** [yamoo9/likelion-FEQA#254]
## 질문 작성자

전하준

## 문제 상황

로그인, 회원가입 파트를 진행 중, 다른 인증방법들은 다 완성하고 현재 카카오 로그인을 진행중인데, 어려움이 느껴져 질문을 드립니다!
현재, 카카오 로그인 API를 통해서 카카오 access token과 데이터를 받아오는 데 까지는 어찌저찌 성공한 상황입니다.
이후 프로세스를 구글링 해보니 Firebase Admin SDK 비공개 키를 받아서 커스텀 토큰을 생성해야 한다는 정보들을 보고, 
공식문서를 찾아 보니 이해가 가지 않는 부분이 있어서 질문을 드립니다.

![스크린샷 2023-03-27 오후 4 07 58](https://user-images.githubusercontent.com/83108580/227866087-bf61d7ab-7b6e-4592-b8b1-dcbd49380092.png)

▲ 카카오 user data, access token

![스크린샷 2023-03-27 오후 4 09 06](https://user-images.githubusercontent.com/83108580/227866921-85c82a0b-2c32-4c7b-9b47-e7bbc2547977.png)

위 공식문서의 "인증 서버" 라는 부분이 어디를 말하는 건지 이해가 되지 않아서 질문 드립니다.
또한 그 이후의 과정은 어떻게 진행되는지 궁금합니다..!

- 질문 내용을 자세하고 명확하게 풀어 이해할 수 있도록 작성합니다.
- 상황 이해를 돕기 위한 이미지 첨부가 필요한 경우 작성합니다. (권장)
- 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 프로젝트 저장소 URL

https://github.com/likelion-lab10/godlife/tree/login/kakaoLogin
login/kakaoLogin 브랜치

https://firebase.google.com/docs/auth/web/custom-auth?hl=ko
firebase 공식문서 인증-웹-맞춤 인증 시스템 사용하기 탭

## 환경 정보

- 운영체제 정보 macOS
- Node.js 정보 v18.12.1
- 라이브러리 정보 
   firebase: v9.17.2
   React v18.2.0

**Comment by yamoo9** [comment]
## 문제 확인

.env 파일을 포함하지 않아 테스트를 수행할 수 없습니다.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/1850554/227886116-41bb31fc-715c-42d4-bda1-b73f8714c1aa.png">

## 문제 해결을 위한 제안

Kakao 인증은 Firebase에서 자체 제공하는 인증 공급자가 아니므로 별도로 필요한 절차를 수행하는 구성이 필요합니다.
인증 방법은 "이메일/패스워드"를 사용하거나 또는 "커스텀 토큰"을 사용해야 합니다.

질문에서는 커스텀 토큰을 선택한 듯 하나, 이 방법을 사용하려면 인증을 위한 서버가 필요합니다.
하지만 우리 프로젝트는 백엔드 개발 영역을 다루지 않기 때문에 별도로 인증 서버가 없습니다. 😳
직접 Node.js 서버(예: Express 등)를 구성하는 과정이 필요한데 현 단계에서 그것을 수행 하기란 어렵습니다. ([참고](https://velog.io/@hadam/integrate-kakao-login-with-firebase-using-react-and-functions-2#express))

다른 방법인 "이메일/패스워드"는 별도로 서버를 거치지 않고도 카카오 계정(이메일)을 통해 
회원가입이 가능할 것으로 보입니다. ([참고](https://luen.tistory.com/200#article-2--%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-+-%ED%8C%8C%EC%9D%B4%EC%96%B4%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%9D%B8%EC%A6%9D)) 링크를 따라가면 진행 방법을 확인할 수 있습니다. 
안내 사항을 확인해 진행해보세요. 😃

<img width="640" alt="" src="https://user-images.githubusercontent.com/1850554/227892015-ce668dd0-c703-453c-9cf4-2fc8f3c5c7c5.png">
