### ISSUE TITLE
[LAB-10] 코드 리뷰 부탁드립니다.

### ISSUE THREAD

**Issue by sm022** [yamoo9/likelion-FEQA#255]
## 질문 작성자

윤성민

## 문제 상황

가이드방에서 알려주신 대로 firebase storage를 따로 파서 시험 중입니다 
처음엔 잘 뜨는 것 같았는데 중간에 다시 과금 오류가 떴고 
다시 또 새로고침을 해보니 더이상의 오류는 나오지 않습니다

![image](https://user-images.githubusercontent.com/77651050/227867968-2d1cafc1-9612-4faf-93a7-d35eb96fdfa2.png)

해당 오류는 category.jsx에 38번째 줄이었던
` useEffect(() => {
    getStorageData().then((data) => {
      setUrls(data);
      updateFilteredChallenges(data);
    });
  }, [getStorageData, updateFilteredChallenges]);`
여기였습니다. 그래서 리소스 요청이 과다하게 나오는 문제였고 이 부분을 삭제하여 한번만 받아오게끔 만들었습니다.

코드 사진을 같이 첨부하겠습니다

![image](https://user-images.githubusercontent.com/77651050/227868764-d7ee1ace-73d7-483b-92bf-b1e22980cbe8.png)

useCategoryData.js 훅도 문제가 되는 부분이 없었습니다

![image](https://user-images.githubusercontent.com/77651050/227869175-95eb1014-c070-48f5-9801-5bd33f1b3d29.png)

지금껏 일어난 과금 오류 사태를 한번 더 일으킬 순 없기에 머지 하기 전 최종 점검해주시면 감사하겠습니다.

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 [여기에](https://github.com/likelion-lab10/godlife) 남깁니다.
- filter/filter
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
[filter_3.zip](https://github.com/yamoo9/likelion-FEQA/files/11076698/filter_3.zip)

## 환경 정보

-  Windows
- Node.js v16.16.0
- React v8.12.1

**Comment by sm022** [comment]
다시 firebase를 파서 변경하였습니다!

**Comment by yamoo9** [comment]
> 다시 firebase를 파서 변경하였습니다!

@sm022 님 첨부된 ZIP이 다운로드 안되는데, 죄송하지만 다시 한 번 첨부해주시겠어요? 😥

<img width="619" alt="" src="https://user-images.githubusercontent.com/1850554/227919597-670c6a46-9c9e-4056-a20f-db99580e5ec2.png">

**Comment by sm022** [comment]
[filter_3.zip](https://github.com/yamoo9/likelion-FEQA/files/11077814/filter_3.zip)
다시 올렸습니다!

**Comment by yamoo9** [comment]
## 코드 리뷰

**Category.jsx** 파일의 useEffect 종속성 배열을 아래와 같이 바꾸는 것 말고 큰 문제는 보이지 않네요 😀

```jsx
useEffect(() => {
  updateFilteredChallenges(urls);
}, [updateFilteredChallenges, urls]);
```

**Comment by sm022** [comment]
감사합니다! 배열 고치고 최종 머지하도록 하겠습니다
