### ISSUE TITLE
[LAB-4] 동적 세그먼트 라우팅 새로고침 오류

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#257]
## 질문 작성자

서석원

## 문제 상황

세그먼트 라우팅 페이지가 새로고침시 에러가 발생합니다.. 해결방법을 모르겠습니다.
로더를 사용하지 않는 상태입니다
**정확히는 새로고침, url창에서 주소를 입력해서 들어가면 에러가 나타납니다.**

![세그2](https://user-images.githubusercontent.com/73629761/227874936-a4e97275-2df7-4199-b1d4-3e06d8387d4e.PNG)
![세그3](https://user-images.githubusercontent.com/73629761/227874949-006b3457-9b42-4a80-a2da-af1dbe152998.PNG)

![버그](https://user-images.githubusercontent.com/73629761/227875824-23a102f7-967d-4cd0-8ca1-21ff4939721e.gif)

## 프로젝트 저장소 URL

[해당 레포지토리 **develop 브랜치**
](https://github.com/LikeLion-FE-React-Project04/project-repo)
## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 원인

[새로 고침 할 때 React Router가 정상적으로 작동하지 않는 이유는 무엇입니까?](https://sentry.io/answers/why-don-t-react-router-urls-work-when-refreshing-or-writing-manually/) 참고해 문제 원인을 파악할 수 있습니다. 😳

> React Router는 클라이언트 환경에서 라우트 변경을 처리하고, 라우트가 변경될 때 서버에 요청하지 않습니다. 
> 웹 브라우저 [historyAPI](https://developer.mozilla.org/en-US/docs/Web/API/History_API)를 사용해 클라이언트 측 URL을 변경하고 해당 라우트의 뷰를 렌더링 합니다.
> 이 문제는 홈 페이지 경로(`/`)에 없는 경로에 대해 발생합니다.<br />예를 들어 클라이언트 측 라우트에 이동한 후, 새로 고침 하면 문제가 발생합니다.

## 문제 해결

`public/index.html` 파일에 base 요소 코드를 아래와 같이 삽입하면 해결됩니다. 😊
관련 이슈 답변 https://github.com/froala/angular-froala/issues/170#issuecomment-1349009398 을 참고하세요.

```html
<base href="/" />
```

결과는 아래 영상과 같습니다. 새로고침 해도 라우트는 정상적으로 유지되고 앱은 깨지지 않습니다. 😀

![](https://user-images.githubusercontent.com/1850554/227907335-f6958113-4fc5-404b-af93-090f14da422a.gif)

**Comment by ssw6750** [comment]
허걱... 에러만 그대로 구글링했어도,, 해결 가능했을것 같네요...ㅠㅠ 이제부턴 에러부터 구글링 하겠습니다..!!!
해결해주셔셔 감사합니다...!!!!!
