### ISSUE TITLE
🛎️ 주어진 배열을 수정하지 않고 요소교체

### ISSUE THREAD

**Issue by Anyudbwls** [yamoo9/likelion-FEQA#26]
STD 4 질문입니다. 

// 퀴즈1: 주어진 배열 안의 딸기 아이템을 키위로 교체하는 함수를 만들기
// 단, 주어진 배열을 수정하지 않도록!
// input: ['🍌', '🍓', '🍇', '🍓']
// output: [ '🍌', '🥝', '🍇', '🥝' ]

주어진 배열을 수정하지 않고 딸기 두개를 어떻게 교체해야할까요? 
배열을 수정하지 말라고 했으니 문자열로 수정해야하는지, 
반복문을 돌려서 수정해야하는지 궁금합니다.

**Comment by shoveller** [comment]
안녕하세요. @Anyudbwls 님!
전형적인 코딩테스트용 문제네요!
출제자는 `Array.prototype` 안의 메소드에 익숙해지라는 의도로 출제했을거에요.
배열을 수정하지 않고 푸는 문제는 주로 [Array.prototype.splice](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)로 풉니다.

저는 이만 총총...

**Comment by yamoo9** [comment]
재원 멘토님께서 해결 가능한 힌트를 주셨으니, 저도 함수의 로직 코드를 모자이크 힌트로 남깁니다. 😌
문제 핵심은 **주어진 배열을 파괴하지 않고, 새로운 배열을 반환하는 함수를 만들면 되겠죠.**

`map`,` filter`와 같은 배열 메서드는 원본 배열을 파괴하지 않고 
새로운 배열을 반환하니 이 메서드 등을 활용해볼 수 있을 거에요.
물론 for문을 사용해서 해결할 수도 있습니다~ 😉

![](https://user-images.githubusercontent.com/1850554/210971297-b8d46d8c-a1ae-48f7-887c-2f332f72178a.png)
