### ISSUE TITLE
[LAB-9] Firebase 호스팅을 활용하여 배포 과정에서 Github Actions 오류가 발생하였습니다.

### ISSUE THREAD

**Issue by jaesukpark77** [yamoo9/likelion-FEQA#268]
## 질문 작성자

박재석

## 문제 상황

- 과정은 해당 블로그를 참고하여 Firebase의 호스팅을 활용하여 배포를 진행하였습니다.
  - https://velog.io/@jgi0105/Learn-Firebase-with-me-1-%ED%98%B8%EC%8A%A4%ED%8C%85
- 설정 과정에서 깃허브와 연동을 진행하였습니다.
- 블로그의 순서를 참고하여 모든 설치가 완료된 이후, Github Actions가 연결이 되긴 했는데 build_and_deploy가 오류가 발생하였습니다.
![image](https://user-images.githubusercontent.com/73949086/228176245-acefd4b2-2291-4cad-953d-2d42b7605940.png)
-  Process completed with exit code 254의 오류가 발생하였습니다.
![image](https://user-images.githubusercontent.com/73949086/228177519-ecefcb6b-01a4-4222-89fa-6a787ab7c760.png)
![image](https://user-images.githubusercontent.com/73949086/228176523-62ac4bed-3ac6-4672-9ccc-c26115f5b8c0.png)
- 설치 과정에서 문제가 발생한것 일까요? 아니면 폴더의 경로가 문제가 있는 걸까요? 

## 프로젝트 저장소 URL

- https://github.com/withPet-team/withPet-client
- main 브랜치에서 배포를 진행하였습니다.
- [withPet-client-main.zip](https://github.com/yamoo9/likelion-FEQA/files/11087138/withPet-client-main.zip)

## 환경 정보

- Windows
- Node.js v18.12.1
- React v18.0.2

**Comment by yamoo9** [comment]
## 문제 분석

오류 메시지를 보면 packaage.json을 찾을 수 없다는 메시지로 보이네요.
**보아하니 withpet-client가 2번 중복되는 부분이 의심 스럽네요. 그 부분을 확인해보세요. 왜 경로가 2번 반복되는 지 말이죠.**

<img width="1183" alt="" src="https://user-images.githubusercontent.com/1850554/228182330-7d476387-0bb0-4767-b30b-1c536b21df03.png">

## 레퍼런스

GitHub Actions 포함 Firebase 호스팅에 배포하는 영상 가이드를 참고해보세요.

- [How to Deploy React App on Firebase Hosting? (CI/CD with GitHub Actions | Preview | Custom Domain)](https://www.youtube.com/watch?v=Bnd4IO3f2hU)
- [Getting started with Firebase Hosting (and GitHub Actions!)](https://www.youtube.com/watch?v=P0x0LmiknJc)
