### ISSUE TITLE
🛎️ [STD-4] 회문 판별기 코드의 동작 방식이 궁금해요

### ISSUE THREAD

**Issue by kimzeze** [yamoo9/likelion-FEQA#27]
## 문제 상황

STD 4조 질문입니다.

Javascript 재귀 함수에 대해 찾아보다가 아래와 같은 예제를 보게 되었습니다.

배열의 가장 앞과 뒤를 비교하고 값이 일치하면 slice로 잘라 다시 비교하는 것 같은데

전체적인 코드 동작이 충분히 이해되지 않습니다. (그리고 재귀함수를 사용하지 않고도 똑같이 동작할 수 있을까요?)

```js
const palindrome = (str) => {
  if (str.length <= 1) {
    return true;
  }
  const lastIndex = str.length - 1;

  if (str[0] === str[lastIndex]) {
    return palindrome(str.slice(1, lastIndex));
  } else {
    return false;
  }
};

console.log(palindrome("level"));
console.log(palindrome("우영우"));
```

+ 아래 코드에 lastIndex 대신 str.length를 넣는다면 왜 동작하지 않는건지도 궁금합니다.

```js
return palindrome(str.slice(1, lastIndex)); 
```

**Comment by shoveller** [comment]
안녕하세요. @kimzeze 님!

전형적인 올림피아드/코딩테스트 문제로군요.
이런 유형의 코드는 vscode의 리팩토링 기능으로 변수의 이름을 한글로 바꾸면 난이도가 낮아집니다. (실제 코딩테스트를 하실 때도 도움이 됩니다.)
몇몇 계산식도 한글로 바꿔서 결과를 변수에 담아보았습니다.

```jsx
const 회문판별 = (문자열) => {
  const 판별할_글자가_남지_않았거나_하나만_남았다면 = 문자열.length <= 1
  if (판별할_글자가_남지_않았거나_하나만_남았다면) {
    return true // 회문이다
  }
  
  const 문자열의_길이 = 문자열.length
  const 문자열의_마지막_인덱스 = 문자열의_길이 - 1
  const 첫번째문자 = 문자열[0]
  const 마지막문자 = 문자열[문자열의_마지막_인덱스]
  const 문자열의_양_끝이_같다면 = 첫번째문자 === 마지막문자

  if (문자열의_양_끝이_같다면) {
    const 문자열의_양_끝을_제외한_나머지_문자열 = 문자열.slice(1, 문자열의_마지막_인덱스)
    
    return 회문판별(문자열의_양_끝을_제외한_나머지_문자열)
  } else {
    // 회문이 아니다
    return false
  }
}

console.log(회문판별('level'))
console.log(회문판별('우영우'))
```

저는 올림피아드/코딩테스트가 전문이 아니므로 이 정도의 도움만 드릴 수 있을것 같습니다.
재귀함수는 반드시 반복문으로 바꿀 수 있고, 그 역도 성립합니다.
아래의 유튜브 영상으로 알고리즘을 파악하시면 답을 찾을실 수 있지 않을까 생각해 봅니다. ^^

[자바스크립트 코딩테스트 문제풀이 EP#3 | 팰린드롬/회문 (Palindrome)](https://youtu.be/FczytvdK750)
