### ISSUE TITLE
[LAB-11] context API의 정보로 firebase의 데이터가 가져와지지 않는 문제

### ISSUE THREAD

**Issue by to06109** [yamoo9/likelion-FEQA#270]
## 질문 작성자

최예송

## 문제 상황
유저의 정보를 authUser 컨텍스트로 관리하고 있습니다. authUser 데이터는 다음과 같습니다. 
 ```
{
    name: '최예송',
    email: 'to06109@naver.com',
    uid: 'xzcdsSDAFSDSfdcsdfd'
    isLogin: true,
    categories: 
      {
        Daily: 'DSFSDdsfsfsd',
        Food: 'sdafSDAFSfsad',
        Travel: 'sdafsafsdaSDF',
        Hobby: 'SDFASfdsdfsd'
      }
  }
```
- 코드는 `pages/CategoryPage.jsx`를 보시면 될 것 같습니다. 
로그인 후에 메인페이지에서 각 카테고리 버튼을 누르면 `http://localhost:3000/categories/Hobby` 이런 식으로 라우팅이 되어 카테고리 페이지로 이동합니다. 이때 useParams와 authUser 컨텍스트를 사용해 해당 사용자의 해당 카테고리 uid를 가져오고(user_uid와 category_uid는 문제없이 가져옵니다), 이를 이용해 firebase에 쿼리문을 보내서 이미지 데이터를 가져오려는데 data가 가져와지지 않습니다. 
야무쌤의 onChangeTodoList유틸함수를 변형해 실시간 렌더링을 구현하려고 만든 onChangeCategoryList함수는 `utils/utils.js 파일에 있습니다. 

그리고 콘솔창에 다음과 같은 오류가 뜹니다. 
오류를 보니 ToggleButton과 LikeButton이 함께 문제가 있는 것 같은데 아무리 해봐도 답을 찾지 못해서 질문합니다 ㅜㅜ
![image](https://user-images.githubusercontent.com/69625013/228183702-d016191b-d368-4fb9-a5fa-9301e4049a97.png)

 
- 원하는 상황은 Daily 카테고리 페이지에 사용자가 업로드한 Daily 이미지가 뜨는 것입니다. 
- 로그인 정보는 ID: abc@naver.com / PW: 111111 사용하시면 됩니다!

## 프로젝트 저장소 URL

- 커밋을 하기 애매해서 node_modules를 제외한 작업 폴더를 제출합니다. 
[Asparagus.zip](https://github.com/yamoo9/likelion-FEQA/files/11087465/Asparagus.zip)

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by to06109** [comment]
야무쌤.... 같은 팀원이 바로 전에 단 이슈에 야무쌤 답변을 보고 문제를 해결했습니다... 
images 데이터를 업로드할 때 category 오타가 있었네요 ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ
오타를 고치고 연결해보니 잘 나오는 것을 확인했습니다...

**Comment by yamoo9** [comment]
> 야무쌤.... 같은 팀원이 바로 전에 단 이슈에 야무쌤 답변을 보고 문제를 해결했습니다... images 데이터를 업로드할 때 category 오타가 있었네요 ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ 오타를 고치고 연결해보니 잘 나오는 것을 확인했습니다...

아 분석 중이어었는데? 잘 해결되었나요? 다행입니다~ 예송님 🥹
프로젝트 마무리 잘 하시고 오늘 밤도 화이팅입니다!! @to06109

**Comment by to06109** [comment]
진짜 감사합니다!!!!
