### ISSUE TITLE
[LAB-4] 빌드 파일 빈화면 오류

### ISSUE THREAD

**Issue by ssw6750** [yamoo9/likelion-FEQA#271]
## 질문 작성자

서석원

## 문제 상황

웹펙 세팅으로 빌드 후 build/index.html을 열어보니깐 빈화면이 나옵니다.
절대경로 설정문제 같은데 어떻게 해결해야할지 잘 모르겠습니다.
![빌드버그](https://user-images.githubusercontent.com/73629761/228225432-d11049ae-e53c-40d9-8c5c-af7c5f69ca46.PNG)

## 프로젝트 저장소 URL

[**build 브랜치**](https://github.com/ssw6750/karly-react-project)

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 분석

public/assets 디렉토리의 에셋 출력 경로에 문제가 있었습니다.

## 빌드 구성

createCopyPlugin.js 파일 구성에서 출력 경로를 assets으로 변경합니다.

<img width="1011" alt="" src="https://user-images.githubusercontent.com/1850554/228230969-3703fea0-2b8f-4734-ba9f-c51af51a2b35.png">
<img width="1792" alt="" src="https://user-images.githubusercontent.com/1850554/228231716-fe0b90fc-3760-46b4-b5f9-8386f15f3295.png">


그러면 정상적으로 이미지가 출력될 거에요. 😃

<img width="1786" alt="" src="https://user-images.githubusercontent.com/1850554/228230686-299ff572-ae13-4d1c-8ff2-84efa27d3459.png">

**Comment by ssw6750** [comment]
![image](https://user-images.githubusercontent.com/73629761/228234515-2857eb9c-45d2-467d-b79a-8c1d9b46e790.png)
고쳐봤는데 여전히 빈화면이 뜨네요,,, 
npm run build 하고 build/index.html 확인하면 원래나오는거 맞나요..?

**Comment by yamoo9** [comment]
> ![image](https://user-images.githubusercontent.com/73629761/228234515-2857eb9c-45d2-467d-b79a-8c1d9b46e790.png) 고쳐봤는데 여전히 빈화면이 뜨네요,,, npm run build 하고 build/index.html 확인하면 원래나오는거 맞나요..?

@ssw6750 님 아래 명령을 실행해서 구동해야 합니다. 😊

```sh
npx serve -s build
```

[CRA - Deployment](https://create-react-app.dev/docs/deployment) 참고해보세요.

<img width="1071" alt="" src="https://user-images.githubusercontent.com/1850554/228239837-48f423db-454a-4707-a0a1-6b2d69598f1a.png">

**Comment by ssw6750** [comment]
그러면 해당 프로젝트는 깃허브 페이지로만으로는 배포가 불가능한건가요?

**Comment by yamoo9** [comment]
@ssw6750 님 Create React App 공식 문서대로 진행하시면 배포 가능합니다.

[GitHub Pages 배포](https://create-react-app.dev/docs/deployment/#github-pages)

<img width="1074" alt="" src="https://user-images.githubusercontent.com/1850554/228246527-ffc25157-a4bc-4bef-9248-fce5b01e2cbf.png">
