### ISSUE TITLE
[LAB19] Github page 배포 시 서버 에러

### ISSUE THREAD

**Issue by luvdo0112** [yamoo9/likelion-FEQA#274]
## 질문 작성자

정진이

## 문제 상황

Vite로 만든 작업물을 Github page 배포 시 사이트가 열리지 않습니다.
build를 쉽게 하기 위해서 gh-pages 라이브러리를 사용했습니다.

참고 문서:
vite 공식 문서
https://vitejs-kr.github.io/guide/static-deploy.html

블로그
https://doridori-samsam.tistory.com/31

(로컬에서 페이지를 연 모습 : 정상 작동)
![image](https://user-images.githubusercontent.com/60957961/228289644-b2ee2ffc-2ed7-4813-adca-3373eded30de.png)

(빌드 후 github page에서 연 모습 : 에러 메세지와 함께 빈 화면)
![image](https://user-images.githubusercontent.com/60957961/228292065-31c77767-f24d-4d0a-9715-bff4322dc09f.png)

에러 메세지 : Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.

vite.config.js 파일
base 추가한 모습
![image](https://user-images.githubusercontent.com/60957961/228293515-6f5438a7-062a-4f55-b980-a243f2cb2701.png)

## 프로젝트 저장소 URL

https://github.com/luvdo0112/React-Web-Market

github Page url :
https://luvdo0112.github.io/React-Web-Market/

## 환경 정보

![image](https://user-images.githubusercontent.com/60957961/228294934-9e12b9ef-749c-4eb9-aaaa-dd7097570bca.png)

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)
-

**Comment by yamoo9** [comment]
## 문제 상황 파악

질문이 6시간(오전 1시 쯤) 전에 작성 되었고, 질문을 확인한 현재(오전 7:40) GitHub Pages URL로 접속 했을 때 
빈 화면이 아닌 걸로 보아 문제가 해결된 것이 아닌가 생각이 드네요. 🤔

<img width="1613" alt="" src="https://user-images.githubusercontent.com/1850554/228382936-e4b29569-d784-45f1-9ab9-308c522dec83.png">

<img width="1613" alt="" src="https://user-images.githubusercontent.com/1850554/228383532-5d3157a1-23ac-4a8a-aa47-1164144cb6d5.png">

현재 배포에 문제가 없다고 판단되어 이슈를 클로즈 하겠습니다.
