### ISSUE TITLE
🛎️getElement 와 querySelector / 화살표 함수에서의 클로저

### ISSUE THREAD

**Issue by ovelute53** [yamoo9/likelion-FEQA#28]
## 문제 상황

1. getElement요소와 querySelector를 사용하였을 때 성능적인 측면에서는 getElement요소가 더 유용한데 querySelector의 어떤 장점 때문에 사용 빈도가 quertSelector가 더 많은 지 궁금합니다.

2. 화살표 함수에서도 클로저를 사용할 수 있다고 알고있는데 그 표현 방식을 예시를 통해서 이해하고 싶습니다.

**Comment by yamoo9** [comment]
## 안내

재원 멘토님이 답변할 글이 많은 듯 하여 관련 질문에 대신 답변합니다. 😃

## 답변 1

`getElementById` 또는 `getElementsByTagName` API를 사용해 문서 요소 또는 요소 집합을 탐색할 수 있지만, 
`querySelector` API 만큼 편리하지는 않습니다. 예시를 살펴봅시다.

다음 문서 구조에서 'demo3' 텍스트 정보를 포함한 앵커(anchor) 요소를 선택해볼까요?
한 번 생각해보세요. `getElementById` 또는 `getElementsByTagName` API로 어떻게 선택해야 할 지 말이죠.

```html
<div id="root">
  <nav class="navigation">
    <ul>
      <li><a href="/#demo1">demo1</a></li>
      <li><a href="/#demo2">demo2</a></li>
      <li><a href="/#demo3">demo3</a></li>
      <li><a href="/#demo4">demo4</a></li>
    </ul>
  </nav>
</div>
```

아마도 아래와 같이 작성하려 생각했을 거에요.
음... 요소 하나 선택하기 힘드네요. 😥

```js
const root = document.getElementById('root');
const navigation = root.getElementsByClassName('navigation')[0];
const anchor3 = navigation.getElementsByTagName('a')[2];
```

그렇다면 querySelector API를 사용해 같은 요소를 탐색해볼까요?
오! CSS 선택자를 사용하니 보다 쉽게 요소를 선택할 수 있군요.

```js
const anchor3 = document.querySelector('#root .navigation li:nth-child(3) a');
```

## 답변 2

화살표 함수를 사용해 클로저를 사용할 수 있습니다. 
카운트 다운 함수(클로저)를 화살표함수를 사용해 작성해봅시다.

```js
const setCountDown = (count = 10) => () => {
  if (count === 0) return '카운트 다운 완료!';
  return count--;
};
```

위 함수를 일반 함수로 표현하면 다음과 같이 작성합니다.
화살표 함수 표현보다 복잡한 느낌이 들죠.

```js
function setCountDown(count = 10) {
  return function countDown() {
    if (count === 0) return '카운트 다운 완료!';
    return count--;
  }
};
```

그럼 작성한 setCountDown 함수를 사용해 카운트 다운을 실행하는 함수를 생성합니다.
setCountDown 함수를 실행하면 클로저(폐쇄) 영역 안에 있던 함수가 반환되어 변수(또는 상수)에 참조됩니다.

```js
const countDown10 = setCountDown();

console.log(countDown10()); // 10
console.log(countDown10()); // 9
console.log(countDown10()); // 8
```

다른 카운트 다운 함수도 생성해 활용할 수 있겠죠. (재사용)
숫자 3부터 시작하는 카운트 다운 함수를 생성해 카운트 다운할 수 있습니다. 😃

```js
const countDown3 = setCountDown(3);

console.log(countDown3()); // 3
console.log(countDown3()); // 2
console.log(countDown3()); // 1
console.log(countDown3()); // "카운트 다운 완료!"
```
