### ISSUE TITLE
글로벌 실행 컨텍스트의 특징이 궁금합니다.

### ISSUE THREAD

**Issue by jaesukpark77** [yamoo9/likelion-FEQA#29]
## 문제 상황

1. '글로벌 실행 컨텍스트의 특징으로 무조건 하나의 전역 실행 컨텍스트 만이 존재하며, 애플리케이션이 종료될 때(웹 페이지에서 나가거나 브라우저를 닫을 때)까지 유지하는 것이다.'의미를 예시를 통해 추가적으로 설명 듣고 싶습니다.
2. 스코프 체인의 경우 스택 구조로 생각해도 괜찮은지 궁금합니다.

**Comment by shoveller** [comment]
안녕하세요! @jaesukpark77  님!

- 글로벌 실행 컨텍스트의 특징

전역 실행 컨텍스트를 설명하는 방법은 여러가지가 있겠습니다만, 
저는 이것을 시각화하는 방법으로 설명을 대체할까 합니다.
아래의 코드를 웹 브라우저의 콘솔창에 붙여넣고 실행해 보시겠어요?

```jsx
function 첫번째_함수() {
    debugger;
    console.log("첫번째_함수 실행");
    두번째_함수();
}
function 두번째_함수() {
    debugger;
    console.log("두번째_함수 실행");
    세번째_함수();
}
function 세번째_함수() {
    debugger;
    console.log("세번째_함수 실행");
}
첫번째_함수();
```

그러면 개발자 도구의 호출스택에서 실행 컨텍스트가 차례차례 쌓이는 모습을 엿볼 수 있습니다.
호출스택의 가장 아래에 위치한 `(익명)` 이라는 이름의 콜 스택이 바로 글로벌 실행 컨텍스트입니다.
웹 페이지가 닫히기 전까지 프로그램의 실행을 계속 기다릴 것입니다.
<img width="1203" alt="스크린샷 2023-01-08 오후 1 37 04" src="https://user-images.githubusercontent.com/1357198/211183152-2a354b05-ee69-4189-ab65-b25a79c8515a.png">


- 스코프 체인을 스택 구조로 생각해도 괜찮을까요?

스코프 체인이라는 어휘는 1999년 12월에 발표된 [ECMA-252_3rd](https://www.ecma-international.org/wp-content/uploads/ECMA-262_3rd_edition_december_1999.pdf) (ES3)까지 존재했던 것이라는 것이며,

[2015년 6월에 발표된 ECMAScript 2015(ES5) 부터는 렉시컬 환경(Lexical Environment)의 선언적 환경 레코드(Declarative Environment Record)라는 어휘로 대체되었습니다.](https://262.ecma-international.org/5.1/#sec-D)

그러므로 변수를 결정하는 멘탈 모델을 굳이 스코프 체인이라는 이름의 [연결리스트](https://ko.wikipedia.org/wiki/%EC%97%B0%EA%B2%B0_%EB%A6%AC%EC%8A%A4%ED%8A%B8)로 제한하지 않아도 될 것 같습니다.

또한 [렉시컬 환경은 실행 콘텍스트의 구성요소](https://tc39.es/ecma262/#sec-execution-contexts)이고 [실행 콘텍스트의 자료구조는 스택으로 규정](https://tc39.es/ecma262/#execution-context-stack)되어 있으니 멘탈 모델을 스택으로 가져가도 좋을 것 같습니다.
(그렇다고 해서 스코프 체인을 고집하는 분들과 굳이 논쟁을 하실 필요는 없다고 봅니다.)

질문에서 굉장히 많은 고민을 하신 것을 느낍니다.
설명에서 모자란 부분이 있다면 지적을 부탁드립니다.
좋은 개발자가 되시길 바랍니다 ^^
