### ISSUE TITLE
[LAB-16] 코드 리뷰 요청드립니다.

### ISSUE THREAD

**Issue by no-support** [yamoo9/likelion-FEQA#293]
## 질문 작성자

노지원

## 문제 상황

- 개인 프로젝트로 회원가입, 로그인, 할 일 CRUD를 구현한 프로젝트를 만들었습니다.
- 프로젝트를 만들면서 리팩토링의 여지는 있어보이는데 어떻게 리팩토링해야 할지 모르겠는 부분들이나 질문들을
프로젝트 소스 코드 내에 `// 질문: ` 이라는 주석으로 작성했습니다(총 7개 질문).
- 질문이 많아서... 한 번에 전부 답변해주시지 않고 일부만 답변 주셔도 정말 감사드리겠습니다.

## 프로젝트 저장소 URL

- [프로젝트 주소](https://github.com/no-support/wanted-pre-onboarding-frontend)
[todo.zip](https://github.com/yamoo9/likelion-FEQA/files/11198691/todo.zip)

## 환경 정보

- 운영체제 정보 (윈도우 10)
- Node.js 정보 (예: v18.13.0)
- 라이브러리 정보 (예: React v18.2.0)

**Comment by yamoo9** [comment]
## 코드 리뷰 파일

리뷰한 압축 파일입니다. 질문에 모두 답변을 달았으니 내려 받아 확인해보세요. 😃

[code-review-by-yamoo9.zip](https://github.com/yamoo9/likelion-FEQA/files/11207634/code-review-by-yamoo9.zip)

## 문제가 해결된 데모 영상

아래 영상을 보면 질문의 문제 상황이 모두 해결된 것을 볼 수 있습니다.

https://user-images.githubusercontent.com/1850554/231363699-7674875c-4e68-4c61-a70b-5b502e7727c9.mp4

**Comment by no-support** [comment]
야무쌤 감사합니다! 큰 도움 되었습니다!! 그런데 reducer 함수에서 remove 동작일 때 객체가 아니라 원시 타입을 줘야 바로 화면에서 삭제가 되는지 이해가 되지 않습니다... 😥

**Comment by no-support** [comment]
야무쌤 감사합니다! 큰 도움 되었어요!!!
