### ISSUE TITLE
두개의 차이가 궁금합니다.

### ISSUE THREAD

**Issue by bellaru2022** [yamoo9/likelion-FEQA#30]
## 문제 상황

안녕하세요 선생님 ~~^^
질문 드립니다 

1)
```jsx
function add(arr, el) {
  arr.unshift(el);
  return arr;
}
```

2)
```jsx
function add(arr, el) {
  return arr.unshift(el);
}
```

2개 함수의 차이가 무엇인지 궁금합니다.
감사합니다 :) !!

**Comment by shoveller** [comment]
안녕하세요! @bellaru2022 님! 아주 중요한 지점을 지적하셨네요.
그런데 이 질문은 `문제에 접근하는 요령`부터 설명을 드리면 스스로 공부하실때 더 도움을 드릴 수 있을것 같다는 생각이 듭니다.
이것은 훈계가 아니니 부디 이해를 바랍니다.
`문제에 접근하는 요령`부터 설명이 필요한것 같다는 생각입니다.

1. 무엇을 모르는지를 가장 작은 단위로 쪼개서 파악해 봅시다.
위 질문에서는 `function add(arr, el) {}` 가 중복이 됩니다.
`function add(arr, el) {}` 를 빼 봅시다.
![스크린샷 2023-01-07 오전 4 14 28](https://user-images.githubusercontent.com/1357198/211083367-b08cbd1c-135e-4cca-bfa1-e3364cd6cc9c.png)
그러면 결국 `arr.unshift(el)` 만 남게 되겠네요?
그렇다면, 사용하는 방법에 따라 `arr.unshift(el)` 이 다른 결과를 낸다는 것을 모르는 상태라는걸 스스로 알게 됩니다.
이렇게 되면 `무엇을 모르는지 모르는 상태`를 벗어나게 됩니다.
이제 `arr.unshift(el)` 까지 범위를 좁혔습니다.

2. 모르는 것의 정확한 이름을 찾아봅시다.
`arr.unshift(el)` 에서 `arr` 과 `el` 은 변수의 이름이므로 빼 봅시다.
그러면 `.unshift()`가 남으니 구글에서 검색을 해 봅시다.
최상단에 mdn 의 문서가 나옵니다. 저는 운이 좋았네요.
![image](https://user-images.githubusercontent.com/1357198/211082625-fdc7988e-095e-4083-9b42-e99b82811139.png)
그런데 mdn 에서는 `.unshift()` 를 [Array.prototype.unshift()](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift) 로 부르고 있네요?
그렇네요. 우리는 [Array.prototype.unshift()](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift) 의 정확한 사용법을 배워야 합니다.

3. 모르는 것의 정확한 사용법을 찾아봅시다.
이제 본 문제에 도달했습니다. 이제부터 mdn을 보고 연구를 해야 합니다.
`Array.prototype.unshift()` 을 요리조리 사용을 해 보고, 사용법을 검색해 보는 시간이 꼭 필요합니다.

결론부터 말하면, `Array.prototype.unshift()` 는 원래 배열의 맨 앞에 요소를 추가하고,  그 배열의 길이를 반환합니다.
그렇다는 것은...
1)
```jsx
function add(arr, el) {
  // el을 arr앞에 추가한다
  arr.unshift(el);
  // el을 추가한 arr을 반환한다
  return arr;
}
```

2)
```jsx
function add(arr, el) {
  // el을 arr앞에 추가한다.
  // el을 추가한 arr의 길이를 반환한다 
  return arr.unshift(el);
}
```
두 함수는 전혀 다른 동작을 하고 있다는 것을 알게 되었네요.

부디 이 과정이 와 닿으시기를 바랍니다.
감사합니다.

**Comment by shoveller** [comment]
@bellaru2022 님! 그러면 이 질문의 제목은 어떻게 바꾸면 좋을까요?
제목 수정을 부탁드리고 싶어요.
그 이유도 댓글로 적어주시겠어요?

**Comment by yamoo9** [comment]
> @bellaru2022 님! 그러면 이 질문의 제목은 어떻게 바꾸면 좋을까요? 제목 수정을 부탁드리고 싶어요. 그 이유도 댓글로 적어주시겠어요?
