### ISSUE TITLE
🛎️ 얕은복사와 깊은복사의 차이점이 궁금합니다.

### ISSUE THREAD

**Issue by hayeonn2** [yamoo9/likelion-FEQA#31]
## 문제 상황
- 얕은 복사와 깊은 복사의 정확한 차이점에 대해서 알고싶습니다.
- 그리고 어떤 상황에서 두가지 복사가 이루어지는지에 대해서도 궁금합니다. (꼭 복사를 해주어야 하는 상황 예시같은 것이 있을까요?)

**Comment by shoveller** [comment]
안녕하세요! 질문자님. 아주 중요한 질문을 주셨네요.
**얕은 복사와 깊은 복사에 대한 이해는 앞으로 이어질 react.js 강의에서 굉장히 중요하게 쓰입니다.**

- 얕은 복사와 깊은 복사의 정확한 차이점에 대해서 알고싶습니다.

일단 깊은 복사와 얕은 복사의 차이는 mdn의 설명과 아래의 그림으로 대체하겠습니다.
제가 어떻게 설명을 해도 그림의 해설 이상이 되지 못하네요.
[깊은 복사: 값 자체를 복사](https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy)
[얕은 복사: 메모리의 주소를 복사](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy)
![image](https://user-images.githubusercontent.com/1357198/211191815-19f48faa-4070-491e-b968-b6021e44df90.png)

- 꼭 복사를 해주어야 하는 상황이 있을까요?
react.js 에서 데이터를 다룰 때는 반드시 깊은 복사를 해야 합니다.
react.js 에서 데이터를 수정할 때 깊은 복사를 하지 않으면, 원하는대로 동작을 하지 않습니다.

더 자세한 내용이 필요하시다면 댓글을 남겨주세요.
더 깊은 대화가 오가길 바랍니다. ^^
