### ISSUE TITLE
🛎️ TDD 프로그래밍 학습 시점이 궁금합니다.

### ISSUE THREAD

**Issue by Juhee-Hwang** [yamoo9/likelion-FEQA#32]
## 문제 상황

현업에서 단위 테스트를 굉장히 중요하게 생각한다고 알고 있습니다. 
그래서 TDD 프로그래밍을 적용해서 프로젝트를 진행해보고 싶은데 어느 정도의 레벨이 되었을 때 이걸 도입해보는 것이 좋은지 궁금합니다. 
JavaScript를 어느정도 해보고 나서 TypeScript로 프로젝트를 해보면 좋다! 처럼 이를 시도해보면 좋을 법한 시기가 있을까요?

**Comment by yamoo9** [comment]
## 안내

재원 멘토님이 답변할 글이 많은 듯 하여 관련 질문에 대신 답변합니다. 😃

## 테스트 주도 개발 학습 시점

어떤 로직(logic)을 개발해야 할 때 테스팅이 필요하다고 경험한 시점에 학습하면 좋습니다.
예를 들면 아래와 같은 상황을 경험했을 때 테스트가 필요하다고 느낄 수 있습니다.

> 약 3개월 전에 작성했던 함수가 버그를 유발했습니다. 
> 기억이 가물가물한데 처음부터 그 함수 로직을 다시 살펴보려니 골치 아픕니다.

> 함께 프로젝트를 하는 팀 동료가 물었습니다.
> OO님이 작성한 함수가 _____ 경우에도 잘 작동하는 지 테스트 했나요? 문제가 발생하던데 이유가 뭔가요?

참고로 React 수업 시간에 테스트 주도 개발 방식으로 컴포넌트를 설계하는 것을 학습합니다.
구현해야 할 컴포넌트 기능을 코드 작성 전에 생각하고, 정리한 다음에 테스트 코드를 먼저 작성할 겁니다.
그리고 작성된 테스트 코드가 실패하지 않도록 컴포넌트 코드 로직을 작성할 거에요.
그렇게 여러 테스트 검수를 모두 마친 컴포넌트는 완성도가 높아집니다.

**정리할께요. 지금은 JavaScript 수업에 집중해주세요.
JavaScript 프로그래밍에 익숙해지면 그 때 생각한 바를 구현할 때 테스트 주도 개발을 반영해보세요. 😊**
