### ISSUE TITLE
Number.prototype 과 valueOf() 메소드 관련 문제 질문있습니다!

### ISSUE THREAD

**Issue by jangjihoon96** [yamoo9/likelion-FEQA#33]
책으로 공부하던 중 나오는 예제문제가 이해가 안돼서 질문드립니다!

```jsx
Number.prototype.power = function(n = 2){
  return this.valueOf() ** n
}

const a = 12;
console.log('a.power() :', a.power());
console.log('a.power(3) :', a.power(3));
console.log('a.power(4) :', a.power(4));
```

질문 1) `Number.prototype`을 사용한 이유?

질문 2) 함수안에 `this.valueOf()` 에 의미?

**Comment by shoveller** [comment]
안녕하세요! @jangjihoon96 님. 아주 좋은 질문을 주셨네요.
프로토타입 기반 상속에 대한 이해를 드릴 수 있으면 기쁘겠습니다.

질문 1) `Number.prototype`을 사용한 이유?
자바스크립트는 프로토타입 기반 객체지향 언어입니다.
모든 생성자 함수는 그것이 원래 존재해야 모습에 해당하는 프로토타입을 가지고 있고, 
생성자 함수로 생성한 변수들(인스턴스라고도 부릅니다)은 그 프로토타입을 물려받습니다.
위의 코드에서 `a`는 `Number` 생성자 함수의 자손이므로 `Number.prototype` 을 사용할 수 있습니다.

위의 코드에서 `Number.prototype` 에 `power` 라는 `함수`를 추가해주고 있지요?
그러면 모든 `Number` 생성자 함수의 자손인 숫자는,`power` 라는 `메소드`를 호출할 수 있게 됩니다.
그러면 거듭제곱을 구하기가 훨씬 편해지겠네요.
(엄밀하게 따지면, 숫자는 `Number` 생성자 함수의 자손이 아닙니다. 맨 마지막에 설명이 있습니다.)

질문 2) 함수안에 `this.valueOf()` 에 의미?
this가 숫자가 아니기 때문입니다.
아래의 코드를 개발자도구에 붙여넣고 확인을 해 보시겠어요?
```jsx
Number.prototype.power = function(n = 2){
  debugger;
  return this.valueOf() ** n
}

const a = 12;
console.log('a.power() :', a.power());
```

그러면 아래와 같은 경험을 할 수 있습니다.
![스크린샷 2023-01-07 오전 5 57 25](https://user-images.githubusercontent.com/1357198/211099099-83d4cea7-1d15-4f00-a172-2cece3bd032d.png)

`Number` 생성자로 생성한 변수(=인스턴스)는 숫자가 아닙니다.
이것을 숫자로 만들려면, `Number.prototype.valueOf` 를 호출해주어야 합니다.
![스크린샷 2023-01-07 오전 6 06 16](https://user-images.githubusercontent.com/1357198/211100281-c4334bc7-a3bc-422d-8a15-b0a4099a90d1.png)

그런데, 아래의 코드에서는 `Number.prototype.valueOf` 를 사용하지 않잖아요?
왜죠?
```
const a = 12;
console.log('a.power() :', a.power());
```

그것은 자바스크립트 엔진이 
```
const a = 12;
console.log('a.power() :', a.power());
```
를
```
const a = 12;
console.log('a.power() :', new Number(a).power());
```
로 해석하기 때문입니다.
이것을 mdn 에서는 [원시 래퍼 객체](https://developer.mozilla.org/ko/docs/Glossary/Primitive#javascript%EC%97%90%EC%84%9C%EC%9D%98_%EC%9B%90%EC%8B%9C_%EB%9E%98%ED%8D%BC_%EA%B0%9D%EC%B2%B4) 라고 합니다.
숨어있는게 꽤 많지요?

### 결론

이제 첨부해주신 코드에 주석을 달아서 정리해봅시다.
이런 모습이 되겠네요.
```jsx
// Number.prototype 에 power라는 함수를 추가한다
Number.prototype.power = function(n = 2){
  // 이 시점의 this는 Number 이다.
  return this.valueOf() ** n
}

const a = 12;
// 자바스크립트 엔진은 new Number(a).power() 로 해석한다 
console.log('a.power() :', a.power());
console.log('a.power(3) :', a.power(3));
console.log('a.power(4) :', a.power(4));
```

자바스크립트의 원시값에는 래퍼객체가 기능한다는 사실을 이해하시면, 객체지향 코드를 좀 더 쉽게 작성하실 수 있겠습니다.

**Comment by shoveller** [comment]
그러면 @jangjihoon96 님.
예시로 든 코드에는 어떤 단점이 있을까요?  
```jsx
Number.prototype.power = function(n = 2){
  return this.valueOf() ** n
}

const a = 12;
console.log('a.power() :', a.power());
console.log('a.power(3) :', a.power(3));
console.log('a.power(4) :', a.power(4));
```

**Comment by shoveller** [comment]
위의 코드를
```jsx
Number.prototype.power = function(n = 2){
  return this.valueOf() ** n
}

const a = 12;
console.log('a.power() :', a.power());
console.log('a.power(3) :', a.power(3));
console.log('a.power(4) :', a.power(4));
```

클래스 문법으로 만들면 이런 모습이 됩니다.
java 등에 익숙한 사람이라면 이 코드가 더 익숙할 것입니다.
```jsx
class MyNumber extends Number {
  power(n = 2) {
    return this.valueOf() ** n
  }
}

const a = new MyNumber(12)
console.log('a.power() :', a.power())
console.log('a.power(3) :', a.power(3))
console.log('a.power(4) :', a.power(4))
```
