### ISSUE TITLE
🛎️ ES6 클래스 문법 추가에 관해서 달라진 점 특징 및 장점이 궁금합니다

### ISSUE THREAD

**Issue by ukssss** [yamoo9/likelion-FEQA#34]
## 문제 상황

ES6 문법에서 클래스 문법이 추가되면서 어떠한 장점이 생겼는지 궁금합니다.
함수형 프로그래밍 언어로 생각했던 JS 인데 클래스 문법도 추가되면서 객체형 프로그래밍 언어로도 접근할 수 있게 되었는데, 이를 통해 얻는 장점이나 추가된 특징들을 알고 싶습니다.

## 환경 정보

X

**Comment by shoveller** [comment]
안녕하세요! @ukssss 님.
먼저 자바스크립트는 객체지향형 언어(Object Oriented Language)라는 점을 먼저 짚고 넘어가고 싶군요.
이 내용은 자바스크립트의 산업 표준을 정의한 [ECMAScript international 의 스펙 문서](https://262.ecma-international.org/13.0/#sec-overview)에 정의가 되어 있습니다. 단지 함수형 언어의 기능을 제공하는 수준이라고 봐 주시면 좋을것 같아요.
그리고 함수형 언어에는 `this`로 대표되는 맥락(context)이 있어서는 안 됩니다.

### 클래스 문법이 도입이 되면서 어떤 장점이 생겼는가?
자바스크립트는 프로토타입에 기반한 객체지향 언어입니다.
자바나 C++등의 언어와 비교했을 때, 객체지향을 구현한 방식이 유별나게 다릅니다.
그래서 객체지향 언어이면서도 객체지향적으로 프로그램을 만들기가 어려웠습니다.
이것에 대한 문제제기가 꾸준히 있어왔기에 지금 클래스 문법이 도입된 것으로 알고 있습니다.
프로토타입 기반 객체지향 언어라는 본질은 바꾸지 않고, 자바나 C++와 비슷한 문법으로 클래스를 정의하는 기능이 추가된 것입니다.
예전에 비해서는 클래스를 사용하는 난이도가 많이 낮아졌다고 요약할 수 있겠습니다.

### 참고자료
좋아했던 주제라 나름 수집한 자료가 있습니다.
시간이 되실때 확인을 해 보셔도 좋겠습니다.

- [함수형 언어의 역사](https://www.youtube.com/watch?v=VXqiLvf_uWw)
- [자바스크립트는 유일하게 살아남은 프로토타입 기반 객체지향 언어](https://medium.com/@limsungmook/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%8A%94-%EC%99%9C-%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85%EC%9D%84-%EC%84%A0%ED%83%9D%ED%96%88%EC%9D%84%EA%B9%8C-997f985adb42)

도움이 되었기를 바랍니다.
감사합니다 ^^

**Comment by shoveller** [comment]
마침 #33 이 비슷한 이슈를 다루고 있습니다.
참고해보시면 좋을것 같아요.

**Comment by yamoo9** [comment]
[#11 답변 1](https://github.com/yamoo9/likelion-FEQA/issues/11#issuecomment-1372349074)에서 함수가 반환하는 객체와 클래스를 사용해 생성하는 객체에 대해 다룬바 있습니다. 
관련 답변 글에서 예시로 작성된 클래스 프로그래밍 코드도 참고하면 좋겠네요. 😃
