### ISSUE TITLE
🛎️ html 요소에 접근하기

### ISSUE THREAD

**Issue by no-support** [yamoo9/likelion-FEQA#37]
document.querySelector(':hover')와 같은 의사 클래스는 요소에 접근이 가능한데 ::before, ::after같은 가상 요소는 접근이 안 되는 거 같은데 이유가 뭘까요? 그리고 의사 클래스도 일부(:first-child)는 쿼리셀렉터 메소드로 접근 불가능한 거 같은데 왜 이 이런식으로 동작하는지 궁금합니다. 웹 페이지를 만드는 순서와 관련이 있는 걸까요?

**Comment by yamoo9** [comment]
### CSS 유사 요소가 `querySelector`에서 작동하지 않는 이유

[CSS 유사(의사) 요소](https://developer.mozilla.org/ko/docs/Web/CSS/Pseudo-elements)는 [Selector API (공식 문서)](https://www.w3.org/TR/selectors-api/#grammar)가 명시한 대로 **어떠한 요소도 반환하지 않기 때문**입니다.

![](https://user-images.githubusercontent.com/1850554/211506676-7d5c1dbf-ef7a-4f89-9d13-2b729e60627a.png)

### 결론

**Selector API 제작자(설계자)가 그 부분은 반영을 안되도록 만들었으므로 작동하지 않는 것입니다.** 😁
