### ISSUE TITLE
🛎️ console.log(this)는 console이 찍혀나와야 하지 않나요?

### ISSUE THREAD

**Issue by no-support** [yamoo9/likelion-FEQA#38]
this는 실행 시에 호출한 객체인데, console.log(this)를 호출한 객체는 console 아닌가요? 왜 window가 나오는 건가요..?

**Comment by yamoo9** [comment]
혼동스런 `this`가 가리키는 대상을 잘 생각해봅시다. 😃

`console` 객체의 `log` 메서드가 실행되는 내부에서 `this`가 참조하는 것이 `console` 객체입니다.

```js
const myConsole  = {
  log(...data) {
    // this ← myConsole 객체
  },
};
```

`log` 메서드에 전달되는 `this`는 `console.log()` 메서드가 실행되는 영역을 가리킵니다.

```js
myConsole.log(this); // ← 실행 영역의 this 참조 전달
```

그럼 다시 `console.log()`와 this에 대해 생각해보세요. 🧐

```js
document.addEventListener('click', function() {
  console.log(this); // ← this === document 객체
});
```

```js
document.addEventListener('click', () => {
  console.log(this); // ← this === window 객체
});
```
