### ISSUE TITLE
[STD-6] strict mode 모드 활성화에 대해

### ISSUE THREAD

**Issue by jaesukpark77** [yamoo9/likelion-FEQA#39]
## 문제 상황

- 오늘 수업 시간에 모듈화에 대한 내용을 학습하던 중 범쌤께서 모듈화는 strict mode가 된다고 설명을 해주셨습니다. 그러면 일반 script에서 'use strict'을 이용하는 거랑 모듈화를 통해 strict mode가 되는 거는 어떠한 차이가 있는지 궁금합니다!!!

**Comment by yamoo9** [comment]
## 모듈이 아닌 파일은 기본적으로 sloppy mode

웹 브라우저에서 호출되는 일반 JavaScript 파일은 모듈 파일이 아니므로 
기본적으로 엄격 모드([strict mode](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Strict_mode))가 아닌, 느슨한 모드([sloppy mode](https://developer.mozilla.org/en-US/docs/Glossary/Sloppy_mode))로 작동합니다.

그러므로 사용자가 JavaScript 엔진의 최적화 작업을 어렵게 만드는 실수들을 바로 잡기 위해 
명시적으로 `"strict mode"` 코드를 파일의 상단 또는 함수 선언 내부에 작성해야 합니다.

## 모듈 파일은 기본적으로 strict mode

반면 모듈 파일로 인식(`type="module"` 또는 Node.js 런타임 환경에서의 JavaScript 파일)될 경우,
기본적으로 엄격 모드가 활성화됩니다. 즉, 사용자가 명시적으로 `"strict mode"` 코드를 작성할 필요가 없습니다.

## 정리(요약)

파일의 모듈 여부에 따라 `"strict mode"` 코드를 명시적으로 작성해야 하거나, 생략 무방함의 차이일 뿐입니다. 😄
