### ISSUE TITLE
[STD-1] forEach문 매개변수 array 사용 예제

### ISSUE THREAD

**Issue by pingandthepong** [yamoo9/likelion-FEQA#40]
안녕하세요. 서재원 멘토님!
forEach문에서 배열 매개변수 array를 사용해 호출하면, 배열의 요소 수만큼 배열이 출력되는 것을 확인했는데요.
제가 배경지식이 많지 않아 실무에서 어떻게 사용되는지 감이 잡히지 않아, 간단히 알고싶습니다.
예제로 보여주셔도 괜찮고, 설명만 해주셔도 괜찮습니다.
감사합니다.

<img width="647" alt="forEach질문" src="https://user-images.githubusercontent.com/85279489/212321941-99b0a3e5-f551-49ac-8542-75ca52114c74.png">

**Comment by shoveller** [comment]
안녕하세요! @pingandthepong 님!

저도 실무에서 세번째 인수를 사용할 일은 없었네요.
하지만 아주 tricky 한 방법으로 사용하는 방법이 있긴 해요.
원래 `forEach` 는 실행중에 `break`로 멈출수가 없습니다.

코딩테스트 문제 중에는 반복문을 실행하는 중에 `break` 로 멈춰야 하는 경우가 있거든요.

```jsx
var 배열 = [1, 2, 3, 4, 5]
배열.forEach((number, index, array) => {
  // 이 시점에서 실행을 멈췄으면 좋겠는데
  if (index === 2) {
    // forEach 에서는 break 를 사용할 수 없다!
    // break;
  }
  console.log(number)
})

console.log(배열)
```

하지만, 세번째 매개변수 `array` 를 사용하면 원본 배열을 실행중에 조작해서 중간에 멈출수가 있어요.
```jsx
var 배열 = [1, 2, 3, 4, 5]
배열.forEach((number, index, array) => {
  // 이 시점에서 실행을 멈췄으면 좋겠는데  
  if (index === 2) {
    // 원본 배열의 길이를 줄여서 실행을 멈춰버린다
    array.length = index + 1
  }
  console.log(number)
})

console.log(배열)
```

하지만 위의 방법은 원본 배열을 고쳐버리기 때문에 아주 조심해서 써야 합니다.
그래서 코딩테스트를 보실 때에는 `for ~ of` , `for ~ in` 이 안전합니다.
```jsx
var 배열 = [1, 2, 3, 4, 5]
for (const index in 배열) {
  // 이 시점에서 실행을 멈췄으면 좋겠는데
  if (index === '3') {
    break
  }

  console.log(배열[index])
}
```

### 결론

`forEach` 의 세번째 매개변수 `array` 는 원본이므로, 실행중에 원본을 고칠때 사용할 수 있다.
원본을 고쳐버리므로 주의해서 사용하자

**Comment by pingandthepong** [comment]
아하 세 번째 매개변수 array를 사용할 경우 원본배열이 고쳐지네요! 감사합니다 :)
