### ISSUE TITLE
🛎️ 라이브 서버 첫 구동시와, 페이지 reload 시의 콘솔 값 변화에 대해

### ISSUE THREAD

**Issue by sykang013** [yamoo9/likelion-FEQA#41]
## 문제 상황
질문 작성자: 5.강수영

this에 대해 좀 더 알아보려 연습하던 중 발생한 의문입니다.
아래와같이 코드를 적고, 처음으로 live server를 구동했을 때, 브라우저 콘솔창에 'Object'가 찍히는 것을 발견했습니다.
그런데 같은 내용을 저장/또는 새로고침하여 페이지가 reload 되니, {객체}가 직접 나오더라구요. 
let과 var의 차이인가 하여 테스트해보았습니다만, 결과는 똑같았습니다.

의문점이 들어 질문 올려봅니다!

---

**사진1) 콘솔창 Object**
![스크린샷 2023-01-13 오후 11 18 17](https://user-images.githubusercontent.com/113448786/212342958-731628fa-1a5d-48ef-bd10-22ecb0700578.png)
**사진2) 콘솔창 Object 아래화살표를 열었을 때**
![스크린샷 2023-01-13 오후 11 32 22](https://user-images.githubusercontent.com/113448786/212344787-e609d021-3ed9-46b5-9d81-14b8c6a6da31.png)
**사진3) 페이지를 reload 했을 때** 
![스크린샷 2023-01-13 오후 11 19 08](https://user-images.githubusercontent.com/113448786/212343161-4dd44a5f-652c-4644-bd65-f4759d50cffc.png)

---

**html 코드**
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="./main.js"></script>
    <title>startLet</title>
  </head>
  <body></body>
</html>

```

**JS 코드**
```
let someone = {
  name: "suyeong",
  whoAmI: function () {
    console.log(this);
  },
};

someone.whoAmI();

```

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 : macOS
- Node.js 버전 (예: v16.14.0)

**Comment by yamoo9** [comment]
안녕하세요 수영님 😃
질문 내용에서 말한 의문점이란 것이 Live Server 구동 시, 
처음 표시된 Object와 웹 브라우저가 새로고침 되었을 때 표시되는 객체 표기인 듯 파악됩니다.

live server 구동 시 `Object`로 표시되지만, 화살표를 열어 확인해서 알 수 있듯 결과는 `{ ... }`와 동일합니다.

<img alt="" src="https://user-images.githubusercontent.com/1850554/212470665-a6fdaba0-ff64-4a81-9352-529beec2e010.png" height="180" />

이는 웹 브라우저에서 표시하는 방법의 차이일 뿐, JavaScript 언어 관점에서는 큰 차이가 없습니다.

웹 브라우저 내부에서 왜 이렇게 표시하는 방법이 다른 지는 웹 브라우저 개발자가 아니라서 정확히 알 수 없지만
확인한 결과만 보면 **처음 웹 개발 도구(devtools)를 열 때만 `Object`로 표시되고, 개발 도구가 
열린 상태에서는 새로 고침 시 `{ ... }` 방법으로 표시됩니다.**
