### ISSUE TITLE
🛎️ getComputedStyle 결과값이 vscode에서랑 브라우저에서랑 다른이유

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#42]
## 문제 상황

style 로 font-size 를 바꿨을때 계산된 값이 나오지 않는것까지는 알겠습니다

근데 콘솔창과 vscode 에서 직접 찍어봤을때 getComputedStyle 결과값이 달라

질문합니다.  밑에 주석 남겨놨습니다!

![image](https://user-images.githubusercontent.com/109938280/212348993-375cb0cd-29cd-4ade-9601-567387425ed2.png)

```JS
const first = getNode(".first");

console.log(first.className);

first.style.backgroundColor = "red";
first.style["font-size"] = '100px'

/* 계산된 스타일 읽기 ------------------------------------------------------- */

let size = getComputedStyle(first)['font-size'];

console.log(size);  // ! 100px 이 나올줄 알았는데 32px이 뜹니다 ,  하지만 브라우저 콘솔창에 직접  getComputedStyle(first)['font-size'] 을 입력하면 100px이 뜹니다

css(".first", "font-size"); // get
// css(".first", "font-size", "100px"); // set



```

**Comment by yamoo9** [comment]
질문에 남겨진 코드 그대로 [예시](https://jsbin.com/qapupequpe/edit?html,js,console,output)를 작성해봤습니다.
결과는 아래 이미지와 같이 `'32px'`이 아니라,`'100px'`이 나옵니다. 👀

<img width="1211" alt="" src="https://user-images.githubusercontent.com/1850554/212425619-7a67ca2c-5cd5-4b17-a5c7-390d388b2033.png">

별도로 추가 작성된 코드가 없음에도 @5wintaek님 에디터에 작성된 코드의 실행 결과가 다른 것은 
코드 전문 또는 문제가 되는 파일들을 묶어 압축해서 첨부해야 원인 분석이 이뤄질 듯 합니다. 🧐

[예시](https://jsbin.com/qapupequpe/edit?html,js,console,output) 결과를 확인해보세요.

```js
function getNode(selector, context = document) {
  return context.querySelector(selector);
}

/* --------------------------------------------------------------------- */

const first = getNode(".first");

console.log(first.className);

first.style.backgroundColor = "red";
first.style["font-size"] = '100px';

/* 계산된 스타일 읽기 ------------------------------------------------------- */

let size = getComputedStyle(first)['font-size'];

console.log(size);
```
