### ISSUE TITLE
🛎️ [STD-1] debounce 와 throttle

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#43]
## 문제 상황

debounce와 throttle 설명 해주시면 감사하겠습니다 ㅠ

```JS
function debounce(callback, limit = 2000) {
  let timeout;
  return function (...args) {
    console.log(args);
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      callback.apply(this, args);
    }, limit);
  };
}





function throttle(callback, limit = 1000) {
  let waiting = false;
  return function () {
    if (!waiting) {
      callback.apply(this, arguments);
      waiting = true;
      setTimeout(() => {
        waiting = false;
      }, limit);
    }
  };
}
```

**Comment by simseonbeom** [comment]
안녕하세요 승택님 :)
debounce와 throttle의 실행 흐름에 대해 알아보겠습니다.

### **1. debounce**
debounce는 입력 주기가 끝남과 동시에 이벤트를 호출하는 특징을 가지며, 
이를 구현하기 위해  정해준 시간 이후에 함수가 실행될 수 있는`setTimeout` 내장함수를 사용합니다.

`setTimeout`함수는 실행과 동시에 자신의 타이머 값을 내뱉게 되는데 이 값을 가지고 스케쥴상에 등록된 타이머를 해제`clearTimeout`시킬 수 있습니다.

![image](https://user-images.githubusercontent.com/35365227/212510274-d3000f06-fd9f-4c86-b888-2372da471184.png)

그래서 이렇게 하단에 타이머를 등록하면 상단의 변수로 타이머의 id값을 담아두고,  다음 debounce함수가 실행되면 기존에 스케쥴링 되어있던 타이머를 해제하고 다시 타이머를 재 등록하게 됩니다. 
![image](https://user-images.githubusercontent.com/35365227/212511111-41098335-e4d4-42a5-af75-bdfe9783d51a.png)

처럼 debounce함수가  여러번 실행이 된다면 결국 기존에 타이머들은 설정과 제거를 반복하며 전혀 실행되지 않는 흐름을 가지다, 마지막 debounce 함수에서 등록된 새롭게 생성된 타이머가 일정 시간 이후 딱 한번만 호출되므로,   마우스가 멈춘 후 단 한번만 실행이 되는 함수가 됩니다.

---


### **2. throttle**

throttle은 입력 주기를 방해하지 않고, 일정 시간 동안의 입력을 모아, 정해진 시간마다 이벤트를 호출하는 개념으로 정해진 시간에 맞춰 주기적으로 함수를 호출할 수 있습니다.

함수안에 상태 변수의 값이 거짓일 경우만 실행이 될 수 있는 조건문을 만든 후 함수를 실행하고, 실행과 동시에 상태 변수의 값을 true로 변경하면 해당 함수는 단 한번만 실행이 되는 함수가 됩니다.
![image](https://user-images.githubusercontent.com/35365227/212513727-23721f8e-88a8-4688-8c0d-630e76d275d3.png)

이후 실행된 조건문 안을 확인하면,  현재`true`로 변경된 `waiting` 변수를 `setTimeout` 함수를 사용해 일정 시간이 지난 후  다시`false`로 변경하는 작업을 거치게 되고, `false`로 변경된 상태변수는 다시 조건문에 들어와 함수를 한번 실행하고 다시`true` 상태로 변경이 됩니다. 이후 타이머가 다시`false`를 만드는 과정을 거치게 되죠, 

이렇게`waiting` 변수를 주기적으로`true`와`false`로 바꿔가며 정해진 시간동안 콜백함수를 실행시키게 만드는게 throttle의 개념입니다.

중요한건 debounce와 throttle 함수 모두  한번만 실행하고 끝나는게 아닌 지속적으로 호출이 된다는 점을 잊으시면 안됩니다. ! 
지속적인 호출이 있어났을 때 안쪽 함수의 흐름을 이해해보시면 좋을것 같습니다 :)

**Comment by shoveller** [comment]
안녕하세요! @5wintaek 님!
범쌤이 너무 설명을 잘 해주셔서 제가 더 설명하기가 민망하네요.
답변을 위해 여러모로 조사를 해 봤는데, 요즘엔 신입의 기술면접에서도 디바운싱과 쓰로틀링을 물어보는 추세인가 봅니다.
꽤 고급기술인데 시대가 많이 변했군요!

저는 쓰로틀링 기법과 디바운싱 기법을 검색창을 구현할때 딱 한번 써 보았습니다.
검색창에 텍스트를 입력하면 그것의 결과값을 서버에 요청하는 용도로요.
텍스트 입력 이벤트는 아주 빠르게 발생하기 때문에 그 때마다 서버가 반응하게 만들면 서버에 무리가 가거든요.

아래는 검색창을 구현하는 상황을 가정하고 @5wintaek 님께서 보여주신 코드로 만든 예제입니다.
[쓰로틀링 테스트](https://codepen.io/shoveller/pen/LYBjVaL?editors=1010)
[디바운싱 테스트](https://codepen.io/shoveller/pen/OJwjyJr?editors=1010)

실제로 동작을 해 보시고, 그 소감을 댓글로 남겨주시겠어요?
어떤 상황에서 사용할 수 있을지, 그 상황과 대면하기 위해선 어떤 준비가 필요한지를 고민해본다면, 
그것이 면접 준비도 겸할 수 있지 않을까 생각해봅니다.
