### ISSUE TITLE
🛎️ [STD-3] 가장 작은 단위의 유틸함수와 가장 큰 단위의 유틸함수에 대해 

### ISSUE THREAD

**Issue by sykang013** [yamoo9/likelion-FEQA#44]
## 문제 상황

질문작성자: 강수영

서재원멘토님께 드리는 질문입니다! 아는 것이 많지 않아 질문이 두리뭉술 할 수 있는 점 양해부탁드립니다.

1)실무에서 최종적으로 완료된 프로젝트 파일들과, 최적화된 프로젝트 파일들의 비교 예시를 볼 수 있을까요?
-.어떤 관점에서 얼마나 어떻게 차이가 나는가? 데이터는 얼마나 줄어들고, 그 밖의 크게 바뀌는 사항은?

2)함수형 프로그래밍에서 가장 작은 단위의 유틸함수와 가장 큰 단위의 유틸함수 실무예제를 볼 수 있을까요?
-.함수는 어디까지 쪼개질 수 있으며, 쪼개는 기준은 무엇이고, 또 반대로 어디까지 커질 수 있는가?

---

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by shoveller** [comment]
안녕하세요 @sykang013 님.

말씀해주신 내용은 실제로 프로젝트에 투입이 되면 고민하게 될 문제일것 같습니다.
이미 그 시점을 내다보셨다니 좋은 개발자가 되실것 같습니다.
마침 여기에 제가 실제로 풀어야 했던 문제가 있습니다.
저작권이 지엄하여 실제 코드를 옮겨드리기는 어려울 것 같습니다.
하지만, 개선이 필요한 코드와, 개선된 코드는 보여드릴 수 있을것 같습니다.
이해를 돕기 위해 함수와 변수의 이름은 한글로 지정했습니다.

# 문제
```bash
Q: 사업자등록번호는 10자리의 연속한 숫자값이다. 
   아래의 유효성 조건을 만족하는 사업자등록번호 판별 함수를 구현하라.
   
[유효성 조건]
규칙 1 : 입력받은 값에서 8자리를 가져온다. 
        가져온 값의 각각의 자리에 1, 3, 7, 1, 3, 7, 1, 3 을 곱한 값을 더한 값을 구한다.
규칙 2 : 입력받은 값의 9번째 자리값에 5를 곱한 값을 구한다. 
        그 값의 십의 자리, 일의 자리값을 더한 값을 구한다.
규칙 3 : 10 에 (규칙 1 + 규칙 2) 을 10으로 나눈 나머지 값을 뺀 값을 구한다.
        
규칙 3과 입력받은 값의 끝자리가 같으면 유효한 사업자등록번호이다.
```

자바스크립트 언어에 익숙하지 않으시거나, 기능을 쪼개는 것에 익숙하지 않은 분들은 아래와 같은 코드로 옮기곤 합니다.
이것을 `최종적으로 완료된 프로젝트 파일` 로 가정하겠습니다.
함께 일하는 동료가 어떤 사람이냐에 따라 다를 수 있겠습니다만, 이렇게 구현한 코드는 merge가 되지 않을 수 있습니다.

### 개선이 필요한 코드
```jsx
const 사업자_등록번호_판별기 = (입력값 = '') => {
  const 앞에서부터_8자리 = 입력값.substring(0, 8)
	
  let 규칙1 = 0
  let 규칙1_가중치 = [1, 3, 7, 1, 3, 7, 1, 3]
  for (let 인덱스 = 0; 인덱스 < 8; 인덱스++) {
    let 자릿수 = 앞에서부터_8자리[인덱스];
    let 가중치 = 규칙1_가중치[인덱스]
    규칙1 = 규칙1 + (parseInt(자릿수, 10) * 가중치)
  }
	
  let 앞에서부터_9번째자릿값 = 입력값.substring(8,9)
  let 중간결과값 = (parseInt(앞에서부터_9번째자릿값, 10) * 5) + ''
  let 십의자리 = parseInt(중간결과값[0], 10)
  let 일의자리 = parseInt(중간결과값[1], 10)
  let 규칙2 = 십의자리 + 일의자리
	
  let 규칙3 = 10 - ((규칙1 + 규칙2) % 10)
  let 끝자리값 = parseInt(입력값.substring(9,10), 10)
	
  return 규칙3 === 끝자리값
}

console.log(사업자_등록번호_판별기('1248100998'))
```

아래는 같은 내용을 여러개의 함수로 쪼갠 코드입니다.
함수가 하나의 역활만 담당하고, 스스로를 설명할 수 있게 만들었습니다.
### 개선한 코드

```jsx
const 숫자로바꾸기 = (문자열 = '') => {
  return parseInt(문자열, 10)
}

const 문자로바꾸기 = (숫자 = 0) => {
  return `${숫자}`
}

const 규칙1_구하기 = (가중치_배열 = []) => (문자열 = '') => {
  // 규칙 1 : 사업자번호 앞 8자리 수에 각각 1 3 7 1 3 7 1 3 을 곱한 값을 더한 값
  const 규칙1 = 가중치_배열.reduce((누적, 가중치, 인덱스) => {
    const 자릿수 = 숫자로바꾸기(문자열[인덱스])

    return 누적 + (자릿수 * 가중치)
  }, 0)

  return 규칙1
}

const 규칙2_구하기 = (문자열 = '') => {
  // 규칙 2 : 사업자번호 9번째 자리값과 5를 곱한 값의 십의 자리값과 일의 자리값을 더한 값
  const [십의자리, 일의자리] = 문자로바꾸기(숫자로바꾸기(문자열) * 5)
  const 규칙2 = 숫자로바꾸기(십의자리) + 숫자로바꾸기(일의자리)

  return 규칙2
}

const 규칙3_구하기 = (규칙1 = 0, 규칙2 = 0) => {
  // 규칙 3 : 10 – (규칙 A + 규칙 B) % 10 값과 맨 끝자리 숫자가 일치해야 유효
  return 10 - ((규칙1 + 규칙2) % 10)
}

const 사업자_등록번호_판별기 = (입력값 = '') => {
  const 규칙1 = 규칙1_구하기([1, 3, 7, 1, 3, 7, 1, 3])(입력값)
  const 앞에서부터_9번째자릿값 = 입력값.substring(8,9)
  const 규칙2 = 규칙2_구하기(앞에서부터_9번째자릿값)
  const 규칙3 = 규칙3_구하기(규칙1, 규칙2)
  const 끝자리값 = 입력값.substring(9,10)
  const 마지막값 = 숫자로바꾸기(끝자리값)

  // 규칙 3과 입력받은 값의 끝자리가 같으면 유효한 사업자등록번호이다.
  return 규칙3 === 마지막값
}

console.log(사업자_등록번호_판별기('1248100998'))
```

# 결론
원고를 쓰다보니.. @sykang013 님께는 코딩 스타일에 대한 피드백이 필요한 타이밍이 아닐까? 라는 생각이 듭니다.
그런데 요즘은 이 피드백을 기계가 일부분 담당하게 만들 수 있단 말이지요?
eslint 와 prettier , husky 라는 node.js 기반 도구를 사용하면 코딩 스타일을 계속 교정받을 수 있습니다.
이 도구들은 헬스장의 헬스 트레이너처럼 바른 코딩 스터일을 유지하도록 잔소리를 합니다.
[함수형 프로그래밍 원칙을 강제하는 플러그인](https://github.com/eslint-functional/eslint-plugin-functional)을 사용하면, 자기도 모르게 함수형 프로그래밍 원칙이 몸에 익게 되지요.

eslint 와 prettier , husky 는 결국 react.js 시간에 배울 가능성이 높습니다.
이것들의 선행학습을 진행하는게 좋을수도 있겠습니다..

**Comment by shoveller** [comment]
아.. 그리고 `실무에서 최종적으로 완료된 프로젝트 파일들과, 최적화된 프로젝트 파일들의 비교 예시` 는 결국 웹 사이트의 성능 최적화라는 주제로 옮겨가게 될 것이라는 생각이 드네요.
그 때는 폰트와 이미지, 한번에 내려받는 자바스크립트 코드의 양, 서버의 캐시 등을 종합적으로 배우는 시간을 가지셔야 하는데..
요즘에 나오는 최신 프레임워크(next.js 가 대표적)는 이 부분을 대부분 자동으로 처리해주기 때문에 일부러 배우기가 더 어렵습니다.

그렇다면...
일단 동작하는 코드를 생성하시고, 그것의 코드 리뷰를 받는 것이 좀 더 현실적일것 같다는 생각이 드네요!
