### ISSUE TITLE
[STD-2] new 연산자를 통한 인스턴스 생성 시 / 생성자 함수에 인수를 집어넣었을 때의 차이점

### ISSUE THREAD

**Issue by to06109** [yamoo9/likelion-FEQA#45]
## 질문
1. new를 이용해서 인스턴스를 만들 때 인수를 넣어주면 인자를 받지 않는 함수여도 일단 받아서 내부에서 사용하지 않으면 값을 무시하고 그냥 인스턴스를 만든다고 추측을 해봤는데 이 추측이 맞는건지 궁금합니다.  
2. new Person(값) 과 Person(값)의 어떤 차이 때문에 결과값이 다른건지 궁금합니다.

(특강을 듣고 나니 이 문제가 함수의 arguments와 관계가 있을 것 같다는 생각이 듭니다. 맞을까요?)

## 문제 상황
[[STD-1] 생성자 표기법으로 생성한 변수와 리터럴 표기법으로 생성한 변수는 프로토타입이 다른가요?](https://github.com/yamoo9/likelion-FEQA/issues/8)
해당 질문의 답변을 분석하다가 생긴 질문입니다. 

```javascript
// 생성자 표기법으로 생성한 변수의 프로토타입은 생성자 함수고
function Person() {
  this.name = '사람'
}
var person = new Person()
console.log('생성자 표기법으로 생성한 변수의 프로토타입은 생성자 함수고 ', person.valueOf(), person.__proto__)

// 리터럴 표기법으로 생성한 변수의 프로토타입은 자기 자신의 객체다
var person1 = new Object({ name: '사람' })
console.log('리터럴 표기법으로 생성한 변수의 프로토타입은 자기 자신의 객체다', person1.valueOf(), person1.__proto__)
```
**다음은 제가 의문을 품게 된 과정입니다.** 

생성자 함수로 생성한 변수는 리터럴로 생성한 변수보다 프로토타입 체인을 1단계 더 거슬러 올라가야 한다는 부분의 객체 구조를 보고 다음과 같은 의문이 들었습니다.
```javascript
// 그럼 여기에서 이렇게 되는걸까요? 
// Person이 (객체를 프로토타입으로 가진) 함수로 만들어진거니까..?

new Person() === new Person(new Object({ name: '사람' }))
```
이를 확인하는 과정에서 애초에 `Person` 함수가 인자를 받지 않기 때문에 그 안에 인수로 객체를 넣어주는 게 말이 안된다는 결론을 내렸습니다. 

(또, 두 변수의 프로토타입 체인 차이는 두 객체 안의 프로토타입이 Person과 Object로 다르기 때문이어서 위의 방식으로는 이를 같게 만들 수는 없다는 점도 이해했습니다. )

그런데 이 과정에서 Person 함수는 인자를 받지 않는데 new로 인스턴스를 생성할 때 여기에 인수를 넣어주면 들어간 인수를 무시하고 Person 객체를 상속받은 인스턴스를 잘 내보내는 것을 확인하였습니다.  
![Untitled (36)](https://user-images.githubusercontent.com/69625013/212471229-23772c46-db88-4fae-a0c1-306433915066.png)
그런 반면에 그냥 Person 함수에 인수로 값을 넣어주면 undefined가 나오는 것을 확인하였습니다. 
![Untitled (37)](https://user-images.githubusercontent.com/69625013/212471245-282376cb-4395-46b4-b00a-8bac0f609775.png)

**Comment by shoveller** [comment]
안녕하세요! @to06109 님. 

1. 네. 자바스크립트는 매우 관대한 언어이므로, 사용하지 않는 인수를 생성자 함수에 넘겨도 에러를 내지 않습니다. 
   하지만 [Object.prototype.constructor](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor) 의 설명과 [Classes 의 constructor](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Classes/constructor)의 설명을 모두 찾아봤음에도 이것의 근거를 찾을수는 없었네요.. 아쉽습니다.
하지만, 실무에서는 타입스크립트를 주로 사용하시게 될 것인데, 이 경우에는 타입스크립트 컴파일러가 사용하지 않는 인수를 생성자 함수에 넘기는 등의 행위를 엄격하게 단속할 것입니다.
이런 것을 `정적 분석` 이라고 하는데, 타입스크립트를 사용하는 이유이기도 합니다.

1. [MDN의 설명](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/new#%EC%84%A4%EB%AA%85)을 보니, `new` 연산자를 사용해서 인스턴스를 생성해야만 프로토타입 체인이 생기는군요!
    같은 내용을 [야무 선생님의 프론트엔드 마스터 강의](https://yamoo9.github.io/front-end-master/lecture/js-pay-constructor-prototype.html#%EC%98%81%EC%83%81-%EA%B0%95%EC%9D%98) 에서도 자세히 설명하고 있네요.
    `Person()` 의 결과값이 `undefined` 인 것도 함수가 아무것도 반환하지 않아서라는걸 잘 알겠습니다.
    

```jsx
function Person() {
  this.name = '사람'
}

console.log('new 연산자를 사용하면, 프로토타입 체인을 가진 인스턴스가 생긴다', new Person())
console.log('new 연산자를 사용하지 않으면 일반 함수로 동작한다', Person())

```

늘 좋은 질문을 품고 계시네요. 그 호기심을 오래 유지하시길 바랍니다.
감사합니다. ^^
