### ISSUE TITLE
for in문 사용처(?)

### ISSUE THREAD

**Issue by pingandthepong** [yamoo9/likelion-FEQA#46]
안녕하세요 멘토님! for in문 관련해 정확한 정보를 알고싶어 질문 올립니다.

책에서 본 바에 의하면 for in문은 '배열'과 함께 사용 가능하다고 나오는데, 다른 자료들을 보면 '객체'에서 사용한다고 기재되어 있습니다. 이게 배열이 객체에 포함된 개념이라 그런걸까요? (결국 배열, 객체 모두 사용 가능한걸까요? )

for in은 배열 요소 하나하나를 꺼내서 사용할 수 있고, 반복 변수에 인덱스가 들어가는 게 특징이라고 나와서 제가 외울 때 index라 in이고, index는 배열의 특징이니 for in은 배열에 사용한다!라고 외웠거든요.. 그런데 '배열'에 사용하는 것이 잘못된 정보일 수 있다는 생각에 정확히 여쭤보고자 질문 올립니다.

**Comment by yamoo9** [comment]
## 객체 순환을 위한 문(statement)

for - in 문은 **객체를 순환할 목적으로 사용합니다.**
`in`은 `index`를 줄인 말이 아니라, 말 그대로 "~안에(in)" 입니다.

객체가 포함한 속성을 확인할 때 `in`을 사용합니다.
예를 들어 CSS Grid를 웹 브라우저 환경에서 지원하는 지 확인할 때 다음과 같이 작성합니다.

```js
console.log('grid' in document.body.style);
```

작성한 코드 로직을 재사용 하기 위해 isSupportCss 함수를 작성할 수도 있습니다.

```js
const isSupportCss = (feature) => feature in document.body.style;

console.log(isSupportCss('flex'));
```

in에 대해 살펴봤으니 for - in문 코드를 살펴보죠.

```js
const containerStyle  = {
  maxWidth: '1200px',
  margin: '0 auto'
};

for (let property in containerStyle) {
  let value = containerStyle[property];
  console.log({ property, value });
}
```

코드를 실행한 결과를 보면 객체의 속성, 값을 순환해 Console 패널에 출력합니다.

![](https://user-images.githubusercontent.com/1850554/212855110-efe77e4b-d361-4c0c-9a2a-1c88ac12916e.png)

## 배열 객체 순환

배열 객체에서도 for - in 문 사용은 가능하지만, 사용하지 않는 것이 권장됩니다.

**일반적으로 배열은 각괄호(`[]`) 내부에 포함된 것만 순환한다고 생각하지만,
배열 또한 객체이므로 속성을 가질 수 있습니다.**

그러므로 배열과 for - in 문을 사용할 경우 의도치 않은 상황에 직면할 가능성이 있습니다.
예를 들어 아래 작성된 코드의 `number.temporalData`가 그러합니다.

```js
const numbers = [ 10, 100, 1000, 10000 ];
numbers.temporalData = '임시 데이터';
```

자 그럼 for - in문을 사용해 배열 객체를 순환 하면 어떤 문제가 발생할까요?
아래 코드를 작성하고 실행하면 의도하지 않은 결과가 출력될 것입니다.

```js
for (let index in numbers) {
  let value = numbers[index];
  console.log(index, value);
}
```

for - in 문은 객체의 속성을 조회할 때 사용 하므로 배열에 인덱싱 된 항목 뿐만 아니라,
배열 객체의 속성까지 모두 조회하게 됩니다. 👀

![](https://user-images.githubusercontent.com/1850554/212857497-024a86e6-13a6-4c09-aa8e-5edb3a55f33c.png)

반면 for 문을 사용한다면 이러한 문제가 발생하지 않습니다.

```js
for (let index = 0; index < numbers.length; index += 1) {
  let value = numbers[index];
  console.log(index, value);
}
```

결과를 보면 `number.temporalData` 속성은 조회하지 않죠.
그러므로 배열을 순환 하려면 for - in문이 아닌, for 문을 사용하는 것이 적절합니다.

![](https://user-images.githubusercontent.com/1850554/212858079-a73731bd-e41d-4625-b1cd-00978053fb16.png)

**Comment by pingandthepong** [comment]
감사합니다. 질문 드리기를 정말 잘 한 것 같습니다! 특히 `console.log('속성' in 객체)`로 먼저 설명해주신 덕분에 이해가 확실히 되었습니다. 감사합니다 선생님!!👍🏻
