### ISSUE TITLE
🛎️ 야무쌤 프론트엔드 강좌 XMLHTTPREQUEST Lecture 03. Ajax 

### ISSUE THREAD

**Issue by chaewon0128** [yamoo9/likelion-FEQA#47]
## 문제 상황

질문 내용을 자세하고 명확하게 풀어 작성합니다.
상황 이해를 돕기 위한 이미지 첨부가 필요한 경우 작성합니다. (권장)

💡 안녕하세요 야무쌤
프론트엔드 강좌를 들으며 실습하던 중 궁금한점이 생겨 질문드립니다. 
XMLHTTPREQUEST Lecture 03. Ajax 동기 통신 실습에서 
버튼을 만들어서 클릭을 하면 xhr.send() 를 실행시키는 작업을 진행중인데.. 밑에 캡쳐본 처럼 undefined가 나옵니다..

![image](https://user-images.githubusercontent.com/119389600/213212167-00b0485c-cc39-438c-8d10-23cb55315a57.png)
undefined

버튼을 지우고 xhr.send() 를 실행하면 정상적으로 작동하는데 무슨 문제인지 모르겠습니다ㅠㅠ 

![image](https://user-images.githubusercontent.com/119389600/213212936-3ec719ee-e052-4dbb-8a7b-45f1c5179bea.png)
정상작동

**Comment by yamoo9** [comment]
안녕하세요. @chaewon0128 님 😄

동기 방식으로 서버에 데이터를 요청하는 학습 과정 중에 문제가 생겼군요. 
이 문제는 요청 방식이 동기(sync) 임을 생각해보면 원인을 알 수 있어요.

## 버튼 코드가 포함된 경우

버튼을 클릭하면 서버에 요청을 보내는 코드와 
응답 받았을 경우 응답 결과를 `res`에 담는 코드를 살펴봅시다.

```js
serverBtn.addEventListener('click', () => {
  xhr.send();
});

let res;

if (xhr.status === 200) {
  res = xhr.response;
}

textArea.insertAdjacentHTML('beforeend', res);
```

사용자가 버튼을 눌러야 서버에 요청을 보냅니다.

```js
serverBtn.addEventListener('click', () => {
  xhr.send();
});
```

그런데 아래 코드가 작성된 위치를 보면 **사용자가 버튼을 누르기 전에 실행되겠죠?**
그럼 코드가 실행되는 시점에 **서버에 요청을 보낸 적이 없기 때문에 `xhr.status` 값은 `200`이 아니에요.**
즉, **조건이 거짓이므로 if문 블록은 실행되지 않습니다.**

```js
let res;

if (xhr.status === 200) {
  res = xhr.response;
}
```

그러면 `res` 값은 `undefined`겠죠?
그래서 결과적으로 화면에 `undefined`가 표시된 거에요.

```js
textArea.insertAdjacentHTML('beforeend', res);
```

## 버튼 코드를 지운 경우

반면에 버튼 코드를 지운 경우는 
**바로 서버에 요청 보내기를 했으니까 응답이 와야 아래 코드가 실행 되요.**

```js
let xhr = new XMLHttpRequest;
xhr.open('GET', './xhr.txt', false);

// 서버에 요청 보내기 (동기 방식)
xhr.send(); 

// 아래 코드는 서버에서 요청 응답이 오면 실행
let res;

if (xhr.status === 200) {
  res = xhr.response;
}

textArea.insertAdjacentHTML('beforeend', res);
```

## 가이드

이해를 돕기 위해 [DEMO](https://jsbin.com/mutupopaqi/edit?html,js,output)를 작성했습니다.
DEMO 링크를 클릭해 결과를 확인해보고, 코드에 남겨진 주석도 살펴보면서 학습해보세요. 😉

```js
// 요청 버튼 요소 참조
const requestButton = document.querySelector('.request');

// 응답 출력 요소 참조
const responseOutput = document.querySelector('.response');

// AJAX 통신을 위한 객체 생성
const xhr = new XMLHttpRequest();
// GET 요청, 요청 URL, 동기 방식으로 통신 요청 열기
xhr.open('GET', 'https://randomuser.me/api/?results=3', false);

// 요청(동기 방식)을 처리하는 이벤트 리스너
function handleRequest() {  
  // 통신 요청 보내기
  xhr.send();
  
  // 동기 방식이므로 이 코드는 응답을 받은 후 실행
  // 응답의 상태 코드 값이 200(OK)인 경우 조건문 실행
  if (xhr.status === 200) {
    // 응답 객체로부터 responseText 정보 추출
    let { responseText } = xhr;
    // 응답 출력 요소의 콘텐츠 업데이트
    responseOutput.textContent = `randomuser.me/api로부터 ${JSON.parse(responseText).results.length}개의 데이터를 응답 받았습니다.`;
    // 요청 버튼 요소 비활성화 (재요청 X)
    requestButton.disabled = true;
  }
}

// 요청 응답 버튼 요소에 click 이벤트 추가 (handleRequst 리스너 연결)
requestButton.addEventListener('click', handleRequest);
```
