### ISSUE TITLE
🛎️ 하나의 js와 여러 html 파일의 연결성(?)

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#48]
## 문제 상황

서로 다른 html 파일에 아래 사진과 같은 공통적인 부분이 있는데,
![image](https://user-images.githubusercontent.com/48400229/214189162-cf7ba539-c274-4466-90dc-ee616470da04.png)

이때 "(주) 쿠캣 사업자 정보 ∧"를 클릭하면 
![image](https://user-images.githubusercontent.com/48400229/214189615-9742faba-40a7-4d2d-975f-67a2ae6d25cc.png)
위의 사진처럼 접히게 해뒀습니다!

서로 다른 html 파일에 공통적인 부분이기에 html에 똑같은 코드가 아래처럼 각 html 파일마다 적혀있어요

![image](https://user-images.githubusercontent.com/48400229/214191066-7294cff0-2da0-4ab9-b885-ef2a1212e1ef.png)

각 html 파일에 연결된 js 파일 코드는
![image](https://user-images.githubusercontent.com/48400229/214195031-33d9a277-9608-44eb-bffd-546f4cfb75fe.png)

이것입니다!

그래서 문제 상황은 원래 자스코드로 실행하면 main.html에서는 실행되지만 나머지 html 파일이 js 코드가 적용되지 않는 상황이 발생했습니다. 그래서 브라우저에서 페이지 검사를 이용해서 보니 active라는 클래스가 toggle되지 않는것이 문제였습니다. 그래서 아래처럼 toggle을 두 번 해줬는데 

![image](https://user-images.githubusercontent.com/48400229/214194928-ac0a695b-b92f-4249-98b2-8f48740f59b2.png)

그랬더니 main.html에서만 작동 않게 되고 나머지 html 파일들은 잘 작동합니다. 왜 그런지 이유를 도무지 알 수 없어서 질문드립니다ㅜㅜ

도와주세요!!ㅜㅅㅜ

💡 이미지 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by yamoo9** [comment]
질문 유형과 같이 문제가 되는 실습 파일을 첨부해주셔야 정확한 원인 판단이 가능합니다.
에디터에 작성된 코드 이미지를 직접 보고 타이핑 할 수는 없으니까요. 😥

실습 파일을 봐야 문제 원인을 알 수 있고, 답변이 가능하다는 점에서 당장 원하는 답변을 드릴 수는 없지만.
비슷한 UI 컴포넌트를 구현한 데모 파일을 첨부합니다. 

[demo.zip](https://github.com/yamoo9/likelion-FEQA/files/10485655/demo.zip)

결과적으로 하나의 JavaScript 파일이 여러 HTML 페이지의 컴포넌트를 컨트롤하는데 아무런 문제가 없습니다.
데모 코드를 살펴보고나서도 질문의 문제가 안 풀리면 실습 파일을 첨부해주세요. 확인하고 답변드릴께요. 😃
