### ISSUE TITLE
🛎️ tailwind를 사용할 때 build를 위한 output.css 파일이 무엇이고 꼭 존재해야하나요?

### ISSUE THREAD

**Issue by senasoon** [yamoo9/likelion-FEQA#49]
## 문제 상황

안녕하세요. 개인적으로 tailwind를 사용한 프로젝트를 하고 있는데 질문이 있어 올립니다.
tailwind CSS 공식 문서를 보고 순서대로 프로젝트에 적용했습니다. 

https://tailwindcss.com/docs/installation

위 사이트 4번째 단계인 Start the Tailwind CLI build process를 적용하면 output.css라는 파일 하나가 생기는데 이 파일에 프로젝트에 사용되는 모든 tailwind 속성들이 자동 기록되고 있습니다. 

![image](https://user-images.githubusercontent.com/102699437/214838353-3d1720a8-18fb-4dae-b251-c789d80f36dc.png)

![image](https://user-images.githubusercontent.com/102699437/214838485-3f4e7c03-df80-44fa-9a1c-3ea067a7f652.png)

여러명이서 작업하다보니 merge 할 때마다 이 파일에서 충돌이 나서 **이 파일이 무엇을 위해 존재하고 프로젝트를 할 때 매번 충돌을 어떻게 관리해야하는지, 파일을 삭제해도 되는 것인지** 궁금합니다.

혼자 알아보려했지만 어려움이 있어 질문 드립니다.
답변 부탁드립니다! 감사합니다.

**Comment by shoveller** [comment]
아.. 저 튜토리얼을 참고하셨다면..
input.css 는 번역이 필요한 css이고, output.css 는 웹 브라우저에서 곧장 사용할 수 있게 번역을 끝낸 css 입니다.
(압축 `--minify` 까지 했다면, 납품도 가능한 최종 산출물이 되겠네요.)

output.css가 매번 생성되어서 고민이시라면, output.css를 메모리에 만드는 것도 방법이 될 것 같습니다.
[output.css를 메모리에 만드는 가장 간단한 방법은 tailwindcss를 cdn으로 인스톨하는 방법](https://tailwindcss.com/docs/installation/play-cdn)인것 같아요.

실제로 프로젝트를 하신다면 [tailwindcss를 postcss의 플러그인으로 사용하는 방법](https://tailwindcss.com/docs/installation/using-postcss)을 주로 사용하시게 될 것 같습니다.
거기에 바닐라js를 사용하는 경우에는 vite 를 번들러로 사용하는게 괜찮았습니다.

**Comment by yamoo9** [comment]
재원님께서 답변을 잘 달아주셔서 제가 크게 더 이야기 드릴 것은 없지만, 
관련 이슈에 대한 답변([#352](https://github.com/tailwindlabs/discuss/issues/352))이 도움이 될 듯 하여 참고하시라 답변 드려요.

> 여러명이서 작업하다보니 merge 할 때마다 이 파일에서 충돌이 나서 
> 이 파일이 무엇을 위해 존재하고 프로젝트를 할 때 매번 충돌을 어떻게 관리해야하는지, 
> 파일을 삭제해도 되는 것인지 궁금합니다.

Tailwind CSS 토론 주제인 Should tailwind's autogenerated tailwind.css file be committed on git? 
답변을 보면 개발 중일 때 생성된 output.css는 Git 제외 파일(.gitignore)에 추가해서 커밋하지 않도록 하고, 
배포할 때만 서버에 업로드 한다는 답변입니다. ([참고](https://github.com/tailwindlabs/discuss/issues/352#issuecomment-545606781)) 🤨
