### ISSUE TITLE
[LAB 18] 꼭 fork 후 브랜치 생성을 해야하는건지

### ISSUE THREAD

**Issue by MIINII** [yamoo9/likelion-FEQA#51]
## 문제 상황

원본 레포지토리(karly Organization)에서 브랜치를 새로 만든다음에 작업하는게 나을지, 아니면 개인계정으로 fork후 브랜치를 새로 만들어서 작업하는게 나을지 궁금합니다.

![image](https://user-images.githubusercontent.com/83333217/215024744-16d6a58b-5aa2-432d-9846-ffb048e48c5b.png)
![image](https://user-images.githubusercontent.com/83333217/215024773-caf6edac-8fa8-4b21-a0b5-53d374c97657.png)

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 프로젝트 저장소 URL

GitHub 학습 저장소 URL을 여기에 남깁니다. (참고용)
https://github.com/karlyLion18/karly_fe

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by yamoo9** [comment]
방법은 Branch & Merge를 이용하거나, Fork & Pull Request를 이용하는 방법이 있는데 
선택은 팀에서 결정하는 방향으로 정하면 됩니다.

다만 어떤 방법을 추천하는 지 물어본 것이라면 저는 Fork & Pull Request 방법을 권합니다.
Fork는 Branch와 비슷하지만 프로젝트를 통째로 복제해서 개발하는 방식이죠. Branch와 달리
Merge를 바로 하는 것이 아니라, Pull Request를 사용해 프로젝트 관리자에 Merge를 요청하여 
처리 하므로 **중간에서 문제가 생길 수 있는 가능성을 한차례 더 걸러주기 때문입니다.**

정리하면 방법은 Fork만 되는 것은 아니며, Branch를 사용해도 됩니다.
선택은 팀에서 결정하는 것으로 하되, 개인적으로 추천하는 방법은 Fork입니다. 😃

**Comment by sykang013** [comment]
저희 팀은 공동 저장소를 만들어 main 브랜치를 두고, 로컬에 클론하여 사용하는데 Pull Request 요청이 가능한것으로 나옵니다.
이 경우 Branch와  Pull Request 두 가지를 활용한 방식으로 볼 수 있는 걸까요?

**Comment by yamoo9** [comment]
@sykang013 님이 말씀주신 것처럼 **팀이 공동 저장소를 구성한 후, 공동 저장소를 각 팀원의 로컬 드라이브로 클론 하여 
기능을 개발/완료한 후 공동 저장소의 주인(owner)에게 풀 리퀘스트(PR) 요청할 수 있습니다.**

다시 확인하니 당시 답변을 남길 때 제가 질문을 잘못 이해했던 것 같습니다. 
Git 특강에서 2가지 방법을 소개했다고 들었는데 어떤 방식을 소개한 건지 
맥락 이해가 완전하지 않은 상태에서 남긴 답변이었어요. 😓

이전 답변 글을 수정 해야겠네요. 🥹
