### ISSUE TITLE
[LAB-17] 클론해 온 파일에서 브랜치 생성 시 해쉬 암호가 같은 브랜치가 생성됨

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#52]
## 문제 상황

저희가 원격 저장소에 있는 파일들을 포크하고 클론해서 코딩할려는 중인데, 클론한 파일을 열어서 브랜치를 하나 생성 후, 그 브랜치에서 작업을 할려고 생성을 했는데 main의 해쉬암호(?)와 새로 생성한 header 브랜치의 해쉬암호가 같게 나옵니다ㅜㅜ 이거 왜 이런 걸까요... branch 생성할때 쓴 명령어는 git checkout -b header 도 해봤고, git branch header로도 해봤습니다. 결과는 같아요ㅠ

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 
![image](https://user-images.githubusercontent.com/48400229/215274866-00c10706-d303-4d76-b556-e211f7558337.png)

## 프로젝트 저장소 URL
https://github.com/SSY1203/karly-17-devfolio.git

GitHub 학습 저장소 URL을 여기에 남깁니다. (참고용)

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by seulbinim** [comment]
안녕하세요 
해당 해시값은 브랜치를 분기할 때 HEAD의 위치를 나타냅니다.
어느 커밋에서 분기가 일어난 것인지 표시가 되고 있는 상황으로
정상적인 상태입니다.
걱정하지 않고 작업을 이어나가셔도 됩니다 ^^

브랜치가 main에서 분기 되었을 때 main의 해시값이
새로 분기된 브랜치의 HEAD 값이 되는 설명은 아래 사이트를 읽어보시기 바랍니다.
https://git-scm.com/book/ko/v2/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EB%B8%8C%EB%9E%9C%EC%B9%98%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80
