### ISSUE TITLE
🛎️ 위치 가운데 고정?

### ISSUE THREAD

**Issue by zerocalorie1226** [yamoo9/likelion-FEQA#53]
## 문제 상황

![image](https://user-images.githubusercontent.com/65861663/215305531-283f1757-6968-4331-81fe-2172b32a3d4b.png)

![image](https://user-images.githubusercontent.com/65861663/215305543-2dd5f9e5-6681-4366-b1d0-bb6110183e0a.png)

위에 사진처럼 "이 상품 어때요?" 이 문구를  밑에 사진처럼 창을 줄였을 때 이미지들처럼 그냥 위치 고정하고 사라지게 하고싶은데 위치가 창에 맞게 조절되고 위치가 고정이 안됩니다... 어떻게 해야되는지 모르겠어서 질문 남깁니다..ㅠㅠ

**Comment by seulbinim** [comment]
해당 질문은 이슈 등록 절차에 맞지 않습니다.
다시 올려주세요.
프로젝트 관련 이슈는 project Q/A 레이블을 달아주시고
음성채널로 호출을 원하신다면 SOS! 레이블을 함께 달아주세요.
그리고 질문을 올리실 때는 꼭 github URL을 알려주시기 바랍니다.

**Comment by yamoo9** [comment]
프로젝트 과정에서 발생한 질문은 Project Q/A 이슈 템플릿을 선택한 후 작성해야 합니다.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/1850554/215306993-85e0141a-fc16-41e4-a4e9-8358f014e51f.png">
