### ISSUE TITLE
[LAB-8] 퍼블리싱 깨짐 현상

### ISSUE THREAD

**Issue by hwanyplaying** [yamoo9/likelion-FEQA#54]
## 문제 상황
마켓칼리의 header와 footer 부분의 퍼블리싱을 완료하고 팀원들에게 제 브랜치로 넘어와서 퍼블리싱 깨짐 현상을 확인 부탁 후 검수를 하고 있는데 note1(window, chrome)와 note2(macos, chrome)에서 퍼블리싱이 깨졌다는 소리를 듣고 제 desktop으로 여러 해상도로 확인해 본 결과 저는 문제가 없어서 무엇이 문제인지 몰라서 질문을 남깁니다. note3(window, chrome)에서는 퍼블리싱이 깨지지 않는다고 합니다.
사진의 순서는 desktop(chrome), note1(window, chrome), note2(mac, chrome), note3(window, chrome) 순서입니다.

![desktop](https://user-images.githubusercontent.com/87050952/215411257-b4cd5d9e-ee82-4ed6-88af-f070cdb52abe.png)
![note1(window)](https://user-images.githubusercontent.com/87050952/215411280-86a02dd8-7dff-4f98-942e-a7634096c292.png)
![note2(mac)](https://user-images.githubusercontent.com/87050952/215411338-dc4fb3ec-8f81-4029-a5f4-0e46e3f9cd47.png)
![note3(window)](https://user-images.githubusercontent.com/87050952/215411354-36c7f619-e4a0-4779-b9bd-cff8ff7edb03.png)

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 질문 작성자

질문 작성자 : 문창환

## 프로젝트 저장소 URL

https://github.com/likelion-lab8-JS/market-karly
브랜치명 : page_common

## 환경 정보 (Optional)

- 운영체제 종류 : window10 (desktop, note1, note3), macos(note2)
- Node.js 버전 14.17.5

**Comment by seulbinim** [comment]
안녕하세요
해당 질문 주신 부분은 제가 테스트하고 있는 환경 (MacOS Ventura, Chrome 버전 108.0.5359.98)에서는 정상적으로 렌더링 되고 있습니다.
<img width="997" alt="스크린샷 2023-01-30 오후 4 38 21" src="https://user-images.githubusercontent.com/7028746/215417547-1c18df7c-e380-4bf7-940a-13d79e94fed5.png">

만약 윈도우 환경에서 레이아웃에 문제가 생긴다면 개발자 도구를 통해
왜 레이아웃이 무너졌는지 추론해 보는 과정이 도움이 될 것 같습니다.
또 한가지 label, input, button을 모두 하나의 div 요소에 포함하고
해당 div 요소의 클래스를 form__input으로 지정한 것 같습니다.
이 부분 분리해서 배치해 보는 것도 좋은 선택일 것 같습니다.
잠시 후 LAB8실로 방문하여 추가 설명 드리도록 하겠습니다.
