### ISSUE TITLE
[LAB-12, SOS] PR이 안되는 문제

### ISSUE THREAD

**Issue by copiCat0** [yamoo9/likelion-FEQA#55]
## 문제 상황

fork를 통해 받아온 레포지토리에서 degit 으로 내용을 동기화 시킨 후에, 내용을 일부 변경하고 PR을 보내려고 하는데, 

> There isn’t anything to compare.

이 뜨는 상황입니다. 육안으로 확인 했을 때에는 다른 점이 있습니다. 브랜치 선택도 맞게 했는데 안되는 이유를 알 수 없습니다 ㅠㅠ

degit 을 사용한 이유는 pull 시행 시마다 충돌이 나서 충돌을 해결하기 어려워서 폴더를 복사하는 방법을 선택했습니다. 현재 PR 오류 말고도, 프로젝트 폴더가 업데이트 될 때마다 pull을 하는 방법에 대한 조언을 듣고 싶습니다.

## 질문 작성자
이원준

## 프로젝트 저장소 URL

프로젝트 폴더
https://github.com/likelion-LAB12-VainillaProject/LAB12

김진희님 폴더
https://github.com/kyuran6/LAB12/commits/develop

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
  - macOS
- Node.js 버전 (예: v16.14.0)
  -18.13.0

**Comment by yamoo9** [comment]
## 충돌 문제 원인

동일한 파일을 각기 다른 팀원이 수정하고 내용에 다를 경우 
Git은 충돌(conflict)이 발생 했음을 알리고 사용자가 직접 문제를 해결해야 함을 안내합니다.

프로젝트 저장소 `README.md` 파일을 보면 `<<<<<<< HEAD` 내용이 있는 것으로 보아
아마도 `README.md` 파일을 양쪽에서 서로 다르게 수정하여 병합 하려 시도하다 보니 
해당 문제가 발생한 것으로 보입니다.

충돌 없이 PR 하려면 팀 구성원과 담당을 정확히 나눠 동일한 파일을 수정하는 일이 없도록 피해야 합니다.
정확한 상황은 옆에서 지켜보는 것이 좋을 듯 하네요.

## There isn’t anything to compare 문제

### 오류 발생 상황

이 오류가 발생하는 이유는 이전에는 default 브랜치가 `master`였는데 반해 
현재는 `master`에서 `main`으로 바뀌어 아직 `main` 브랜치에 미 적용 단계여서 
위와 같은 문구가 나왔던 것으로 보입니다.

### 오류 해결 방법

이 오류는 아래 명령을 순서대로 입력하여 `master` 브랜치의 내용이 `main` 브랜치로 덮이도록 하여 해결합니다.

```sh
git switch master
git branch main master -f
git switch main
git push origin main -f
```
