### ISSUE TITLE
[LAB-3] img태그의 alt값의 구체성에 대하여

### ISSUE THREAD

**Issue by nahee09** [yamoo9/likelion-FEQA#57]
## 문제 상황
안녕하세요! img태그의 alt값에 대해 질문이 하나 있습니다! 

<img width="229" alt="image" src="https://user-images.githubusercontent.com/119389649/215638772-9d2494f1-2a7a-488b-8995-894f7c59cbdf.png">

여기서 img태그의 alt값을 저는 첫번째 사진의 경우 "양갈래 머리를 한 유미의 세포 캐릭터가 미소 짓고 있는 슬비님의 프로필 사진"이라고 생각을 하였는데 다른 팀원의 의견으로는 프로필의 구분이 중요한 거니까 "슬비님의 프로필 사진"이라고만 적자고 하시는데 어떤 게 더 좋은 방법일까요?

## 질문 작성자

김나희

## 프로젝트 저장소 URL

https://github.com/likelion-fe4-js3/taing (참고용)

**Comment by seulbinim** [comment]
안녕하세요 ^^
이미지의 대체텍스트에 관해 질문을 주셨네요.
제 의견을 말씀드리면 두 가지 대체텍스트 모두 틀리지 않다고 생각합니다.
다만 프로필 이미지의 성격을 고민해보고 간단하게 제공할 경우와 
너무 과도하게 제공할 경우 어떤 Side Effect가 있지는 않을지 팀원들끼리 논의해 보면 좋을 것 같습니다.
어떤 한가지 이슈에 대한 모범답안은 여러가지가 있을 수 있습니다.
다만 Context에 따라 모범답안이 달라질 수 있겠죠.
아래 읽어볼 만한 링크를 첨부해 드릴테니 팀원들과 함께 살펴보고 고민해보세요.
[Headshot Alt Text](https://sc.edu/about/offices_and_divisions/digital-accessibility/guides_tutorials/alternative_text/headshot-alt-text/index.php)

**Comment by yamoo9** [comment]
답글 남기는 중에 슬비님께서 의견을 남겨주셨네요!! 역시 👍🏼 ㅎ
저도 작성 중인 글이 있었으니 의견 남겨봅니다! 😃

제 생각은 해당 이미지는 "장식(decorative) 이미지"라고 생각합니다.
중요한 건 이미지가 아니라, "프로필 선택 정보를 안내하는 버튼"이라고 보기 때문입니다.

<img width="1031" alt="" src="https://user-images.githubusercontent.com/1850554/215643196-7b724355-fe39-427b-bdc8-4c9b60f47746.png" />

그리고 이미지 주변에 프로필 이름이 있죠? 그러므로 W3C [An alt Decision Tree](https://www.w3.org/WAI/tutorials/images/decision-tree/) 기준에 따라 
해당 이미지는 장식 이미지로 볼 수 있다고 생각해요.

<img width="915" alt="" src="https://user-images.githubusercontent.com/1850554/215645353-e4108d5d-b522-4734-8f28-dca948803657.png" />

그러므로 저는 이미지의 `alt` 값을 비우고, 레이블 콘텐츠를 버튼의 레이블로 설정하는 방향을 제안해 봅니다. 

```html
<li>
  <button type="button" aria-labelledby="profile-button-id">
    <img src="..." alt="" />
  </button>
  <span id="profile-button-id">콘텐츠</span>
</li>
```
