### ISSUE TITLE
[LAB-2] 아이콘 접근성을 생각했을때 궁금증입니다.

### ISSUE THREAD

**Issue by leejh4197** [yamoo9/likelion-FEQA#58]
## 문제 상황

접근성을 고려해보면 체크표시 아이콘도 tab으로 접근이 가능해야할 것 같은데 svg파일을 button태그로 감싸는게 좋은 방법인지 궁금하여 문의 드립니다.

![image](https://user-images.githubusercontent.com/91236732/215681773-d3262866-3f12-4727-97cb-50bee04756c9.png)

## 질문 작성자

이주형 입니다.

**Comment by seulbinim** [comment]
안녕하세요 
해당 UI의 경우 "선택/선택해제"가 가능하도록 제공하는 것이 좋을 것 같습니다.
이 경우 radio나 checkbox 버튼이 적절할텐데요.
아이콘의 경우는 라디오 버튼이나 체크박스 버튼의 역할을
커스텀 스타일로 제공하면 좋을 것 같습니다.

**Comment by leejh4197** [comment]
감사합니다!
