### ISSUE TITLE
[LAB-3, SOS!] 스와이퍼가 제 머리카락을 뺴앗아 갑니다

### ISSUE THREAD

**Issue by PracticeKJY** [yamoo9/likelion-FEQA#59]
## 문제 상황
스와이퍼를 사용하여, taing 메인페이지의 재벌집막내아들 쪽 구역을 작업중입니다.
다름이 아니라, 버튼은 생기나 슬라이드 이동이 안되서 혼자 6시간 찾아보다가 질문을 드려요 ㅜㅜ..

작업순서는,
1. 권장규격에 맞게 html 코드를 작성한다 ( .swiper>.swiper-wrapper>.swiper-slide+스와이퍼버튼next+prev+스와이퍼pagination )
![image](https://user-images.githubusercontent.com/119389577/215705659-d2c5f94f-83be-4d5b-8426-85987d6e3bbe.png)
 
2. js 파일을 연결시킨다
![image](https://user-images.githubusercontent.com/119389577/215706066-5390b7ce-8736-46bb-aac0-0e6d39f6900d.png)

3. 작동해본다

이렇게 했었습니다.... 

결과는 계속 이렇네요 ㅜㅜ

![2023-01-31 17;22;55](https://user-images.githubusercontent.com/119389577/215706304-f7b0c8e5-dd7e-4e5d-9d6a-66c5e6f10168.gif)

구글링을 통해, 실습자료라던가 공식홈페이지에 나와있는 링크를 통해 가져온 파일들도 새 디렉토리 환경에서 해봤는데 
지금 증상과 같은 상태입니다 ㅜㅜ..
범쌤이랑 실습할 때 잘되는거 보면 뭘 안깔거나 하진 않은거같은데... 제가 뭘 놓치고 있는걸까요?
같은 조원들이랑 얘기도 해보고, 구동확인한 js코드를 가져와서 작업해봐도 작동이 안되네요 ㅜㅜ
조언을 해주시면 감사하겠습니다 ㅜㅜㅜ

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 질문 작성자

5.김종엽 / 프로젝트 3조

## 프로젝트 저장소 URL

https://github.com/PracticeKJY

## 환경 정보 (Optional)
window

**Comment by PracticeKJY** [comment]
ps. 직접 화면원격으로 한번 체크해주시면 정말 많은 꺠우침을 얻을 것 같습니다 ㅜㅜ.. 제가 글로 뭔가 배우는 속도가 느린편이여서요...

**Comment by seulbinim** [comment]
음성채널에서 답변이 필요한 경우 제목에 SOS! 레이블을 달아주셔야 합니다.

**Comment by PracticeKJY** [comment]
수정했습니다 ㅜㅜ

**Comment by simseonbeom** [comment]
화이팅~~!

**Comment by seulbinim** [comment]
안녕하세요
범쌤이 잘 설명해 주셔서 이해하셨으리라 생각합니다.
HTML 문서를 웹브라우저가 파싱해서 DOM을 구성할 때
<script> 태그를 만나면 파싱을 중단하고 스크립트를 다운로드 및 실행을 하게 됩니다.
만약 파싱을 중단하지 않고 스크립트를 병렬로 다운로드 받은 후
DOM 구성이 끝났을 때 스크립트가 실행되도록 하고자 한다면 defer 속성을 제공하시면 됩니다.
모던 자바스크립트에 기재된 defer와 async 속성을 읽어보시기 바랍니다.
[defer, async](https://ko.javascript.info/script-async-defer)

**Comment by PracticeKJY** [comment]
정말정말감사합니당
