### ISSUE TITLE
🛎️ for문에서 continue를 만나면 어떻게 되죠?

### ISSUE THREAD

**Issue by kelly121212** [yamoo9/likelion-FEQA#6]
## 문제 상황
오늘 수업 복습 도중 모던튜토리얼 읽고 있었는 데 아래 이미지 내 노랗게 색칠한 부분의 코드가 해석이 안되네요..
showPrimes(10); 으로 주었을 때 isPrime(10); 이렇게 똑같이 주고 코드를 해석해보았는데 
isPrime(10); 값이 true 까지 나왔지만 showPrimes(10); 코드에서 
if(!isPrime(i)) continue;  부분 부터 막힙니다. true 값을 !isprime(true) 넣으면 false 값인데, 
false 결과면 구문이 끝나고 마는 건지 ..?

![image](https://user-images.githubusercontent.com/69451362/210354553-6a840efb-6416-41c6-a2e9-70a14d3ea0ed.png)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 : Window
- Node.js 버전 (예: v16.4.0)

**Comment by yamoo9** [comment]
## 질문 분석

보영(@kelly121212)님이 남겨주신 질문을 살펴보면? `isPrime()` 함수의 결과 값이 `false`일 때 구문이 끝나는 건지를 물어본 듯 싶네요. 🤔

> `if(!isPrime(i)) continue;` 부분 부터 막힙니다. 
> `true` 값을 `!isPrime(true)` 넣으면 `false` 값인데, `false` 결과면 구문이 끝나고 마는 건지 ..?

## 답변

for문 내부에서 **`continue`를 만나면 다음 반복 절차로 건너띈 후 이어서 다음 절차가 진행**됩니다.

아래 촬영된 GIF 이미지를 참고하면 이해하기 쉬울 거에요. 😃
`continue` 부분 다음에 넘어가는 부분과 오른쪽 WATCH 패널 영역의 `!isPrime(i)` 결과 값도 같이 확인해보세요.

![continue 구문 흐름](https://user-images.githubusercontent.com/1850554/210373453-c8766ace-182b-4252-97a1-ceb583ce8698.gif)
