### ISSUE TITLE
[LAB-10] a태그겉에 btn 태그로 감싸는 이유가 궁금합니다. 

### ISSUE THREAD

**Issue by SimYuseon** [yamoo9/likelion-FEQA#60]
## 문제 상황
이미지에서 보라색 부분은 li>a하고 분홍색 부분은 btn>a 로 배웠던거 같은대 보라색부분은 이해가 가는대 분홍 부분에서 a 태그만 써도 가능한대 btn태그를 써서 감싸는 이유가 a태그만 쓰기보단 btn으로 감싸는게 좀더 시멘틱해서 사용한다는 이유만 있는게 맞을까요? 아니면 다른 이유가 있는걸까요? 

![KakaoTalk_20230131_113541818](https://user-images.githubusercontent.com/111304551/215703968-4ec0ee9b-6af8-4f5e-9095-4337cce1b470.png)

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 질문 작성자
심유선
## 프로젝트 저장소 URL
https://github.com/LikeLion-VJS10/TAING10
GitHub 학습 저장소 URL을 여기에 남깁니다. (참고용)

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by seulbinim** [comment]
안녕하세요.
해당 질문에 대한 답변을 드리면 button 요소 내부에 a 요소는 사용할 수 없다는 사실입니다.
두가지 요소는 모두 인터렉티브 요소로 button 내 자식요소로 a 요소를 허용하지 않습니다.
[button](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element) 요소에 관한 레퍼런스를 확인해 보시기 바랍니다.
<img width="1567" alt="스크린샷 2023-01-31 오후 5 34 10" src="https://user-images.githubusercontent.com/7028746/215709352-5fe7681f-fc90-4a19-aba7-9a8e586bf119.png">
