### ISSUE TITLE
[LAB-17] lighthouse 충족 정도

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#61]
## 문제 상황

이번 프로젝트의 웹 접근성을 위해 최대한 저 점수를 100점으로 만들고 싶은데, 성능과 PWD는 100점으로 맞출려 하니.. 너무 어렵더라구여.. 그.. 어느정도까지 맞춰야 웹 접근성을 잘 고려한 건지 기준을 좀더 알 수 있나요? 

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 
![image](https://user-images.githubusercontent.com/48400229/215736454-9373fbf0-9580-4a5b-a715-424f0180e0d8.png)

## 질문 작성자

신선

## 프로젝트 저장소 URL

[GitHub 학습 저장소 URL을 여기에 남깁니다. (참고용)](https://github.com/SSY1203/karly-17-devfolio/tree/header_footer)

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by seulbinim** [comment]
안녕하세요
점수는 높을수록 좋겠죠?
그라고 99점이 나왔다고 하더라도 이슈를 한가지 준수하지 못했는데 그 이슈가 크리티컬한 문제여서 사용자가 서비스를 이용할 때 치명적이라면 웹접근성 준수를 lighthouse에만 의존하지말고 체크리스트를 만들어서 정성적으로 점검도 함께하시기를 권장합니다. 
최소한의 기준만 맞춰야지보다 할 수 있는 범위에서 최선을 다해 주시면 됩니다^^
