### ISSUE TITLE
[LAB-10 SOS!!!] ESLINT 및 PRETTIER 설정이 적용이 되는건지 제대로 설정 한건지 모르겠습니다

### ISSUE THREAD

**Issue by SimYuseon** [yamoo9/likelion-FEQA#62]
## 문제 상황

프리티어와 esllint 설정을 했는대 기존 prettier를 다같이 꺼도 세팅되는게 다 다르고 검색해서 하긴 했는대 제대로 설정 한건지도 잘 모르겠습니다. 혹시 세팅이 잘된건지 같이 확인 해주실수 있을까요? 

## 질문 작성자

심유선

## 프로젝트 저장소 URL

[LikeLion-VJS10/TAING10](https://github.com/LikeLion-VJS10/TAING10)

**Comment by yamoo9** [comment]
프로젝트를 clone한 후 테스트 해본 결과 설정에 문제 없는 것을 확인했습니다.
참고로 파일 저장 시 자동 포멧되도록 설정하려면 Format on Save 옵션이 활성화되어야 합니다.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1850554/215914573-e83315ea-d37f-4e84-a7aa-cdf78b8fb23c.png">

clone한 프로젝트 파일 중, `.prettierrc.js` 파일은 현재 포멧팅이 적용되지 않았습니다.

```js
module.exports = {
    "printWidth": 80,
    "tabWidth": 2,
    "singleQuote": true,
    "trailingComma": "none",
    "bracketSpacing": true,
    "semi": false ,
    "useTabs": false,
    "arrowParens": "avoid",
    "endOfLine": "auto"
  };
```

Format on Save 활성화 되었을 경우, 저장 시 자동으로 포멧팅 되어 아래처럼 정렬됩니다.

```js
module.exports = {
  printWidth: 80,
  tabWidth: 2,
  singleQuote: true,
  trailingComma: 'none',
  bracketSpacing: true,
  semi: false,
  useTabs: false,
  arrowParens: 'avoid',
  endOfLine: 'auto'
}
```

**Comment by sykang013** [comment]
# 문제상황 
현상은 해결되었으나 의문점이 생겨 질문드립니다.
저의경우 Format On Save 옵션을 확인해보니 이미 활성화가 되어 있어, 
setting.json에서 * `editor.defaultFormatter": "esbenp.prettier-vscode`를 주고(*기본 포메터를 프리티어로 설정)
.prettierrc.js 파일의 * `printWidth`의 값을 `250`을 주었더니 해결되었습니다.(*줄바꿈 폭을 250으로 설정)

![스크린샷 2023-02-01 오전 10 20 04](https://user-images.githubusercontent.com/113448786/215921623-126b93c7-7911-4cd8-996b-87b096cf0e5e.png)
![스크린샷 2023-02-01 오전 10 30 03](https://user-images.githubusercontent.com/113448786/215922768-ad886f3f-c17f-40e2-85da-b0936a47d033.png)


한가지 의문점은, vsc 익스텐션인 프리티어는 disabled 상태로 두어 동작하지 않게 헀고, npm i 를 이용해 .prettierrc.js 파일을 실행한것인데, 
어째서 setting.json 의 `editor.defaultFormatter": "esbenp.prettier-vscode` 유무에 영향을 받는 것인가요?

# 질문자
강수영

**Comment by yamoo9** [comment]
@sykang013 님 ^^

printWidth는 행폭을 말하는데 250은 너무 길어요.
기본 값이 80인 점에 맞춰 조정해보세요.

그리고 npm i 명령은 패키지 설치 명령입니다.
Prettier 구동하는 명령은 아니에요.

Prettier CLI 명령을 사용해야 구성 파일을 읽어
자동 포멧팅 처리할 수 있어요.

지금 버스 안이라 윗 부분 명령어는
사무실 들어가서 작성하겠습니다.

**Comment by shoveller** [comment]
안녕하세요. @sykang013 님.
저도 흥미가 생겨서 찾아봤는데 ,해당 익스텐션(prettier-vscode)에 대해 비슷한 이슈가 있네요.
[`editor.defaultFormatter` 을 typescript에만 적용했는데 prettier 가 기본 포매터로 동작하더라](https://github.com/prettier/prettier-vscode/issues/2813)

결국은 이것이 버그인지를 해당 익스텐션(prettier-vscode)의 동작을 파악해서 따져봐야 할 것 같은데..
정확한 답을 구하려면 해당 확장기능 제작자에게 이슈를 남겨보는게 좋을것 같다는 생각이 드네요.
