### ISSUE TITLE
[LAB-17] 웹접근성 탭키 이동 문제 

### ISSUE THREAD

**Issue by kelly121212** [yamoo9/likelion-FEQA#63]
## 문제 상황
질문 : 원본 마켓 컬리 스와이퍼 내 탭키 이동처럼 진행되고 싶어, 
마켓컬리와 똑같은 구조로 컨텐츠 a태그(.product_item)로 감싸고 장바구니 버튼을 a태그 내부 button태그(.cart)로 두었습니다.
그런데 장바구니만 탭키 포커싱이 되고 a태그가 되질 않습니다.

1. 원본 마켓컬리 메인페이지 내 "이 상품 어때요?" 들어가서 탭키 누를시 작동되는 버전 동영상
https://user-images.githubusercontent.com/69451362/215933676-a1ff13f4-d63f-4b58-bd46-f643191120ba.mp4

2. 랩실 마켓칼리 메인페이지 내 "이 상품 어때요?" 들어가서 탭키 누를시 작동되는 버전 동영상
https://user-images.githubusercontent.com/69451362/215933718-32832e2e-4797-442a-8c90-72a235b7c3e0.mp4

3. 해당부분 적용된 html 구조 
![image](https://user-images.githubusercontent.com/69451362/215934109-866690a5-6813-4111-8862-5df82df2124c.png)

4. 해당부분 적용된 css 구조 
![image](https://user-images.githubusercontent.com/69451362/215934146-751623d5-2611-4541-8b83-6302a8de2228.png)

## 질문 작성자

최보영 

## 프로젝트 저장소 URL

[kelly121212/karly-17-devfolio](https://github.com/kelly121212/karly-17-devfolio)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 : window 
- Node.js 버전 (예: v16.14.0)

**Comment by kelly121212** [comment]
제 깃허브 develop 브랜치에 해당 이슈 푸시하였습니다.

**Comment by yamoo9** [comment]
## 문제 원인

해당 이슈는 Slider 라이브러리 적용 시 발생한 문제로 확인되었습니다.

> 해당 문제는 Discord 화면 공유를 통해 원인은 분석한 후, 해결 방법을 안내했습니다. 😃

## 문제 해결방법

a 요소 `href` 속성에 연결될 URL을 설정하면 기본적으로 초점 이동이 가능합니다.

```html
<a class="product_item" href="... 페이지 링크 URL ...">
  <div>
    <img class="thumbnail" src="./assets/index/recomment_food1.jpg" alt="풀무원 탱탱쫄면 4개입">
    <button>
      <img class="cart" src="./assets/index/icon_cart.png" alt="장바구니">
    </button>
  </div>
  <p class="product_title">[풀무원] 탱탱쫄면 (4개입)</p>
  <p class="product_price">4,980 원</p>
</a>
```

<img width="787" alt="" src="https://user-images.githubusercontent.com/1850554/215952637-07d52eff-4499-4414-aebe-f4ebfa8fed35.png">


확인 결과 Swiper가 설정된 이후 초점 이동이 표시되지 않는 문제가 발생했습니다.
[Swiper 접근성(A11Y)](https://swiperjs.com/swiper-api#accessibility-a11y) 설정에는 별도 옵션을 제공하지 않으므로 CSS 스타일링으로 Swiper가 설정한 스타일을 재설정(덮어쓰기)해야 합니다.
