### ISSUE TITLE
[LAB-2] 명도대비

### ISSUE THREAD

**Issue by leejh4197** [yamoo9/likelion-FEQA#64]
## 문제 상황
시안대로 color를 지정했더니 명도대비로 인해 접근성 점수가 낮아졌는데 혹시 접근성을 위해 시안대로 말고 색을 임의로 지정해여 명도를 맞춰야하는 것 일까요 ?
## 이주형

**Comment by simseonbeom** [comment]
안녕하세요 주형님 :)

색상은 임의로 지정해서 디자인이 달라지지 않게 작업해주시면 좋을것 같습니다 ~~

**Comment by seulbinim** [comment]
안녕하세요.
마켓칼리의 경우 현재 마켓컬리 사이트 디자인을 바탕으로 제작되어 있기때문에
명도대비 관련 이슈가 있을 수 있습니다.
이런 경우 실무에서라면 디자이너에게 문제가 있음을 알리고
원활한 커뮤니케이션을 통해 수정을 제안하는 것이 좋은 방법일 수 있습니다.
물론 설득이 될 수 있도록 근거와 수정 사례를 준비하는 것이 좋겟지요 ^^
지금은 실제 업무는 아니지만 디자인 상 이슈가 발생한 것으로 가정하고
어떤 색상으로 제안을 하면 디자인을 헤치지 않으면서 접근성을 준수할 수 있을지
팀원들기리 고민해 보시면 좋을 것 같습니다
