### ISSUE TITLE
[LAB-17] 라이브서버와 npm run dev 서버에서 받아오는 이미지가 다릅니다. 

### ISSUE THREAD

**Issue by kyoungholee** [yamoo9/likelion-FEQA#65]
## 문제 상황

1. 문제점 : 메인페이지(index.html)에서 상대경로를 이용해 footer.html 파일을 불러왔습니다.
코드 :  <iframe data-include="./layout/footer.html" frameborder="0"></iframe>

![메인 페이지 footer](https://user-images.githubusercontent.com/65242726/216246723-82ca02eb-4c98-4589-8227-2af4c2dd53ed.PNG)

  
하지만 로그인페이지에서 똑같이 상대경로를 이용해 footer.html을 불러 왔지만  이미지가 보이지 않는 현상이 일어납니다. 
코드 :    <iframe data-include="../../layout/footer.html" frameborder="0"></iframe>

![로그인 페이지 footer](https://user-images.githubusercontent.com/65242726/216246738-fb5a36a6-8972-48f2-a058-0131357ff1cf.PNG)

2. 문제점 :  저희가 맨 처음엔 라이브서버를 이용하면서 코딩 작업을 했을때는 절대경로를 이용해 그림이 잘 보였습니다.

하지만 전부 코드를 merge한 이유 json-server에서 확인 해보니 그림이 다 깨지는 현상이 일어났고 , 경로를 상대 경로로 바꾸니 잘 보였습니다.

이 문제는 어떻게 해결 할까요?

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 

## 질문 작성자 : 이경호

GitHub 아이디로 질문자를 유추하기 어렵습니다. 질문 작성자의 실명을 입력해주세요.

## 프로젝트 저장소 URL

GitHub 학습 저장소 URL을 여기에 남깁니다. (참고용)
https://github.com/likelion-4fe-karly/karly-17-devfolio/tree/develop

develop브랜치 입니다.

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류: window
- Node.js 버전 : v18.12.1

**Comment by yamoo9** [comment]
## 문제 확인

경로에 따른 문제로 확인되었습니다. 서버로부터 에셋 경로를 찾을 수 없는 경우입니다.

## 문제 해결 방법

*🎥 디스코드를 통해 랩실 접속 후 영상으로 가이드 하였습니다.*

이 문제는 절대 경로를 사용해 에셋에 접근하면 해결 가능합니다.

프로젝트 `package.json` 파일에 설정된 웹 서버 루트(root) 경로가 `client`이고 이 폴더가 절대 경로의 기준(`/`)이 됩니다.

```json
{
  "scripts": {
    "dev": "live-server client"
  } 
}
```
