### ISSUE TITLE
[LAB-17] iframe으로 인한 잔상

### ISSUE THREAD

**Issue by SSY1203** [yamoo9/likelion-FEQA#66]
## 문제 상황

헤더와 푸터 부분이 공통적인 부분이라 iframe으로 header, footer html의 마크업을 호출하는 형식으로 코딩했는데, 새로고침할 때 header의 css가 삽입되기 전의 마크업이 나왔다가 css가 적용된 마크업이 나오는 잔상이 생깁니다. 이는 어떻게 해결할 수 있을 까요ㅠ 구글링 해봤는데 이런 사례가 잘 없어서 해결 못했습니다,,

아래 비디오 입니다!

[잔상 현상.zip](https://github.com/yamoo9/likelion-FEQA/files/10575123/default.zip)

## 질문 작성자

신선영

## 프로젝트 저장소 URL

https://github.com/SSY1203/karly-17-devfolio.git

**Comment by yamoo9** [comment]
## 문제 상황

iframe을 이용한 공통 페이지 모듈 호출 및 적용 사이 발생하는 UI 렌더링 이슈

## 문제 해결

> Discord를 통한 화면 공유 방식으로 문제 상황과 해결책을 함께 살펴봤습니다.

문제 해결에 추가 구성된 코드 로직은 다음과 같습니다.

- [x] UI 렌더링 문제 해결을 위한 가짜 컨테이너(fake container) 요소 생성 설정
- [x] UI 렌더링에 불필요하게 표시되는 iframe 요소 감추기(hidden) 설정
- [x] iframe 페이지가 로딩 완료되면 가짜 컨테이너 요소 삭제 설정

## 문제 해결 가이드 파일

문제가 해결된 가이드 파일 코드를 포함하는 ZIP 파일입니다.

[karly-17-devfolio-confirm-by-yamoo9.zip](https://github.com/yamoo9/likelion-FEQA/files/10575726/karly-17-devfolio-confirm-by-yamoo9.zip)
