### ISSUE TITLE
[LAB-14] 코드 변경 사항이 있음에도 에러 없이 Branch 이동이 됩니다.

### ISSUE THREAD

**Issue by choinamechoi** [yamoo9/likelion-FEQA#67]
## 문제 상황

문제 상황 : 
* 정상 이미지 
![image](https://user-images.githubusercontent.com/119389120/216532873-335ff61a-1757-4474-bf10-1b7eb41a76ab.png)

* 문제 발생 이미지
![image](https://user-images.githubusercontent.com/119389120/216533162-48d871a5-539c-45db-8bba-fb914c80dde0.png)

* 문제 이해를 돕기 위한 이미지
![image](https://user-images.githubusercontent.com/119389120/216533537-d2afbf83-93ea-4f84-adf8-e759bbed336b.png)

위 그림판과 같이 A->B 브랜치로 이동 후 . B 브랜치에서 코드2 를 새롭게 작성하였습니다.

커밋을 하지않은 상태에서 B->A 브랜치 이동을 시도하면 [정상 이미지]처럼 에러가 나야 되는데

에러가 나지 않고 [문제 발생 이미지] 처럼 A 브랜치로 바로 이동이 됩니다.

## 질문 작성자

최영범

## 프로젝트 저장소 URL

https://github.com/likelion-lab14

## 환경 정보 (Optional)

환경 : window

**Comment by yamoo9** [comment]
## 문제 원인

확인 결과 Git의 기본 동작과 달리, 특정 로컬 컴퓨터 환경에서만 발생한 이슈입니다.
문제가 발생한 로컬 컴퓨터 환경에서 면밀하게 분석해야 정확한 원인 파악이 가능할 듯 합니다.
안타깝게도 화상 강의 형태이다 보니 직접 로컬 컴퓨터 환경 테스트가 어렵습니다. 😥  

## 문제 해결 방법

우선 의심되는 문제 해결을 위한 여러 수단을 요청했습니다.

- [ ] Git 구성 파일(`.gitconfig`)에 특정 옵션 설정 유무 검토
- [ ] 사용 가능한 자택의 다른 컴퓨터 환경에서 동일한 증상이 발생하는 지 검토
- [ ] 위 2가지 경우 확인했음에도 문제 파악이 안된다면? 최종적으로 설치된 Git 삭제 후, 재설치
