### ISSUE TITLE
[LAB-17] mainpage Swiper 버튼 사라짐 이슈 

### ISSUE THREAD

**Issue by hamjongseok** [yamoo9/likelion-FEQA#68]
## 문제 상황
<img width="791" alt="스크린샷 2023-02-03 오후 5 06 07" src="https://user-images.githubusercontent.com/82271040/216545625-a1f07a0e-e47a-4d3a-9e1a-1ed6cd065a23.png">

제가 구현 하고자 하는것은 <이상품 어때요?> , <놓치면 후회할가격> 의 swiper 첫번째 슬라이드에서 
prev버튼을 제거 하려고 코드를 작성중에 있습니다. 

<img width="791" alt="스크린샷 2023-02-03 오후 5 20 40" src="https://user-images.githubusercontent.com/82271040/216548505-19c0fe74-d6e4-466b-be7f-6b60c46e4fdb.png">
 
현재 문제가 loop:true 로 되어있는데 loop를 없애야 해서 loop:true를 지우면  
놓치면 후회할가격에 대해서만 버튼이 아예사라지고 페이지검사를 해본결과 
swiper-button-lock 이라는 클래스가 놓치면 후회할 가격에 추가가 되어있습니다. 
구글링을 해봐도 왜추가가된건지 
어떻게 해결해야할지 모르겠어서 질문올립니다 ! 

## 질문 작성자

함종석 

## 프로젝트 저장소 URL
https://github.com/hamjongseok/karly-17-devfolio/tree/product_detail

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- MacOs

- Node.js 버전 (예: v16.14.0)

**Comment by simseonbeom** [comment]
안녕하세요 종석님 :)

상품에 대한 스와이프는 loop를 가질 필요가 없을것 같습니다. 

loop를 설정하지 않으면 스와이프는 자동적으로 해당 항목의 마지막 지점을 인식해 swiper-button-disabled 라는 클래스를 추가해주고 있으므로,  css만 넣어서 활용해주시면 됩니다 ^^

swiperAPI를 확인해보면 diabledClass 이름을 커스텀으로 변경해서 사용할 수 있는 방법도 제공을 해주고 있습니다.
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/35365227/216553659-58a58af0-405e-4d08-a19f-ed8d0bbaf679.png">

**Comment by hamjongseok** [comment]
답변감사합니다 !  아직 해결을 하지못해서 질문을 다시 드립니다 

해당 swiper에서 loop를 사용하지 않을거지만 loop를 설정하지 않는다면 자동적으로 해당 항목의 마지막 지점을 인식해 
swiper-button-disabled 라는 클래스를 추가해주고 있다고 하셔서 loop:false 를 적용하였지만, 그래도 
놓치면 후회할가격 부분의 swiper가 아예 슬라이드 작동을 하지않고, lock-class가 추가되는 이유를 모르겠습니다 ! ㅠ ㅠ
