### ISSUE TITLE
[LAB-14] PR 시 구성원은 스크럼 마스터로부터 reject 또는 accept를 받을 때 까지 대기해야하나요?

### ISSUE THREAD

**Issue by djswns7** [yamoo9/likelion-FEQA#69]
## 문제 상황

https://youtu.be/0MeVEaDz2vQ 야무쌤과 범쌤이 함께 만들어주신 영상을 본 후에 생겨난 궁금증입니다  

예시를 들어 질문을 드려보자면 
구성원A가 본인의 원격저장소(A의 깃허브)에서  PR을 스크럼마스터에게 보냈다고 하였을 때,
A의 입장에선 PR이 항상 승인이 나면 좋겠지만 아닐 수 도 있기 때문에 PR 승인이 나기 전까지는  
upstream(영상을 따라한다는 가정하에 스크림마스터의 저장소)에서 받은 가장 최근의 git pull 명령 후,  
변경한 파일들에 대한 작업은 멈춘 상태에서 다른 파일을 작업하거나,  
승인된 파일에 이어서 해야 하는 작업 이 있는 경우엔 PR승인이 날 때 까지 대기해야 하는 게 맞는지 궁금합니다.

> 프로젝트 중간에 항상은 아니지만 구성원 중에 다른 작업을 못하고 멈춰야 하는 상황이 자연스럽게 발생할 수 있다는 것이 맞는지 확인하고 싶어서 질문드립니다. 

### 
추가로 영상을 따라하는 방식으로 진행하게 되면 스크럼 마스터가 한 명이 되는데  
모든 구성원의 공동저장소에 대한 직접 push 권한을 차단한 상태에서(pull 만 가능하도록)  
모든 팀 인원이 스크럼 마스터 역할을 하되, 본인의 PR에 대해서만 승인하지 않도록 컨벤션을 정하여
PR 처리속도를 빠르게 하는 방식은 잘 사용하지 않는지 궁금하여 질문드립니다

## 질문 작성자

박원준

**Comment by yamoo9** [comment]
## 문제에 대한 논의

### 1. PR 승인 전 대기 상황

https://github.com/yamoo9/likelion-FEQA/issues/51#issuecomment-1407784392 댓글에서 PR의 목적을 거론했습니다. 피드백(feedback) 또는 도움(help)이 필요할 때, 
혹은 병합(merge) 준비가 완료 되었을 때는 PR을 생성합니다. 기능 개발 중 코드 리뷰가 필요하거나, 
기능 개발이 완료 되었음에 병합을 요청할 때 PR을 합니다.

"PR 승인날 때까지 대기하는 것이 맞냐?"고 질문주셨지만, 이 상황은 옳고 그름을 다루는 문제는 아니라고 봅니다.
목적(리뷰 또는 병합)에 맞게 PR 요청을 했다면 절차대로 대기하고, 다른 기능을 개발하거나 그 외 이슈를 처리 할 수 있겠죠.
막연히 할 일을 멈추고 대기하는 상황은 아닐 것입니다. 

그리고 PR 요청 처리가 지연된다면? 지연되는 이유를 확인하고 처리 방안에 대해 논의할 수 있지 않을까요? 🤔

### 2. PR 컨벤션 설정 처리 속도 향상

영상 가이드는 다양한 방법 중 한가지일 뿐입니다. 늘 다양한 방안을 강구하고 반영하는 노력을 가질 필요가 있습니다.
팀마다 컨벤션이 다르듯 적용 가능한 방법 또한 다를 수 있겠죠. 제안한 방식이 팀에 적합하다면 그 방법을 사용하지 않을 이유가 없습니다.

생각한 방법대로 진행해보세요. 그걸 위한 바닐라 프로젝트입니다. 체험하고 느끼고 깨닫고 하는 시간이죠. 
생각대로 PR 처리 속도는 빨라지는 지 업무 효율성은 개선되는 지, 남이 말하는 경험 말고 직접 갖는 경험으로 성장하시길 바랍니다. 😊
