### ISSUE TITLE
🛎️ 변수의 스코프

### ISSUE THREAD

**Issue by shoveller** [yamoo9/likelion-FEQA#7]
[STD5 - 2주차 멘토링 2번째 질문](https://likelion.notion.site/2-1-7-f907e68b642c4cf0afa1b5be78d18dac)

함수 스코프 : var

블록 스코프 : let , const

일단 이런 개념이 맞는지 궁금하고…

```jsx
// 함수 스코프 var

let age = 30;

if(age>19) {
  var txt = '성인'
}

console.log(txt); // 성인
```

함수 스코프라서 조건문엔 가능하고

```jsx
function add(a, b){
  var result = a + b;
}

  add(2, 3);
  console.log(result); //error
```

함수안에서는 바깥에 변수가 접근을 못해서 에러가 나는데

console.log괄호 안에  result가  함수 안으로 들어간다는건지 모르겠습니다(런타임때 알고리즘 진행 방향을 모르는게 맞는것 같습니다)

**Comment by shoveller** [comment]
안녕하세요! 익명의 질문자님.

아래의 인식을 명확하게 하고 계신것 같습니다.
- var 가 함수 단위의 유효범위를 가진다(=함수 안에서만 유요하다)
- let 과 const 는 블록 단위의 유효범위를 가진다(= 괄호 안에서만 유효하다)

마지막 질문에서 등장한 `result`는 함수 안에서만 유효하기 때문에 `result` 가 바깥으로 못 나가는게 맞습니다.
이 내용은 크롬의 개발자 도구와 `debugger` 문을  이용하면 눈으로 확인할 수 있습니다.

지금 크롬 웹 브라우저에서 개발자 도구를 열어보세요(ctrl + shift + i).
지금 이 글을 읽는 용도로 사용하고 있는 브라우저도 좋습니다.
그리고 아래의 코드를 복사해 크롬 개발자 도구의 콘솔에 붙여넣고 엔터를 쳐 보세요.
```jsx
function add(a, b){
  var result = a + b;
  debugger;
}

add(2, 3);
 debugger;
console.log(result); //error
```

그러면 순간적으로 프로그램의 실행을 멈추고 변수의 상태를 엿볼 수 있게 됩니다.
지금 프로그램이 멈춘건 어디까지나 `debugger` 문의 도움입니다.
![1](https://user-images.githubusercontent.com/1357198/210359862-212d0a57-97da-4537-96c1-fa3106098e33.png)

이제 ![스크린샷 2023-01-03 오후 9 42 26](https://user-images.githubusercontent.com/1357198/210360004-40775ff1-d1df-44df-919a-a003d3e2e831.png)를 눌러서 다음 `debugger` 문이 가리키는 시점으로 이동해 봅시다.
![2](https://user-images.githubusercontent.com/1357198/210360124-76b2c481-279c-41e4-a3f5-c1b3d364a21e.png)

눈으로 보니까 좀 더 확실해지는것 같습니다.
### 결국 `console.log(result); //error` 에서 `console.log` 함수는 존재하지 않는 `result` 를 읽으려고 시도해서 에러를 낸 것이네요.
잘 하고 계십니다.
화이팅

**Comment by rowooncoding** [comment]
질문자입니다! 이렇게 보니까 이해가 잘되네요!!! 감사합니다 야무쌤

**Comment by shoveller** [comment]
흑흑… 제 이름은..

**Comment by yamoo9** [comment]
@rowooncoding 님 ㅎ 제가 답변 남긴 글이 아니고, 
재원 멘토님(@shoveller)님이 남겨주신 소중한 글이에요 😅
