### ISSUE TITLE
[LAB-2] git pull request 이슈

### ISSUE THREAD

**Issue by leejh4197** [yamoo9/likelion-FEQA#70]
## 문제 상황
팀원과 코드를 합치기위하여 main 으로 pr 후 mege를 하는 과정에서 confilct가 났지만 버튼이 활성화되지 않았습니다. 그래서 해당 pr을 close하였고
아래 사진처럼 나와있는 상황입니다.
close돼 있는 pr은 재 pr이 안되는 것 같던데 delete branch만 나와있어 어떻게 해야 할지 길을 잃은 상황입니다..

![image](https://user-images.githubusercontent.com/91236732/216630271-5d14c2b7-a9a0-40e1-8adc-349976ac4b74.png)
## 질문 작성자
이주형

## 프로젝트 저장소 URL

https://github.com/TellmeMarket/Market-Kalry

**Comment by yamoo9** [comment]
## 문제 파악 중...

충돌(conflict) 상황에서 **버튼 활성화가 되지 않았다는 말이 정확히 무엇을 말하는 건지 추가 설명이 필요합니다.**

그리고 첨부된 이미지는 PR이 성공적으로 병합되어 상황이 종료 됨을 안내하고 있고, Delete branch는 
병합된 브랜치를 삭제하는 버튼입니다. ([참고](https://docs.github.com/ko/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/deleting-and-restoring-branches-in-a-pull-request))

병합된 브랜치를 Delete branch 버튼을 누르지 않고 자동 삭제할 경우 별도 설정이 필요합니다. ([참고](https://docs.github.com/ko/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches))

**Comment by seulbinim** [comment]
조언해드린 것처럼 스크럼마스터가 아닌 해당 코드를 작성한 개발자가 
오가니제이션 저장소를 Pull 한 후 충돌을 해결하시기 바랍니다.
해당 충돌이 해결 된 후 다시 Push하고 PR을 생성하면
문제 없이 main 브랜치에 merge가 될 것으로 판단됩니다.
해당 이슈는 close 하겠습니다.
