### ISSUE TITLE
[LAB-14] input checkbox가 안나오는 문제

### ISSUE THREAD

**Issue by YmChoi-Repo** [yamoo9/likelion-FEQA#71]
## 문제 상황

![문제상황1](https://user-images.githubusercontent.com/82636319/216648682-90b67917-01f6-4de5-b32a-6e612a115f1b.PNG)

안녕하세요! 늦은 시간까지 고생이 많으십니다
자바스크립트 파일을 다루다가 동작이 안돼서, 본래 html/css만 입혀놓았던 원래의 상태로 돌려놓았는데  
사진과 같이 checkbox만 안나오고 있어서 질문 드립니다!

## 질문 작성자

최영민

## 프로젝트 저장소 URL

(https://github.com/likelion-lab14/lab14-project)

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by seulbinim** [comment]
채팅방 방문해서 점검해 드리도록 하겠습니다.
