### ISSUE TITLE
[LAB-2] git pull request 이미지 파일 누락현상

### ISSUE THREAD

**Issue by rodwnl** [yamoo9/likelion-FEQA#72]
## 문제 상황

![git pull request 이미지누락](https://user-images.githubusercontent.com/88178123/216654568-a656f102-9718-45d4-b895-45f86bd1ede9.png)
![image](https://user-images.githubusercontent.com/88178123/216656577-aa63e56f-dfd7-49c3-ad4b-6706da37b07e.png)

저희가 feature/kyoungju/main 브랜치를 main에 병합을 했는데 feature/kyoungju/main banner 폴더와 product 폴더에 있는 이 이미지 파일들이 계속 누락된 채로 병합이 됩니다. (사진 왼쪽에 보시면 빨간색 - 표시로 사라진 채 병합된 것을 확인할 수 있습니다.) 참고로 banner01-04.png와 product01-04.png 들은 main에는 없는 이미지들이어서 충돌요소도 아니었습니다. 

충돌 요소가 아닌데도 그냥 누락되서 merge가 되는데 이러한 이유가 있을까요?

## 질문 작성자
이경주

## 프로젝트 저장소 URL
https://github.com/TellmeMarket/Market-Kalry

## 환경 정보 (Optional)

- 운영체제 종류 : window

**Comment by seulbinim** [comment]
새로운 브랜치의 이미지 파일 모두 커밋이 완료되었고
해당 커밋 역시 반영을 위한 PR을 보내셨나요?

**Comment by rodwnl** [comment]
> 새로운 브랜치의 이미지 파일 모두 커밋이 완료되었고 해당 커밋 역시 반영을 위한 PR을 보내셨나요?

네 지금 사진에 누락된 사진들은 원래 브랜치에서 commit이 다되어있는 상태였고 브랜치를 병합하는데 성공적으로 병합하는 과정에서 이상하게 이미지파일들만 누락되서 병합이 됩니다 ㅠㅠ
