### ISSUE TITLE
[LAB-10] li태그 안에 a태그 가운대 정렬 되지 않는 문제 

### ISSUE THREAD

**Issue by SimYuseon** [yamoo9/likelion-FEQA#73]
## 문제 상황

li태그 안에 있는 a태그 실시간 부분의 글자를 다른 글자들과 같이 가운대로 보내야 하는대 포지션을 하면 깨지고 text align /align intems/ vertical align 등등 이런것을 하지 않아도 정렬 되지 않아서 display inline block 을 해도 되지 않는대 무슨 문제 일까요? 

<ul class="NavMenu__list">
            <li class="NavMenu__list__item NavMenu__list__liveItem">
              <img class="NavMenu__list__liveItem__img" src="../../client/assets/svg/header/live.svg" alt="live image" />
              <a href="/" class="list__link list__liveItem"> 실시간</a>
            </li>

💡 이미지, GIF, 비디오 파일을 입력 필드로 끌어 옮기면 자동 삽입됩니다. 
<img width="730" alt="스크린샷 2023-02-04 오후 1 22 59" src="https://user-images.githubusercontent.com/111304551/216748307-7b22ddb3-2b9b-4a20-9bb5-84ab31f55640.png">
## 질문 작성자

GitHub 아이디로 질문자를 유추하기 어렵습니다. 질문 작성자의 실명을 입력해주세요.
심유선
## 프로젝트 저장소 URL
https://github.com/LikeLion-VJS10/TAING10
GitHub 학습 저장소 URL을 여기에 남깁니다. (참고용)

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by seulbinim** [comment]
해당 저장소의 어떤 브랜치를 확인해야 하는지 알려주시기 바랍니다.
