### ISSUE TITLE
[LAB-8] radio value undefined

### ISSUE THREAD

**Issue by hwanyplaying** [yamoo9/likelion-FEQA#74]
## 문제 상황
추가입력 사항에 있는 radio 값을 선택해서 css를 적용하고 싶은데 기본적으로 `checked` 된 값이 존재하지 않아 `undefined` 상황 일 때, 이 아이를 제어 할 방법을 알고싶어서 질문 드립니다.

![](https://user-images.githubusercontent.com/87050952/216855789-4d6de245-5fb3-411f-aa94-a5bc62a3fbbd.png)

## 질문 작성자

질문 작성자 : 문창환

## 프로젝트 저장소 URL

https://github.com/likelion-lab8-JS/market-karly
브랜치명 : page_register

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 window10
- Node.js 버전 14.17.5

**Comment by yamoo9** [comment]
## 오류 상황

오류 상황을 효과적으로 전달하려면 오류 메시지를 보여줘야 합니다.
**정확한 오류 상황은 `undefined`에 있는 것이 아니라, 문서 요소가 존재하지 않아 `null`이므로 `value` 속성을 가질 수 없다는 것입니다.**

<img width="931" alt="image" src="https://user-images.githubusercontent.com/1850554/216858920-054d1ef2-68d1-40ee-a79e-96959ae1c385.png">

## 오류 해결

해당 문제는 조건 처리를 통해 오류가 발생하지 않도록 조치할 수 있습니다.
아래 코드를 참고하세요.

```js
const add = function () {
  
  let add_value = '';
  const addInput = document.querySelector('input[name="add"]:checked');
  
  if (addInput) {    
    add_value = addInput.value;
  }

	if (add_value == "recommend") {
		add_recommend.classList.remove("none");
	} else if (add_value == "event") {
		add_event.classList.remove("none");
	} else {
		add_recommend.classList.add("none");
		add_event.classList.add("none");
	}
}
```
