### ISSUE TITLE
[LAB-2] Swiper 관련 문제 

### ISSUE THREAD

**Issue by rodwnl** [yamoo9/likelion-FEQA#75]
## 문제 상황

![image](https://user-images.githubusercontent.com/88178123/217036826-f4e849f1-b2c7-4bc9-a1f3-6da07aadb2cf.png)
![image](https://user-images.githubusercontent.com/88178123/217039013-646b60c0-4881-42aa-88e1-6f245b02e9e9.png)
![image](https://user-images.githubusercontent.com/88178123/217036955-63a79f35-13b6-4cf2-b634-e7d88377381f.png)
1. 이 상품 어때요? 와 놓치면 후회할 가격 스와이프에 실제 마켓컬리 페이지처럼 슬라이드 끝에 갔을 때 다음 버튼을 사라지게 하고, 슬라이드 맨 첫 부분일 때는 이전 버튼이 사라지게 하려고했습니다. 그래서 스와이프 끝과 처음을 인식하는 reachBeginning, reachEnd 을 알게 되었고 사용하려고 했으나 웹페이지를 켰을 때 reachBeginning의 log가 아닌 reachEnd의 log가 계속 처음에 찍힙니다. 이러한 이유가 있을까요?

![image](https://user-images.githubusercontent.com/88178123/217037308-70ecc5c7-9e44-4906-822b-ce8eb1d5b581.png)
![image](https://user-images.githubusercontent.com/88178123/217038058-511ba931-13e6-44bd-a65a-0c0e7334941e.png)

2. 최근 본 상품 swiper의 slide 높이를 51px로 지정하려 .product-img-wrapper(최근 본 상품 swiper의 slide 클래스명)에 height 값을 지정해주었습니다. 하지만 지정한 적 없는 element.style { height : 129px }이 적용되어 51px 높이가 적용이 되질 않습니다. element.style {height : 129px}를 지정해주지 않았는데 계속 이 요소가 들어가는 이유가 있을까요? 이를 없애기 위해 두번째 사진과 같은 코드도 작성했는데 이도 적용안되는 이유는 무엇인가요?

## 질문 작성자
이경주

## 프로젝트 저장소 URL
https://github.com/TellmeMarket/Market-Kalry/tree/feature/kyoungju/main
https://github.com/rodwnl/Market-Kalry/tree/feature/kyoungju/main

둘 중 아무데나 들어가셔도 됩니다. clone 하고 확인 시 npm run all로 데이터 서버까지 켜주셔야 확인이 가능합니다!

## 환경 정보 (Optional)
- 운영체제 종류 : Windows

**Comment by simseonbeom** [comment]
안녕하세요 경주님 :)

1. 슬라이드의 끝지점은 reachBeginning, reachEnd 로 잡을 수 있지만, 기본적으로 스와이프엔 처음과 끝지점을 인식해 버튼에게 swiper-button-disabled 라는 클래스를 넣어주고 있습니다.
해당 클래스를 사용해 css를 적용하면 그대로 반영이 되니 참고하시면 좋을것 같아요. 
또는 swiper API 에는 disabled 클래스를 커스텀 할 수 있는 속성도 제공하니 확인해보세요 :)

2. swiper는 슬라이드의 크기를 부모의 크기에 몇개를 보여줘야 하는가? 를 인식해 크기를 잡아서 계산합니다 혹시 js 설정에 slidePerView 항목이 적혀 있는지 확인해보세요~

**Comment by rodwnl** [comment]
> 안녕하세요 경주님 :)
> 
> 1. 슬라이드의 끝지점은 reachBeginning, reachEnd 로 잡을 수 있지만, 기본적으로 스와이프엔 처음과 끝지점을 인식해 버튼에게 swiper-button-disabled 라는 클래스를 넣어주고 있습니다.
>    해당 클래스를 사용해 css를 적용하면 그대로 반영이 되니 참고하시면 좋을것 같아요.
>    또는 swiper API 에는 disabled 클래스를 커스텀 할 수 있는 속성도 제공하니 확인해보세요 :)
> 2. swiper는 슬라이드의 크기를 부모의 크기에 몇개를 보여줘야 하는가? 를 인식해 크기를 잡아서 계산합니다 혹시 js 설정에 slidePerView 항목이 적혀 있는지 확인해보세요~

![image](https://user-images.githubusercontent.com/88178123/217117189-2c180289-5bb6-4a60-84eb-12bd638bb7fa.png)
범쌤 답변감사합니다!! 덕분에 1번은 해결했는데 2번은 아직 해결하지 못했습니다ㅠㅠ 최근 본 상품의 스와이프의 wrapper와, swiper 크기를 지정한것은 맞으나 사진과 같이 방향과 이전,다음 버튼 인식, a11y만 있기 때문에 slidePerView의 영향은 아닌 것 같습니다. 다른 이유가 있을까요??

**Comment by simseonbeom** [comment]
swiper 슬라이드는 보여줄 갯수를 지정하지 않으면 기본 1개의 슬라이드를 보여주도록 설정됩니다.
swiper의 크기를 129px로 잡으셨다면 슬라이드의 항목들도 한개씩 보여야 하기 때문에 129px의 높이를 그대로 가져가게 되는것이죠, 

이 문제를 해결하기 위해선 슬라이드의 보여줄 갯수 `slidesPerView` 의 옵션값으로 2.5개를 넣어 해결할 수 있습니다.  

`slidesPerView:2.5`
