### ISSUE TITLE
[LAB-17] json파일 불러오기

### ISSUE THREAD

**Issue by Simyumi** [yamoo9/likelion-FEQA#76]
## 문제 상황

<img width="557" alt="" src="https://user-images.githubusercontent.com/59659154/217087508-d3e60dc5-bb72-46a4-8119-1b642497bf7b.png">

json 파일을 불러오는걸 못하겠습니다.........살려주세여

## 질문 작성자

심유미
product_list

## 프로젝트 저장소 URL

https://github.com/Simyumi/karly-17-devfolio

## 환경 정보 (Optional)

- 운영체제 종류 (예: Windows, macOS). 
- Node.js 버전 (예: v16.14.0).     v18.12.1

**Comment by simseonbeom** [comment]
안녕하세요 유미님 :)

해당 코드 로직만 올려주시면 질문의 의도를 파악하는데 어려움이 있습니다. 
어느 부분에 에러가 발생하는지 자세히 작성해주시면 좋을것 같아요~

**Comment by Simyumi** [comment]
에러라기 보다 아애 아무것도 안떠서 ........에러도 검색해 볼수가없습니다...

**Comment by yamoo9** [comment]
@Simyumi 님이 이해할 수 있도록 제품 리스트를 렌더링 하는 JSON 요청/응답 렌더링 데모를 작성해봤습니다.
작성된 코드를 찬찬히 살펴보고 이해해보세요. 😊

→ [JSON 요청/응답 렌더링 데모](https://stackblitz.com/edit/web-platform-ltajjk?file=index.html)

<img width="300" alt="" src="https://user-images.githubusercontent.com/1850554/217116256-28d1b0ed-3a1d-443b-8a70-ab4daf662e50.png">

데모에 작성된 함수 코드는 아래와 같아요.

<details open>
  <summary>컨테이너 HTML 요소</summary>

  ```html
  <ul class="container"></ul>
  ```
</details>

<details open>
  <summary>데모(demo) 함수</summary>

  ```js
  let API_ENDPOINT = 'https://makeup-api.herokuapp.com/api/v1/products.json?product_category=gel&product_type=eyeliner';

  async function demo() {
    const container = document.querySelector('.container');
    const data = await loadProducts(API_ENDPOINT);
  
    displayProducts(data, container);
  }
  
  globalThis.addEventListener('DOMContentLoaded', demo);
  ```
</details>

<details open>
  <summary>loadProducts 함수</summary>

  ```js
  function loadProducts(endpoint) {
    return fetch(endpoint)
      .then((response) => response.json())
      .catch((error) => console.error(error));
  }
  ```
</details>

<details open>
  <summary>displayProducts 함수</summary>

  ```js
  function displayProducts(products, container) {
    container.innerHTML = products
      .map((product) => createHTMLString(product))
      .join('');
  }
  ```
</details>

<details open>
  <summary>createProductTemplate 함수</summary>

  ```js
  function createProductTemplate(product) {
    return `
      <li>
        <a 
          href="${product.product_link}" 
          rel="noopener noreferrer"
          target="_blank" 
        >
          <img src="${product.image_link}" alt="" />
          <em>${product.brand} ${product.name}</em>
          <p>${product.description}</p>
          <span>${product.price_sign}${product.price} (${product.currency})</span>
        </a>
      </li>
    `;
  }
  ```
</details>
