### ISSUE TITLE
[LAB-14] 인터폴레이션 내부에서 코드 작성

### ISSUE THREAD

**Issue by djswns7** [yamoo9/likelion-FEQA#77]
## 문제 상황

어제 마지막에 제가 범쌤께 질문한 내용중에서(인터폴레이션 구문안에 일반코드 넣는거)
${} 내부에 if 문을 넣었는데 Uncaught SyntaxError 가 계속 발생합니다
제가 뭔갈 놓친 부분이 있는것 같은데 
리터럴 인터폴레이션 관련해서 구글링해도 자꾸 변수 하나 넣는것들 위주로만 떠서 질문드립니다...

![image](https://user-images.githubusercontent.com/72201211/217125528-a17036d2-4a65-4ffd-853d-804db8f5f8e6.png)

![image](https://user-images.githubusercontent.com/72201211/217125364-fc490e5d-fc1b-4304-81b0-eb60c85ba53c.png)  

## 질문 작성자
박원준

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 
  윈도우

**Comment by simseonbeom** [comment]
안녕하세요 원준님 :) 

문은 값을 반환하지 못하므로 if문 대신 비
값을 반환하는 식(삼항연산식)을 사용해보세요  :)

**Comment by djswns7** [comment]
> 안녕하세요 원준님 :)
> 
> 문은 값을 반환하지 못하므로 if문 대신 비 값을 반환하는 식(삼항연산식)을 사용해보세요 :)

감사합니다! 삼항연산자로 당장 문제는 해결하였습니다.

다만 확인하고 싶은 부분이 있어 덧붙이자면
원래의 질문에서도 오류가 났던 이유가 if문이 값을 반환하지 못해서 에러가 났던 것이지,
인터폴레이션 구문 안에서 if 를 사용하는 것 자체는 상관이 없는걸까요?
=>"인터폴레이션 구문은 하나의 값을 리턴하는 형식으로 구성해야한다" 라고 이해하는게 맞는지가 궁금합니다

**Comment by simseonbeom** [comment]
인터폴레이션 자체가 식이기 때문에 문을 사용하는것 자체가 안됩니다. for while 등등..


에러 메시지를 보면 `SystaxError Unexpected token 'if'` 라고 나오는데요, 이 구문은 문법오류이며, if 라는 토큰은 올 수 없다 라고 안내가 되어있습니다.  :)
