### ISSUE TITLE
[LAB-3] SOS!!!! JSON 파일의 값들을 불러와 랜더링할 때 효율성 문제

### ISSUE THREAD

**Issue by hardy-is-cat** [yamoo9/likelion-FEQA#78]
## 문제 상황

![1](https://user-images.githubusercontent.com/76080643/217171940-8cf88a39-f4c4-46c1-9bb6-4df04d871458.png)

처음에 이런 식으로 data.json 파일을 만들고 최상단 스와이퍼를 동적으로 랜더링하는데까지는 성공했습니다.

![스크린샷 2023-02-07 오후 4 05 26](https://user-images.githubusercontent.com/76080643/217172070-492829f3-6677-4fef-ab14-1c4762652cdb.png)

스와이퍼의 종류가 많아 각각 mainVisual, recommendTaing ... 등으로 나누어 데이터를 불러오고 싶은 상태인데요.

```js
const contentsContainer = getNode(".swiper-wrapper");

export async function rendingContents(slideName) {
  try {
    let response = await tiger.get(
      "http://localhost:3000/contents"
    );
    let contentsData = response.data[slideName];

    contentsData.forEach((data) => {
      renderContents(contentsContainer, data);
    });

    console.log("랜더링성공");
  } catch (err) {
    console.log(err);
  }
}

export const createMVSlide = ({
  id = "",
  story = "",
  image = "",
} = {}) => {
  return /* html */ `
    <div class="swiper-slide" data-index="mainVisual${id}">
      // 슬라이드 내용
    </div>`;
};

export const renderContents = (target, data) => {
  insertLast(target, createMVSlide(data));
  console.log("랜더링성공");
};
```

위와 같은 코드를 사용했고, 만들어야 하는 스와이퍼의 갯수는 6개인데,
두번째 슬라이드와 같은 json 파일을 만들어 스와이퍼를 랜더링하고 싶은데
함수를 각각 만들어야 하는지...아무래도 효율이 좋지 않은 것 같은데
코드를 어떤 식으로 짜야할 지 점점 뇌가 굳어가고 있습니다...ㅠㅠ

## 질문 작성자

조정현, 김종엽

## 프로젝트 저장소 URL

https://github.com/likelion-fe4-js3/taing/issues
아직 해당 코드를 push 하진 않았습니다

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by yamoo9** [comment]
## 문제 상황

JSON Server 라우팅 이슈입니다. ([참고](https://github.com/typicode/json-server#routes))

## 문제 해결

Discord 화상으로 문제 상황을 검토하고 적절한 해결 방법을 제시하였습니다.

```sh
http://localhost:3000/main-visual
http://localhost:3000/recommand-taing
```
