### ISSUE TITLE
[LAB-8] swiper loop 기능으로 복사된 슬라이드에 tab 포커스가 되지 않게 하고 싶습니다.

### ISSUE THREAD

**Issue by jh1109** [yamoo9/likelion-FEQA#79]
## 문제 상황

- 마켓 칼리에서 tab으로 메인 배너에 접근할 때 복사된 슬라이드까지 tab 포커스가 잡힙니다.
- 마크업 된 swiper-slide는 4개 이고 swiper는 `loop`가 `true` 입니다.
- 문제 상황으로 포커스 되는 tab 순서는, 4번 슬라이드 > 1번 슬라이드 > 2번 슬라이드 > 3번 슬라이드 > 4번 슬라이드 > 1번 슬라이드 > prev 버튼 > next 버튼 순서 입니다. (4번과 1번 슬라이드가 두 번 포커스 되는 상황입니다.)
- 원하는 구현은 슬라이드의 중복이 없도록 tab 포커스가 되는 것입니다.

- 시도1 : `loop` 순환을 위해 복사된 슬라이드에 `swiper-slide-duplicate`라는 클래스가 추가되는 것을 확인하고 `tabindex=-1`을 작성했는데도 여전히 문제상황으로 동작합니다.(mainswiperjs 이미지 참고)
- 시도2 : swiper-slide에 모두 `tabindex`를 지정해도 문제상황으로 동작합니다. (방법2 이미지 참고)

![html 구조](https://user-images.githubusercontent.com/117807467/217203588-d7215bac-2bc2-43a4-878f-bf021daf8790.png)

![mainswiperjs](https://user-images.githubusercontent.com/117807467/217203628-ac9eb665-44b9-47c9-8c46-7824f7cb0bc3.png)

![방법2](https://user-images.githubusercontent.com/117807467/217203655-40e6fae4-5f61-4453-b08c-8ee714bb5d84.png)

## 질문 작성자

노주희 

## 프로젝트 저장소 URL

- https://github.com/likelion-lab8-JS/market-karly

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS) : Windows
- Node.js 버전 (예: v16.14.0) : 18.12.1

**Comment by yamoo9** [comment]
## 문제 상황

복제한 프로젝트를 실행해본 결과 다음의 접근성 이슈가 발견되었습니다.

- [ ] Swiper `loop` 설정으로 복제된 슬라이드에 초점이 이동하는 문제
- [ ] 화면에 감춰진 이전/다음 탐색 버튼에 초점이 이동하는 문제
- [ ] 마우스 또는 포커스 이벤트 발생 시 자동재생 슬라이드 정지/시작 설정 필요

## 문제 해결

Swiper API 문서를 읽고 요구사항 구현을 위해 필요한 기능을 활용합니다.

- [autoplay 설정](https://swiperjs.com/swiper-api#autoplay)
  - [autoplay.start() 메서드](https://swiperjs.com/swiper-api#method-swiper-autoplay-start)
  - [autoplay.stop() 메서드](https://swiperjs.com/swiper-api#event-autoplayStop)
- [on 설정](https://swiperjs.com/swiper-api#events)
  - [afterInit 이벤트](https://swiperjs.com/swiper-api#event-afterInit)
  - [slideChangeTransitionStart 이벤트](https://swiperjs.com/swiper-api#event-slideChangeTransitionStart) 

### 해결된 접근성 이슈

- [x] Swiper `loop` 설정으로 복제된 슬라이드에 초점 이동 차단 (`tabindex="-1"`)
- [x] 화면에 감춰진 이전/다음 탐색 버튼 비활성화 설정  (`disabled`)
- [x] 마우스 또는 포커스 이벤트 발생 시 자동재생 슬라이드 정지/시작 설정 (`mouseenter`, `mouseleave`, `focusin`, `focusout`)

### 구현 가이드

아래는 요구사항을 구현한 코드입니다. 
작성된 주석을 참고하고 질문이 있다면 요청주세요. Discord에서 해설해드릴께요.

```js
// 메인 배너 요소 참조
const mainBannerElement = document.querySelector('.swiper_main_banner')

const mainBannerSwiper = new Swiper('.swiper_main_banner', {
  autoplay: {
    delay: 3000,
  },
  // ...
  on: {
    afterInit() {
      // 복제된 슬라이드 내부의 앵커(링크) 집합 참조
      const duplicatedSlideLinks = mainBannerElement.querySelectorAll('.swiper-slide-duplicate a')
      // tabindex="-1" 설정
      duplicatedSlideLinks.forEach((link) => link.setAttribute('tabindex', -1))

      // 이전/다음 탐색 버튼 집합 참조
      const prevNextButtons = mainBannerElement.querySelectorAll('[class*="swiper-button-"]')
      // 비활성화 설정 (초점 이동 차단)
      prevNextButtons.forEach((button) => button.setAttribute('disabled', 'disabled'))

      // 스와이퍼 자동재생 정지 핸들러
      const handleSwiperStop = (e) => { e.currentTarget.swiper.autoplay.stop() }

      // 스와이퍼 자동재생 시작 핸들러
      const handleSwiperPlay = (e) => { e.currentTarget.swiper.autoplay.start() }

      // 마우스 이벤트 핸들링
      mainBannerElement.addEventListener('mouseenter', handleSwiperStop)
      mainBannerElement.addEventListener('mouseleave', handleSwiperPlay)
      // 포커스 이벤트 핸들링
      mainBannerElement.addEventListener('focusin', handleSwiperStop)
      mainBannerElement.addEventListener('focusout', handleSwiperPlay)
    },
    slideChangeTransitionStart() {
      // tabindex="-1" 요소 집합 참조
      const tabindexMinusOnes = mainBannerElement.querySelectorAll('[tabindex="-1"]')
      // tabindex 속성 제거 (초점 이동 가능하도록)
      tabindexMinusOnes.forEach((link) => link.removeAttribute('tabindex'))

      // 화면 밖에 위치한 슬라이드의 앵커(링크) 집합 참조
      const invisibleSlideLinks = mainBannerElement.querySelectorAll('.swiper-slide-duplicate a')
      // tabindex="-1" 설정 (초점 이동 차단)
      invisibleSlideLinks.forEach((link) => link.setAttribute('tabindex', -1))
    },
  },
})
```

**Comment by jh1109** [comment]
감사합니다!!
