### ISSUE TITLE
🛎️ 생성자 표기법으로 생성한 변수와 리터럴 표기법으로 생성한 변수는 프로토타입이 다른가요? 

### ISSUE THREAD

**Issue by shoveller** [yamoo9/likelion-FEQA#8]
[STD1 - 1주차 멘토링 5번째 질문](https://likelion.notion.site/1-f42db4f5dfc143d78632a77f2b10e85a)

```
❓ 리터럴과 생성자의 차이를 찾아보았는데
생성자 표기법으로 생성한 변수의 프로토타입은 생성자 함수고, 
리터럴 표기법으로 생성한 변수의 프로토타입은 자기 자신의 객체다

라는 부분에서 프로토타입의 차이로 생기는 차이점을 잘 모르겠습니다. 
```

안녕하세요. 익명의 질문자님. 어려운 질문을 주셨네요. 

**네.  생성자 표기법으로 생성한 변수의 프로토타입과 리터럴 표기법으로 생성한 변수의 프로토타입은 다를 수 있습니다.**

지금 브라우저의 개발자 도구를 여시고, 아래의 코드를 붙여넣어 보세요.
이 코드는 리터럴로 선언한 변수의 프로토타입과 원시값을 표시합니다.

```jsx
var person = { name: '사람' }
console.log('리터럴로 선언한 변수의 프로토타입', person.__proto__)
console.log('리터럴로 선언한 변수의 원시값', person.valueOf())
```
![1](https://user-images.githubusercontent.com/1357198/210700755-1f9bf593-bb35-490e-9b21-57ccca3e6ed2.png)

이제 아래의 코드를 붙여넣어 보세요.
이 코드는 생성자로 선언한 변수의 프로토타입과 원시값을 표시합니다.

```jsx
function Person() {
  this.name = '사람'
}
var person1 = new Person()
console.log('생성자로 선언한 변수의 프로토타입', person1.__proto__)
console.log('생성자로 선언한 변수의 원시값', person1.valueOf())
```
![2](https://user-images.githubusercontent.com/1357198/210700809-dbbbc9c8-248e-4276-b517-b5203b519592.png)

프로토타입과 원시값이 다르네요!
![1](https://user-images.githubusercontent.com/1357198/210700755-1f9bf593-bb35-490e-9b21-57ccca3e6ed2.png)
![2](https://user-images.githubusercontent.com/1357198/210700809-dbbbc9c8-248e-4276-b517-b5203b519592.png)

### 왜 이렇죠?

자바스크립트 엔진은 코드를 해석하다가 리터럴로 선언한 객체를 만나면, 
[Object 생성자 함수로 감싼 것으로 해석합니다.](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object)

```jsx
// 자바스크립트 엔진이 이 코드를 
var person = { name: '사람' }
person.valueOf()

// 이렇게 해석한다!
var person = new Object({ name: '사람' })
person.valueOf()
```

그러면 이제 위의 말이 이해가 됩니다.
단어가 좀 어렵게 쓰였네요.
`리터럴 표기법으로 생성한 변수의 프로토타입은 자기 자신의 객체` -> `리터럴로 선언한 변수는 Object 생성자 함수로 선언한것`
`생성자 표기법으로 생성한 변수의 프로토타입은 생성자 함수` ->`생성자 함수로 선언한 변수는 그 생성자 함수로 선언한것`

```jsx
// 생성자 표기법으로 생성한 변수의 프로토타입은 생성자 함수고 
function Person() {
  this.name = '사람'
}
var person = new Person()
console.log('생성자 표기법으로 생성한 변수의 프로토타입은 생성자 함수고 ', person.valueOf(), person.__proto__)

// 리터럴 표기법으로 생성한 변수의 프로토타입은 자기 자신의 객체다
var person1 = new Object({ name: '사람' })
console.log('리터럴 표기법으로 생성한 변수의 프로토타입은 자기 자신의 객체다', person1.valueOf(), person1.__proto__)
```
![3](https://user-images.githubusercontent.com/1357198/210701069-15d3b1f6-f5a7-48f8-b993-8e9e24997a31.png)

### 기능적인 차이는 있나요?
없다고 단언할 수 있습니다.
두 방법 모두 프로토타입 체인을 사용할 수 있거든요.
만약, `Object.prototype.hasOwnProperty` 를 사용하고자 한다면.

생성자 함수로 생성한 변수는 프로토타입 체인을 1단계 더 거슬러올라가야 하는데
![4](https://user-images.githubusercontent.com/1357198/210701182-931d0738-eea5-44e5-a342-05299c72aa0a.png)

객체 리터럴로 생성한 변수는 프로토타입 체인을 한단계 덜 찾는 정도의 차이가 있네요.
![5](https://user-images.githubusercontent.com/1357198/210701397-c3b4db79-7160-4611-9e8f-2ac27b9e60f7.png)

### 결론
```
리터럴로 선언한 객체(= {} )는 객체 생성자로 선언한 객체(=  new Object({}) )와 같다.
리터럴로 선언한 객체는 프로토타입 체인이 짧다.
 ```

이 지식을 기술면접에서 활용하시게 될 그 날이 꼭 오길 바랍니다.
화이팅.

**Comment by yamoo9** [comment]
멋진 답변 감사합니다~ 👏🏻
