### ISSUE TITLE
[LAB-17] json 파일에서 value를 추출하는 법을 모르겠습니다 

### ISSUE THREAD

**Issue by Simyumi** [yamoo9/likelion-FEQA#80]
## 문제 상황

화면에 띄우기까지는 성공했는데 json에 `undefined` 값이 있는 곳에도 공간이 생겨 `undefined`일 때 `display:none`을 하고싶은데 

<img width="779" alt="" src="https://user-images.githubusercontent.com/59659154/217212703-510ad81f-0a9a-4e4f-bcd3-14695c0074b9.png">

<img width="827" alt="" src="https://user-images.githubusercontent.com/59659154/217212988-ce2bb500-f4d4-41b2-9504-bbf302906597.png">

<img width="767" alt="" src="https://user-images.githubusercontent.com/59659154/217213120-6f077959-5bd9-4dac-8ade-6a2eed684a1b.png">

<img width="724" alt="" src="https://user-images.githubusercontent.com/59659154/217213309-9f87bdf1-27e7-48e2-bde5-740fdc5c66f6.png">

`product.saleRatio`가 콘솔에 찍히지 않아서 ㅠ 

## 질문 작성자

심유미

## 프로젝트 저장소 URL

https://github.com/Simyumi/karly-17-devfolio

## 환경 정보 (Optional)

운영체제 종류 (예: Windows, macOS).
Node.js 버전 (예: v16.14.0). v18.12.1

**Comment by yamoo9** [comment]
## 문제 작성에 관해

질문에 대해 말씀드리면 "**뭘 물어보는 지 알 수 없다**" 입니다.
정확한 답변을 원한다면 무엇을 원하는지, 무엇이 문제인지 자세히 기술하세요.

### 질문 작성 시 유의할 점

문제를 작성할 때는 **이미지와 함께 관련 코드를 아래처럼 넣어주세요.**

```js
fetch('http://localhost:3000/products')
  .then((res) => res.json())
  .then((json) => {
    // ...
  });
```

그리고 **해당 코드가 GitHub 저장소 어디에 있는 파일인지 알려줘야 합니다.**
시간을 들여 찾아본 결과... 해당 코드는 존재하지 않았습니다. (동공 지진)

## 문제 해결 방법

정확히 무엇을 물어보는 지 알 수 없으나, 추론된 질문에 대한 답변을 드려봅니다.

### 질문

> `product.saleRatio` 값이 `undefined`인 경우 화면에 표시하고 싶지 않다.

### 답변

[조건부 렌더링](https://stackblitz.com/edit/web-platform-oy5pcj?file=index.html) 데모 코드를 작성했습니다.
데모 코드는 1초마다 조건부 렌더링 처리됩니다.
