### ISSUE TITLE
[LAB-10] 무료 호스팅 사이트와 FTP프로그램을 이용해 실제 도메인에 결과물을 올려보고자 합니다.

### ISSUE THREAD

**Issue by s-ja** [yamoo9/likelion-FEQA#81]
## 문제 상황

무료 도메인과 호스팅 서비스를 이용하여 프로젝트 결과물을 실제 인터넷 주소로 들어갈 수 있게끔 해보고 싶습니다!.

사용중인 무료 호스팅 사이트
https://nowhosting.kr/

사용중인 무료 도메인 사이트
https://xn--220b31d95hq8o.xn--3e0b707e/

사용중인 FTP프로그램
https://filezilla-project.org/

위 세가지 서비스를 이용하여 실제 도메인에 저희 결과물을 올려 발표에 활용하고자 합니다.
그런데, 아직 서비스나 프로그램에 대한 기능들을 잘 몰라 json 파일을 어디에 올려야 통신이 가능한지 모르겠습니다.

<img width="622" alt="Screenshot 2023-02-07 at 7 41 27 PM" src="https://user-images.githubusercontent.com/69342971/217223102-c9d0bc57-84d0-49e9-abfd-cb1902bb11b0.png">

이러한 의견을 제시한 제가 json 파일을 이용한 기능 구현에 참여하지 않아서 질문이 조금 막연한 느낌이지만,
프로젝트 기한이 얼마 남지 않았고, 시간이 늦기 전 질문 올리는 것이 좋을것이라고 판단하여 우선 글 남겨 봅니다.

## 질문 작성자

안승지

## 프로젝트 저장소 URL

https://github.com/LikeLion-VJS10/TAING10

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.14.0)

**Comment by yamoo9** [comment]
무료 이용이 가능한 [mockend](https://mockend.com/) 서비스를 이용해보세요. 😃
설치 후 이용 가능합니다. ([참고](https://github.com/marketplace/mockend))

<img width="958" alt="imag" src="https://user-images.githubusercontent.com/1850554/217227504-5f2adcfc-d8a5-40f8-8d6c-ad791492752f.png">

![](https://user-images.githubusercontent.com/1850554/217227554-b46d9483-311d-4ca8-b506-dc1630e911c3.png)
