### ISSUE TITLE
[LAB-8] 로그인 조건식 구현

### ISSUE THREAD

**Issue by hwanyplaying** [yamoo9/likelion-FEQA#82]
## 문제 상황
fetch 함수를 이용해서 data.json에 있는 데이터들을 읽어온 후
아이디의 존재 유무를 판단하고 localstorage에 남기는 방법은 구현한 것 같은데..
객체에서 아이디 비밀번호를 뽑아내서 조건을 거는 방법을 알고싶습니다..

![image](https://user-images.githubusercontent.com/87050952/217402655-55cf2bd0-4ae7-4075-97eb-c7577701ce70.png)

## 질문 작성자
문창환

## 해당 브랜치
page_login

## 프로젝트 저장소 URL

https://github.com/likelion-lab8-JS/market-karly

## 환경 정보 (Optional)

환경과 관련된 문제가 의심될 경우 작성합니다.

- 운영체제 종류 : windows10
- Node.js 버전 : 14.17.5

**Comment by simseonbeom** [comment]
안녕하세요 창환님 :)

로그인 버튼을 눌러 서버에 요청을 보낼 때 모든 유저를 요청해서 반복문을 돌리는 방법도 있지만, 

json-server의 api를 읽어보면, [특정 대상만 검색](https://www.npmjs.com/package/json-server#full-text-search)해서 찾는 방법도 있고 [필터](https://www.npmjs.com/package/json-server#filter)를 통해 대상만 찾아오는 방법도 있는듯 합니다.


검색을 통해 특정의 아이디만 찾아오고 validation 하는 코드를 구현해 보자면, 이런식으로 나올것 같네요 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/35365227/217409385-d17c169e-5ce2-4eb0-ad50-3e8d4032c0f1.png">


공식 문서의 다양한 api기능들을 살펴보세요 :)

**Comment by hwanyplaying** [comment]
앞으로 근본적인 api 기능의 공식 문서를 찾아보고 읽는 것을 습관으로 들이도록 하겠습니다.
항상 감사합니다 범쌤 :D
