### ISSUE TITLE
[LAB-13, SOS!] json-server에서 post를 했을 때, 기존 데이터베이스 초기화 문제

### ISSUE THREAD

**Issue by hungerbk** [yamoo9/likelion-FEQA#83]
## 문제 상황

현재 프로젝트에서 두개의 데이터베이스를 사용하고 있기 때문에, 두 데이터베이스를 서버에 동시에 구동하기 위해 index.js에 두 파일을 require하여 export했습니다.
그리고 서버를 구동하면 두 데이터베이스를 모두 확인할 수 있습니다.

하지만, 이렇게 서버를 구동한 뒤 post를 시도하면, 기존의 데이터 베이스가 사라지고 새로 입력한 내용만 남습니다.
또한, 이 경우 vscode에 있는 json 파일은 변경되지 않고, 서버에서만 반영이 됩니다.
post 메소드임에도 id 값이 새로 생기지 않고 제가 보낸 내용만 서버에 남게 됩니다. (서버를 껐다 켜면 초기화됩니다.)

json-server에서 js 파일을 경로에 넣어서 문제가 발생한걸까요...?
같은 코드에서 구동되는 서버 경로 를 json 파일로 바꿨을 때는 정상적으로 작동했습니다.

## 이미지

<img width="663" alt="스크린샷 2023-02-08 오후 2 04 02" src="https://user-images.githubusercontent.com/43366461/217438268-02cd9234-4c98-45dc-8192-fa694bc862ae.png">
<img width="591" alt="스크린샷 2023-02-08 오후 2 04 28" src="https://user-images.githubusercontent.com/43366461/217438328-8a8095d6-5afa-43aa-ad9a-be4d0e933277.png">

<  post 요청 보내기 전 서버와 vscode의 데이터베이스>
<br><br><br>
<img width="362" alt="스크린샷 2023-02-08 오후 2 05 40" src="https://user-images.githubusercontent.com/43366461/217438716-65c738cf-65a9-4169-8d81-44be2dd21b47.png">
<img width="652" alt="스크린샷 2023-02-08 오후 2 06 06" src="https://user-images.githubusercontent.com/43366461/217438845-e685db38-7652-4713-ac52-b9e1bcfb0efb.png">
<img width="586" alt="스크린샷 2023-02-08 오후 2 06 36" src="https://user-images.githubusercontent.com/43366461/217439009-80917e8f-dc63-49ca-bf64-90a32c967780.png">

<post 요청을 보낸 후의 서버, database, snapshot>
<br><br><br>
<img width="228" alt="스크린샷 2023-02-08 오후 2 07 31" src="https://user-images.githubusercontent.com/43366461/217439315-cc461ae7-acd6-48b7-a43f-a0a916145b11.png">

<server 파일 구성>
<br><br><br>
<img width="409" alt="스크린샷 2023-02-08 오후 2 07 57" src="https://user-images.githubusercontent.com/43366461/217439468-d7096816-c70d-40cf-9c89-44eb71d1752b.png">

<server/index.js 코드>
<br><br><br>
<img width="760" alt="스크린샷 2023-02-08 오후 2 08 40" src="https://user-images.githubusercontent.com/43366461/217439582-93d73f0f-d9e0-4970-b03f-f6dd4873db93.png">

<package.json 코드 내용>

처음에는 아래처럼 작성했다가 같은 문제가 발생하여 위처럼 바꿔둔 상태입니다.
"serve": "npx json-server --watch server/db/index.js",

<br><br><br>
<img width="563" alt="스크린샷 2023-02-08 오후 2 10 28" src="https://user-images.githubusercontent.com/43366461/217439827-941485cc-f4ed-4737-8ea6-8cc396bf8d25.png">

<post 요청 보내는 함수>
함수는 기존의 tiger 함수를 user로 바꾸어 사용하였고, 주석처리한 부분은 데이터를 불러오는지 확인하기 위해 작성한 코드입니다.
<br><br><br>

또한 post를 요청했을 때 아래와 같은 에러가 발생하는데, 혹시 이 에러와 관련이 있는걸까요?

<img width="314" alt="스크린샷 2023-02-08 오후 2 19 45" src="https://user-images.githubusercontent.com/43366461/217441266-1469d7fb-5fbb-48b9-8d80-b42df4560508.png">

## 질문 작성자

강보경

## 프로젝트 저장소 URL

https://github.com/phoenix-kurly/phoenix-kurly

## 환경 정보 (Optional)

- 운영체제 종류: macOS
- Node.js 버전: v18.12.1

**Comment by yamoo9** [comment]
## 문제 풀이

Discord를 통해 해당 현상에 대해 범쌤이 안내해드렸습니다.
