### ISSUE TITLE
리액트 CORS에러가 발생하면서 리액트 cdn이 동작하지 않습니다.

### ISSUE THREAD

**Issue by hardy-is-cat** [yamoo9/likelion-FEQA#85]
## 문제 상황

안녕하세요.

야무쌤 깃허브 저장소에 있는 내용을 그대로 가져온 다음
npm install로 서버 구동에 필요한 패키지를 설치해주었습니다.

![스크린샷 2023-02-14 오후 1 19 27](https://user-images.githubusercontent.com/76080643/218638452-fa3438c2-9e70-48a4-aedf-ed5ae7f90df2.png)

npm start로 서버를 구동하면 위와 같이 잘 실행되고 브라우저도 열리면서 수업때의 내용이 랜더링되는데

![2023-02-13_11 42 32](https://user-images.githubusercontent.com/76080643/218638554-b6892645-f7d4-4fdd-8e01-2c8dd61751ce.png)

코드 수정 후(크게 바꾼 것도 없습니다ㅠㅠ) 저장을 하면
위와 같은 CORS 에러가 발생하면서 리액트 cdn 자체가 동작하지 않습니다.

제가 짠 코드에 이상이 있나 싶어서 모두 삭제한 다음 깃허브 내용을 그대로 가져와 패키지만 설치,
서버를 실행하면 브라우저에 정상적으로 랜더링이 되는데, 새로고침을 하면 똑같이 CORS 에러가 발생합니다.

(https://velog.io/@silent10z/React-CORS-에러-해결)

위의 글을 읽어보았으나 보안상 이슈 때문에 접근할 수 없는 것이다...
라는 정도만 이해가고 에러 문구도 다릅니다.

(https://github.com/mjackson/unpkg/issues/229)
위의 글은 에러 문구는 같은데 하단의 해결 방법들이 이해가 안 갑니다

게다가 몇몇 분들에게 여쭤봤을 때 이게 저한테만 생기는 오류인 것 같아서요.
아예 안되면 모르겠으나 되다가 안되다 하니 알 수 없을 노릇입니다.
어떻게 해결하면 좋을까요...

## 코드 검토 리소스

코드는 야무쌤 코드를 그대로 가져왔습니다ㅠㅠ

## 환경 정보

- 운영체제 종류 : macOS
- Node.js 버전 : v.18.12.1

**Comment by shoveller** [comment]
안녕하세요! @hardy-is-cat 님.
지금 문제가 발생한 프로젝트를 github 등에 올려주시겠어요?
`gh` 같은 cli를 사용하면 좀 더 쉽게 올릴 수 있겠습니다.

**Comment by shoveller** [comment]
어쩌면.. 크롬에 설치한 플러그인이 문제를 일으켰을수도 있겠습니다.
웹 브라우저를 edge 등으로 바꿔서 테스트 해 보시겠어요?

**Comment by hardy-is-cat** [comment]
> 어쩌면.. 크롬에 설치한 플러그인이 문제를 일으켰을수도 있겠습니다. 웹 브라우저를 edge 등으로 바꿔서 테스트 해 보시겠어요?

헉 파이어폭스로 열어보니 잘 동작합니다 도대체 어떤것 때문인지...

![스크린샷 2023-02-14 오후 2 48 51](https://user-images.githubusercontent.com/76080643/218650611-e8004dfe-adf7-4d84-b622-23cf75c17bd7.png)

현재 깔려있는 확장프로그램은 이렇게 있거든요ㅠㅠ

현재 코드는 https://github.com/yamoo9/likelion-react 여기에 있는 코드를 그대로 끌어와서 사용하고 있습니다
git clone 으로 받아온 후 전혀 수정하지 않고 npm install 로 패키지를 설치하고 npm start 로 서버만 실행했었어요

**Comment by shoveller** [comment]
그렇군요. 아무래도 이 플러그인들이 가장 수상하네요.
![218650611-e8004dfe-adf7-4d84-b622-23cf75c17bd7](https://user-images.githubusercontent.com/1357198/218651561-b03ff0aa-9d71-493f-ba52-30c14e65c6e1.png)

**Comment by shoveller** [comment]
아.. 그리고 앞으로 리액트 관련 질문을 다른 분(완전히 처음 보는)께도 하시게 될 것인데.
늘 github에 올리셔서 공유하는 습관을 올리시면 원하는 답을 들으실 확률이 높아질 것 같아요.

**Comment by hardy-is-cat** [comment]
> 아.. 그리고 앞으로 리액트 관련 질문을 다른 분(완전히 처음 보는)께도 하시게 될 것인데. 늘 github에 올리셔서 공유하는 습관을 올리시면 원하는 답을 들으실 확률이 높아질 것 같아요.

헉 세상에 세개 전부 지웠더니 해결됐습니다!!!
하나씩 지우면서 확인해봤어야 했는데...급한 마음에 한번에 지웠더니 어떤게 원인이었는지...
보기에는 제일 위의 확장이 수상해보이긴 하네요
예전에 공공API 끌어올 때 CORS 오류를 만나서 이거저거 구글링하다가 깔았던 확장인데...

얘기해주신 github 공유 습관은 잊지 않겠습니다 감사해요!!!!

**Comment by shoveller** [comment]
> > 아.. 그리고 앞으로 리액트 관련 질문을 다른 분(완전히 처음 보는)께도 하시게 될 것인데. 늘 github에 올리셔서 공유하는 습관을 들이시면 원하는 답을 들으실 확률이 높아질 것 같아요.
> 
> 헉 세상에 세개 전부 지웠더니 해결됐습니다!!! 하나씩 지우면서 확인해봤어야 했는데...급한 마음에 한번에 지웠더니 어떤게 원인이었는지... 보기에는 제일 위의 확장이 수상해보이긴 하네요 예전에 공공API 끌어올 때 CORS 오류를 만나서 이거저거 구글링하다가 깔았던 확장인데...
> 
> 얘기해주신 github 공유 습관은 잊지 않겠습니다 감사해요!!!!

앗. 네네
