### ISSUE TITLE
[STD-6] 바닐라 스크립트 프로젝트에서 Unique ID에 관련하여

### ISSUE THREAD

**Issue by hyunwlee-dev** [yamoo9/likelion-FEQA#86]
회원가입시 유저정보를 생성할때마다 Unique ID값의 중복을 확인하는게 맞았을까요?  

먼저, 깃 커밋해시충돌 경우에는 아래 참고한 글로 중복검사를 따로 안할거라 유추했습니다.
<img width="827" alt="스크린샷 2023-02-14 오후 11 16 25" src="https://user-images.githubusercontent.com/55472696/218764337-748e2509-a37a-475c-9fe9-beb7c3c103d0.png">   
  
[[참고 GIT사이트](https://yunwuxin1.gitbooks.io/git/content/ko/012849b64a30e5067c634aaec58f75b4/312565d7f7ce9af5f2b6f8de88388421.html)]  
  
6조는 (소문자 26개 + 대문자 26개 + 숫자 0~9) 62개중 랜덤한 값 한개로 10자리 Unique를 만들었습니다.  
62<sup>10</sup> => 대략 <strong>2<sup>60</sup></strong>    
그리고 대략 2<sup>30</sup>이 10.5억이라 생각했을 때, 충돌날 확률이 <ins>등록된 회원 수 / 10.5억 * 10.5억</ins>이라고 판단했습니다.  
>  저희가 사용할 Unique ID값도 중복될 확률 상 극저하므로 안하는게 적합한거였을까요??  
>  그리고 실제  JWT토큰발급 중복도 극저한가요?  

- 프로젝트에서는 혹시몰라서 중복검사를 하도록 짜놓긴 했습니다...    
  
```js
function getPseudoAccessToken() {
  let ret = '';
  let alphabetNum =
    Number('z'.charCodeAt(0)) - Number('a'.charCodeAt(0)) + 1;
  for (let i = 0; i < 10; ++i) {
    const randValue = Math.floor(
      Math.random() * (alphabetNum * 2 + 10)
    );
    if (randValue >= 52) {
      ret += randValue - 52;
    } else if (randValue >= 26) {
      ret += String.fromCharCode(
        Number('A'.charCodeAt(0)) + randValue - 26
      );
    } else {
      ret += String.fromCharCode(
        Number('a'.charCodeAt(0)) + randValue
      );
    }
  }
  return ret;
}


async function handlingCheckDuplicateAccessToken() {
  let isDuplicated = false;
  let randomValue = getPseudoAccessToken();
  const result = await tiger.get(
    'http://localhost:3000/users'
  );
  result?.data?.some((item) => {
    if (item?.accessToken === randomValue) {
      isDuplicated = true;
      return;
    }
  });
  if (!isDuplicated) {
    return randomValue;
  }
  return handlingCheckDuplicateAccessToken();
}
```

## 질문 작성자

이현우

**Comment by shoveller** [comment]
안녕하세요! @hyunwlee-dev 님. 제가 아는만큼 첨언을 하자면..
전 좀 다른 관점에서 Unique ID의 중복체크는 하지 않는게 좋지 않았을까.. 라는 의견을 남기고 싶습니다.

유저 정보는 관계형 DB에 담겨질 가능성이 매우 높은데,  결국 Unique ID 로 탐색 알고리즘을 실행해야 한단 말이지요..?
자바스크립트 엔진의 구현에 따라 다르겠습니만, [Array.prototype.some 은 선형탐색을 한다고 되어 있으니 시간복잡도가 O(n) 이 될 것 같고요..(=유저 수만큼 탐색)](https://tc39.es/ecma262/#sec-array.prototype.some)
시간복잡도를 낮추려면 DB에서 인덱싱을 해야 하는데, Unique ID의 인덱싱은 공간만 많이 차지하고 효과가 매우 낮은 것으로 알고 있습니다.
(실제로 uuid를 pk로 썼다가 db의 속도가 매우 느려진 사례를 본 적이 있음.)

따라서.. Unique ID의 중복체크는 건너뛰고, jwt 토큰 자체의 위조 여부까지만 체크하는게 좋지 않을까 라는 생각입니다.

도움이 되었으면 좋겠네요.

**Comment by hyunwlee-dev** [comment]
먼저 shoveller멘토님 답변에 감사드립니다. 
제가 부족한지라 관계형 DB의 인덱싱, uuid에 관해 지식이 없어 관련 내용을 찾아본 후, 답변을 다시 읽어봐야 할 것같습니다!!
그리고 다른 관점으로 생각하도록 폭을 넓혀주심에 감사합니다!!
