### ISSUE TITLE
[LAB-1] 이 두 가지의 createElement 문법이 동일한지 

### ISSUE THREAD

**Issue by kelly121212** [yamoo9/likelion-FEQA#89]
## 질문자
최보영 

## 문제 상황
23년 2월 14일 3시 이후 오후 수업 내용 중 
- 함수 내 props null 과 { } 을 넣어준 것에 대한 차이? 질문에 대한 답변을 야무쌤이 해주시던 중 짜준 스크립트 캡쳐입니다! 

![image](https://user-images.githubusercontent.com/69451362/218797484-b200e772-850f-43ee-9a50-b6b002e973d3.png)

위 이미지 내 빨간네모박스 안의 문법과 
아래 이미지 내 빨간네모박스안의 문법은 같은 걸까요?
아래 이미지는 React 공식 문서 페이지 내에 캡쳐해온 createElement() 문법 내용입니다. 

![image](https://user-images.githubusercontent.com/69451362/218797599-43953880-d652-4ad4-abaa-11882f07f46d.png)

`React.createElement(
  type,
  [props],
  [...children]
)` 이라고 알고 있는 데 이부분에서 
`return {
  type, props : { ...props, children };
}`
이라고 적혀져 있어서 `props : {...props, children};`  과 `[props]` 가 같은 건지 궁금합니다.

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요. @kelly121212 님. 밤늦게까지 수고가 많으셔요.
저 문서를 여러번 보았지만, 왜 [props] 라고 적혀 있는것을 눈치채지 못했을까요..!
하지만 제가 기억하기로.. react.js 가 베타버전일때부터 단 한번도 props에 배열을 넘겨본 적이 없었단 말이지요?
(자바스크립트에서는 배열도 객체이니 가능은 할것 같습니다만..)
그래서 저 문서에 적힌 시그니쳐([props])가 배열이 아니지 않을까..? 라는 의심이 피어오릅니다만.. 결국 증거는 찾지 못했네요.

대신에 제가 찾은 자료들로 props가 배열이 아니라는걸 증명하고자 하니 확인해주시길 바랍니다..
[새로운 react.js 공식문서에서의 createElement의 설명](https://beta.reactjs.org/reference/react/createElement)
[createElement의 소스코드](https://github.dev/facebook/react/blob/fccf3a9fba5fd778c678657c556344b333111cfb/packages/react-dom-bindings/src/client/ReactDOMComponent.js#L378)

**Comment by yamoo9** [comment]
@kelly121212 님 ^ㅡ^

## React.createElement

React 공식 문서의 [createElement](https://reactjs.org/docs/react-api.html#createelement)에서 안내하는 `[props]`는 선택 입력사항임을 의미합니다. `[...children]`도 마찬가지이죠.

```js
React.createElement(
  type,
  [props],
  [...children]
)
```

즉, React 요소를 생성할 때 `type` 입력은 필수이고 `props`, `children` 입력은 선택입니다.

```js
React.createElement('div');
```

```js
React.createElement(
  'img', 
  { 
    src: '/assets/react-logo.svg', 
    alt: 'React',
  },
);
```

```js
React.createElement(
  'ul', 
  null,
  React.createElement('li', null, 'type 입력은 필수'),
  React.createElement('li', null, 'props, children 입력은 선택'),
);
```

## createElement 모방

그리고 질문의 가상 요소(virtual element)를 생성하는 `createElement` 함수 코드는 React의 그것을 모방한 예입니다.

```js
function createElement(type, props, ...children) {
  return { type, props: { ...props, children } };
}
```

모방해 구현한 createElement 함수를 사용해 가상 요소를 생성할 수 있습니다.

```js
createElement('div');
```

아래 이미지는 생성된 가상 요소를 캡쳐한 것입니다. `props`를 보면 내부에 `children`이 포함된 것을 볼 수 있습니다.

<img width="480" alt="" src="https://user-images.githubusercontent.com/1850554/218822265-938c4ea9-115a-447f-8ebb-c3cc01abd807.png">

이어서 props 객체를 설정한 예도 살펴봅시다.

```js
createElement(
  'img', 
  { 
    src: '/assets/react-logo.svg', 
    alt: 'React',
  },
);
```

생성된 가상 요소의 `props`에 `alt`, `src`, `children`이 포함된 것을 확인할 수 있습니다.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1850554/218823228-1f2dff34-4d0d-4722-aada-8774fcd01e21.png">

마지막으로 `createElement()` 함수에 `...children`을 설정한 예를 살펴봅니다.

```js
createElement(
  'ul', 
  null,
  createElement('li', null, 'type 입력은 필수'),
  createElement('li', null, 'props, children 입력은 선택'),
);
```

생성된 가상 요소(ul)의 `children` prop 타입이 배열이며, 내부에 2개의 가상 요소(li)를 포함합니다.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1850554/218823827-d3c5fcfc-71f2-4dd3-9cf8-508f9d9f5457.png">

## 결론

React.createElement의 `[props]`는 **선택 입력 사항**을 말하며,
모방한 createElement 함수의 `return { type, props : { ...props, children }; }`는 **생성된 가상 요소를 반환하는 구문**입니다.

그러니까 정확히 말하면 **둘은 같은 것이 아닙니다.**

모방한 함수에서 `[props]` 선택 입력사항을 구현한 코드가 `return { type, props : { ...props, children }; }`인 것입니다. 🤔

**Comment by kelly121212** [comment]
아하!!! [props]가 선택 입력 사항 부분 인걸 알았는데 제가 props : { ...props, children}; 이 부분이 뭔지 몰랐어서 헷갈렸던 것 같습니다! 두분 다 답변 감사합니다!!
