### ISSUE TITLE
[LAB-1] JSX 조건부 렌더링 내 JSX 문밖에 못쓰는 이유 

### ISSUE THREAD

**Issue by kelly121212** [yamoo9/likelion-FEQA#90]
## 질문 작성자

최보영

## 문제 상황
어제 2월 16일 수업 중 `JSX 조건부 렌더링` 파트 에서 
"JSX는 문을 못쓰고 식밖에 못쓴다. 그래서 React에는 삼항연산자, 논리연산자, nullish 등이 많이쓰인다" 라고 말씀해주셨습니다.

혹시 문을 못쓰고 식밖에 못쓰는 이유는 제가 구글링해보니, 

- React컴포넌트 return 문 내부(JSX 문법 공간)에서 if문 사용불가
- JSX -> JS 로 변환 시 JS 객체로 인식한다
- 즉 객체 내부에 if문 등이 들어갈수 없다 

위 내용이 맞을까요? (참고한 링크 : https://velog.io/@jhy979/React-%EA%B0%92%EC%8B%9D%EB%AC%B8 ) 
React의 { } 객체 내에는 값과 식만 들어갈 수 있다는 부분을 설명을 더 듣고 싶은데... 요청드릴 수 있을까요? ㅠㅠ
복습하다가 이 부분이 이해가 안가서요..ㅠㅠ

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요! @kelly121212 님.
저는 수업을 듣진 못했지만, 아마 이런 상황을 말씀하시는게 아닌가 싶어요.
[codesandbox에 예제를 만들어 보았습니다.](https://codesandbox.io/p/github/codesandbox/codesandbox-template-vite-react/csb-pyrgyi/draft/musing-liskov?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A25%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A25%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl5s649nz000elngf1atl6slv%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fsrc%252FApp.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cle5uu7r500153b6lwm5qq5j2%2522%253A%257B%2522key%2522%253A%2522cle5uu7r500153b6lwm5qq5j2%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522yarn%2520dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cle5uu7r500163b6lxrg6yd5v%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cle5uu7r500153b6lwm5qq5j2%2522%252C%2522spacesOrder%2522%253A%255B%2522cle5uu7r500153b6lwm5qq5j2%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

굳이 위의 코드를 보여드린 이유는, 바벨이나 타입스크립트 컴파일러가 jsx 파일을 번역해서 js 파일로 만든다는 것을 강조하기 위해서입니다.
jsx 에서 html 태그와 비슷한 것들은 결국 `createElement` 라는 함수로 번역이 된다는 것을 이해하시게 된다면..
`createElement` 라는 함수 안에서 문(=statement)를 사용할 수 없다는게 자연스럽게 이해하실 수 있지 않을까?? 라는 생각이 드네요.
early return 을 사용하는 예제와 IIFE를 사용하는 예제도 넣어 보았습니다.

제가 질문의 의도를 잘 이해했기를 바랍니다.

**Comment by kelly121212** [comment]
안녕하세요 재원멘토님! 답변 감사합니다!! 
직접 만들어주신 예제 파일까지 ㅠㅠ... !! 예제 파일을 보면서 비교해보니 이해에 더 도움가요! 
천천히 살펴보겠습니다. 늦은시간에 감사합니다 ~!

**Comment by kelly121212** [comment]
감사합니다 야무쌤!!! JSX = 식 ! 이다를 머릿속에 넣어야겠어용!! 예시까지 들어주셔서 더 쏙 들어오네용 감사합니당
