### ISSUE TITLE
[LAB-1] 클래스 필드의 this 란 

### ISSUE THREAD

**Issue by kelly121212** [yamoo9/likelion-FEQA#91]
## 질문 작성자

최보영 

## 문제 상황
어제자 오후 수업 중 `조건부렌더링` 공부 하는 예제에서 App.js 파일 부분을 보다가 궁금한 점이 생겨 문의드립니다! 
바인딩 하는 3가지 방식 중 마지막 세번째 방식이였던 클래스필드에 핸들러에만 화살표 함수를 넣는 방식을 배웠습니다.
그리고 클래스필드란, 아래 이미지 빨간 영역의 바깥쪽 영역이며, 이 영역의 `this` 는 인스턴스라 작동이 된다고 말씀주셨는데, 
이 영역의 `this` 란 즉 `1번 라인의 class App` 를 말하는 걸까요? 클래스필드 영역의 `this`가 어디인 지 궁금합니다..! 

![image](https://user-images.githubusercontent.com/69451362/219096279-2a9c59c5-a506-4cb8-950f-6868c20867e6.png)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
@kelly121212 님 질문에 답변 드립니다. 😃

> 클래스필드란, 아래 이미지 빨간 영역의 바깥쪽 영역이며, 이 영역의 this 는 인스턴스라 작동이 된다고 말씀주셨는데, 이 영역의 this 란 즉 1번 라인의 class App 를 말하는 걸까요? 클래스필드 영역의 this가 어디인 지 궁금합니다..!

## 클래스 필드(class fields)

[Public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) MDN 문서를 참고하면 클래스 필드에 대해 학습할 수 있어요.

퍼블릭(public) **인스턴스 필드는 클래스의 생성된 모든 인스턴스(this)에 적용됩니다.**
퍼블릭 인스턴스 필드는 컨스트럭터(constructor) 실행 직후 인스턴스에 추가됩니다.

```js
class 클래스 {
  인스턴스_필드;
  인스턴스_필드_초기화 = "초기값";

  constructor() { ... }
}
```

`new 클래스()` 문법으로 인스턴스를 생성 하면 클래스 필드에 선언한 모든 것은 인스턴스의 멤버(members)가 됩니다. 즉, 인스턴스가 클래스 코드 내부의 `this`가 되는 것이죠. 그래서 `인스턴스.멤버` 방식으로 클래스 필드에 선언된 것들을 접근하거나 사용할 수 있는 것입니다.

```js
const 인스턴스 = new 클래스();

console.log(Object.hasOwn(인스턴스, '인스턴스_필드')); // true
console.log(인스턴스.인스턴스_필드); // undefined
console.log(인스턴스.인스턴스_필드_초기화); // "초기값"
```

## 클래스 컴포넌트와 이벤트 핸들러

수업 시간에 다룬 React 클래스 컴포넌트 코드를 살펴봅시다.

```js
class App extends React.Component {
  
  // this.state 로 접근 가능
  state = {
    headline: 'React Application',
    isToggle: false,
  };

  // this.originalHeadline
  originalHeadline = this.state.headline;
  
  // this.willUpdateHeadline
  willUpdateHeadline = 'NEW HEADLINE! 😃';

  // this.handleChangeHeadline
  handleChangeHeadline = () => {
    // this === App 컴포넌트로 생성된 엘리먼트를 가리킴
    if (this.state.isToggle) {
      this.setState({
        isToggle: false,
        headline: this.originalHeadline,
      });
    } else {
      this.setState({
        isToggle: true,
        headline: this.willUpdateHeadline,
      });
    }
  };

  render() {
    // ...
  }
}

export default App;
```

클래스 필드에 선언된 모든 것들은 생성된 인스턴스(`this`)를 통해 접근 가능한 멤버 들입니다.

- `state`
- `originalHeadline`
- `willUpdateHeadline`
- `handleChangeHeadline`

멤버는 클래스의 인스턴스 메서드(예: `render()`)에서 접근 가능합니다.

```js
render() {
  console.log(this.state.headline); // 'React Application'
  // ...
}
```

다만 이벤트 핸들러 메서드의 경우 조금 특별하게 아래처럼 작성했을 때, `this`가 인스턴스가 아닌, `undefined`가 됩니다. ([참고](https://ko.reactjs.org/docs/handling-events.html))

```js
class 클래스 extends. 리액트.컴포넌트 {
  이벤트핸들러() {
    console.log(this); // undefined
  }
}
```

반면에 클래스 필드 문법을 사용해 이벤트 핸들러를 설정하면 화살표 함수의 `this`는 일반 함수의 `this`와 달리 화살표 함수가 위치한 상위 영역의 `this`를 가리키므로 인스턴스가 됩니다.

```js
class 클래스 extends. 리액트.컴포넌트 {
  이벤트핸들러 = () => {
    console.log(this); // 인스턴스
  }
}
```

## 결론

클래스 필드(영역)의 `this`는 App 컴포넌트로 생성된 App 엘리먼트를 가리킵니다.

```jsx
// 컴포넌트(클래스)
class App extends React.Component { ... }

// 엘리먼트(인스턴스) with JSX
<App />

// 엘리먼트(인스턴스) without JSX
React.createElement(App);
```
