### ISSUE TITLE
[LAB-1] onClick 이벤트와 상관 없이 함수는 호출이 되나요?

### ISSUE THREAD

**Issue by kyoungholee** [yamoo9/likelion-FEQA#92]
## 질문 작성자
이경호

## 문제 상황
1. 버튼 태그안에  onClick 이벤트가 있고, 그 이벤트를 누르지 않았는데  일반 함수인 this.handleFilterLab(4)가 호출되는게 궁금합니다.
그럼 여기선 onClick에 역할을 못하는 건가요?

2. 위에 문제를 해결하기 위해 화살표 함수로 바꾸셨는데,  이유가 뭘까요? 이부분은 onClick과 관계가 없나요?

## 코드 검토 리소스

![45](https://user-images.githubusercontent.com/65242726/219306130-9c3f57d4-9149-4065-9bc4-b5072a64e140.PNG)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요 @kyoungholee 님!
> 버튼 태그안에 onClick 이벤트가 있고, 그 이벤트를 누르지 않았는데 일반 함수인 this.handleFilterLab(4)가 호출되는게 궁금합니다.
그럼 여기선 onClick에 역할을 못하는 건가요?

네 맞습니다. 
`this.handleFilterLab(4)` 에서 이미 함수를 실행하고 있으므로(=괄호를 닫았으므로) 이벤트 호출 여부와 관계없이 `this.handleFilterLab(4)` 는 실행됩니다.
이벤트가 발생한 시점에 호출을 하려면 `this.handleFilterLab` 를 넘겨야 할 것인데.. 이러면 인수로 `4`를 넘기지 못하겠네요.
별수없이 `this.handleFilterLab(4)`를 반환하는 함수를 넘겨줘야 하니 `() => this.handleFilterLab(4)` 로 한번 감싸서 넘기는게 괜찮은 선택인것 같습니다.



> 위에 문제를 해결하기 위해 화살표 함수로 바꾸셨는데, 이유가 뭘까요? 이부분은 onClick과 관계가 없나요?

`this.handleFilterLab(4)`  자체가 함수를 실행하라는 뜻이니.. onClick 에 아래와 같은 방법으로 함수를 한번 감싸서 넘겨야 할 것입니다.
```js
function () {
  return this.handleFilterLab(4)
}
```
또는 
```js
() => this.handleFilterLab(4)
```

그런데 화살표 함수를 사용하는 또 중요한 이유가 있는데,  `화살표 함수의 this는 상위 환경이 된다` 라는 점입니다.
이 말은 `화살표 함수의 this는 부모 컴포넌트를 가리킨다` 라고 바꿔서 말할수도 있겠네요. 

[간단한 예제를 만들어 보았습니다. this 가 사라지는 현상을 확인해 보시면 이해가 더 잘 될지도 모르겠습니다.](https://codesandbox.io/p/github/codesandbox/codesandbox-template-vite-react/csb-riuli7/draft/quirky-hooks?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A11%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A14%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl5s649nz000elngf1atl6slv%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fsrc%252FApp.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cle5uu7r500153b6lwm5qq5j2%2522%253A%257B%2522key%2522%253A%2522cle5uu7r500153b6lwm5qq5j2%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522yarn%2520dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cle5uu7r500163b6lxrg6yd5v%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cle5uu7r500153b6lwm5qq5j2%2522%252C%2522spacesOrder%2522%253A%255B%2522cle5uu7r500153b6lwm5qq5j2%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

**Comment by kyoungholee** [comment]
자세한 답변 정말 감사드립니다. ~^^
