### ISSUE TITLE
[STD-2] React 클래스 컴포넌트 이벤트 핸들러의 this가 undefined가 되는 이유

### ISSUE THREAD

**Issue by to06109** [yamoo9/likelion-FEQA#93]
## 질문 작성자

최예송

## 문제 상황
다음은 `handleChangeHeadline` 메서드를 바인딩하기 전의 코드입니다. 
```js
class App extends React.Component {
  state = {
    headline: 'React Application',
  }

  // this.handleChangeHeadline
  handleChangeHeadline() {
    // this는 과연 컴포넌트의 인스턴스(엘리먼트)인가??
    console.log('1', this) // undefined
  }

  confirmThis() {
    console.log('2', this) // App {}
  }

  render() {
    this.confirmThis()

    return (
      <div data-component="App">
        <h1>{this.state.headline}</h1>
        {/* React의 JSX(React 엘리먼트)에 연결한 이벤트 리스너(함수)는 언제 실행되는가? */}
        <button type="button" onClick={this.handleChangeHeadline}>
          헤드라인 변경
        </button>
      </div>
    )
  }
}
```

먼저 `render` 메서드 안에서 `this.confirmThis()` 를 했을 때는 `confirmThis` 메서드를 실행시킨 this(App)가`confirmThis` 메서드 안에서의 this가 된다고 이해했습니다.  

반면에 button 요소에 연결된 클릭 이벤트 핸들러는 렌더링 할 때 `handleChangeHeadline` 메서드를 실행하는 것이 아니라, 버튼을 클릭했을 때 `handleChangeHeadline` 메서드를 실행하기 때문에 버튼을 클릭한 순간, `handleChangeHeadline`를 실행시킨 this가 `handleChangeHeadline` 메서드의 this가 되는 것이라고 생각했습니다.

그래서 버튼을 클릭한 순간 `handleChangeHeadline` 메소드를 실행시켜주는 this는 어떤 객체가 되는 것인지, 결과로는 undefined가 나오는데 왜 undefined가 되는건지 궁금합니다. 

결론적으로 궁금했던 것은 `handleChangeHeadline`를 바인딩해야하는 이유인데, 위 질문에 대한 답을 들으면 바인딩해야 하는 이유를 알 수 있을 것 같아서 질문드립니다!

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
## 클래스 컴포넌트 이벤트 핸들러와 `this` 바인딩

React 클래스 컴포넌트의 다른 메서드와 달리, 이벤트 핸들러는 `this` 바인딩이 필요합니다.

```js
class Demo extends React.Component {

  constructor(props) {
    super(props);
    // this 바인딩
    this.handleBindingThisMethod = this.handleBindingThisMethod.bind(this);
  }

  handleUnbindingThisMethod() {
    console.log('unbinding', this); // undefined
  }

  handleBindingThisMethod() {
    console.log('binding', this) // App {}
  }

  render() {
    return (
      <>
        <button type="button" onClick={this.handleUnbindingThisMethod}> 
          this 바인딩 안 한 이벤트 핸들러
        </button>
        <button type="button" onClick={this.handleBindingThisMethod}> 
          this 바인딩 한 이벤트 핸들러
        </button>
      </>
    )
  }
}
```

### `this` 바인딩 이슈는 React가 아닌, JavaScript 작동 방식

`this` 바인딩이 필요한 이유는 React가 아닌, **JavaScript에서 작동하는 방식에서 이유를 찾아야 합니다.** 

#### 일반 함수의 `this`

ECMAScript 2015(ES6)부터 사용된 모듈(module) 코드는 [엄격 모드(strict mode)](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Strict_mode)로 작동 되며, 일반 함수의 `this`는 엄격 모드에서 `undefined` 입니다. (엄격 모드가 아닌 경우, [globalThis](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/globalThis) 객체 출력)

```js
function printThis() {
  console.log(this); // undefined
}

printThis();
```

#### 객체 메서드의 `this`

반면 객체의 메서드(함수)를 호출하면 `this`는 메서드를 호출한 객체를 가리킵니다.

```js
const printer = {
  name: '야무 프린터',
  print() {
    console.log(this.name); // this는 printer 객체
  }
};

printer.print(); // '야무 프린터'
```

#### 변수에 할당된 함수 참조의 `this`

객체의 메서드(함수) 참조를 다른 변수에 할당하면 메서드 내부의 `this`는 `undefined`가 됩니다. (엄격 모드인 경우) 변수에 참조된 객체 메서드(함수)의 `this`가 객체를 컨텍스트(context)로 가리키지 않기 때문입니다. 이처럼 JavaScript의 `this`는 실행 중에 변경(또는 결정) 되므로 이해하기가 쉽지 않습니다. 🧐

```js
// printer.print 메서드(함수) 참조를 변수에 할당
const printLog = printer.print;

printLog(); // undefined
```

#### 이벤트 핸들러와 `this`

React 클래스 컴포넌트를 걷어낸 순수한 JavaScript 클래스로 `this`의 작동 방식을 확인해보겠습니다.

```js
class Printer {
  constructor(name) {
    this.name = name;
  }
  print() {
    console.log(this.name);
  }
}

const printer = new Printer('야무 프린터');
printer.print(); // '야무 프린터'

// 클래스로부터 생성된 인스턴스(객체)의 메서드(함수) 참조를 변수에 할당합니다.
// 이 부분이 React 클래스 컴포넌트 이벤트 핸들러를 DOM 요소에 연결하는 과정과 유사합니다.
const printLog = printer.print;
// 참조된 함수를 실행하면 this는 undefined가 됩니다.
// 함수 실행 시, this가 클래스 컴포넌트를 가리키지 않기 때문입니다.
printLog(); // TypeError: this is undefined
```

그럼 이제 React 클래스 컴포넌트 예시를 다시 살펴봅시다.

```js
class Printer extends React.Component {

  handlePrint() {
    console.log(this); // undefined
  }

  render() {
    return (
      <>
        <button type="button" onClick={this.handlePrint}> 
          this 바인딩 안 한 이벤트 핸들러
        </button>
      </>
    )
  }
}
```

React 클래스 컴포넌트로부터 생성된 React 엘리먼트(객체)의 이벤트 핸들러(함수) 참조는 변수에 할당 되므로 `this`가 클래스 컴포넌트를 가리키지 않게 됩니다.

```js
// React 엘리먼트(element) 생성
const print = React.createElement(Printer);

// 이벤트 핸들러(함수) 참조를 변수에 할당
const buttonClickHandler = print.handlePrint;

buttonClickHandler(); // TypeError: this is undefined
```

이것이 React 클래스 컴포넌트 이벤트 핸들러에 `this` 바인딩이 필요한 이유입니다. 클래스 컴포넌트의 컨스트럭트(constructor) 메서드는 컴포넌트 생성 과정에서 가장 먼저 실행된다는 점에서 이벤트 핸들러에 `this`를 바인딩 하기 좋습니다.

```js
class Printer extends React.Component {

  constructor(props) {
    super(props);
    // this 바인딩
    this.handlePrint = this.handlePrint.bind(this);
  }

  handlePrint() {
    console.log(this); // Printer {}
  }

  render() {
    return (
      <>
        <button type="button" onClick={this.handlePrint}> 
          this 바인딩 한 이벤트 핸들러
        </button>
      </>
    )
  }
}
```

## 클래스 필드 구문을 활용하세요.

[클래스 필드](https://helloworldjavascript.net/pages/270-class.html#%ED%81%B4%EB%9E%98%EC%8A%A4-%ED%95%84%EB%93%9C%EC%99%80-this) 구문을 사용하면 화살표 함수를 사용해 `this` 바인딩 하지 않아도 클래스 컴포넌트를 컨텍스트로 인식합니다.

화살표 함수는 일반 함수와 달리 함수가 연결된 객체가 아닌, 화살표 함수가 위치한 클래스 필드의 `this`를 바인딩 하기 때문입니다. React 클래스 컴포넌트 클래스 필드의 `this`는 생성된 React 엘리먼트를 가리킵니다. 그러므로 문제없이 작동합니다. 😃 

```js
class Demo extends React.Component {

  // 클래스 필드 구문으로 선언된 이벤트 핸들러
  handleClassFieldMethod = () => {
    console.log(this); // App {}
  }

  render() {
    return (
      <>
        <button type="button" onClick={this.handleClassFieldMethod}> 
          클래스 필드 구문 이벤트 핸들러
        </button>
      </>
    )
  }
}
```

**Comment by to06109** [comment]
이해했습니다 야무쌤 답변 감사합니다!!
