### ISSUE TITLE
[STD-2] JSX가 주입공격(XSS)을 방지하는 원리와 이유가 무엇인가요?

### ISSUE THREAD

**Issue by parkilbeom** [yamoo9/likelion-FEQA#94]
## 질문 작성자

박일범

## 문제 상황
reactjs.org의 공식 문서를 리뷰하며 생긴 궁금증입니다 렌더링
![image](https://user-images.githubusercontent.com/119389877/219435566-2f7b7d1f-a2e6-4847-b35c-5ad443c30e3d.png)

**JSX가 보안에 좋다고 하는  이유가 무엇인가요? 어떤 식으로 보안 이슈를 해결하는지 또는 방지할 수 있는 것 인지 궁금합니다**

스터디원들이 생각한 점.

1. 사용자 입력을 방지하는 게 사용자가 홈페이지 들어갔을 때 개발자 도구에서 JSX를 사용 못 해서 주입 공격을 방지 하는 걸까?
2. 아니면 저렇게 title 변수를 넣어서 title로 지정된 값만 렌더링 되니까 보안에 좋다고 하는 것 일까?
    
     → 근데 그러면 노드.textcontent 에다가 title 넣어도 지정된 값을 넣는 게 아닐까?
     → 렌더링 되기 전에 노드는 없어서 이렇게도 못한다 아닐까?
    
3. 값이 들어오기 전에는 렌더링이 안 되니까? 보안에 좋은 게 아닐까?
4. 모든 항목이 렌더링 전 문자열로 변환된다는데 주입될 악성 스크립트가 어떻게 처리되어 입력이 안 되는 걸까?
## 코드 검토 리소스
https://ko.reactjs.org/docs/introducing-jsx.html

**Comment by yamoo9** [comment]
# JSX가 XSS 공격을 방지하는 원리와 이유

해당 질문은 React 공식 문서 ["JSX는 주입 공격을 방지합니다"](https://ko.reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks)에서 안내하는 내용 중 [이스케이프(Escape)](https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-in-html)와 [사이트 간 스크립팅(XSS) 공격](https://ko.wikipedia.org/wiki/%EC%82%AC%EC%9D%B4%ED%8A%B8_%EA%B0%84_%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8C%85)에 대해 이해해야 의문이 풀릴 것입니다. 🤔 

이 문제는 ⚠️ "보안(Security)"과 관련된 주제입니다. 보다 상세한 내용은 [관련 글](https://noirstar.tistory.com/266), [XSS](https://namu.wiki/w/XSS)를 참고하세요.

## 사이트 간 스크립팅 공격 (XSS, cross-site-scripting)

XSS는 웹 애플리케이션 관리자가 아님에도 악의적 의도를 가진 악성 스크립트 코드를 외부에서 삽입하는 취약점을 말합니다. Cross Site Scripting 이름임에도 CSS가 아닌 XSS로 불리는 이유는 웹 기술인 CSS와 혼동할 수 있기 때문입니다.

XSS 공격은 일반적으로 **여러 사용자가 이용하는 게시판에 악성 스크립트가 담긴 글을 올리는 형태로 이뤄집니다.** 이 취약점은 **웹 애플리케이션이 사용자로부터 입력 받은 값을 제대로 검사하지 않고 사용할 경우 나타납니다.**

이 공격으로 사용자 정보(쿠키 또는 세션)를 탈취하거나, 비정상적인 기능을 수행해 웹 애플리케이션에 문제를 유발합니다. 주로 다른 웹 애플리케이션과 정보를 교환하는 방식으로 작동하므로 "사이트 간 스크립팅"이라고 부릅니다.

<img src="https://user-images.githubusercontent.com/1850554/219472319-d3e0219d-bfb6-4a46-9e10-b2478ded913f.png" width="400" alt />


## 이스케이프 (Escape)

XSS 공격을 방어하는 방법입니다. 사용자가 입력한 값을 출력할 때 검증이 필요합니다. XSS 공격 대응을 위한 필터링(이스케이프)을 적용하여 악의적인 스크립트 실행을 방지해야 합니다.

이러한 방어 방법에 대한 예로 GitHub 이슈에 글을 작성할 때 인라인 스타일 또는 스크립트 코드를 작성해 넣고 서버에 전송해도 해당 코드는 모두 제거된 채 저장됩니다. "XSS 공격을 방어하기 위한 절차"입니다.

사용자 입력 내용 중 주로 필터링 해야 하는 것이 `<`, `>`입니다. 필터링 된 코드는 각각 `&lt;`와 `&gt;`로 변경됩니다. HTML 코드가 아닌 단순한 문자로 인식하도록 필터링 해야 악의적 코드가 삽입되는 것을 막을 수 있습니다.

## JSX는 주입 공격을 방지합니다.

ReactDOM은 React 엘리먼트(JSX)를 실제 DOM에 삽입합니다. ReactDOM은 렌더링 전에 JSX에 삽입된 모든 값을 이스케이프(필터링) 처리합니다. 즉, 삽입될 가능성이 있는 악의적 코드를 모두 일반 문자 값으로 변환하기 때문에 실행되지 않도록 차단합니다. 그렇기에 XSS 공격으로부터 안전합니다.

```js
응답(response) 받은 데이터를 title 변수에 참조합니다.
const title = response.potentiallyMaliciousInput;

// JSX는 HTML이 아니라, React 엘리먼트입니다.
// JSX는 삽입된 모든 값을 렌더링 전에 이스케이프 처리합니다.
// 그러므로 element가 웹 애플리케이션에 삽입 되더라도 안전합니다.
const element = <h1>{title}</h1>;
```
