### ISSUE TITLE
[LAB-6] Babel Standalone CDN 환경에서 JSX 에러 발생 문제 원인은?

### ISSUE THREAD

**Issue by hamjongseok** [yamoo9/likelion-FEQA#95]
## 질문 작성자

함종석

## 문제 상황

JSX관련 수업 내용 복습도중 안되는점이 2가지 있어서 .. 해결이 도저히 되지않아 질문남깁니다 ㅠㅠ.. 

공통상황
- Babel관련된 정보를 JSON에 추가를 하지않고 CDN으로만 babel/standalone 만 사용하였습니다.

**1. 첫번째 질문**

 index.html에   <script type="text/babel" data-type="module" src="./demo.js"></script> 추가하여 JSX를 사용하면 
오류없이 사용이 잘됩니다. 
하지만 public경로의 demo파일이 아닌 src경로의 main.js에 jsx를 사용하여 똑같은 
 <script type="text/babel" data-type="module" src="../src/main.js"></script>를 추가하게되면 
아래와 같은 에러가 나옵니다.. 

<img width="1024" alt="스크린샷 2023-02-17 오후 9 24 11" src="https://user-images.githubusercontent.com/82271040/219652912-7062ee84-7aa1-421f-bcd6-45938e71f6f4.png">

main.js에는 딱히 문제될만한 코드는 없는것같습니다 
<img width="851" alt="스크린샷 2023-02-17 오후 9 24 57" src="https://user-images.githubusercontent.com/82271040/219653042-47af4bc6-360a-4aec-a81e-c5da39685517.png">

파일구조는 이와같습니다 
<img width="170" alt="스크린샷 2023-02-17 오후 9 25 33" src="https://user-images.githubusercontent.com/82271040/219653151-f564c59c-84cf-46bc-a177-ecf5ed91f7e1.png">

**2. 두번째 질문**

첫번째와 비슷해보이는 문제인거 같긴한데 
index.html에서 
<img width="967" alt="스크린샷 2023-02-17 오후 9 27 56" src="https://user-images.githubusercontent.com/82271040/219653635-609728f0-5cdd-4c54-994e-d3d8d0d03eac.png">

head태그안에 script태그안에 JSX를 사용하면 잘되는데 이번에도 
    <script type="text/babel" data-type="module" src="../src/main.js"></script>
똑같이 하면 오류가 같이뜨고있습니다 

어떠한 차이점으로 인하여 오류가 생기고 오류가 생기지 않고 정상 작동을 하는건지 궁금합니다 !  

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
## 질문

public 경로의 `demo.js` 파일이 아닌, src 경로의 `main.js`에 JSX를 사용하여 똑같은
`<script type="text/babel" data-type="module" src="../src/main.js"></script>`를 추가하게 되면 아래와 같은 에러가 나옵니다.

head 영역 안에 작성한 script 태그의 JSX를 사용하면 잘 되는데 이번에도
`<script type="text/babel" data-type="module" src="../src/main.js"></script>` 똑같이 하면 오류가 같이 뜨고 있습니다.

어떠한 차이점으로 인하여 오류가 생기고 오류가 생기지 않고 정상 작동을 하는건지 궁금합니다 !

## 답변

@hamjongseok 님 질문주신 문제 상황은 동일한 증상이 맞습니다. 해당 오류가 발생한 이유는 "웹 서버 라우팅"과 관련있습니다.
우리는 수업에서 `backend/server.js` 파일에 작성된 서버 프로그램을 구동해 호스팅 하였습니다.

### 웹 서버 옵션

`server.js` 파일에 작성된 `params`는 웹 서버 옵션을 설정한 객체이죠. 아마도 설정이 아래와 같이 되어 있을 것입니다.

```js
let params = {
  host: 'localhost',
  port: 3000,
  root: DIR.public,
  file: 'index.html',
  // mount: [['/scripts', DIR.src]],
  open: false,
  wait: 200,
};
```

### 웹 서버 루트

웹 서버 루트(root) 위치를 `public` 디렉토리로 설정 하였으므로, 같은 계층의 `src` 디렉토리는 호스팅 되지 않습니다.

<img src="https://user-images.githubusercontent.com/82271040/219653151-f564c59c-84cf-46bc-a177-ecf5ed91f7e1.png" alt height="300" />

### 문제 원인

오류 발생 원인은 상대 경로로 `public` 디렉토리를 벗어나 호스팅 되지 않는 `src` 디렉토리의 `main.js`에 접근하려 시도했기 때문입니다.

```html
<script type="text/babel" data-type="module" src="../src/main.js"></script>
```

### 문제 해결

`backend/server.js` 파일의 서버 옵션을 다음과 같이 변경합니다.

```js
let params = {
  host: 'localhost',
  port: 3000,
  root: DIR.public,
  file: 'index.html',
  mount: [['/src', DIR.src]], // ← 이 부분 설정으로 src 디렉토리도 호스팅 할 수 있습니다.
  open: false,
  wait: 200,
};
```

그리고 `frontend/public/index.html` 파일에 작성된 `src` 경로를 절대 경로로 변경해주세요.

```html
<script type="text/babel" data-type="module" src="/src/main.js"></script>
```

설정을 마친 후, 웹 서버를 다시 구동하면 정상적으로 React 애플리케이션이 작동할 것입니다. 😊

```sh
npm start
```

### 참고

참고 목적으로 frontend, backend 디렉토리를 압축한 가이드 파일을 첨부합니다.

[guide.zip](https://github.com/yamoo9/likelion-FEQA/files/10772086/guide.zip)

<p></p>

**Comment by hamjongseok** [comment]
아 ! 뭔가 놓친거같다는 부분이 있다생각이 들었는데 이거였군요 ㅠㅠ .. 감사합니다
또한 제가 원하는 결과대로 나오게하려면 어떠한 코드를 수정해야하는지도 알려주셔서 감사합니다 많은도움이 되었습니다 
좋은 주말되세요
