### ISSUE TITLE
[STD-6] 클래스 constructor() 역할 그리고 super() 사용에 대해

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#96]
## 문제 상황
제가 아는 constructor () 역할은 이렇습니다.

-  constructor 의 메서드가 하는 역할이 new 로 인스턴스 객체가 생성되면서 전달받는 인자로 property를 생성하게 위함
-  또한 class 생성된 객체를 생성하고 초기화하기 위한 특수한 메서드

![image](https://user-images.githubusercontent.com/109938280/219688567-e1ce63b4-6e79-4e91-bc9f-438ccdf85aa9.png)

하지만 밑에 사진을 보면 constructor() 을 사용하지 않고 state 를 초기화 하고 사용을 하는데 constructor( ) 을 왜 사용안하는지 모르겠습니다
또한  extends React.Component 를 사용했는데 super() 왜 사용 안한지두 잘 모르곘습니다. 

![image](https://user-images.githubusercontent.com/109938280/219688959-6edb150f-6ef1-4511-ba48-a8e32d16345a.png)

야무쌤이 방식의 차이라고 설명을 해주신것으로 기억이 나는데요! 제가 이해한게 맞는지 한번 더 물어보려고 질문을 올립니다

- 질문 내용을 자세하고 명확하게 풀어 작성합니다. [6하 원칙](https://namu.wiki/w/%EC%9C%A1%ED%95%98%EC%9B%90%EC%B9%99)에 맞춰 이해하기 쉽도록 작성합니다. 
- 질문이 파악되어야 정확하고 이해하기 쉬운 답변이 주어진다는 점 잊지마세요!
- 상황 이해를 돕기 위한 이미지 또는 비디오(최대 10MB) 첨부가 필요한 경우 첨부합니다. (권장)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요 @5wintaek 님.
우선 `constructor( )` 의 `선언`여부는 선택사항이라는걸 짚고 넘어가고 싶어요.
`constructor( )`를 따로 선언하지 않으면, 자바스크립트 엔진은 class에 내장된 `constructor( )`를 사용하는 것으로 간주합니다.
`constructor( )` 는 개발자가 `constructor( )` 의 동작에 관여하고 싶은 경우에만 다시 선언합니다.
다시말해, 첫번째 그림에서는 사실 `constructor( )` 를 다시 선언할 필요가 없었던 것입니다.
![1](https://user-images.githubusercontent.com/1357198/219698662-50805874-2a0a-42f8-9660-990ac0c88f73.png)


두번째 그림에서 내장된 `constructor( )` 를 사용하는 예를 보여주고 있네요.
![2](https://user-images.githubusercontent.com/1357198/219698908-9519fd78-f206-4d27-a48c-ff40ea4905e7.png)

화이팅 ^^
