### ISSUE TITLE
[LAB-2] Files not updating using 'git pull'

### ISSUE THREAD

**Issue by djswns7** [yamoo9/likelion-FEQA#97]
## 질문 작성자

박원준

## 문제 상황

지난 팀 프로젝트에서도 가끔씩 발생하던 문제인데 (팀플에서도 한번씩 다른 오류 메세지 없이 몇몇 파일이 pull받으려고 한 저장소의 내용과 일치하지 않게 받아진 후 source 탭에서도 충돌하는 파일이 없다고 뜨는 경우가 있었습니다)
변인이 파악이 안되어서 질문을 못드리고 있었다가 자꾸 해당 이슈가 나타나서 질문드립니다

```git pull [야무쌤 깃헙주소] [pull 받으려는 브랜치명]``` 을 통해서 명령을 입력했고
아무 오류 메세지 없이 pull을 통한 fetch merge가 정상적으로 이루어 진 줄 알았는데
몇몇 파일은 변경(변경이 된 파일은 새로 받은 내용과 아예 다르거나 완전 새 파일인 경우는 한번도 해당 현상은 없었습니다)이 되었으나 일부 파일이 변하지 않은 상태 그대로 남아있는 경우가 발생했어서 질문드립니다

문제상황과 비슷한 질문이 있던 페이지가 있어 첨부합니다 
(다른 검색결과들은 보통 오류메세지가 뜨는 경우에 대한 문서가 많았습니다.)
https://stackoverflow.com/questions/20581914/files-not-updating-using-git-pull
정확하게 알고 실행해보고 싶어서 위 페이지에 있던 방식들은 시도해보지 않은 상태입니다.
(원인이 무었인지 보다 '이런이런 방식을 시도해봐라'라는 식의 방법 위주의 답변이 많아서 일단 보류했습니다.)

- 운영체제 종류 : 윈도우

**Comment by yamoo9** [comment]
## 문제 원인

Git은 소스 코드 관리 시스템으로서 파일과 데이터가 손실되지 않도록 최선을 다합니다. 
이러한 이유로 **Git은 `git pull` 명령을 수행할 때 로컬 파일을 원격 저장소의 파일과 병합하는 것을 거부할 수 있습니다.**

## 문제 해결 방법

로컬 파일이 원격 저장소의 파일과 병합이 거부될 경우, 문제를 해결할 수 있는 다양한 방법이 있습니다.

### 1. stash → pull

로컬 파일의 코드를 `git stash` 명령으로 임시 보관 처리한 후, `git pull` 명령을 사용해 원격 저장소 파일을 가져옵니다. 
그 후 스태시 한 것을 꺼내 병합하는 방법입니다. (충돌이 발생할 경우 문제를 해결해 병합합니다.)

### 2. commit → pull

로컬 파일의 변경 사항을 커밋 하여 이력을 남깁니다. 그 후 `git pull` 명령으로 원격 저장소 파일을 가져옵니다.

### 3. delete → pull

로컬 파일의 변경 사항을 보관 또는 이력을 남길 필요가 없다면 삭제한 후, `git pull` 명령을 수행합니다.
로컬 변경 사항을 삭제하고자 할 경우, 다음 명령을 사용할 수 있습니다.

```sh
# --force, -d : 추적하지 않는 디렉토리를 포함한 파일을 삭제합니다.
git clean -fd
```

## 레퍼런스

[Git Pull Not Updating Files](https://www.delftstack.com/howto/git/git-pull-not-updating/)
