### ISSUE TITLE
[LAB-2] 함수 컴포넌트에서의  Static method 

### ISSUE THREAD

**Issue by 5wintaek** [yamoo9/likelion-FEQA#98]
## 질문 작성자

오승택

## 문제 상황

당일 수업내용 (04-react-toolchain) -  Counter.function.jsx 파일에서 defaultProps 값을 함수 밖에서 선언을 하였습니다. 

혹시 function 바깥에서 선언한 이유가 class 컴포넌트처럼 static method 로 이용하려고 사용하신다고 했는데 

function 안에서도 사용을 할 수 있을거 같은데 왜 밖에다가 하는지 잘 모르습니다.

수업 중간에  제가 질문는데도 잘 이해가 가질 않아서 다시 질문 남깁니다 !

![image](https://user-images.githubusercontent.com/109938280/220053163-76c8f96d-bb55-4c1d-8239-b70a2472e040.png)

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by shoveller** [comment]
안녕하세요. @5wintaek 님. 이 부분은 제가 히스토리를 알고 있는 것이 있어요.
react.js 는 es5(2015년) 등장 이전에 개발된 라이브러리이고.. 그 시절부터 props 에 초깃값을 설정하는 자체적인 방법을 가지고 있었습니다. 
그것이 [`Component.defaultProps`](https://ko.reactjs.org/docs/react-component.html#defaultprops) 이고, 함수형 컴포넌트와 클래스 컴포넌트 모두에 적용하는 방법이었습니다.
즉, `Component.defaultProps` 는 react.js 의 기본 기능이므로 외워야 하는 부분으로 보여요.
 
하지만..? 
세월이 흘러 es6부터는 자바스크립트가 언어적으로 [default function parameter(기본값 매개변수)](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Default_parameters) 와 [Destructuring assignment(구조분해 할당)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) 이라는 기능을 지원하게 되었습니다.
이 두개의 기능들을 섞어서 사용하면 `Component.defaultProps` 의 훌륭한 대체품이 됩니다.

[간단한 예제를 만들어 보았습니다.](https://codesandbox.io/s/quizzical-feather-l58m4q?file=/src/App.js:161-187)
혹시 이 방법이 취향에 맞으시다면 사용해보셔도 좋겠습니다.
도움이 되었기를 바랍니다. ^^

**Comment by yamoo9** [comment]
## 질문

function 안에서도 (static 메서드를) 사용을 할 수 있을거 같은데 왜 밖에다가 하는지 잘 모르습니다.

## 답변

함수는 클래스와 달리 내부에 `static` 키워드를 사용한 메서드 사용이 가능하지 않습니다.

<img width="570" alt="" src="https://user-images.githubusercontent.com/1850554/220088478-23ff2bcc-ef22-4f57-b339-279d0c1502da.png" />

```jsx
function App() {
  const [count, setCount] = useState(0)

  // 🚨 Declaration or statement expected.
  //    선언 또는 문이 필요합니다. (문법 오류)
  static defualtProps = {
    count: 0,
  };

  return (
    <div className="App">
      <!-- ... -->        
    </div>
  )
}
```

### 함수 컴포넌트의 defaultProps

static 메서드는 클래스 컴포넌트에서만 사용 가능하므로, 함수 컴포넌트는 `컴포넌트.defaultProps` 방식으로 사용합니다.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/1850554/220089886-9fa87f69-d56b-453b-b01a-8d279b45b828.png">

```jsx
function App() {}

App.defualtProps = {
  count: 0,
};
```

### 함수 컴포넌트의 props + default pameters

재원 멘토님이 답변한 것처럼 ES6의 기본 매개변수 문법을 사용하면 
`컴포넌트.defaultProps`를 사용하지 않고도 props의 기본 값을 설정할 수 있습니다. 😊

<img width="457" alt="" src="https://user-images.githubusercontent.com/1850554/220090508-63ccb777-b0d4-471b-bb78-a95ddeaf2584.png" />


```jsx
function App({ count = 0 }) {
  // ...
}
```

**Comment by 5wintaek** [comment]
두분 답변 정말 감사드립니다 !
