### ISSUE TITLE
[LAB-5] 가상DOM의 이해가 잘 되지 않습니다.  

### ISSUE THREAD

**Issue by PracticeKJY** [yamoo9/likelion-FEQA#99]
## 질문 작성자

김종엽

## 문제 상황

[멘토링에 올렸던 질문이였는데,  시간이 부족해서 이슈로 다시 올립니다..!]

https://ko.reactjs.org/docs/reconciliation.html

![image](https://user-images.githubusercontent.com/119389577/220083214-1a2ef9f8-31f4-4b67-ab41-6d2aa6ce1c00.png)
![image](https://user-images.githubusercontent.com/119389577/220083241-15b241d5-fcb3-4348-9275-de484dd2be0e.png)

안녕하세요 쌤..! 다름이 아니라, 가상 DOM이란 것에 대해 이해가 잘 가지 않아 질문드립니다.
머리속에 남아있는 개념은 'React를 사용하여 가상DOM트리을 형성하고,  상태가 바뀐 것들만 DOM에 렌더링 함으로써,
 불필요한 렌더링 과정을 줄여 성능적으로 이점을 챙길 수 있다." 입니다.     
근데 막상 이걸 다른분들에게 설명하려니..  잘 안되네요 ㅜㅜ... 위의 첨부된 링크나 그림들을 말로 제대로 풀지도못하고,  
가상DOM이란 개념의 흐름이 잘 이해가 가지 않은 것 같습니다...
혹시 조언을 좀 구할 수있을까요..!

ps:  제가 글로 궁금증을 설명하는것도, 그리고 개념을 이해하는것들도  조금 서툴러서... 혹시 가능하시다면 디코로 피드백을 해주신다면 더 많이많이많이 도움이 될 것 같습니다 ㅜㅜㅜㅜ ....

## 코드 검토 리소스

React는 구성된 개발 환경에 따라 문제 상황이 다르고, 상황을 정확히 분석해야 문제를 해결할 수 있습니다.
문제 상황을 온라인 개발 도구 환경에서 구현하여 제시하거나, GitHub 저장소를 이용해 질문주시길 바랍니다.

- [github.com 저장소 활용](https://github.com)
- [stackblitz.com 활용](https://stackblitz.com/)
- [codesandbox.io 활용](https://codesandbox.io/)

## 환경 정보

환경과 관련된 문제가 의심될 경우 작성합니다. (입력 선택 사항)

- 운영체제 종류 (예: Windows, macOS)
- Node.js 버전 (예: v16.15.0)

**Comment by yamoo9** [comment]
@PracticeKJY 님께서 디스코드로 피드백을 요청주셨으니 관련 질문에 대한 답변은 디스코드로 드리겠습니다.
내일(2023. 2. 21) 다시 연락 드리겠습니다. 😊
